### ISSUE TITLE
"on" block not being honored 

### ISSUE THREAD

**Issue by NicosKaralis** [capistrano/capistrano#1008]
I have one server that has only the role `:web` and other with only `:db`

In one of the db taks i have this code:

    on roles(:db) do
      if test '[ -z "$(getent passwd postgres)" ]'
        fatal "postgres user not created"
      else
        execute "echo -e 'postgres:password' | sudo chpasswd"
      end
    end

of course `fatal` don't kill the task, so i had to do it like this:

    raise "postgres user not created"

or

    fatal "postgres user not created"
    exit -1

in any server with `:db` role it works great, but when i have to run it on the `:web` server, this ruby code is evaluated and it quits my execution.

Am I doing something wrong? what should i do?

**Comment by mattbrictson** [comment]
Closing since this has been in the "need more info" state for over a year. Let us know if this is still an issue that needs to be looked at.
