### ISSUE TITLE
Load directive used instead of require

### ISSUE THREAD

**Issue by slowjack2k** [capistrano/capistrano#1042]
This files

[console.rb](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/console.rb)
[deploy.rb](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/deploy.rb)
[dotfile.rb](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/dotfile.rb)
[framework.rb](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/framework.rb)
[git.rb](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/git.rb)
[hg.rb](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/hg.rb)
[install.rb](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/install.rb)
[setup.rb](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/setup.rb)
[svn.rb](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/svn.rb)
[git.rake](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/tasks/git.rake)

use load instead of require. This leads to unexpected behavior. For instance I can't override some git tasks because the stage task loads the git tasks during execution and appends to custom changes in the task. 

I think it should be reconsidered if load is the right directive or require should be used.

**Comment by mattbrictson** [comment]
> For instance I can't override some git tasks because the stage task loads the git tasks during execution

This in particular we have plans to fix. See #1125.

**Comment by mattbrictson** [comment]
Capistrano 3.7.0.beta1 has been released! 🎉 

This version brings a new SCM plugin system, which makes it much easier to override Git tasks or completely replace the SCM behavior with your own code. SCM is now installed via your Capfile, which means the SCM tasks are loaded and available for you to override in `deploy.rb`.

SCM plugins use `require`, not `load`, and are explicitly installed. No magic.

You can read more about the new behavior here:

* [Custom SCM](http://capistranorb.com/documentation/advanced-features/custom-scm/) (official how-to from the docs)
* [Capistrano 3.7.0 upgrade guide](https://github.com/capistrano/capistrano/blob/master/UPGRADING-3.7.md)

Please test the beta and send us feedback!
