### ISSUE TITLE
Defaults for stage_config_path and deploy_config_path should be absolute paths

### ISSUE THREAD

**Issue by slowjack2k** [capistrano/capistrano#1060]
Defaults for stage_config_path and deploy_config_path are relative paths.
When I'm in a subfolder, for instance lib, and want to call `cap <stage> deploy`
it does not work because theses paths are relative to my working directory. Rake supports this kind of behavior so I think capistrano should support 
this feature too. Maybe booth path can be changed for instance this way:

``` ruby
      def capfile_path
         unless @capfile_path
             (capfile_found, @capfile_path) = Rake.application.find_rakefile_location
               @capfile_path = Dir.pwd unless capfile_found
         end
         @capfile_path
      end

     def full_path(partial_path)
         File.join(capfile_path, partial_path)
     end


     def stage_config_path
        Pathname.new fetch(:stage_config_path, full_path('config/deploy'))
      end

      def deploy_config_path
        Pathname.new fetch(:deploy_config_path, full_path('config/deploy.rb')
      end

```

**Comment by will-in-wi** [comment]
Looks like a PR was created and then closed two years ago. I'm going to close this. Feel free to reopen if needed.
