### ISSUE TITLE
SSHKit.config.command_map :rake and :gem can not be overridden

### ISSUE THREAD

**Issue by MarioLinden** [capistrano/capistrano#1069]
`SSHKit.config.command_map` does not behave as expected in Capistrano when defining `gem` and `rake`, they seem to be locked to `bundle exec`.

``` ruby
SSHKit.config.command_map[:mycommand] = "whatever I want"
puts SSHKit.config.command_map[:mycommand]
#=> "whatever I want" # GOOD

SSHKit.config.command_map[:rake] = "whatever I want"
puts SSHKit.config.command_map[:rake]
#=> "bundle exec rake" # WTF!

SSHKit.config.command_map[:gem] = "whatever I want"
puts SSHKit.config.command_map[:gem]
#=> "bundle exec gem" # WTF!
```

I'm using capistrano and capistrano-bundler gems:

``` ruby
gem 'capistrano', '3.1.0'
gem 'capistrano-bundler', '1.1.2'
```

And this is my Capfile:

``` ruby
set :deploy_config_path, 'deploy/capistrano/deploy.rb' # we use a different file structure than default /config/deploy.rb
set :stage_config_path, 'deploy/capistrano/deploy'

require 'capistrano/setup' # Load DSL and Setup Up Stages
require 'capistrano/deploy' # Includes default deployment tasks
require 'capistrano/bundler' # Install gems from the Gemfile

# Loads custom tasks
Dir.glob('deploy/capistrano/lib/tasks/*.cap').each { |f| import f }
```

I already sent [this issue to SSHKit](https://github.com/capistrano/sshkit/issues/145#issuecomment-44663039) but it turns out that without Capistrano, `SSHKit.config.command_map` works just fine.

**Comment by sbonami** [comment]
I'm a bit late to the party, but this seems to still be an issue regardless of any change to `bundle_bins`. Because this is related, linking here: https://github.com/capistrano/sshkit/issues/299
