### ISSUE TITLE
colorize not working when tty is not present

### ISSUE THREAD

**Issue by juanbrein** [capistrano/capistrano#1079]
This is the case when you run capistrano using jenkins. Still I would like to see colors on the outputs. This is broken on sshkit and downgrading to 1.3.0 fixed it.

Is this the expected behaviour? If so is there a way to enable color output with stdout.tty? = false ?

Thanks!

**Comment by tom-lord** [comment]
To any future readers who, like me, stumbled here via a google search:

You can now enable coloured Jenkins output for Capistrano tasks, by setting:

    ENV['SSHKIT_COLOR'] = "true"

(As can be seen in the SSHkit code [here](https://github.com/capistrano/sshkit/blob/db4d1d3cb4c95ce40fc28782d68b21858021e2c0/lib/sshkit/color.rb#L24).) This could either be configured globally, or on a per-job basis.

**Comment by ryderstorm** [comment]
@tom-lord - comments like [yours](https://github.com/capistrano/capistrano/issues/1079#issuecomment-252850010) bolster my faith in humanity. I've been needing a fix for this for months.

**Comment by mattbrictson** [comment]
@tom-lord @ryderstorm If we could do a better job at documenting this, please feel free contribute a PR and I'll merge it. Thanks!

**Comment by leehambley** [comment]
Locking the issue because we ought all to know how the relationship between a tty and terminal control colorization codes works... Colorization is not magic, it's a feature of a terminal. No terminal, no colours, without forcing the issue.
