### ISSUE TITLE
#ask asks value several times

### ISSUE THREAD

**Issue by srilumpa** [capistrano/capistrano#1095]
Hi,

We're using Capistrano to deploy massively one of our projects to servers inside our LAN. As SSH is forbidden between our application servers and our git server, we use HTTPS to clone/update the code on our app servers.

In order for this to work, we added in our deploy.rb file two `ask` directives: one for `:git_http_username` and one for `:git_http_password`.

Here is our deploy.rb file:
```ruby
# config valid only for Capistrano 3.2.1
lock '3.2.1'

set :application, 'project'
set :repo_url, 'https://my.git.server/my/project.git'

ask :git_http_username, fetch(:local_user) || ENV['USER']
ask :git_http_password, ''

# Default branch is :master
ask :branch, proc { `git rev-parse --abbrev-ref HEAD`.chomp }
# ...
```

And here is the output :
```
mad@madness:~/Documents/dev/project$ cap production deploy
 INFO [1aba96f2] Running /usr/bin/env mkdir -p /tmp/project/ on server02
 INFO [89c6f234] Running /usr/bin/env mkdir -p /tmp/project/ on server01
 INFO [89c6f234] Finished in 0.098 seconds with exit status 0 (successful).
 INFO Uploading /tmp/project/git-ssh.sh 100.0%
 INFO [1aba96f2] Finished in 0.144 seconds with exit status 0 (successful).
 INFO [fad08740] Running /usr/bin/env chmod +x /tmp/project/git-ssh.sh on server01
 INFO [fad08740] Finished in 0.006 seconds with exit status 0 (successful).
 INFO Uploading /tmp/project/git-ssh.sh 100.0%
 INFO [3d561ae5] Running /usr/bin/env chmod +x /tmp/project/git-ssh.sh on server02
 INFO [3d561ae5] Finished in 0.010 seconds with exit status 0 (successful).
Please enter branch (master): 
Please enter git_http_username (mad): Please enter git_http_username (mad): 
Please enter git_http_password (): Please enter git_http_password (): 
```

So my Git username and password are asked by Capistrano for each server it has to deploy to and I don't understand why this doesn't work like the `ask :branch` which is called only once.

I think this is a bug, but I'm probably missing something here.

**Comment by josetapadas** [comment]
Same here:

````
DEBUG [58a5de9a] Command: mkdir -p /opt/www/cruises-cms/shared/config
INFO [9aa15742] Finished in 0.254 seconds with exit status 0 (successful).
Please enter aws_secret_access_key (aws-staging): INFO [58a5de9a] Finished in 0.255 seconds with exit status 0 (successful).
````

I consider this workaround not totally applicable.

**Comment by koenpunt** [comment]
The latest version of Capistrano doesn't have the behavior described in the original issue. So `ask` only asks once, even with multiple servers

**Comment by koenpunt** [comment]
Could this be the commit that fixed it? https://github.com/capistrano/capistrano/commit/b1ea1cd1028827b19859889592b757b2f0d947a9

**Comment by leehambley** [comment]
Looks like.
