### ISSUE TITLE
Missleading "Stage not set, please call [...]"

### ISSUE THREAD

**Issue by protoswype** [capistrano/capistrano#1105]
I just set up capistrano and was wondering why my cap tasks were not working. I got the error message "Stage not set, please call something such as `cap production deploy`, where production is a stage you have defined." (https://github.com/capistrano/capistrano/blob/master/lib/capistrano/i18n.rb#L11). I was not in the root directory of my application, so Capistrano would not find my stages. I think the error message can be missleading and I suggest to include something like: "Make sure to be in your root directory." I can do a pull request if you like to. Just close this issue, if you think this wouldn't improve anything :)
Keep up the great work :+1:

**Comment by lakesare** [comment]
Just stumbled upon the issue on 3.4.0. 
Thank you for advising to look at what folder I am.
