### ISSUE TITLE
cannot add role to the hosts when they exist

### ISSUE THREAD

**Issue by shawzt** [capistrano/capistrano#1115]
I use capistrano (3.2.1) and have the following definition:

``` ruby
role :app, %w{a b}, user: "test", password: "xxx"
role :db,    %{a}, user: "test", password: "xx"
```

but I cannot run some tasks on role :db which is because roles(:db) is empty.
I read the source code and find the root cause is the following code:

``` ruby
def server(host)
    servers.find { |server| server.matches? Server[host] } || Server[host]
end

def matches?(other)
    user == other.user && hostname == other.hostname && port == other.port
end
```

Why we need to add the `matches?(other)` method? I think we should remove this logic.

**Comment by will-in-wi** [comment]
If I create a new Capistrano project, and put the role definitions from the original ticket in `production.rb` and the following in `deploy.rb`:

```ruby
task :test_roles do
  on roles(:db), in: :parallel do |host|
    puts "DB: #{host.hostname}"
  end

  on roles(:app), in: :parallel do |host|
    puts "APP: #{host.hostname}"
  end
end
```

And then run `cap production test_roles`, I get:

```
DB: a
APP: b
APP: a
```

I think this is the correct behavior. I'm closing this ticket. Feel free to reopen (or open a new one) if anyone can reproduce the original issue in latest Capistrano.
