### ISSUE TITLE
Switch users while deployment running

### ISSUE THREAD

**Issue by ohshhh** [capistrano/capistrano#1160]
I need to login with user1 by ssh key, and then run full deployment processs with user2(uses passphrase).
Is it real ? Tried to use 'before :starting, :custom_task' and there switch user with command "sudo su user_name" or tried prefixes before each deployment tasks with hash[command] = "<< sudo stuff >> #{command}", but deployment fails when passphrase requested.
Thanks.

**Comment by stevenhaddox** [comment]
This is sad. This setup is completely valid and fairly frequent and easily supported in cap 2. SSHkit even supports it through the `as` method. Is there a way to wrap all commands in an as block with a dynamic user param like `sudo_user` if `use_sudo` is true? Just a thought. I was able to get most of the way there just by overriding each method in cap's deploy.rake file with an as block... Not sure how hard it is to dynamically inject the as block based on a config setting....

**Comment by leehambley** [comment]
Vote with a pull request for better open source software if you think you can implement it reliably, we've tried, and 3.4 includes some changes that go in this direction, but this issue as it was discussed remains impossible to implement.
