### ISSUE TITLE
Capistrano in Ruby script is broken

### ISSUE THREAD

**Issue by devaroop** [capistrano/capistrano#1167]
The description here: http://capistranorb.com/documentation/advanced-features/capistrano-pure-ruby/ says that we can do away with the 'config' and 'deploy' folders which does not seems to be the case. The code 'lib/capistrano/setup.rb' line 14 still requires the folders :(

The code snippet in the link (above) fails if there is no 'config/deploy/production.rb'. Also, all settings in the config folder override the script settings.

Am I missing something?

**Comment by Kriechi** [comment]
maybe is this related to https://github.com/capistrano/capistrano.github.io/issues/107?

**Comment by calvinwyoung** [comment]
Out of curiosity, does anyone know if there are plans to make Capistrano work in pure ruby again? This would be really convenient for smaller projects.

**Comment by leehambley** [comment]
@calvinwyoung it's not broken, it's just not well documented how to use it.

**Comment by calvinwyoung** [comment]
@leehambley ah, got it — thanks for the quick response. If it's not too much trouble, it'd be really nice to update the documentation. Just from Googling around, I feel like there are a lot of folks out there who'd love to be able to use Capistrano with pure ruby if possible.

**Comment by will-in-wi** [comment]
The documentation has been removed and an attempt to make this possible has stalled. I'm closing this ticket. If anyone wants to attempt this again, feel free to reopen or open a new ticket. Thanks!
