### ISSUE TITLE
cap deploy from a directory above

### ISSUE THREAD

**Issue by lightheaded** [capistrano/capistrano#1194]
Hello! 

I have a project with a capistrano deployment setup as a submodule (i.e. in a `deploy/` directory). Is there any way that I can launch `cap deploy` from my project directory but still keep capistrano contained within a submodule with a dedicated repository?

**Comment by will-in-wi** [comment]
I have a case like this, and I used a Makefile at the root of the project to simplify this.

At best, I think we might consider a PR to introduce a `--config-path` parameter or something to define where Capistrano should find its configuration.

Given the age of this ticket and the number of easy workarounds, I'm closing.
