### ISSUE TITLE
set does not accept passing a block the easy way

### ISSUE THREAD

**Issue by gucki** [capistrano/capistrano#1196]
In capistrano 2 a block could be passed to `set`. Capistrano 3 always expects two parameters and passing a block like this is no longer possible. 

Does not work in capistrano 3 (but it should work!):

    set :rvm_ruby_version do
      within release_path do
        capture(:rvm, "current")
      end
    end

Works in capistrano 3 (but looks like an ugly hack):

    set :rvm_ruby_version, proc{
      within release_path do
        capture(:rvm, "current")
      end
    }

Why has this support been removed? Anything against adding it again?

**Comment by xavierholt** [comment]
Old thread, but I got very confused this afternoon when trying to pass a delayed-execution block to the set functions.  I agree with @gucki that this doesn't match Ruby conventions / violates the principle of least surprise.

I don't think it needs to be a breaking change, though.  It should be possible to support both methods simultaneously.  Proposed patch: https://github.com/capistrano/capistrano/pull/1478

**Comment by gucki** [comment]
Thansk! :+1:
