### ISSUE TITLE
Capistrano 3.3.3 broke something wrt ssh config

### ISSUE THREAD

**Issue by romanbsd** [capistrano/capistrano#1202]
I have the following configuration for the server in the deploy/production.rb (I changed the domain to "example"):
```ruby
server 'prod.example.com', user: 'roman', roles: %w{web app db}
```
Here's what happens on 3.3.3 (3.2.1 works fine):
<pre>
INFO[9b834765] Running /usr/bin/env mkdir -p /tmp/example/ on prod.example.com
INFO[820d7d2a] Running /usr/bin/env mkdir -p /tmp/example/ on prod.example.com
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host prod.example.com: Authentication failed for user @prod.example.com

Net::SSH::AuthenticationFailed: Authentication failed for user @prod.example.com

Tasks: TOP => git:check => git:wrapper
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing on host prod.example.com: Authentication failed for user @prod.example.com
</pre>

Please note, that adding ssh_options: {user: 'roman'} has no effect.

versions:
net-ssh (2.9.1)
sshkit (1.5.1)

**Comment by reiz** [comment]
Indeed. That is confusing. And it's a breaking change without bumping up the major version number. This update broke my build!

**Comment by leehambley** [comment]
It's not something we did intentionally.

**Comment by reiz** [comment]
It can happen, we are humans, not robots. I just downgraded to 3.2.1 for now.

**Comment by Kriechi** [comment]
I guess this could be closed with #1301 or #1355?

**Comment by leehambley** [comment]
Seems like @Kriechi

**Comment by jitendrak1** [comment]
Hello friends i am also use Capistrano gem, and one more thing I am trying to my project from bitbucket branch. I have already upload my project on bitbucket branch thats name "test" branch, Now i want to deploy this branch on my aws(ec2) sever, when I executed "bundle exec cap staging deploy" command then I got following errors...

ubuntu@ip-***IP Address***:~/project_folder$ bundle exec cap staging deploy
DEBUG [4550afd9] Running /usr/bin/env which passenger as ubuntu@***IP Address***
DEBUG [4550afd9] Command: /usr/bin/env which passenger
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as ubuntu@***IP Address***: Authentication failed for user ubuntu@***IP Address***

Net::SSH::AuthenticationFailed: Authentication failed for user ubuntu@***IP Address***

Tasks: TOP => rvm:hook => passenger:rvm:hook => passenger:test_which_passenger
(See full trace by running task with --trace)
ubuntu@ip-***IP Address***:~/Project_folder$ 
  
Please help me ....

**Comment by AmitPatel-BoTreeConsulting** [comment]
@jitendrak1 have you got your problem solved. I lately started facing this issue.

http://stackoverflow.com/questions/39831186/netsshauthenticationfailed-while-deploying-rails-4-2-x-application-using-cap
