### ISSUE TITLE
variables are cached

### ISSUE THREAD

**Issue by gucki** [capistrano/capistrano#1207]
I wasn't able to find much information about how variables behave in capistrano 3. However the document I found (http://capistranorb.com/2013/06/01/release-announcement.html) states that variables are not cached:

> The system has now 100% less magic. If you set a variable using set(), it can be fetched with fetch(), if the value you set into the variable responds to #call then it will be executed in the current context whenever it is used, the values will not be cached, unless your continuation does some explicit caching. Again, we are favoring clarity over micro optimisation.

However this simple code only outputs "aa" once, so clearly the variable is cached:

```
set :rvm_ruby_version, proc{
  puts "aa"
}

10.times{ fetch(:rvm_ruby_version) }
```

Is this expected? If yes, why and how to disable caching?

**Comment by will-in-wi** [comment]
I'm going to say that using `#set` really shouldn't have side-effects, which would make the caching an issue. If anyone has a use case where this causes issue, please open a ticket with that.

Thanks!
