### ISSUE TITLE
Should primary() invoke roles filtering?

### ISSUE THREAD

**Issue by cxyokk** [capistrano/capistrano#1213]
(Related issue: capistrano/rails#97)

It seems that `primary()` doesn't involve roles filtering, so if I do this:
(Slightly modified from [capistrano-rails](https://github.com/capistrano/rails/blob/master/lib/capistrano/tasks/migrations.rake#L7))

``` ruby
  task :migrate do
    on primary(:db) do # <= here
      ...
```

And then try to deploy like this:

``` bash
cap production migrate ROLES=app
```

The `migrate` task gets executed anyway, regardless of the roles filtering.

So my questions are:
- Is this on purpose? (`primary()` not involving roles filtering)
- How do I achieve my goal in this situation? (filter out a task that uses `primary()` rather than `roles()`)

Thanks!

**Comment by townsen** [comment]
Have a read of the [host and role filtering documentation](http://capistranorb.com/documentation/advanced-features/host-and-role-filtering/) and you'll see that `primary()` doesn't role filter - it returns everything that it should. However `on()` then applies the role filter. This distinction was made somewhat recently - are you using the latest version?

**Comment by leehambley** [comment]
@townsen I have had a few more bug reports about this, and agree to fix it for one of my clients. Since I notice you worked on filtering this morning, I wanted to invite you to share your opinion. I made it as far as two test cases for this, but not to fix the implementation yet.

I think `primary()` should return nothing if the `ROLES` filter filters out that role?

**Comment by townsen** [comment]
I still think that the current behaviour of `primary()` makes sense: it doesn't look at the ROLES filter. In the OPs post he says that 'the `migrate` task gets executed anyway, which is exactly what you'd expect, the host and role filters don't work at the _task_ level, they work at the `on()` level (which is where the actual servers are SSH'd into). So in the example given the ellipsis after `on primary(:db)` does _not_ get executed.

Having said that I do remember some historic issues with roles and capistrano/rails and db migrations, but I just rechecked and it seems ok to me. Can @cxyokk check if this problem occurs with the latest Capistrano/SSHkit?

Thanks

**Comment by will-in-wi** [comment]
It sounds like this might have been resolved. Please reopen if it is still an issue.
