### ISSUE TITLE
Capistrano connects to metrics even after disabling

### ISSUE THREAD

**Issue by pepijn** [capistrano/capistrano#1218]
I answered `n` to the question about enabling statistics, blocked the connection to `metrics.capistranorb.com`, and still Capistrano throws an exception because it can not connect.

`.capistrano/metrics`:

```
false
```

Std{out,err}:

```
        Would you like to enable statistics?  Here is an example message we would
        send:

        1|2014-12-09T14:53:47+01:00|2.1.3|x86_64-darwin13.0|3.3.3|211fa010

Do you want to enable statistics? (y/N): n
n
Your preferences have
           been saved.
(Backtrace restricted to imported tasks)
cap aborted!
Errno::EHOSTDOWN: Host is down - sendto(2) for "metrics.capistranorb.com" port 1200
```

`Gemfile.lock`:

```
GEM
  remote: https://rubygems.org/
  specs:
    capistrano (3.3.3)
      capistrano-stats (~> 1.0.3)
      i18n
      rake (>= 10.0.0)
      sshkit (~> 1.3)
```

**Comment by taf2** [comment]
how do you disable the prompt... ?

**Comment by taf2** [comment]
solution roll back to older version 3.3.5 - why isn't there either an option to never interactive prompt?

**Comment by mattbrictson** [comment]
Metrics were completely removed in Capistrano 3.4. Upgrade to 3.4 or newer and you are all set.

**Comment by taf2** [comment]
awesome, so i'm not against metrics at all i think you should have metrics... just not prompt or if i answer yes never prompt again 👍   but i'll upgrade now too
