### ISSUE TITLE
change repo_url

### ISSUE THREAD

**Issue by stamm** [capistrano/capistrano#1227]
If I change repo_url, capistrano still clone code from old repo.
In file repo/config origin also from old repo.

I remove directory repo, and it works with new repo

**Comment by jomo** [comment]
FTR, had the same issue, found the solution [on StackOverflow](http://stackoverflow.com/a/23863673/2517068).

**Comment by ajahongir** [comment]
https://coderwall.com/p/4k1lja/fixing-capistrano-3-deployments-after-a-repository-change

**Comment by will-in-wi** [comment]
I've run into this several times. The solution in each case is just to nuke the repo directory. This isn't an issue when it is just one server, but in one case I'm deploying to 6 servers. However, changing the repo url is rather uncommon, so it is most just an annoyance.

For a workaround, try this: https://rubygems.org/gems/capistrano-git-delete_repo

**Comment by will-in-wi** [comment]
As I was reading the comments in the link above, I noted that someone suggested this:

```ruby
namespace :git do
  task :update_repo_url do
    on roles(:all) do
      within repo_path do
        execute :git, 'remote', 'set-url', 'origin', fetch(:repo_url)
      end
    end
  end
end
```

This might be worth making a standard part of the Git deployment workflow. I doubt that it would take long on deploy, and might solve this issue.

**Comment by leehambley** [comment]
I can't see what version of Git that was added to - I'll check the changelogs - https://git-scm.com/docs/git-remote

**Comment by wangboguo** [comment]
@stamm Thank you! I deleted dir repo and it solved my problem!
