### ISSUE TITLE
After does not support *args on invoke

### ISSUE THREAD

**Issue by newdark** [capistrano/capistrano#1230]
During a deploy I would like to provide a after event and pass in some args. This would allow me to pass in extra information that should only happen during a deploy process. However because the args are not passed down threw the invoke method the extra data is missing from the task.

I would like this line of code changed to something that looks like this.
https://github.com/capistrano/capistrano/blob/master/lib/capistrano/dsl/task_enhancements.rb#L14

```ruby
def after(task, post_task, *args, &block)
  Rake::Task.define_task(post_task, *args, &block) if block_given?
  post_task = Rake::Task[post_task]
  Rake::Task[task].enhance do
     post_task.invoke(*args)
  end
end
```

This small change lets you do something like this. 

```ruby
namespace :deploy do
  namespace :maintenance do
    desc 'Turn Maintenance on'
    task :on, :reason, :back_at do |_task, _args|
    end
  end
end
after :started, 'deploy:maintenance:on', 'Application is currently Deploying', '20 years'
```

**Comment by leehambley** [comment]
Closing as I'm satisfied that the OP has what he needs as he hasn't replied in a long time.

For clarity, my succestion was following

``` ruby
task :deploy do
  # (this augments the existing implementation, it does not replace it)
  set(:are_we_deploying, :yes)
end
```

Then at any other time you can use `fetch(:are_we_deploying)` to detect if that's how you entered into the command.
