### ISSUE TITLE
Wiki pages seems to be littered with spam pages. 

### ISSUE THREAD

**Issue by donnykurnia** [capistrano/capistrano#1233]
I just noticed that the wiki pages have been littered with spam titles. The pages could be seen in the pages sidebar https://github.com/capistrano/capistrano/wiki

One of the pate at the top of the list contain the actual content, but the title have been changed to a spam text.

**Comment by leehambley** [comment]
I cloned the wiki and force reset to `dff2fd6` and force pushed, seems to have all the valuable things back.
