### ISSUE TITLE
documentation on capistranorb.com contains mistype probably

### ISSUE THREAD

**Issue by epifanov** [capistrano/capistrano#1271]
Hi,

I read docs here http://capistranorb.com/documentation/advanced-features/host-filtering/, specifically this part: "set :filter, :hosts => %w{server1 server2}". I tried to apply this in my script, but it did not work.

I checked source code and it looks like it should be "set :filter, :host => %w{server1 server2}" ("host" instead of "hosts")

BR

**Comment by leehambley** [comment]
We'd love a PR to the documentation site if you can, it's all simple
Markdown, hosted at Github

Lee Hambley
http://lee.hambley.name/
+49 (0) 170 298 5667

**Comment by epifanov** [comment]
Good point! Done: https://github.com/capistrano/capistrano.github.io/pull/109
