### ISSUE TITLE
More spam in the Wiki 

### ISSUE THREAD

**Issue by peterjmit** [capistrano/capistrano#1272]
I am not sure how this is happening, but there is yet more spam in the wiki

![image](https://cloud.githubusercontent.com/assets/867628/5663579/cfec1df6-9716-11e4-94b4-f943d09b9b7f.png)

Is there a permissions setting or something for people who can edit the wiki we can change?

**Comment by leehambley** [comment]
Wiki is locked (what a shame...) to only allow edits from people with `capistrano/capistrano` push access. Thanks for the report, and sorry for having to lock the wiki, rendering it 50% useless :-1:

**Comment by kirs** [comment]
I'm having a conversation with Github stuff to prevent the spam.

**Comment by leehambley** [comment]
Lemme know anything g you learn mate, thanks
