### ISSUE TITLE
No guided walkthrough

### ISSUE THREAD

**Issue by operand** [capistrano/capistrano#1297]
Hi guys.

I'm basically submitting this issue to request a clearer getting started walkthrough on the main site. I remember with version 2 there was a thorough walkthrough for getting started (here it is https://github.com/capistrano/capistrano/wiki/2.x-From-The-Beginning), but although there is a section titled "Getting Started" on the version 3 site, as a new user of version 3, I was left hanging with how to move forward initially. I'm currently just following the old guide and substituting any changes that I learn about. It seems to mostly still be relevant, so that's the good thing. I just wanted to point out this bit of frustration that I've had. Cheers and thank you for the good work!

**Comment by leehambley** [comment]
Hey @operand good to know. Let me take the time to ask you, would it have been worth it for you to pay for a tutorial video walking through the common things? I've been approached by a company who wanted to (I would write and record them) produce a series of screencasts for getting people into v3 in general.

**Comment by operand** [comment]
Yeah I think that would be great. Although I'm personally a fan of articles over videos.

I'd like to add that the guides on the new site are very good. It was just that I needed something to have more of a step by step, from the beginning, kind of flow to it. I eventually got everything working without too much wasted time, but I used the old guide that I linked to above to help me.

**Comment by CyborTronik** [comment]
Is there any updates?

**Comment by leehambley** [comment]
@CyborTronik no, buy you can cast a vote in favour of constructing some video tutorials to explain how to use Capistrano, and I might make them if there'll be a market for them (making video content and well written docs is even more time consuming than writing and maintaining Capistrano itself)

**Comment by mattbrictson** [comment]
Moving this issue to https://github.com/capistrano/documentation/issues/160
