### ISSUE TITLE
Test that remote file exists

### ISSUE THREAD

**Issue by bigfoot90** [capistrano/capistrano#1323]
I'm witing tests for my deploy script.
I have to check if a specific file exists on remote server.
How to do it?
Thanks.

**Comment by sponomarev** [comment]
``` if test "[[ -f #{file1} && -f #{file2} ]]" ```

**Comment by bigfoot90** [comment]
@sponomarev Can you explaint it? please.

**Comment by sponomarev** [comment]
@bigfoot90 as i understand you need to check file existence in custom capistrano task, here is a good example https://github.com/capistrano/rails/blob/master/lib/capistrano/tasks/assets.rake#L81.

In first code snippet `file*` is string variable with file absolute path

**Comment by bigfoot90** [comment]
@sponomarev I've got it. Thanks.

**Comment by cblackburn-ajla** [comment]
For future reference - for others, here's a possible solution, gleaned from @sponomarev post above:

```
def file_exists?(path)
  capture(:ls, path)
  true
rescue SSHKit::Command::Failed
  false
end
```
