### ISSUE TITLE
Windows Documentation

### ISSUE THREAD

**Issue by rebelweb** [capistrano/capistrano#1324]
I see here, http://capistranorb.com/documentation/getting-started/authentication-and-authorisation/, you don't have any windows documentation. Is this still true? I can contribute documentation if it still need and/or wanted. I use Windows for development and have my Capistrano setup (with rails) going and working.

**Comment by leehambley** [comment]
That would be fantastic Ryan!

**Comment by rebelweb** [comment]
I want to clarify this would be a Windows Development Machine, deploying to Linux Server. Is this what we are needing?

**Comment by leehambley** [comment]
Exactly, that'd be amazing. I don't know even enough about Windows (I haven't used a Windows machine since XP was the new hotness) to even know whether it makes sense to integrate that into our existing docs, or have a special FAQ/quick start Windows document linked from the sidebar, I defer to your wealth of experience on that front.

**Comment by rebelweb** [comment]
What the best way to submit the documentation? Should I create a Wiki Page on github, I ask because the github docs are for legacy 2.X of capistrano.

**Comment by leehambley** [comment]
The repository that contains the docs are https://github.com/capistrano/capistrano.github.io - they are rendered with Jekyll (I think), and served under capistranorb.com by Github.

**Comment by rebelweb** [comment]
I am just coming back to this, should windows documentation be a separate page so it doesn't get confusing? I am finally putting my notes together on this and would like to get this done. Thanks.

**Comment by leehambley** [comment]
Thanks, we should really have the Windows docs separated. Were you able to make much progress here?

**Comment by mattbrictson** [comment]
Closing in favor of https://github.com/capistrano/documentation/issues/161
