### ISSUE TITLE
Capistrano is ignoring my ssh_options

### ISSUE THREAD

**Issue by odigity** [capistrano/capistrano#1331]
I tried specifying them like this:

    # config/deploy.rb
    set :ssh_options, { user: 'test1' }

Didn't work.  I then tried specifying them like this:

    # config/deploy.rb
    SSHKit::Backend::Netssh.configure do |ssh|
      ssh.ssh_options = { user: 'test2' }
    end

Didn't work.  I then tried specifying them like this:

    # config/deploy/production.rb
    set :ssh_options, { user: 'test3' }

Didn't work.  Lastly, I tried specifying them like this:

    # config/deploy/production.rb
    server 'myserver.com', roles: ['web'], ssh_options: { user: 'test4' }

And it finally worked.

All four of these are based on examples in the README.md or on capistranorb.com.

**Comment by odigity** [comment]
FYI-I tested the results with something like this:

task :check_ssh_options do
  on release_roles :all do |host|
    puts "#{host.hostname}:  #{host.netssh_options}"
  end
end

**Comment by Kriechi** [comment]
I found a spec which should test the same thing you are doing:
https://github.com/capistrano/capistrano/blob/239b03a7013677fcbaac3ea8ba0f95cdd8ab4de6/spec/integration/dsl_spec.rb#L382-386
https://github.com/capistrano/capistrano/blob/239b03a7013677fcbaac3ea8ba0f95cdd8ab4de6/spec/integration/dsl_spec.rb#L410-414

As far as I understand the code, the tested approach should be equal to your first example.
For why you seem to have problems with it, I don't know.

Maybe your test output with `host.netssh_options` messes things up?

**Comment by odigity** [comment]
Thanks for the leads.  I'm under deadline today, but I will try to get back to this afterwards as I'd like to resolve it -- I plan to use Capistrano for a long time.  :)

**Comment by odigity** [comment]
I cloned both gem repos and ran the tests in the same VM I experienced the problems.  Here are the results.  Not sure if it'll be helpful:

https://gist.github.com/odigity/05d34ca2b571ebe8dff8

Let me know if there's a specific test case you want me to construct to demonstrate the problem.

**Comment by Kriechi** [comment]
@townsen made some recent changes to a few code bits, which might be related.
@odigity could you maybe try again with Capistrano from master?
Also check out the docs, which got related changes as well.

see:
https://github.com/capistrano/capistrano/pull/1360
https://github.com/capistrano/capistrano/pull/1368
https://github.com/capistrano/capistrano.github.io/pull/120
https://github.com/capistrano/capistrano.github.io/pull/125

**Comment by townsen** [comment]
@odigity - All your examples actually work - just try running a real command (like `id`) on the remote server. I've done the same thing here right now on the latest master and all those option settings work. What is happening is that the defaults used are _not propagated back_ to the host object.

This behaviour is as expected, but it wasn't historically clearly documented. I've just submitted another documentation PR #126  to make that point explicit.

I did recently submit a couple of PR's in this space (which are now in master), but I didn't do this 'push back' into the host object as I didn't think it was a problem. Now that the host object within the `on` block is a copy we could consider adding it but it is not an easy thing to do and guarantee that it's correct. You'd potentially have to duplicate all the defaults logic in the SSH pipeline. I don't think that it's worth it (and don't have time to tackle it) but perhaps @leehambley and @Kriechi can offer an opinion.

**Comment by odigity** [comment]
@townsen -- Are you sure you linked to PR that you meant to?  (#126)  It doesn't look related.

**Comment by Kriechi** [comment]
I think he refers to https://github.com/capistrano/capistrano.github.io/pull/126

**Comment by mattbrictson** [comment]
Closing since this behavior is now documented thanks to https://github.com/capistrano/documentation/pull/126.
