### ISSUE TITLE
Move large parts of README to capistranorb.com

### ISSUE THREAD

**Issue by Kriechi** [capistrano/capistrano#1336]
Currently most parts of documentation are kinda duplicated or (only in one place) in the README.md and the capistranorb.com website. Ideally there should only be one single documentation, in one place, updated every time a change happens or features get added. Currently one has to check both places and keep them in sync.

I propose:
moving large chunks out of the `README` and 
into the website repo at https://github.com/capistrano/capistrano.github.io. 

The `README` **should contain**: 
* Requirements (and VCS requirements)
* Installation
* Usage
* Testing
* SSHKit
* License

The following sections **currently present** in the `README` **should be moved** to the website repo:
* Tasks
* Before / After
* Getting user input
* Password authentication
* Local tasks
* Console
* PTYs
* Configuration
* Host and role filtering
* Metrics

I'm willing to create two PRs, one for cleanup here, one for adding missing stuff to the website repo.
/cc @leehambley @seenmyfate

**Comment by kirs** [comment]
:+1: for me

**Comment by Kriechi** [comment]
I've implemented my ideas: #1338 and https://github.com/capistrano/capistrano.github.io/pull/110

**Comment by kirs** [comment]
I'm ready to merge, waiting for @leehambley approval.

**Comment by leehambley** [comment]
Merged, thanks guys :)
