### ISSUE TITLE
Roles aren't matching explicitly.

### ISSUE THREAD

**Issue by sammarx** [capistrano/capistrano#1341]
I have 2 roles that have similar names.
config/deploy/test.rb
```
role :test, "test-server-1"
role :asdftest2, "test2-server-2"
puts roles(:test)
```
Test task, just to execute our stage
```
task :test do
end
```
Run cap, should only output "test-server-1"
```
$cap test test
test-server-1
test2-server-2
```

It looks like Cap is matching any part of the of the string, instead of the string as a whole.

**Comment by Kriechi** [comment]
#1342 got merged and fixes this issue.
@leehambley please close this.
