### ISSUE TITLE
Capistrano initialization in pure ruby script(question)

### ISSUE THREAD

**Issue by bogdanRada** [capistrano/capistrano#1348]
Hello, 
 First of all i want to thank you for doing such a great job. 

I have been trying to initialize the capistrano application inside a class but i don't know exactly how to do it. I been spenting two weeks on this and i still can't figure it out. Maybe someone can help me with this.

Here is my code:
```ruby
class Worker
  
  
  
  def initialize(*options)
    ARGV.clear
    options.each {|opt| ARGV << opt }
    @cap = Capistrano::Application.new
    Rake.application = @cap
    @cap.options.trace = true
    @cap.options.backtrace = true
    @cap.init
    @cap.load_rakefile 
    @cap.run
  end
  
  
end



```

And i call it like this: 
```
Worker.new("blog", "deploy", "BRANCH=develop")
```

This is my Capfile:
```
# Load deploy capistrano recipe
require 'rubygems'
require 'bundler/setup'
require 'rake'
require 'capistrano/all'
require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/rvm'
require 'capistrano/bundler'
require 'capistrano/multiconfig'
require 'capistrano/sidekiq'

Dir['recipes/**/*.rake'].each { |recipe| load(recipe) }



```

It sems that it only loads the tasks from recipes folder . The worker is not able to find any other tasks from capistrano gem or other gems. 

Am i missing something? Please let me know if you have any suggestions. 
Please let me know if you need more details. Thank you very much

Fogot to mention i am using the latest version 3.3.5 of capistrano

**Comment by Kriechi** [comment]
Did you take a look at http://capistranorb.com/documentation/advanced-features/capistrano-pure-ruby/ ?
Is this maybe related to https://github.com/capistrano/capistrano.github.io/issues/107

**Comment by bogdanRada** [comment]
hello,
  Thank you very much for your suggestions, but honestly i am not even sure if this is capistrano related or capistrano-multiconfig. 
  I am working on a application that needs to use celluloid actors to deploy multiple applications on multiple servers in parallel. 
   The only thing that worked for me was that after i instantiated the object with Capistrano::Application.new to loop through each of the files from lib directory of all capistrano related gems and using this code to load each file which is a very dirty ugly and messy thing. 
  ````
    @cap = Capistrano::Application.new
     .....
     @cap.send(:load, file)
````
  I did find out actually a better way of doing this . Instead of using Capistrano::Application.new and trying to load the tasks inside that object,  I am using sub-processes where i can run easily a shell command and that seems to work just fine. 

  I think this can be closed. Thank you very much for your help and taking the time to answer my question.

**Comment by Kriechi** [comment]
@bogdanRada so please close it then.

Or do you think it might be Capistrano related - then maybe you could gist your script or show us what you try to do?

**Comment by bogdanRada** [comment]
i was trying to achieve something like in here: https://github.com/capistrano/capistrano/issues/199 . But now i realize it's not eactly possible right now.
