### ISSUE TITLE
Inconsistent behaviour when running MCollective rpc commands (cap2 works, cap3 does not)

### ISSUE THREAD

**Issue by bsnape** [capistrano/capistrano#1358]
Hi,

I noticed a weird problem running `mco rpc` commands when upgrading from Capistrano 2 to Capistrano 3. 

Background: we use Capistrano in our deployment pipeline to SSH onto various servers and run various `mco` commands.

In a nutshell: Running `mco rpc` commands fail (hang) when using "Capistrano 3" (in quotes because I tested against `SSHKit` directly) but works fine when using Capistrano 2. I also tried using my own lightweight custom SSH implementation (that I've used in other places) but this doesn't work either.

My (fairly obvious) theory is that Capistrano 2 did something special/different to handle RPC calls.

I've tested this extensively and I've created a repo with examples and documentation: https://github.com/bsnape/sshkit-mco-rpc-bug

I feel like I've hit the limit of my debugging until someone more familiar with the two codebases (cap2/sshkit) can take a look. I think there's plenty of information in my repo and I'm happy to help out in fixing this or adjusting my setup if I'm doing something wrong.

**Comment by leehambley** [comment]
So this is a bug with SSHKit when used directly, as in https://github.com/capistrano/sshkit/blob/master/EXAMPLES.md#using-with-rake ?

If so, could I ask you to move the issue to capistrano/sshkit

**Comment by bsnape** [comment]
Thanks @leehambley, I'm happy to move the discussion there.

I wasn't sure to raise it here or there because of the Capistrano 2 element.

**Comment by leehambley** [comment]
Understood @bsnape - actually there are some subtle differences, it can often relate to really arcane things, http://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/ can also be a decent place to read/grok before reporting, maybe have a poke there and see if running this all in a `ssh -c 'mco rpc ......'` line works or not, and … I'd imagine you and I'll have to remote-pair on this to get things working if we don't have much success with the easy stuff.

Catch you on the other repo, closing here!

**Comment by bsnape** [comment]
Thanks for the advice @leehambley, it's much appreciated.
