### ISSUE TITLE
Deploying of branches has a bug, current_revision is still getting set as master

### ISSUE THREAD

**Issue by ktaragorn** [capistrano/capistrano#1364]
This is in my `deploy/development.rb` 
`set :branch, ENV["REVISION"] || ENV["BRANCH_NAME"] || "regionalization"`

This is in the code that fetches and sets the `current_revision` variable.
```
def fetch_revision
   context.capture(:git, "rev-parse --short #{fetch(:branch)}")
end
```

This is what happens on `cap development deploy`
```
[a24b1bc2] Running /usr/bin/env cd /home/ubuntu/XXX/repo && git rev-parse --short HEAD as ubuntu@YYY-development.ZZZ.net
DEBUG [a24b1bc2] Command: cd /home/ubuntu/XXX/repo && git rev-parse --short HEAD
DEBUG [a24b1bc2]        7d2363c
```

**Comment by leehambley** [comment]
Isn't this a duplicate of an already open issue, which has an already open pull request?

**Comment by ktaragorn** [comment]
Dash it, sorry, I thought I cancelled this.. This is a duplicate of a closed issue actually.. My capistrano was old, an update fixed it.

**Comment by leehambley** [comment]
Thanks :)
