### ISSUE TITLE
Deploying a legacy Rails 2.3 application on a shared host and facing sudo access error

### ISSUE THREAD

**Issue by jiggneshhgohel** [capistrano/capistrano#1366]
Hello,

I have a legacy application built with Rails 2.3.2. I need to deploy this application using Capistrano to a shared host. I am using latest stable version of capistrano which is 3.3.5. Below you can find the specific versions being used:

* Ruby 1.9.3-p551
* Ruby Gems 1.5.3
* Rails 2.3.2
* Capistrano (3.3.5)

I am facing following error (detailed logs can be found in the gist [here](https://gist.github.com/jiggneshhgohel/3dae4ea30f4634e41eed)):

```
INFO [e00fcb66] Running /usr/bin/env sudo /etc/init.d/unicorn_cebucondo_production restart as cebucond@106.186.120.245
DEBUG [e00fcb66] Command: ( PATH=/usr/local/cpanel/3rdparty/bin/git:$PATH /usr/bin/env sudo /etc/init.d/unicorn_cebucondo_production restart )
DEBUG [e00fcb66]    stdin: is not a tty
DEBUG [e00fcb66]    sudo:
DEBUG [e00fcb66]    effective uid is not 0, is sudo installed setuid root?
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as cebucond@106.186.120.245: sudo exit status: 1
sudo stdout: Nothing written
sudo stderr: stdin: is not a tty
sudo: effective uid is not 0, is sudo installed setuid root?
/CCL/lib/capistrano/tasks/restart.cap:6:in `block (4 levels) in <top (required)>'
/CCL/lib/capistrano/tasks/restart.cap:5:in `block (3 levels) in <top (required)>'
SSHKit::Command::Failed: sudo exit status: 1
sudo stdout: Nothing written
sudo stderr: stdin: is not a tty
sudo: effective uid is not 0, is sudo installed setuid root?
/CCL/lib/capistrano/tasks/restart.cap:6:in `block (4 levels) in <top (required)>'
/CCL/lib/capistrano/tasks/restart.cap:5:in `block (3 levels) in <top (required)>'
Tasks: TOP => deploy:restart
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as cebucond@106.186.120.245: sudo exit status: 1
sudo stdout: Nothing written
sudo stderr: stdin: is not a tty
sudo: effective uid is not 0, is sudo installed setuid root?
```
I do not have the sudo access on the shared host and neither it can be provided to my user as it is a shared hosting environment as per update from shared host support team. Also it is strange that I am not using any specific server to serve my application on my remote host but still capistrano tries to run Unicorn script as can be seen in the log below and which in fact needs sudo access and hence failing.

```
INFO [e00fcb66] Running /usr/bin/env sudo /etc/init.d/unicorn_cebucondo_production restart as cebucond@106.186.120.245 
```

Here is the [link](https://gist.github.com/jiggneshhgohel/4e90ec4acf937074c248) to my `deploy.rb` file.

Can you please provide your inputs on how to get rid of the errors being encountered and make the deployment successful?

Thanks,
Jiggneshh

**Comment by leehambley** [comment]
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information (your versions (Ruby, Cap, etc), your Capfile, your logs, and relevant sections out of your Gemfile)

Otherwise support is done via the mailing list (https://groups.google.com/forum/#!forum/capistrano) or at StackOverflow (http://stackoverflow.com/questions/tagged/capistrano) with questions tagged `capistrano`.

**Comment by jiggneshhgohel** [comment]
Thanks @leehambley for the prompt reply. I have posted this question on Stackoverflow and tagged it with `capistrano3`. I already have attached the logs and deploy.rb, the Ruby version and other libraries version. This project doesn't use Bundler so it doesn't have any Gemfile and the gems used are placed in app's `vendor/plugins` folder.

Thanks.

**Comment by leehambley** [comment]
Thanks, might be worth linking the SO post here incase someone else sees it.

**Comment by jiggneshhgohel** [comment]
Sorry I forgot to do that earlier. Here is the link to Stackoverflow post: http://stackoverflow.com/questions/28496061/deploying-a-legacy-rails-2-3-application-on-a-shared-host-and-facing-sudo-access

Thanks.

**Comment by jiggneshhgohel** [comment]
[Here](http://stackoverflow.com/a/28496357/936494) is the accepted answer and my own comment to it describing how the deployment was made successful.

Closing it now.
