### ISSUE TITLE
Sudo Tasks Hang on Asking for Password

### ISSUE THREAD

**Issue by zquintana** [capistrano/capistrano#1378]
I have the following capistrano 3 task:

~~~ rb
desc 'Add root scheduled tasks'
task :root_schedules do
  on roles(:all) do 
    within release_path do
      execute :sudo, :bundle, 'exec whenever -w config/root_schedule.rb -u root'
    end
  end
end
~~~

I need this task to run with sudo privileges because I need the scheduled tasks to run with higher privileges. These are backend scheduled server tasks. Problem is that everytime I run this command I get following:

~~~ terminal
DEBUG [46d3800c] 	[sudo] password for [user]
~~~

After I type my password and hit enter, it never completes anything. No response at all. Any answers out there?

And before anyone asks, yes pty is set to true like:

~~~ rb
set :pty, true
~~~

**Comment by leehambley** [comment]
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information (your versions (Ruby, Cap, etc), your Capfile, your logs, and relevant sections out of your Gemfile)

Otherwise support is done via the mailing list (https://groups.google.com/forum/#!forum/capistrano) or at StackOverflow (http://stackoverflow.com/questions/tagged/capistrano) with questions tagged `capistrano`.

**Comment by robd** [comment]
This fixed the problem (which is an issue) for me: https://github.com/kentaroi/sshkit-sudo

**Comment by zquintana** [comment]
Thanks for the input, I'm going to check it out.

**Comment by robd** [comment]
OK - great, thanks. I'm not sure if this helps, but here is my setup:

- Ruby 2.0.0-p598 
- capistrano (3.4.0)
- capistrano-bundler (1.1.4)
- capistrano-rails (1.1.2)
- sshkit (1.7.1)
- net-scp (1.2.1)
- net-ssh (2.9.2)

Server is a new Ubuntu Trusty (14.04) LTS box

**Comment by leehambley** [comment]
They do not "hang" they are waiting for input which you cannot provide since this is a non-interactive session. http://capistranorb.com/documentation/advanced-features/ptys/

**Comment by robd** [comment]
OK, I'm confused here. My understanding from that [article you linked to](http://capistranorb.com/documentation/advanced-features/ptys/), (which I had read before), was by setting `:pty` to `true`, this should make the session 'interactive', and allow me to provide the input. This was the OPs understanding too:

> And before anyone asks, yes pty is set to true like:
> set :pty, true

Is this your understanding? Or would you still expect this not to work even if after calling `set :pty, true`?

To be clear, this doesn't work. The password I type is echoed on screen, but it doesn't get passed to the server, and the execution doesn't continue.

The [gem](https://github.com/kentaroi/sshkit-sudo) I linked to fixes this issue and allows the password to be captured, and execution continues as expected.

Others with this issue:
- http://stackoverflow.com/questions/19948809/capistrano-3-sudo-task
- http://stackoverflow.com/questions/28598799/capistrano-3-sudo-password-hangs
- http://stackoverflow.com/questions/23781619/sudo-command-for-restart-in-rails-4-capistrano

**Comment by Aathi** [comment]
@zquintana Hello,
I am also facing the same issue ,
DEBUG [46d3800c]    [sudo] password for [user]
 Have you find the solution for this? I have tried https://github.com/kentaroi/sshkit-sudo but no use

**Comment by leehambley** [comment]
This issue is closed, if you read the history you will see why. `sudo` is badly behaved and is prompting for a password when Capistrano does not advertise the system facility to answer it. You might read https://github.com/capistrano/sshkit#interactive-commands
