### ISSUE TITLE
Hi All im using capistrano 3.3.5 

### ISSUE THREAD

**Issue by juniorruby** [capistrano/capistrano#1380]
Hi All ,
           Im new to this capistrano , rails project .

I have one issue . while deploy rails code with capistrano i can able to see the logs in terminal .
But unable to print into a file ...

i have tried linux native method 

cmd  > output.log not working
cmd  2>&1 | tee also not working...

Which is the best way to capture capistrano stadard output & error redirect into an file 

Thanks in advance .

**Comment by leehambley** [comment]
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information (your versions (Ruby, Cap, etc), your Capfile, your logs, and relevant sections out of your Gemfile)

Otherwise support is done via the mailing list (https://groups.google.com/forum/#!forum/capistrano) or at StackOverflow (http://stackoverflow.com/questions/tagged/capistrano) with questions tagged `capistrano`.

**Comment by juniorruby** [comment]
ruby version = ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
cap version =  Capistrano Version: 3.3.5 (Rake Version: 10.4.2)
os -= centos 6.5 64bit
gem version = 2.4.5

=============================================
Capfile pasted below

# Load DSL and set up stages
require 'capistrano/setup'

# Include default deployment tasks
require 'capistrano/deploy'

set :rbenv_type, :exptest
set :rbenv_ruby, '2.1.5'
# Include tasks from other gems included in your Gemfile
#
# For documentation on these, see for example:
#
#   https://github.com/capistrano/rvm
#   https://github.com/capistrano/rbenv
#   https://github.com/capistrano/chruby
#   https://github.com/capistrano/bundler
#   https://github.com/capistrano/rails
#   https://github.com/capistrano/passenger
#
require 'capistrano/rbenv'
 require 'capistrano/bundler'
 require 'capistrano/rails/migrations'
 require 'capistrano/passenger'


# Load custom tasks from `lib/capistrano/tasks' if you have any defined
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }


=================================================================

runcap.sh 

#!/bin/bash

main()
{
	setupenv
	archivelogs
	printenv
        echo -e "\033[104m Server: \033[1m `hostname` \033[21m"
        echo -e " Environment: \033[1m $capenv \033[21m \033[0m"
        echo -e "\033[7m Please verify the values above. \033[5m [Enter to Continue]\033[0m"
        read 
	
#	warnenv

	read -p "Ready to run task $captask [yY]? " readytorun
	if [ x$readytorun = 'xy' -o x$readytorun = 'xY' ]
		then
		echo Running cap $capenv $captask ..
		runcaptask $capenv $captask
	else
		echo Come back when ready..
	fi
}

archivelogs(){
	if  ls $CAPDIR/*cap_run*.txt &> /dev/null; then
	ts=`date +"%d%b%Y"`
	mkdir -p $CAPDIR/logs
	(cd $CAPDIR  && tar --remove-files -czf logs/$ts.tgz *cap_run*.txt)
	#(cd $CAPDIR && mv *cap_run*.txt /tmp)
	echo "INFO: Archived logs to logs/$ts.tgz"
	fi
}
setupenv()
{
	CAPDIR="/home/testuser/apps"
	CAPEXE="/home/testuser/.rbenv/versions/2.1.5/bin/cap"
	MAILRECIP="junior@ruby.com"
	export CAPDIR CAPEXE MAILRECIP
}

emaillogs()
{
	test -p sock || mkfifo sock
	(echo 'set realname="Capistrano QA Buildserver"'; echo 'set from="junior@ruby.com"'; echo 'set use_from=yes') > sock &
	mutt -x -F sock  "$MAILRECIP" -a "$2"  -s "Cap $3 from $1 `date '+%Y/%m/%d %H:%M'`"  <<-EOF
	EOF
}

readtag()
{
	echo 
	read -p "Enter BRANCH value or leave blank to use trunk as repository: " BRANCH
	export BRANCH
	echo
}

printenv()
{
	echo "Select Target environment"
        echo "1). Development"
	echo "2). Staging"
	echo "3). Production"
	read -p 'Enter target environment number [1,2]: ' capenv
	case $capenv in
	1) export capenv=development
	warnenv 'dev';;
	2) export capenv=staging
	warnenv 'qa';;
	3) export capenv=production
	warnenv 'prod';;
	*)
		echo Invalid environment.. exiting..
		exit 1
		;;
	esac
	printmenu
}
warnenv(){
	if [ -n "$1" ] && [ `expr match ${HOSTNAME} $1` -ne 0 ]; then
	true
	else
        echo -e "\033[104m Selected environment does not match server naming convention, please 
verify. \033[0m"
	read "Enter any key continue or CTRL+C to exit"
	fi	
}	
printmenu()
{
	echo -e '\nSelect Cap Task'
	echo "1). deploy (Idempotent - Cold + Incremental)"
	echo "2). deploy:restart"
	read -p 'Enter Cap Task number [1-2]: ' captask
	case $captask in
	1) 
		export captask="deploy"
		readtag
		;;
	2) export captask="deploy:restart";; 
	*)
		echo Invalid Cap Task.. exiting..
		exit 1
		;;
	esac
}

runcaptask()
{
	if [ -d $CAPDIR ]
		then
		cd $CAPDIR
		CAPERRFILE=$1_cap_run_error.txt
		CAPOUTFILE=$1_cap_run_out.txt
		test -f $CAPERRFILE && rm -f $CAPERRFILE
		test -f $CAPOUTFILE && rm -f $CAPOUTFILE
		$CAPEXE $1 $2 1>&2 | tee >( grep -v '** \[err ::' > $CAPOUTFILE ) >( egrep "** \[err ::|rolling back|Not a valid URL" > $CAPERRFILE)	
sleep 2
		if [ -s $CAPERRFILE ]
			then
			echo -e "\n === Errors encountered during the load, error file will be emailed.. ====\n"
			emaillogs $1 "$CAPERRFILE" "Error log"
		fi
	sed -i 's/--username.*--no-auth-cache/--no-auth-cache/g' "$CAPOUTFILE"
	emaillogs $1 "$CAPOUTFILE" "Output log"
	else
		 echo capdir "$CAPDIR" does not exist.. exiting 1
		exit 1
	fi
}

main
