### ISSUE TITLE
Documention doesn't match code

### ISSUE THREAD

**Issue by belt-ascendlearning** [capistrano/capistrano#1384]
http://capistranorb.com/documentation/advanced-features/role-filtering/

This doesn't work.
> set :filter, :roles => %w{app web}

The code expects :role
See: https://github.com/capistrano/capistrano/blob/master/lib/capistrano/configuration/filter.rb around line 27.

**Comment by leehambley** [comment]
The docs are open for public contribution at Github, if you could send a PR we would be most grateful.

**Comment by leehambley** [comment]
https://github.com/capistrano/capistrano.github.io

**Comment by Quagh** [comment]
Same for `role_properties()` which isn't part of a release yet (still in master), but the docs already mention it. Been trying to figure out for hours why this wasn't working…

http://capistranorb.com/documentation/advanced-features/properties/

**Comment by Kriechi** [comment]
v3.4 is released - I guess this issue can be closed now?
