### ISSUE TITLE
run_locally does not run locally but ssh - Net::SSH::AuthenticationFailed 

### ISSUE THREAD

**Issue by arthurtalkgoal** [capistrano/capistrano#1387]
I added a ***run_locally task*** to my production so I can restart my server from the server's command line or cron job

```
####
# For Device to run
######
namespace :device do
  task :restart do
    run_locally do
      invoke "unicorn:restart"
    end
  end
end
```

however, when I run it I got the authentication error

```
cap production device:restart



(Backtrace restricted to imported tasks)
cap aborted!
Net::SSH::AuthenticationFailed: Authentication failed for user user@127.0.0.1

Tasks: TOP => rvm:hook
(See full trace by running task with --trace)
```
Wasn't ```run_locally``` means ***locally run it without ssh***?

I just wanna run the simple tasks like restart in my server side; hope to fix the problem or get around it.

Not sure how should I handl the setting:
```
set :ssh_options
```

**Comment by leehambley** [comment]
`invoke` calls the original task, it does not modify it to run locally.
`run_locally` applies to capture(), execute(), test(), etc only

**Comment by arthurtalkgoal** [comment]
Thanks much Lee.  Is there any standard way I can restart unicorn like the task unicirn:restart do?

Arthur CHAN

Co-founder
Talkgoal.com

**Comment by leehambley** [comment]
No.
