### ISSUE TITLE
How to execute `npm install` in a subdirectory?

### ISSUE THREAD

**Issue by chielkunkels** [capistrano/capistrano#1391]
I'm trying to execute `npm install` in a subdirectory before the release is symlinked, cause composer installs a package which requires it.

However, when I try

```ruby
within release_path + '/foo/bar' do
  execute :npm, 'install'
```

It can't install, cause it only sees `/foo/bar` as the path... am I missing something?

**Comment by leehambley** [comment]
Please see the mailing list at https://groups.google.com/forum/#!forum/capistrano for support.

**Comment by chielkunkels** [comment]
Apologies, will look there.

**Comment by leehambley** [comment]
No problem it is in the CONTRIB guidelines that people are supposed to see before opening an issue that we keep Github just for *bugs* and support happens on the list.
