### ISSUE TITLE
Net::SSH::AuthenticationFailed: Authentication failed for user user@<server_name>

### ISSUE THREAD

**Issue by ArunSakthivel** [capistrano/capistrano#1392]
I'm getting following error, while deploy in the production server,
`$ cap production rvm:check`

`SSHKit::Runner::ExecuteError: Exception while executing as user@<server_name>: Authentication  failed for user user@<server_name>
Net::SSH::AuthenticationFailed: Authentication failed for user user@<server_name>`

Here is my code in config/deploy/production.rb:
`role :app, %w{<server_name>}`
`
  server '<server_name>',
     user: 'user',
     roles: %w{app},
   ssh_options: {
     verbose: :debug,
     proxy: Net::SSH::Proxy::Command.new('ssh user@mygateway -W %h:%p')
   }
`
I can't able to access the production server

**Comment by leehambley** [comment]
Not an issue, please see the mailing list for support.
