### ISSUE TITLE
Create execute (and maybe run) methods for after that say "execute must be placed in role block"

### ISSUE THREAD

**Issue by fjfish** [capistrano/capistrano#1396]
Again - migrating from cap 2 end up with something that complains without helping find the right way. One of those bugs where thing look right but aren't - very hard to spot.

Small suggestion.

**Comment by leehambley** [comment]
I don't get it? `execute()` doesn't even exist outside of a `on()` block, and it's well documented (I thought). of course you can fix the docs

**Comment by fjfish** [comment]
http://stackoverflow.com/questions/27654445/nomethoderror-undefined-method-execute-or-run-capistrano-3 

This guy couldn't see what it was - creating a method that points it out to him would have helped. When you're in one of those blind spots very hard to see. 

Occurred to me that it would be helpful for noobs and folk migrating to see - "execute needs to be in a role block". Stop a lot of wheel spinning.

**Comment by troelskn** [comment]
I believe this issue has been resolved with #1723

**Comment by mattbrictson** [comment]
> I believe this issue has been resolved with #1723

Yes, good catch. Thanks!
