### ISSUE TITLE
PR #1097 breaks deployment

### ISSUE THREAD

**Issue by chrisbloom7** [capistrano/capistrano#1398]
Not sure if this is a bug for me based on my setup, or a bug in general. Unless there's something super funky with my setup, I can't see this working for anyone. 

PR #1097 changed the task `deploy:symlink:release` to:

    task :release do
        on release_roles :all do 
            tmp_current_path = release_path.parent.join(current_path.basename)
            execute :ln, '-s', release_path, tmp_current_path
            execute :mv, tmp_current_path, current_path.parent
        end
    end

During deployment, the following paths are present: 

    (byebug) release_path
    #<Pathname:/home/deploy/rails/app_1/releases/20150318194322>
    (byebug) release_path.parent
    #<Pathname:/home/deploy/rails/app_1/releases>
    (byebug) current_path
    #<Pathname:/home/deploy/rails/app_1/current>
    (byebug) current_path.basename
    #<Pathname:current>
    (byebug) current_path.parent
    #<Pathname:/home/deploy/rails/app_1>

Which ends up trying to execute:

    /usr/bin/env ln -s /home/deploy/rails/app_1/releases/20150318194322 /home/deploy/rails/app_1/releases/current
    /usr/bin/env mv /home/deploy/rails/app_1/releases/current /home/deploy/rails/app_1

Which fails with

    mv: cannot overwrite directory ‘/home/deploy/rails/app_1/current’ with non-directory

Before the PR, it would have:

    /usr/bin/env rm -rf /home/deploy/rails/app_1/current
    /usr/bin/env ln -s /home/deploy/rails/app_1/releases/20150318194322 /home/deploy/rails/app_1/current
    
I have a multi-passenger app setup using Apache. There is one vhost with a `DocumentRoot` of `/var/www/html`. Each app's public folder is already symlinked into that folder:

    $ ls -Al /var/www/html
    total 8
    -rw-r--r-- 1 root root 1234 Mar 17 12:48 index.html
    lrwxrwxrwx 1 root root   43 Mar 17 12:47 ridepilot -> /home/deploy/rails/app_1/current/public
    -rw-r--r-- 1 root root   26 Mar 17 11:58 robots.txt

I have deploy/staging.rb configured as such:

    set :branch, 'my_feature'
    set :rvm_ruby_version, '2.2.0@app_1'
    set :deploy_to, '/home/deploy/rails/app_1'
    set :rails_env, 'staging'
    server 'apps.my-host.org', roles: [:app, :web, :db], user: 'deploy'

**Comment by chrisbloom7** [comment]
Aaaaaaaaaaaaand...  user error. I had setup /home/deploy/rails/app_1/current/public as physical directories so that I could setup the symlink in Apache. deleted them, and it worked.

**Comment by bogdanRada** [comment]
i am having same issue? can you please tell me how you fixed it? I can't seem to figure it out.

**Comment by chrisbloom7** [comment]
@bogdanRada Just make sure any directory that Capistrano is going to try to symlink to doesn't exist as a physical directory. That should probably also go for any file or directory you added to the `:linked_files` or `:linked_dirs` config option.

**Comment by milushov** [comment]
same issue on the last `3.5` version, it's so weird to move symlink somewhere.. 😬

**Comment by bogdanRada** [comment]
Ahh yes, forgot to update this thread, but suggestion from @chrisbloom7  really helped me and i fixed this a long time ago :) Maybe you can try same thing @milushov  and see if that works. For me it did the trick :)

**Comment by zykadelic** [comment]
I ran into the same issue running 3.11.0, together with capistrano/maintenance 1.2.0. I managed to resolve it by, after a failed deploy, deleting the `mysite/current` directory and running `ln -s mysite/releases/VERSION mysite/current` and redeploying.

**Comment by jmuheim** [comment]
My hoster Nine.ch creates the folder `current/public` when creating a new virtual host. That's why the folder exists already. I have to manually remove it (`$ rm -rf current`), so the deployment works.
