### ISSUE TITLE
Host comparison should also check for ports.

### ISSUE THREAD

**Issue by ShogunPanda** [capistrano/capistrano#1400]
Hi all!

Currently Capistrano does this:

```ruby
class Capistrano::Configuration::Server
  def matches?(other)
    hostname == other.hostname
  end
end
```

which only check against the hostname.
Should we include the port as well? Otherwise it's impossible to differentiate the server basing the full address.

```ruby
class Capistrano::Configuration::Server
  def matches?(other)
    hostname == other.hostname && port == other.port
  end
end
```

**Comment by mattbrictson** [comment]
This seems like a very rare scenario that we don't need to support. As a work around, you could give each host+port combination a unique alias using SSH config `Host`s.

**Comment by mattbrictson** [comment]
Re-opening as it seems multiple people have reported this.

**Comment by ShogunPanda** [comment]
I thing you addressed this. Closing this one.
