### ISSUE TITLE
Rails commands not working on production deployed with capistrano 3.4.0

### ISSUE THREAD

**Issue by turboMaCk** [capistrano/capistrano#1401]
Rails console and other rails cmds not working on versions deployed with **Capistrano 3.4.0**. Tested over SSH and [capistrano-rails-console](https://github.com/ydkn/capistrano-rails-console) gem.

```shell
# in [path]/current
$ bundle exec rails console production
# or
$ ~/.rbenv/bin/rbenv exec bundle exec rails console production # I'm using rbenv on my server
Usage:
  rails new APP_PATH [options]
...
```

It looks like rails do not recognize rails project deployed with capistrano + capistrano/rails.

I have no problem using rails cmds on instances deployed with version **3.2.1**

Is it a bug or is there new way to run rails cmds on production/staging??

**Comment by leehambley** [comment]
It's apparently an issue with whatever Gem you are using that provides this behaviour. Please feel free to link an opened issue there for anyone that mistakenly stumbles upon this one.

**Comment by turboMaCk** [comment]
I already opened issue in capistrano-rails-console gem https://github.com/ydkn/capistrano-rails-console/issues/6 but I think that this is issue with capistrano since I'm not able run rails console directly on my server (over SSH) and I haven't found a way to run any rails command on my server with app deployed with capistrano 3.4.0 so there's no way to make this gem working with 3.4.0

**Comment by leehambley** [comment]
Its not Capistrano, maybe some other Gems, plugins, rvm, etc, but there is
literally no possible plausible way that capistrano could have broken
something itself.
