### ISSUE TITLE
Documented walkthrough on how to programmatically use Capistrano in Ruby

### ISSUE THREAD

**Issue by ezekg** [capistrano/capistrano#1403]
The documentation [on this topic](http://capistranorb.com/documentation/advanced-features/capistrano-pure-ruby/) seems out of date, or incorrect. The example code given does not work correctly. Can we get a more thorough explanation of which files to `require` and which methods to use to set a deployment config and initiate a deploy from within a single Ruby script?

I'm trying to integrate Capistrano into an existing command line application, with configuration kept in a Yaml file, and have run into numerous issues trying to configure Capistrano to actually run without the typical configured `deploy.rb` and `Capfile`.

There just doesn't seem to be a clear API to allow something like this, yet the documentation above hints that it should be possible. Any advice on getting a little more up to speed on the _correct_ way to do something like this?

**Comment by leehambley** [comment]
Seems like the issue belongs on the doc repo, you're right it's out of date, but it can be made to work.

**Comment by ezekg** [comment]
Sorry, I wasn't aware that there was another repo for the docs. Do you want me to move this over there?

**Comment by kirs** [comment]
Yes, please
