### ISSUE TITLE
Capistrano not matching servers on deploy

### ISSUE THREAD

**Issue by dphaener** [capistrano/capistrano#1406]
I'm deploying using Capistrano 2.15.5 and having an issue running a custom task I created in an `after("deploy:restart")` hook.

Here's the tasks that I have defined:

    desc "Fire up the sidekiq web ui for the imports queue"
    task :start_sidekiq_web, :roles => [:web], :except => { :no_release => true }, :on_error => :continue  do
      run("cd #{current_path}; RACK_ENV=#{fetch(:rails_env)} bin/rackup sidekiq-web.ru")
    end

    desc "Stop the sidekiq web ui server for the imports queue"
    task :stop_sidekiq_web, :roles => [:web], :except => { :no_release => true }, :on_error => :continue  do
      run("kill `cat #{current_path}/tmp/pids/sidekiq-web.pid`")
    end
 
    before("deploy:restart", "deploy:stop_sidekiq_web")
    after("deploy:restart", "deploy:start_sidekiq_web")

I have the :web role setup, and several other tasks use it without a problem, and the stop_sidekiq_web task runs without any issues. 

Here's the piece of the deploy that works for the accompanying task:

    * 2015-03-24 07:52:05 executing `deploy:stop_sidekiq_web'
    * executing "kill `cat /home/app/drip/current/tmp/pids/sidekiq-web.pid`"

And then calling the start task: 

    * 2015-03-24 07:52:13 executing `deploy:start_sidekiq_web'
    * no servers for "cd /home/app/drip/current; RACK_ENV=staging bin/rackup sidekiq-web.ru"

**Comment by leehambley** [comment]
Sorry @dphaener we don't have the manpower to support 2.x anymore, you might have more luck on the mailing list where some people who're also still using 2x do still hang out!

**Comment by dphaener** [comment]
Understandable. We're thinking of moving to 3.x anyway. That may solve our problem. :+1:

**Comment by leehambley** [comment]
Ping me (also on the mailing list) if you have any problems with the 3x migration, it always does me good to coach people through the tough parts so that I can figure out how to smooth them out! See you on the other side!

**Comment by prcongithub** [comment]
Any update on this? @dphaener were you able to solve this?

**Comment by dphaener** [comment]
@prcongithub I honestly can't remember it's been so long. 😆 I would suggest migrating to 3.x since they aren't supporting 2.x anymore. All of my apps are currently on 3.x and I haven't had this type of issue on that version. Sorry I couldn't be of more help!
