### ISSUE TITLE
bundle stderr: /home/deploy/.rvm/scripts/set: line 19: exec: bundle: not found

### ISSUE THREAD

**Issue by adiakritos** [capistrano/capistrano#1408]
Here is the full error.
    Command: cd /var/www/apps/PersonalApp/releases/20150326201706 && ~/.rvm/bin/rvm default do bundle install --path /var/www/apps/PersonalApp/shared/bundle --without development test --deployment --quiet
    DEBUG [8cd0e53c]    /home/deploy/.rvm/scripts/set: line 19: exec: bundle: not found

I get a similar error that seems to be asking for bundle, looking for it in the env path but it's not findable. 

cd /var/www/apps/PersonalApp/releases/20150326205357 && /usr/bin/env bundle install --path /var/www/apps/PersonalApp/shared/bundle --without development test --deployment --quiet
DEBUG [34eb93b4]    /usr/bin/env:
DEBUG [34eb93b4]    bundle
DEBUG [34eb93b4]    : No such file or directory

**Comment by Kriechi** [comment]
Wild guess: is bundler installed on your server?
Try: `gem install bundler` with the correct ruby/rvm environment.

**Comment by adiakritos** [comment]
I had tried that already. We might as well close this thread because I terminated that EC2 instance and started again without a deploy user. I suspected that there was some confusion with exactly where bundler was installed. But now I've installed it on the default user and it seems to work fine. Thanks for your assistance though.

**Comment by jono-tt** [comment]
I had a similar issue and found that it was an issue in my "deploy.rb" setup where I was specifying the ruby version but i use a different gemset so that is why bundler wasn't being found. Might help someone else experiencing this issue:

```
set :rvm_ruby_version, '2.2.2'
```
became:
```
set :rvm_ruby_version, '2.2.2@my_gemset_name'
```

**Comment by will-in-wi** [comment]
Sounds like this has been resolved.
