### ISSUE TITLE
Can't deploy Rails apps using sprockets 3

### ISSUE THREAD

**Issue by byroot** [capistrano/capistrano#1418]
Sprockets 3 released recently changed the manifest path: 

```
Renaming /u/.../releases/.../public/assets/manifest-ab5dee974c76c3e103b9ea6ce1d15fc0.json to /u/.../releases/.../public/assets/.sprockets-manifest-0998110c17d5a019c2dd8b92b490aa8d.json
```

So then the `backup_manifest` task fails:

```
cp: cannot stat `/u/.../releases/.../public/assets/manifest*': No such file or directory
```

I'll try to submit a PR to fix this latter this week.

**Comment by 9mm** [comment]
Awesome, I was just looking for an answer for this the last few days. I was going crazy thinking no one else was having a problem, but I wasn't sure how to fix it :+1:

**Comment by wzcolon** [comment]
:+1:

**Comment by sime** [comment]
Thanks for logging the issue, it helps reducing grey hairs :)

**Comment by jaredbeck** [comment]
I think this has been fixed in [capistrano-rails][1] 1.1.3.

[1]: https://github.com/capistrano/rails/blob/master/CHANGELOG.md

**Comment by 9mm** [comment]
Yep, new capistrano-rails fixed it for me.

**Comment by leehambley** [comment]
So, I'll just close the issue then… mmkay?

**Comment by sime** [comment]
Just pushed this. Thanks. :+1:
