### ISSUE TITLE
Having trouble with a wildcard scp (on an execute command)

### ISSUE THREAD

**Issue by johnkharvey** [capistrano/capistrano#1419]
Hello folks,

I'm using Capistrano 3.2.1, and I am noticing that I can't copy a directory recursively.

Here's my command:
execute "sudo cp -R /tmp/scriptdir/scripts/* /opt/destinationdir/scripts/."

Both directories are there.  I can manually go to the server and run this exact command and it works.
I can also run the command with non-wildcard files through capistrano and they copy just fine.  It seems to be choking on the wildcard.

I get the following error:
SSHKit::Command::Failed: sudo cp -R /tmp/scriptdir/scripts/* /opt/destinationdir/scripts/. exit status: 1
/tmp/scriptdir/scripts/* /opt/destinationdir/scripts/. stdout: Nothing written

Any ideas what I can do to copy a full directory's inner contents recursively with a wildcard?  I've tried escaping it, and putting the command inside of quote marks-- there doesn't seem to be any effect.

I'd appreciate any input anyone could give me-- I'm stumped for now.

**Comment by leehambley** [comment]
Support is usually done via the mailing list (https://groups.google.com/forum/#!forum/capistrano) or at StackOverflow (http://stackoverflow.com/questions/tagged/capistrano) with questions tagged `capistrano`, it helps keep the issues here focused.

Best guess is that `sudo` is prompting for a password, which you can't provide when it's non-interactive, as with Capistrano, if you need to use `sudo` in this way you need to make sure that your deploy user has access to `sudo cp` without being prompted for a password.

I've closed this issue, if that's not the problem, ping the mailing list, and I'll try and help you there. I'm in CEST timezone, so now is pretty much the end of my day. 

If you're trying to upload a directory of arbitrary things, try https://github.com/capistrano/sshkit/blob/master/EXAMPLES.md#upload-a-directory-of-files (the permissions hints will still apply), Capistrano is backed by SSHKit so all the methods there are available to you.
