### ISSUE TITLE
Rollback documentation is missing

### ISSUE THREAD

**Issue by kapowie** [capistrano/capistrano#1420]
The rollback documentation is missing:
http://capistranorb.com/documentation/getting-started/rollbacks/

Is this feature supported in capsitrano 3 as I know this used to exist in capistrano 2?

**Comment by leehambley** [comment]
Seems like this issue belongs on the documentation repository. Yes rollbacks works exactly like they did in v2, and are documented here http://capistranorb.com/documentation/getting-started/flow/
