### ISSUE TITLE
Capistrano breaks when new deploy started before previous finished

### ISSUE THREAD

**Issue by zdraganov** [capistrano/capistrano#1424]
I was doing `cap staging deploy` and before it was finished I saw that other team member tried to do same thing as well. Both deploy finished successfully.

After second deploy was finished I saw that there's exception into the unicorn.god.log (used by God gem to log unicorn start/restart/stop errors).
```
/usr/local/rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.4/lib/bundler/definition.rb:22:in `build': /home/deployer/apps/xxxxxxxxxxxx/releases/20150428140210/Gemfile not found (Bundler::GemfileNotFound)
```
As you see, I'm using God for managing server processes with touching file in tmp folder for restarting the Unicorn server.
My Capistrano version is 3.3.5

Is there any clear way to handle this scenario?

**Comment by leehambley** [comment]
Communication! There are [some solutions](https://github.com/ndbroadbent/capistrano_deploy_lock) which may or may not be appropriate for your team, but lock-files have a habit of going stale. You might also consider using a service like the one we're building to collaborate on your deployments at https://www.harrow.io/ (Official web based Capistrano (and more) service) launching in a few weeks.

**Comment by mattbrictson** [comment]
I agree; I think this is better solved by an external plugin (or communication) and not by Capistrano itself. Closing as "won't fix".
