### ISSUE TITLE
LoadError: cannot load such file -- capistrano/rbenv

### ISSUE THREAD

**Issue by lahmiro** [capistrano/capistrano#1425]
I followed this tutorial https://gorails.com/deploy/ubuntu/14.04 to deploy my rails app on digital ocean, but when I run cap production deploy, I got the following error messages:
<pre>
<code>
/home/notepad/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/capistrano-3.1.0/lib/capistrano/i18n.rb:4: warning: duplicated key at line 6 ignored: :starting
cap aborted!
LoadError: cannot load such file -- capistrano/rbenv
/home/notepad/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/notepad/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/notepad/notepad/Capfile:6:in `<top (required)>'
/home/notepad/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/home/notepad/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/home/notepad/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/home/notepad/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/home/notepad/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/notepad/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/home/notepad/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/capistrano-3.1.0/lib/capistrano/application.rb:24:in `load_rakefile'
/home/notepad/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/home/notepad/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/notepad/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/notepad/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/capistrano-3.1.0/lib/capistrano/application.rb:15:in `run'
/home/notepad/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/capistrano-3.1.0/bin/cap:3:in 'top (required)'
/home/notepad/.rbenv/versions/2.2.2/bin/cap:23:in `load'
/home/notepad/.rbenv/versions/2.2.2/bin/cap:23:in 'main'
</code>
</pre>

In my Capfile:
<pre>
<code>
require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/bundler'
require 'capistrano/rails'
require 'capistrano/rbenv'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
</code>
</pre>

Gemfile:
<pre>
<code>
gem 'capistrano', '~> 3.1'
gem 'capistrano-bundler', '~> 1.1.2'
gem 'capistrano-rails', '~> 1.1'
gem 'capistrano-rbenv', github: "capistrano/rbenv"
</code>
</pre>

Any suggestions? 

Thank you!

**Comment by kirs** [comment]
Please make sure you use `bundle exec` to call the `cap` command and feel free to open a discussion in the mailing list.
I believe that it's not a capistrano bug.
