### ISSUE TITLE
rewrite the deploy rules:

### ISSUE THREAD

**Issue by kevin25** [capistrano/capistrano#1433]
Hello,

I am trying to rewrite the rules but i haven't succeed yet. Please help me.

namespace :deploy do

  task :link_uploads, :roles => :app do
    run "ln -s #{shared_path}/uploads #{release_path}/public/uploads"
  end

  task :link_receipts, :roles => :app do
    run "ln -s #{shared_path}/cache/receipts #{release_path}/cache/receipts"
  end

  task :start, :roles => :app do
    run "cd #{deploy_to}/current/; RAILS_ENV=production bundle exec unicorn_rails -c #{unicorn_path} -D"
  end

  task :stop, :roles => :app do
    run "if [ -e '#{deploy_to}/shared/pids/unicorn.pid' ]; then kill -QUIT `cat #{deploy_to}/shared/pids/unicorn.pid`; fi"
  end

  task :restart, :roles => :app do
    stop
    start

  end
end

task :notify_rollbar, :roles => :app do
  set :revision, `git log -n 1 --pretty=format:"%H"`
  set :local_user, `whoami`
  set :rollbar_token, 'token_here'
  rails_env = fetch(:rails_env, 'production')
  run "curl https://api.rollbar.com/api/1/deploy/ -F access_token=#{rollbar_token} -F environment=#{rails_env} -F revision=#{revision} -F local_username=#{local_user} >/dev/null 2>&1", :once => true
end

after "deploy:update", "deploy:link_uploads", "deploy:link_receipts"
after :deploy, 'notify_rollbar'

Thanks,

**Comment by leehambley** [comment]
Sorry, support is done on our mailing list.
