### ISSUE TITLE
multiple roles with 3.4.0

### ISSUE THREAD

**Issue by esalter** [capistrano/capistrano#1434]
Sorry if this is already reported.  I'm not sure what happened, but when I updated to 3.4.0 (no other changes), Cap is failing to find one of my servers.  The only thing different about it is it has multiple roles:

server 'aws-dev-http', batch_server_id: 2, roles: %{app build}

I don't think i'm doing anything complex, just simply:

on roles(:build) do ... end   

That returns nothing.  If I use :app instead, it finds all other servers defined as an app role, except for that one.  Reverting to 3.3.5 fixed the issue.  I glanced through the diff and saw something to do with roles_properties but I don't know exactly what broke this.  Does this need to be defined in a different way?  I'm only defining my servers via "server", not via "role".

**Comment by leehambley** [comment]
That sounds indeed like a bug. I think that *might* be happening, assuming that's not a typo in your post:

```
$ irb
irb(main):001:0> %{app build}
=> "app build"
irb(main):002:0> %i{app build}
=> [:app, :build]
```

This way, I'm not sure why "app" would match (I think, maybe in the beginning of the string?) - where "build" doesn't because it's at the end. Double check please, and let me know, if this is really broken, we screwed something up pretty badly.

Cheers, Lee

**Comment by esalter** [comment]
Sorry if I misspoke.  What I mean is, my other servers that ONLY have %{app} defined work.  The one that has %{app build} doesn't work at all, for either role.  (listing roles(:build) returns absolutely nothing, but roles(:app) returns only those servers that ONLY have :app defined).  

Here's the complete server list:

server 'aws-prod-us', batch_server_id: 26, roles: %{app}
server 'aws-prod-eu', batch_server_id: 40, roles: %{app}
server 'aws-prod-sgp', batch_server_id: 30, roles: %{app}
server 'aws-dev-http', batch_server_id: 2, roles: %{app build}

So, when I do roles(:app) I only get the first three, and roles(:build) doesn't return anything.

I haven't used %i{app build} ...i'll try that, but again this is working in 3.3.5.

**Comment by esalter** [comment]
I'm relatively new to ruby as well - if this is some stupid thing I'm doing with ruby feel free to call me out on it, but I'm pretty sure I lifted this directly from the docs.

**Comment by esalter** [comment]
looks like modifying it to %i{app build} works.  I managed to capture the server configuration, and it listed the role as :"app build".  So if that's the recommended way to define roles moving forward that's fine, but it would be nice if it didn't break bc. :)  I'll modify my script.

**Comment by esalter** [comment]
Wow, i'm pretty dumb, the docs do say %w, and I must have fatfingered the delete key at some point.  Sorry!  Please disregard this issue.

**Comment by leehambley** [comment]
It was working by coincidence last time, %i{} and %w{} define sets, or
arrays ( symbols or strings) and %{} just defines a string (whitespace and
all), if it worked previously, you'd just been relying on quirks of the old
matching implementation, its supposed to define a set/array

**Comment by esalter** [comment]
yup. :)  PEBKAC.  sorry about that.
