### ISSUE TITLE
Allow easily selecting deployed branch from CLI

### ISSUE THREAD

**Issue by flyswatter** [capistrano/capistrano#1436]
I understand capistrano pre-`v3` supported an `-S` flag that allowed selecting the deployed branch.

Nowadays it seems it's preferred to define the branch in a config file.

I understand [there are ways](http://stackoverflow.com/a/21067630/272576) to specify the branch from the CLI, but they look like hacks to me.

I think Capistrano should restore first-class support for specifying a deploy branch from the CLI.

**Comment by lkang** [comment]
+1, I used to use -S a lot.  Wouldnt be hard to put back...

**Comment by leehambley** [comment]
It's removed intentionally because you can fix it by doing:

    set :branch, ENV.fetch(:BRANCH, 'master')

and specifying `BRANCH` on the CLI when calling into Capistrano. This isn't a "hack"
