### ISSUE TITLE
Support for dynamic roles

### ISSUE THREAD

**Issue by frankh** [capistrano/capistrano#1438]
I have an expensive lookup for servers in a certain role, so I don't want to perform the lookup for every cap task. Looking through the 2.x docs it looks like in capistrano 2 you could pass the role command a block and have it lazily evaluated[1], is that still possible in cap 3?

At the moment I'm having to invoke a task to load the servers in every single task where the role is used, which obviously isn't ideal

[1] https://github.com/capistrano/capistrano/wiki/2.x-DSL-Configuration-Roles-Role

**Comment by leehambley** [comment]
>At the moment I'm having to invoke a task to load the servers in every single task where the role is used, which obviously isn't ideal

What's to stop you running that loader code in the top of your `<stage>.rb`/`deploy.rb` file, and assigning them to the `{roles: …}` part of the server definition?

**Comment by frankh** [comment]
I only want the roles to be evaluated when calling a task that actually uses the role. 

The other alternative to what I'm doing would be to load the servers even for small tasks that run on a single server (in a static role)

**Comment by leehambley** [comment]
I don't see the use-case personally, if you're doing some API calls to look up roles, then you can easily do that up-front, for one or many machines, if you want to lazy evaluate it, that sounds a bit contrived (i.e wait until you're in the middle of something important, before risking reliance on a 3rd party server.)

We'd take a patch, if you wanted to write one, all the code along these paths is relatively simple, and well tested and robust, but I don't see myself implementing it, sorry.
