### ISSUE TITLE
Access to Rake::Task

### ISSUE THREAD

**Issue by sts** [capistrano/capistrano#1441]
Is there a way to access the current instance of Rake::Task from within rake or ruby methods which are defined in rake?

**Comment by leehambley** [comment]
You can call `Rake::Task[:task_name]` from anywhere that has the code loaded. If you wanted to load the Capistrano recipes from pure Ruby, you might have success simply `load`ing (you might also try `require`ing it, but the semantics can be different with rake under some circumstances) and calling `Rake::Task[:'deploy:starting'].invoke`

https://github.com/ruby/rake might be a better place to ask
