### ISSUE TITLE
capistrano corrupted terminal output

### ISSUE THREAD

**Issue by peter-umb** [capistrano/capistrano#1446]
I am working on deploying 3 servers with capistrano, rvm, ruby1.9.3, rails3.2.1. While setting up, I ran (. capify) on one of the servers and it complained about a version mismatch between my local and the server.  local-2.11.2   server- 3.4. I upgraded the local machine to 3.4 and ran a cap deploy. Doing so corrupted my terminal output. The output no longer comes out in neat little rows and displays like it has random tabs throughout making it harder to read. So I downgraded each version back to 2.11.2 and did a bundle install. Now, when I run cap deploy instead of asking for the password once for 3 servers it asks 5-7 times and usually fails with Authentication failed for user... I did a 'reset' in the terminal which seemed to correct some of the indentation issue, but definitely not all. (echo -e "\xF") did not do much either.

**Comment by peter-umb** [comment]
Just a little more info. When I run
. capify
on the remote server it now returns:
require: command not found
version: command not found
bash: /usr/local/bin/capify: line 15: syntax error near unexpected token `('
bash: /usr/local/bin/capify: line 15: `  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding'

**Comment by peter-umb** [comment]
No one has any suggestions? This is very annoying.

**Comment by leehambley** [comment]
I'm sorry you are not being coherent and I can't understand what you are doing, or anything you are attempting to say. I have no idea why you would be running `. capify` you appear to be [corrupting your own shell](http://ss64.com/bash/source.html).

Whatever you are doing forcing binary encoding is also probably not helping the situation. This is clearly not a bug in Capistrano else you would see other reports of it here, rather something you are doing wrong, come and talk to us in our Google Group support forum.
