### ISSUE TITLE
filtering roles treats String/Symbol as Regex.  This is not documented and is misleading and leads to unexpected behavior

### ISSUE THREAD

**Issue by betesh** [capistrano/capistrano#1456]
Assuming the following configuration:

    server 'host1', roles: [:all_roles_except_web]
    server 'host2', roles: [:web_and_something_else]
    server 'host3', roles: [:web]

Capistrano distinguishes between these two role filters

    roles(/^web$/) # => [host1, host2, host3]
    roles(/web/) # => [host3]

I would expect `roles(:web)` to behave like `roles(/^web$/)`--that is, if I'm using a Symbol instead of a Regex, it's because I want only servers that match my Symbol exactly.  However, instead, it gets converted to a Regex (implicitly, when :web.to_s.match is called here: https://github.com/capistrano/capistrano/blob/v3.4.0/lib/capistrano/configuration/filter.rb#L51 ), and because I did not supply `^` or `$`, it matches anything containing 'web'.

**Comment by joelataylor** [comment]
Could this be why when I have `set :filter, :roles => %w{web}` in my deploy.rb file, it seems to get ignored, however when I use the command: `ROLES=web cap production deploy:check` it works as expected?

**Comment by leehambley** [comment]
@betesh sounds like it's worth fixing, if you prepare a real PR I'd be happy to merge it

**Comment by betesh** [comment]
It looks like this was already fixed in 3.4.0 (9a2fa53d79e793100bddb48ae7283e575b162cb2)--I'm still on 3.3.5 so all I need to do is upgrade.
