### ISSUE TITLE
Capturing capistrano 3 output.

### ISSUE THREAD

**Issue by BenjaminKim** [capistrano/capistrano#1458]
```ruby
namespace :deploy do
  desc 'Notify to co-workers'
  task :notify do
    summury = "[#{fetch(:application)}](#{fetch(:stage)}) " + revision_log_message
    Mail.send_one(summury, 'my-team-mail-address@team.com')
  end

  task :notify_with_full_log do
    full_log = get_capistrano_full_log # here
    Mail.send_one(full_log, 'my-team-mail-address@team.com')
  end
end
```

I made my own task `deploy:notify` to notify deployment to my coworkers and it works well.
I would also want to make `deploy:notify_with_full_log` task but I can't find the way yet.
Is there a method or way to do this?

**Comment by leehambley** [comment]
Hi @BenjaminKim the formatters (take a look) for Capistrano live in SSHKit, mostly - and they take a standard `IO` - typically this is set to $stdout, but you could easily wrap $stdout in something else that responds to `#write`, and keeps a copy. The formatters don't always receive plain strings, they receive `Command` objects, and whatever else, and they make decisions about how to print them, you might take a look at https://github.com/mattbrictson/airbrussh for some inspiration, although you wouldn't have to go anywhere near that far, simply keep a copy of each thing that is written to your output, and then do something with it to render it for the user. That might mean that you do the same thing (mostly, just call `.to_s` on everything you receive, or you might want to do something cleverer, to make it into HTML or strip the colours/formatting for email display.

**Comment by leehambley** [comment]
I hate to bounce people to SO, but this is actually a pretty neat example of how you might do it:

```
class MultiIO
  def initialize(*targets)
     @targets = targets
  end

  def write(*args)
    @targets.each {|t| t.write(*args)}
  end

  def close
    @targets.each(&:close)
  end
end
```
(via http://stackoverflow.com/questions/6407141/how-can-i-have-ruby-logger-log-output-to-stdout-as-well-as-fil)

Although you might get what you need from Airbrussh - since @mattbrictson writes a log file along side the output, but this is pretty much how it works :) Common IO#write interfaces for the win! :rocket:

**Comment by BenjaminKim** [comment]
@leehambley :+1: Oh thank you so much.

**Comment by leehambley** [comment]
Shame on me for not linking to either
https://github.com/capistrano/sshkit/blob/master/lib/sshkit/formatters/pretty.rb
or https://github.com/capistrano/sshkit#output-handling both of which have
loads more information and reference you can use. But that little
knowledge, combined with the MultiIIO thing I linked from SO should give
you a really strong start. Also Airbrussh is awesome, I'd merge it into
SSHKit in a heart beat, and make it the default if I didn't think it was
unfair to Matt to have his work attached to something under my name.

Lee Hambley
http://lee.hambley.name/
+49 (0) 170 298 5667

**Comment by BenjaminKim** [comment]
@leehambley Thanks for your help. I close the issue. :green_heart:
