### ISSUE TITLE
ssh public authentication to server not working on OSX

### ISSUE THREAD

**Issue by maurotdo** [capistrano/capistrano#1459]
When capistrano (3.4.0) is run from OSX (mavericks), ssh public key authentication fails with the error
'Could not parse PKey: no start line'

Same setup on Debian, with the same keys, works flawlessy.

I use the default config snippet:
 ------------------------------------
```ruby
 server 'example.com',
   user: 'xxx',
   roles: %w{web app},
   ssh_options: {
     user: 'xxx', # overrides user setting above
     keys: %w(/home/xxx/.ssh/id_rsa),
     forward_agent: false,
     auth_methods: %w(publickey password)
     # password: 'please use keys'
   }
```

**Comment by robd** [comment]
Hey

What version of SSHKit are you using? I don't know anything about this, but the first google link took me to this post and SSHKit issue:

http://coding-journal.com/argumenterror-could-not-parse-pkey-no-start-line/
https://github.com/capistrano/capistrano/issues/286

Hence I wondered if you are using an old version of SSHKit.

**Comment by maurotdo** [comment]
Given your hint, i investigated my net-ssh installation.
It seems that on OSX, gem install net-ssh pulls version 2.9.2, while on Debian it pulls version 2.10.0.beta2
Forcing the same version (2.10.0.beta2) on OSX, the issue is resolved. So, it seems a bug introduced in net-ssh 2.9.x

Thank you for your help, i'm closing this issue
