### ISSUE TITLE
version 2.15.6 missing on rubygems

### ISSUE THREAD

**Issue by skaes** [capistrano/capistrano#1466]
can you please upload it?

**Comment by leehambley** [comment]
Indeed, I absolutely forgot after throwing you the .gem at the office, incoming.

**Comment by leehambley** [comment]
Done https://rubygems.org/gems/capistrano/versions/2.15.6

**Comment by dideler** [comment]
v2.15.6 is the last 2.x version released on [RubyGems](https://rubygems.org/gems/capistrano/versions) but I can't find the tag on GitHub.
Does this tag still need to be pushed?

**Comment by leehambley** [comment]
```
[master][~/Projects/capistrano/capistrano]$ git push --tags
Counting objects: 77, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (47/47), done.
Writing objects: 100% (77/77), 7.43 KiB | 0 bytes/s, done.
Total 77 (delta 50), reused 57 (delta 30)
To git@github.com:capistrano/capistrano.git
 * [new tag]         v2.15.6 -> v2.15.6
```

**Comment by leehambley** [comment]
(just pushed, sorry)
