### ISSUE TITLE
Don't shorten git sha's

### ISSUE THREAD

**Issue by z5h** [capistrano/capistrano#1468]
This line used to be `rev-parse --short` and now is `--abbrev-commit`. Why get a short SHA back? To save a few bytes? This causes problems with some API integration (namely github's) that requires a full SHA.

https://github.com/capistrano/capistrano/blob/bfc4a82359251b8fd28165fc0d981c7f8f0baf99/lib/capistrano/git.rb#L43

Happy to fix this. Just want to know if there is a valid reason for not changing it.

**Comment by leehambley** [comment]
We'll take a patch, short version is that 8 character shas are virtually immune to collisions, and you can always get the full sha given a short one.

**Comment by z5h** [comment]
> We'll take a patch

super

> you can always get the full sha given a short one

How do I do that with the Github API (not with the command line)?

**Comment by leehambley** [comment]
I really must be missing something, we use short hashes as recommended by Linus himself, if you need a long has, given a short URL, if you need a long one, simply run:

    $ git rev-parse 4cc9af6
    4cc9af6ec437675bf9fdf10a38df52cfd1bfdb26

**Comment by z5h** [comment]
If you don't have git but have a short sha, and want to use a service like github's api, you're screwed. For what gain?

**Comment by z5h** [comment]
Or convince github, and potentially any 3rd party to always support short shas.

**Comment by z5h** [comment]
Also, never mind what Linus said or collision resistance. What is the benefit of the short sha?

**Comment by leehambley** [comment]
I'm closing and locking the issue as I'm convinced you must be trolling to get a rise out of me with your incoherent argument about "convenience" when I provided a suitable snippet of code which solves the problem that you seem to be manufacturing for the sake of causing an argument.
