### ISSUE TITLE
Broken net-ssh dependency

### ISSUE THREAD

**Issue by McAnton** [capistrano/capistrano#1474]
Hi, When installing capistrano using `gem install capistrano` (on Ubuntu 14.04 with Ruby 1.9.3) I get an exception when using `cap [stage] deploy`. I have figured out that the latest version of net-ssh (v2.10.0 released on 02/08/2015) is not compatible.

It looks the latest version of net-ssh that works with capistrano is 2.9.2. I have attached a screenshot of the error.

![capistrano-error](https://cloud.githubusercontent.com/assets/2470624/9040669/8141c984-39fb-11e5-8077-a75c04c5a5b3.jpg)

**Comment by leehambley** [comment]
https://github.com/capistrano/sshkit/issues/269
