### ISSUE TITLE
Deployment ignores updated OAuth token 

### ISSUE THREAD

**Issue by ain** [capistrano/capistrano#1482]
__Steps to reproduce__:

1. Deploy from Github with OAuth token
2. Change OAuth token and update `deploy.rb` accordingly
3. Deploy again

__What happens__: old OAuth token is used, deploy fails.

__What should happen__: new OAuth token should be considered. Workaround: wiping `repo/` on server.

**Comment by GeorgMeyer23** [comment]
+1

**Comment by leehambley** [comment]
Unfortunately (we've had this a lot for various reasons before) - I don't know if this is fixable, any suggestions mate? (Where, and how are you using an oauth token?)

**Comment by ain** [comment]
On a private repo. My first idea was to produce a helper task that kills the `repo/` on the server. If you'd have a way to identify such updates, you could follow the same logic internally?

**Comment by leehambley** [comment]
So you cloned with a oauth token over https, and it was cached by the git credential cache in the repo-cahce?

**Comment by ain** [comment]
Yup, everything over OAuth.

**Comment by leehambley** [comment]
Alright, good to know - last I used https or cloning private repos the credentials weren't cached anywhere. Git is *really* badly behaved when it comes to prompting for input, etc, etc, etc.

Would you consider using a `.netrc` file, and *not* naming your OAuth key in the repo?

**Comment by ain** [comment]
Good call actually. But would it solve the cached repo problem?

**Comment by leehambley** [comment]
There'd be nothing to cache, and the .netrc would always be used, I guess?

**Comment by ain** [comment]
I'll test-drive and ping back.

**Comment by leehambley** [comment]
Cheers :)

Lee Hambley
http://lee.hambley.name/
+49 (0) 170 298 5667

**Comment by shaneog** [comment]
@ain Did the `.netrc` work? I'm using the same method (oauth token)

**Comment by leehambley** [comment]
Duplicate at #1545 where we'll fix this, see the newly linked issue there.
