### ISSUE TITLE
Testing for file existence fails, so the repo is not cloned

### ISSUE THREAD

**Issue by arnekolja** [capistrano/capistrano#1483]
I am struggling with the problem that deployment of a very simple PHP stage does not work, because the repo folder doesn't get created.

There is a thread on SO where I posted the whole problem with every config file: http://stackoverflow.com/questions/32191036/capistrano-3-4-0-repo-folder-not-deployed

I tested a lot of stuff in the discussion following this thread and it seems like testing for file existence somehow returns the wrong result. As soon as a test checks the repo folder, it decides that the folder exists and does not clone/copy the repo. Afterwards, there is still no repo folder.

Is this a bug with Cap?

Here is some debug output from `cap mystage git:clone`:

INFO [a2a97317] Running /usr/bin/env mkdir -p /tmp/appname/ as user@ipaddress 
DEBUG [a2a97317] Command: /usr/bin/env mkdir -p /tmp/appname/ 
INFO [a2a97317] Finished in 1.580 seconds with exit status 0 (successful). 
DEBUG Uploading /tmp/appname/git-ssh.sh 0.0% 
INFO Uploading /tmp/appname/git-ssh.sh 100.0% 
INFO [6a24fa43] Running /usr/bin/env chmod +x /tmp/appname/git-ssh.sh as user@ipaddress 
DEBUG [6a24fa43] Command: /usr/bin/env chmod +x /tmp/appname/git-ssh.sh 
INFO [6a24fa43] Finished in 1.090 seconds with exit status 0 (successful). 
DEBUG [7155f39d] Running /usr/bin/env [ -f /user/www.domain.com/repo/HEAD ] as user@ipaddress 
DEBUG [7155f39d] Command: [ -f /schgsvyr/www.domain.com/repo/HEAD ] 
DEBUG [7155f39d] Finished in 1.088 seconds with exit status 0 (successful). 
INFO The repository mirror is at /user/www.domain.com/repo

**Comment by leehambley** [comment]
Probably the new server doesn't have the SSH key to clone the repository, but it's hard to tell from the log. Please stick to StackOverflow, or our Google Group, Github issues is reserved for verified bugs, only.

**Comment by arnekolja** [comment]
Okay, sorry :-)
