### ISSUE TITLE
How can I stop the execute command with the default shell `/usr/bin/env`

### ISSUE THREAD

**Issue by poc7667** [capistrano/capistrano#1486]
some articles suggest me to add `set :default_shell, '/bin/bash -l'`

However, it's useless,

Any idea ? thanks~

# log

    INFO [77ebee38] Running /usr/bin/env cd /home/sample_user/workspace/web_app_production/current && whenever  -f config/worker_schedule.rb -w as sample_user@13.13.101.114
    DEBUG [77ebee38] Command: cd /home/sample_user/workspace/web_app_production/current && whenever  -f config/worker_schedule.rb -w
    DEBUG [77ebee38]    /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- dotenv (LoadError)
    DEBUG [77ebee38]        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    DEBUG [77ebee38]        from config/worker_schedule.rb:2:in `initialize'

# script

    on roles(:worker) do
      set :default_shell, '/bin/bash -l'
      within current_path do
        execute "cd #{deploy_to}/current && crontab -r ", raise_on_non_zero_exit: false
      end
    end

# capistrano config

    set :use_sudo, false
    set :rbenv_type, :user 
    set :rbenv_ruby, "2.2.2"
    set :rbenv_path, "/home/sample_user/.rbenv"
    set :rbenv_prefix, "RBENV_ROOT=#{fetch(:rbenv_path)} RBENV_VERSION=#{fetch(:rbenv_ruby)} #{fetch(:rbenv_path)}/bin/rbenv exec"
    set :rbenv_map_bins, %w(rake gem bundle ruby rails)
    set :rbenv_roles, :all 
    # set:rails_env, :production
    # set :using_rvm, false   # using rbenv
    set :rbenv_type, :user
    set :bundle_flags, "--deployment --quiet --binstubs --shebang ruby-local-exec"
    set :default_env, { path: "~/.rbenv/shims:~/.rbenv/bin:$PATH" }
    set :default_environment, {
      'PATH' => "$HOME/.rbenv/shims:$HOME/.rbenv/bin:$HOME/bin:$HOME/local/bin:$PATH"
    }
    set :bundle_binstubs, nil 
    set :log_level, :debug
    set :linked_dirs, fetch(:linked_dirs, []).push('log', 'tmp/pids', 'tmp/cache', 'tmp/sockets', 'vendor/bundle', 'public/system')
    set :linked_dirs, %w{log tmp/pids tmp/cache tmp/sockets vendor/bundle public/system}

**Comment by leehambley** [comment]
`:default_shell` was removed from Capistrano 3, and the articles you have found are simply out of date.

This is solved in modern Capistrano by the [`SSHKit Command Map`](https://github.com/capistrano/sshkit#the-command-map)
