### ISSUE TITLE
wrong directory for release_path

### ISSUE THREAD

**Issue by steefaan** [capistrano/capistrano#1487]
I use capistrano3 and capistrano-composer. As working dir for composer the `release_path` for capistrano is used. The release path points to `/home/{USER}` but the deploy itself goes to `/var/www/{USER}`. The deploy target is correct but why I get `/home/{USER}`for `release_path`. Regarding the paths.rb it shouldn't go to `/home/{USER}`. It's more or less the default configuration of capistrano so I didn't change any paths.

**Comment by leehambley** [comment]
I would guess that you are using `release_path` before a release is made, therefore it's *empty* therefore effectively it's `~`

**Comment by steefaan** [comment]
OK thanks I need to become more familiar with the apistrano workflow.
