### ISSUE TITLE
cap install not working on windows

### ISSUE THREAD

**Issue by babiz** [capistrano/capistrano#1489]
Hi 

I have install ruby and Capistrano in windows but when i tried to do cap install then it does not work properly. It gives following error

    C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- dl/import (LoadError)
     from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'
    from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/authen
    tication/pageant.rb:1:in `<top (required)>'
    from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/authen
    tication/agent/socket.rb:5:in `<top (required)>'
         from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/authen
    tication/agent.rb:22:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/authen
    tication/key_manager.rb:4:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/authen
    tication/session.rb:4:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh.rb:11:
    in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends
    /netssh.rb:1:in `<top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/all.rb:3
    2:in `require_relative'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/all.rb:3
    2:in `<top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit.rb:35:in
     `require_relative'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit.rb:35:in
     `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/capistrano-3.4.0/lib/capistrano/
    all.rb:2:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
    `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/capistrano-3.4.0/bin/cap:2:in `<
    top (required)>'
            from C:/Ruby22/bin/cap:23:in `load'
            from C:/Ruby22/bin/cap:23:in `<main>'

**Comment by robd** [comment]
@babiz Don't know anything about this, but the [top google result](http://stackoverflow.com/a/28900142/514483) suggests upgrading to  net-ssh 2.9.3.beta1.

**Comment by leehambley** [comment]
The error is in `NetSSH` - C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/authen
tication/pageant.rb:1:in `<top (required)>'

**Comment by babiz** [comment]
Great. It works now
