### ISSUE TITLE
Set branch from the terminal

### ISSUE THREAD

**Issue by chrisRidgers** [capistrano/capistrano#1491]
While googling, I've seen multiple references to setting a parameter using a -s/-S switch.

Whenever I attempt to use them though I get an ambiguous option error.

For example:

```
bundle exec cap -s branch='branchname' staging deploy
```

and 

```
bundle exec cap -S branch='branchname' staging deploy
```

Both result in:

```
OptionParser::AmbiguousOption: ambiguous option: -s

OptionParser::InvalidOption: invalid option: s
```

Has this functionality been removed/ moved?  How do I go about achieving the same result?

**Comment by leehambley** [comment]
It was removed in v3, and should be replaced by reading a variable from the environment. The `-sS` flag was inconsistent in it's behaviour.

**Comment by chrisRidgers** [comment]
Thanks for that :)

**Comment by leehambley** [comment]
If memory serves, and your team might have done something different already, the easiest way is `set(:branch, ENV.fetch(:GIT_BRANCH, 'master'))` or similar.

**Comment by chrisRidgers** [comment]
I've just gone with: `set :branch, ENV["BRANCH_NAME"] || "develop"`

And that appears to be working.

**Comment by leehambley** [comment]
I saw from your profile that you're an intern/junior, both will work `ENV.fetch()` is probably more robust.

**Comment by chrisRidgers** [comment]
Cheers thanks!

**Comment by chrisRidgers** [comment]
Just tried the fetch approach for another project, ran into a 'no implicit conversion of symbol into string' error.

I was trying:

```ruby
set :branch ENV.fetch(:REVISIONS, ENV.fetch(:BRANCH_NAME, "develop"))
```

Any ideas?  The other approach still works, just curious as to the cause.  Do I have to explicitly define :BRANCH_NAME and :REVISIONS somewhere even if I'm not using them?

**Comment by leehambley** [comment]
`ENV` needs a string for the key:

``` ruby
set :branch ENV.fetch("REVISIONS", ENV.fetch(:BRANCH_NAME, "develop"))
```

**Comment by chrisRidgers** [comment]
of course it does.

Cheers :)

**Comment by hoasung01** [comment]
Do you get this error when deploy with specific branch like that:
 ```
      02 git archive clone_develop | tar -x -f - -C /ho  me/deployer/project_name/releases/20161124062055
      02 fatal: Not a valid object name
      02 tar:
      02 This does not look like a tar archive
      02
      02 tar:
      02 Exiting with failure status due to previous errors
      02
```
I found a way to resolve it is: delete the current repo but I do not want like that so is there another way
