### ISSUE TITLE
may the docs error?

### ISSUE THREAD

**Issue by foreversmart** [capistrano/capistrano#1496]
the latest git version is 2.6.12.but on the centos system use `yum install git-core`. the git version is 1.7.1 but the capistrano  still works good 

in the docs: https://github.com/capistrano/capistrano/blob/master/README.md

`Capistrano support these source code version control systems out of the box:

Git 1.8 or higher
Mercurial
SVN`

**Comment by leehambley** [comment]
that's a horrible out of date version of Git in Centos, but it *should* work. I believe some of the `git-archive` stuff behaves subtly differently on 1.7.x vs 1.8.x.
