### ISSUE TITLE
El Capitan Issue??

### ISSUE THREAD

**Issue by QuietOmen** [capistrano/capistrano#1505]
I upgraded from OS X to El Capitan, and started having some issues with Capistrano. I've been doing some google searching and I haven't been able to discover any solutions. I'm not completely sure this is truly a bug or issue as I know some other employees at my work that have it working on their machines but they don't remember what they did to get it to work. Here's the basic output I'm getting: 

```
10:59 $ bundle install
Using rake 10.4.2
Using i18n 0.7.0
Using colorize 0.7.7
Using net-ssh 2.9.2
Using net-scp 1.2.1
Using sshkit 1.7.1
Using capistrano 3.4.0
Using capistrano-composer 0.0.6
Using capistrano-npm 1.0.1
Using bundler 1.10.6
Bundle complete! 3 Gemfile dependencies, 10 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

Then to test to see if cap is working I simply run the following: 

```
10:59 $ bundle exec cap
bundler: command not found: cap
Install missing gem executables with `bundle install
```

Any direction or insight would be helpful. Thanks.

**Comment by leehambley** [comment]
Most likely scenario is that your `$PATH` is no longer correct, but if it's an El Capatan issue, you might want to look into https://www.reddit.com/r/ruby/comments/3n26gt/upgrade_to_el_capitan_with_homebrew_ruby/ and https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md.

Even if you're not using Homebrew,e etc El Capitan is *very* hostile to developers and I would go as far to recommend you don't try and develop software on it today. Pick a less aggressively oppressive operating system that doesn't violate decades old principles that we've come to rely upon. 

Personally, I'm a happy mac user, but I'm sticking with Yosemite for as long as it's viable, and then I'll move my dev to a VM with a linux distro, and hope that Apple, or the developers who build software for it find reasonable ways to make it still useful.

**Comment by QuietOmen** [comment]
Yeah I have already tried both of those links and the advice they suggest with no luck. But thank you for your post and help. I'm actually a linux user myself, but my work got us Mac's so I'm just trying to get it setup and working. Bundle exec seems to be working with other things so I'm not sure why it wouldn't work with cap.

**Comment by leehambley** [comment]
One thing to check would be what your "bundle env" is, bundle evex forces
some env vars, and you check what it's doing, and verify you have a cap3
shim in the right place. W have seen this where "cap" (the Bundler shim) is
on the PATH, But at v2, not v3, so Bundler just derps.

It also doesn't help that binstubs, vendoring, rvm, rbenv, gemsets, and
your shell all play a part too, so its really difficult to say with any
certainty why its working for your colleagues but not you, even in an ideal
world.

Report back if you solve it, so I can maybe document it?

**Comment by QuietOmen** [comment]
OK will do, thanks for the direction and I'll let you know once I figure it out.

**Comment by klarsendesign** [comment]
Has anyone figured this out?? I am having this issue as well and am on hold on several websites. I get the exact same error and have ruby, rails, bundler, capistrano all installed. I even freshly re-installed everything.

**Comment by leehambley** [comment]
@klarsendesign there isn't really any way that *Capistrano* can run into problems because of El Capitan, but if your Ruby environment is screwed up somehow, it'd help me to know if you were using rvm, rbenv, or any of the other things, and if not, how you installed Ruby, and whether something (extreme, I know) like `sudo find / -type d -name 'capistrano-*'`  (which assuming you're on a Mac!) should scan your entire hard disk and report *any* directories named `capistrano*`

Here's how that looks for me:

```
$ sudo find / -type d -name 'capistrano-*'
find: /dev/fd/3: Not a directory
find: /dev/fd/4: Not a directory
/Library/Ruby/Gems/2.0.0/doc/capistrano-3.4.0
/Library/Ruby/Gems/2.0.0/gems/capistrano-3.4.0
/Users/demo/code/sample_app_rails_4/vendor/bundle/ruby/2.0.0/gems/capistrano-3.4.0
/Users/demo/code/sample_app_rails_4/vendor/bundle/ruby/2.0.0/gems/capistrano-bundler-1.1.4
/Users/demo/code/sample_app_rails_4/vendor/bundle/ruby/2.0.0/gems/capistrano-rails-1.1.3
/Users/leehambley/Projects/capistrano/documentation/_site/documentation/advanced-features/capistrano-pure-ruby
/Users/leehambley/Projects/capistrano/documentation/documentation/advanced-features/capistrano-pure-ruby
/Users/leehambley/Projects/sample_app_rails_4/vendor/bundle/ruby/2.0.0/gems/capistrano-3.4.0
/Users/leehambley/Projects/sample_app_rails_4/vendor/bundle/ruby/2.0.0/gems/capistrano-bundler-1.1.4
/Users/leehambley/Projects/sample_app_rails_4/vendor/bundle/ruby/2.0.0/gems/capistrano-rails-1.1.5
```

(I'd remove them all)

Behind that, the likely culprit is bundle binstubs, or similar - but given that rbenv, rvm, and bundler all have their own idea of binstubs, and probably more things I can't guess - I'll keep an eye on the ticket, and we'll see if we can resolve it here?

**Comment by klarsendesign** [comment]
Thank you! I've found other resources leading me to believe that El Capitan is the source, not in and of itself, but possibly because of the Path change as you mentioned above. However, I'm not sure how to solve that issue... 
We have our sites in Wordpress using Bedrock, Ansible, Roots, and deploying via Capistrano. We've been using it for months. The only change I've had is that I updated to El Capitan this weekend.

When I ran the search, this is what I came up with:
     `/Applications/MAMP/htdocs/hrock-ansible/roles/capistrano-setup`
    `find: /dev/fd/3: Not a directory`
    `find: /dev/fd/4: Not a directory`
    `/Library/Ruby/Gems/2.0.0/gems/capistrano-3.2.1`
    `/Library/Ruby/Gems/2.0.0/gems/capistrano-bower-1.1.0`
    `/Library/Ruby/Gems/2.0.0/gems/capistrano-composer-0.0.4`
    `/Library/Ruby/Gems/2.0.0/gems/capistrano-composer-0.0.6`
    `/Library/Ruby/Gems/2.0.0/gems/capistrano-npm-1.0.1`

**Comment by klarsendesign** [comment]
If this is helpful, my Gemfile is:

    source 'https://rubygems.org'

    gem 'capistrano', '~> 3.2.0'
    gem 'capistrano-composer'
    gem 'capistrano-npm'
    gem 'capistrano-bower'

**Comment by jbelinchonm** [comment]
Hi,

I hope this isn't too long and extensive but I hope that providing all info can make it easier for you to help me and everybody else with the same problem to solve it out.

Thanx in advance.

### How It started

Just upgraded to El Capitan and found this issue when running a usual command:
`$ bundle exec`
`-bash: bundle: command not found`

So I thought it would be related with OS X update, and decided to trust the installer to fix it:
```
$ sudo gem install bundler

Password:
Successfully installed bundler-1.10.6
Parsing documentation for bundler-1.10.6
Done installing documentation for bundler after 5 seconds
1 gem installed
```

And when I tried again:
```
$ bundle exec cap deploy
bundler: command not found: cap
Install missing gem executables with `bundle install`
```

So I tried to install it:
```
$ bundle install

Using highland 1.7.2
Using net-ssh 2.9.2
Using net-sap 1.2.1
Using net-sftp 2.1.2
Using net-ssh-gateway 1.2.0
Using capistrano 2.15.5
Using capistrano-maintenance 0.0.3
Using colored 1.2
Using ini file 2.0.2
Using ruby-progressbar 1.4.1
Using capifony 2.8.6
Using bundler 1.10.6
Bundle complete! 1 Gemfile dependency, 12 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

And found out that it wasn't going anywhere when I retried:
```
$ bundle exec cap deploy

bundler: command not found: cap
Install missing gem executables with `bundle install`
```

### Environment

Late 2012 Macbook Pro
Just updated to El Capitan

#### Gemfile
All this happened when trying to deploy a Symfony app using capifony.

The content of the Gemfile:
```
source 'https://rubygems.org'
gem 'capifony', '~> 2.8.1'
```

#### Ruby Manager
Not used.

#### Which Ruby
```
$ which ruby

#### Bundle Env
```
$ bundle env
Environment

    Bundler   1.10.6
    Rubygems  2.0.14
    Ruby      2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    Git       2.4.9 (Apple Git-60)

Gemfile

    source 'https://rubygems.org'
    gem 'capifony', '~> 2.8.1'

Gemfile.lock

    GEM
      remote: https://rubygems.org/
      specs:
        capifony (2.8.6)
          capistrano (>= 2.13.5, <= 2.16.0)
          capistrano-maintenance (= 0.0.3)
          colored (>= 1.2.0)
          inifile (>= 2.0.2, < 3.0.0)
          ruby-progressbar (= 1.4.1)
        capistrano (2.15.5)
          highline
          net-scp (>= 1.0.0)
          net-sftp (>= 2.0.0)
          net-ssh (>= 2.0.14)
          net-ssh-gateway (>= 1.1.0)
        capistrano-maintenance (0.0.3)
          capistrano (>= 2.0.0)
        colored (1.2)
        highline (1.7.2)
        inifile (2.0.2)
        net-scp (1.2.1)
          net-ssh (>= 2.6.5)
        net-sftp (2.1.2)
          net-ssh (>= 2.6.5)
        net-ssh (2.9.2)
        net-ssh-gateway (1.2.0)
          net-ssh (>= 2.6.5)
        ruby-progressbar (1.4.1)

    PLATFORMS
      ruby

    DEPENDENCIES
      capifony (~> 2.8.1)

    BUNDLED WITH
       1.10.3
```

#### Which Gem
```
$ which gem
/usr/bin/gem
``

#### Which Cap
```
$ which cap
```
(emptiness)

According to recent reading, /usr/bin is not a good path in El Capitan.

Anyway, I would like to hear from you as I am not familiar with the best and cleaner procedure to fix this.

Thank You

**Comment by leehambley** [comment]
> $ which ruby
    // tumbleweed

doesn't look too promising, is that *definitely* your output.

Quick word about `/usr/` under El Captain they basically write protected it in the kernel, https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md is a decent read to understand the problem.

Something occurred to me too, which is that the OSX installers assume that `/usr/local` is virtually empty (it would be, if you weren't a software developer), so I've seen the `5 minutes remaining` progress bar, whilst there have been a few hundred million files in `/usr/local` which needed 5/6 hours to copy, maybe it just gave up at some point and didn't copy most of your gems fully, but enough to let rubygems think they were there?

If you can, check the install path with `bundle show ...` and delete everything in that directory (`gem uninstall --all` ?), then you can start afresh with re-insatlling using [`gem pristine capistrano`](http://guides.rubygems.org/command-reference/#gem-pristine). (gem pristine installs gems 100% from scratch, it's like a forced reinstall).

If you can, it might be better to use something like `rbenv` and `ruby-installer` (standalone, or as a plugin for the former), these install rubies into your home directory, and also has the pleasant side effect of not requiring sudo to install gems.

**Comment by jbelinchonm** [comment]
Actually it aint. 
```
$ which ruby
/usr/local/bin/ruby
```

And also checked again:
```
$ which cap
/usr/local/bin/cap

$ which gem
/usr/local/bin/gem
```

**Comment by leehambley** [comment]
Alright, cool - so my concrete advice would be to use `rbenv` and `ruby-install` to get a real version of Ruby that is 

a) a version you choose (not whatever the system gives you)
b) (becoming more important) not to rely on `/usr/local`

See https://github.com/sstephenson/rbenv#homebrew-on-mac-os-x it's super easy.

**Comment by sbpipb** [comment]
try checking your .bundle/config file maybe you've left something like install development or testing only. In my case, I just deleted the config file.
