### ISSUE TITLE
SSH port setting causes failure to create a symbolic link

### ISSUE THREAD

**Issue by AlexVPopov** [capistrano/capistrano#1510]
Here are some lines from my `staging.rb`:

```ruby
role :app, %w{xxx@xxxxxxx:5722}
role :web, %w{xxx@xxxxxxx:5722}
role :db,  %w{xxx@xxxxxxx:5722}

server 'xxxxxxx', user: 'deploy', roles: %w{web app}, port: 5722
```

Everything works fine. If I remove the `port` argument from the server method and instead have:

```ruby
set :ssh_options, { port: 5722 }
```

deployment fails with:

```bash
INFO[f36a948f] Finished in 0.098 seconds with exit status 0 (successful).
DEBUG[8caa32bf] 	ln: 
DEBUG[8caa32bf] 	failed to create symbolic link '/home/deploy/xxx/releases/20151022143722/config/database.yml'
DEBUG[8caa32bf] 	: File exists
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host xxxxxxxxxxxxxx: ln exit status: 1
ln stdout: Nothing written
ln stderr: Nothing written

SSHKit::Command::Failed: ln exit status: 1
ln stdout: Nothing written
ln stderr: Nothing written
```

Do you have any clues at to what the problem might be? Thank you.

**Comment by leehambley** [comment]
The problem is clearly listed, your repository already contains a `config/database.yml` and therefore linking it from the shared folder (it's probably configured with a `linked_file` directive somewhere)

**Comment by AlexVPopov** [comment]
@leehambley

But why does the problem only occur if the port argument is missing from
the server method?

**Comment by leehambley** [comment]
Because if you set a global option for the port, we see two machines, if you specify the port *on* the machine in the `server` line then they are cleaned up by the duplication detection.

**Comment by AlexVPopov** [comment]
Ok, thanks!
