### ISSUE TITLE
Problem with Capistrano 2.15.5

### ISSUE THREAD

**Issue by bytenel** [capistrano/capistrano#1525]
I have multiple environments setup to deploy to using capistrano (production and staging). In my staging environment it appears everything is correct and my capistrano is linking my release folder correctly when I try to run a cap deploy:migrate. When I try to run the same command in my production environment I get a no such file or directory error like the following:

```
 bash: line 0: cd: /home/deployer/apps/app_name/releases/wrapper.: No such file or directory
```

Why would it not be linking my production environment?

EDIT:

Just to clarify, the cap deploy command for that environment seems to have the proper wrapper replacement with the actual release number. It appears just the migrate command doesn't work.

**Comment by leehambley** [comment]
Thanks for the report, I'm going to close the issue since the 2.x branch isn't supported. 3.x is well over a year old, and has explicit support for composer via a first party plugin. I can't explain why 2.x fails, but it's more than two years since I *used* anything from the 2x branch, there were some funny cases about how it handled aborts, and rollbacks.

**Comment by bytenel** [comment]
Hm, ok. I appreciate the notification. I saw that v 3 was up and running but some of the plugins for this legacy project might not be supported so I was hesitant to make the upgrade. I guess with the problems we're encountering with the tool now we'll have to make the switch. Github should update their notifications because for some reason I just got the notification the ticket was closed in my email and not your comment, I was about to be like - 'wtf? closed out of no where?' but this makes sense.

Thanks again!

**Comment by leehambley** [comment]
Sorry I can't be more helpful, there's already such a myriad of plugins, environments, languages, stacks and operating systems where I am nearly the only support person checking on people, I wish I could do more to support all the use-cases. Ping me if I can help with upgrading on our google group mailing list.

**Comment by bytenel** [comment]
Dude you rock - I know all too well being a one man show on projects!
