### ISSUE TITLE
ArgumentError: wrong number of arguments (0 for 1) in dsl/env.rb

### ISSUE THREAD

**Issue by dentarg** [capistrano/capistrano#1528]
I think `#any?` on https://github.com/capistrano/capistrano/blob/master/lib/capistrano/dsl/env.rb#L16 ([link to same line in v3.4.0](https://github.com/capistrano/capistrano/blob/v3.4.0/lib/capistrano/dsl/env.rb#L16)) should take an argument.

I have only encountered this bug in a project we recently switch over to JRuby, and it doesn't happen every time, so I'm not sure what triggers it. We have seen it happen for different tasks, e.g. `deploy:cleanup`, `deploy:restart`, so it doesn't seem isolated to a particular task. I don't think we have ever seen it with MRI.

I managed to get the error when running with `--trace` and here is that output. (I added `puts "Parallel"` on line 13 in [sshkit/runners/parallel.rb](https://github.com/capistrano/sshkit/blob/v1.7.1/lib/sshkit/runners/parallel.rb) for debugging purposes, that is also included below)

```
$ ruby -v
jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa Java HotSpot(TM) 64-Bit Server VM 24.45-b08 on 1.7.0_45-b18 +jit [darwin-x86_64]

$ bundle exec cap production deploy:restart --trace
uri:classloader:/jruby/kernel/kernel.rb:17: warning: unsupported exec option: close_others
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke chruby:validate (first_time)
** Execute chruby:validate
Parallel
Parallel
Parallel
** Invoke chruby:map_bins (first_time)
** Execute chruby:map_bins
** Invoke bundler:map_bins (first_time)
** Execute bundler:map_bins
** Invoke deploy:restart (first_time)
** Execute deploy:restart
** Invoke deploy:export_upstart (first_time)
** Invoke deploy:foreman:upload_procfile (first_time)
** Invoke deploy:foreman:generate_procfile (first_time)
** Execute deploy:foreman:generate_procfile
** Execute deploy:foreman:upload_procfile
Parallel
Parallel
Parallel
INFO Uploading tmp/Procfile 100.0%
INFO Uploading tmp/Procfile 100.0%
INFO Uploading tmp/Procfile 100.0%
** Execute deploy:export_upstart
Parallel
Parallel
Parallel
INFO [10502ae6] Running /usr/bin/env sudo /usr/local/bin/chruby-exec jruby-9 -- /home/deploy/twingly-lee/shared/bin/foreman export upstart /etc/init -a twingly-lee -u `whoami` -l /home/deploy/twingly-lee/shared/log as deploy@haldir.example.org
INFO [21abb117] Running /usr/bin/env sudo /usr/local/bin/chruby-exec jruby-9 -- /home/deploy/twingly-lee/shared/bin/foreman export upstart /etc/init -a twingly-lee -u `whoami` -l /home/deploy/twingly-lee/shared/log as deploy@huor.example.org
INFO [10502ae6] Finished in 10.656 seconds with exit status 0 (successful).
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@fili.example.org: wrong number of arguments (0 for 1)
/Users/dentarg/.gem/jruby/2.2.2/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:17:in `block in execute'
ArgumentError: wrong number of arguments (0 for 1)
/Users/dentarg/.gem/jruby/2.2.2/gems/capistrano-3.4.0/lib/capistrano/dsl/env.rb:41:in `any?'
/Users/dentarg/.gem/jruby/2.2.2/gems/sshkit-1.7.1/lib/sshkit/command_map.rb:41:in `[]'
/Users/dentarg/.gem/jruby/2.2.2/gems/sshkit-1.7.1/lib/sshkit/command.rb:206:in `to_s'
org/jruby/RubyKernel.java:445:in `String'
/Users/dentarg/.gem/jruby/2.2.2/gems/sshkit-1.7.1/lib/sshkit/formatters/pretty.rb:23:in `write_command'
/Users/dentarg/.gem/jruby/2.2.2/gems/sshkit-1.7.1/lib/sshkit/formatters/pretty.rb:10:in `write'
/Users/dentarg/.gem/jruby/2.2.2/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:134:in `block in _execute'
org/jruby/RubyKernel.java:1755:in `tap'
/Users/dentarg/.gem/jruby/2.2.2/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/Users/dentarg/.gem/jruby/2.2.2/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/Users/dentarg/.gem/jruby/2.2.2/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:28:in `sudo'
/Users/dentarg/.gem/jruby/2.2.2/bundler/gems/capistrano-twingly-66461c19f8f5/lib/capistrano/twingly/tasks/upstart.rake:8:in `block in (root)'
/Users/dentarg/.gem/jruby/2.2.2/gems/sshkit-1.7.1/lib/sshkit/backends/abstract.rb:77:in `within'
/Users/dentarg/.gem/jruby/2.2.2/bundler/gems/capistrano-twingly-66461c19f8f5/lib/capistrano/twingly/tasks/upstart.rake:7:in `block in (root)'
org/jruby/RubyBasicObject.java:1670:in `instance_exec'
/Users/dentarg/.gem/jruby/2.2.2/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/dentarg/.gem/jruby/2.2.2/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:14:in `block in execute'
Tasks: TOP => deploy:export_upstart
```

**Comment by leehambley** [comment]
Isn't this `all?` this one? http://ruby-doc.org/core-2.2.3/Enumerable.html#method-i-all-3F

**Comment by dentarg** [comment]
Yeah, you are probably right @leehambley, seems like I don't know what I'm talking about :) Then I wonder where the error comes from, anything you want me to try?

**Comment by dentarg** [comment]
I don't get the stack trace

    /Users/dentarg/.gem/jruby/2.2.2/gems/capistrano-3.4.0/lib/capistrano/dsl/env.rb:41:in `any?'

So confusing, line 41 is empty: https://github.com/capistrano/capistrano/blob/master/lib/capistrano/dsl/env.rb#L41

**Comment by leehambley** [comment]
I guess JRuby is doing something strange with the code, is there any way to make JRuby be more conservative, or something?

Also, just because your *app* relies on jRuby doesn't mean you need to run cap with jruby, right?

**Comment by dentarg** [comment]
> Also, just because your app relies on jRuby doesn't mean you need to run cap with jruby, right?

That is correct, it's for convenience, our repo has a `.ruby-version` file in the root, so, JRuby get automatically chosen. I will script around it for the moment.

Not aware of settings for JRuby, but I haven't looked into it (yet).

**Comment by dentarg** [comment]
> That is correct, it's for convenience, our repo has a .ruby-version file in the root, so, JRuby get automatically chosen. I will script around it for the moment.

We also have some capistrano plugins in the Gemfile (with the `github` option), so it was a bit more complicated than I though :sob:

**Comment by dentarg** [comment]
If it could help, I added some stuff to my `.jrubyrc` and got the error again, output at https://gist.github.com/dentarg/aff1754213ca1e1c99f5

```
$ cat .jrubyrc
debug.fullTrace = true
backtrace.style = full
backtrace.color = true
errno.backtrace = true
log.backtraces = true
log.callers = true
native.verbose = true
```

**Comment by gerardo-navarro** [comment]
What is any actually suppose to be doing?

I'm getting a similar issue, but without any jRuby env.

```
ArgumentError: wrong number of arguments (0 for 1)
/Users/gerardonavarrosuarez/Development/gadget_day/capistrano/lib/capistrano/dsl/env.rb:13:in `any?'
/Users/gerardonavarrosuarez/Development/gadget_day/capistrano/lib/capistrano/dsl/env.rb:15:in `any?'
/Users/gerardonavarrosuarez/Development/gadget_day/capistrano-jelastic/lib/capistrano/tasks/deploy_on_jelastic.cap:43:in `block (3 levels) in <top (required)>'
``` 

Do you have any idea why this happens?

**Comment by leehambley** [comment]
What version of Ruby are you using?

**Comment by leehambley** [comment]
What version of Ruby are you using?

**Comment by gerardo-navarro** [comment]
`rvm current` says that I am using `ruby-2.0.0-p481`

**Comment by leehambley** [comment]
Could you try something like (you'll have to put it in the right place) something like:

    puts method(:any?).source_location

This, if you get lucky (ideally open `env.rb` in the Capistrano gem and modify it) and share the output, I wonder if something in your env is loading something like ActiveSupport (or, similar) which redefines `any?`

**Comment by mattbrictson** [comment]
```
/Users/Development/capistrano-jelastic/lib/capistrano/tasks/deploy_on_jelastic.cap:43
```

@gerardo-navarro Can you share what your code is doing on this line? Unless the backtrace is omitting something, it looks like you are calling `any?` directly. I'm curious to see what you are using it for.

**Comment by andreimaxim** [comment]
I don't know if this might add more information, but the error described looks very much like what I'm seeing on the Jenkins machine that I use:

```
cap aborted!
ArgumentError: wrong number of arguments (0 for 1)
/home/jenkins/workspace/API/vendor/bundle/jruby/2.2.0/gems/capistrano-3.4.0/lib/capistrano/dsl/env.rb:41:in `any?'
/home/jenkins/workspace/API/vendor/bundle/jruby/2.2.0/gems/sshkit-1.8.1/lib/sshkit/command_map.rb:41:in `[]'
/home/jenkins/workspace/API/vendor/bundle/jruby/2.2.0/gems/sshkit-1.8.1/lib/sshkit/command.rb:209:in `to_s'
/home/jenkins/workspace/API/vendor/bundle/jruby/2.2.0/gems/sshkit-1.8.1/lib/sshkit/color.rb:42:in `colorize'
/home/jenkins/workspace/API/vendor/bundle/jruby/2.2.0/gems/sshkit-1.8.1/lib/sshkit/formatters/pretty.rb:20:in `log_command_start'
/home/jenkins/workspace/API/vendor/bundle/jruby/2.2.0/gems/sshkit-1.8.1/lib/sshkit/backends/netssh.rb:84:in `execute_command'
/home/jenkins/workspace/API/vendor/bundle/jruby/2.2.0/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:121:in `block in create_command_and_execute'
org/jruby/RubyKernel.java:1755:in `tap'
/home/jenkins/workspace/API/vendor/bundle/jruby/2.2.0/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:121:in `create_command_and_execute'
/home/jenkins/workspace/API/vendor/bundle/jruby/2.2.0/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:53:in `execute'
/home/jenkins/workspace/API/vendor/bundle/jruby/2.2.0/gems/capistrano-3.4.0/lib/capistrano/tasks/git.rake:17:in `block in (root)'
org/jruby/RubyBasicObject.java:1670:in `instance_exec'
/home/jenkins/workspace/API/vendor/bundle/jruby/2.2.0/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:15:in `run'
/home/jenkins/workspace/API/vendor/bundle/jruby/2.2.0/gems/sshkit-1.8.1/lib/sshkit/runners/parallel.rb:13:in `block in execute'
Tasks: TOP => git:check => git:wrapper
```

It happens a lot less often on my machine.

The current Ruby version is:

```
jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa Java HotSpot(TM) 64-Bit Server VM 24.71-b01 on 1.7.0_71-b14 [darwin-x86_64]
```

The app is a regular Rails 4.2 application using the latest capistrano gem (3.4.0). 

I'm guessing it's related to the fact that I'm deploying to two servers at once, both of them set up like this in `config/deploy/qa.rb`, but otherwise it's pretty much the standard setup:

```ruby
server '10.0.0.10', user: 'app', roles: %w{web app db}
server '10.0.0.11', user: 'app', roles: %w{web app db}
```

Let me know if I can provide more information. It's rather weird that it works most of the time.

**Comment by mattbrictson** [comment]
@andreimaxim Thanks for the report. My guess is that this is a strange JRuby thing.

Capistrano defines `any?` as part of its DSL, and it requires 1 argument.

Ruby's built-in Enumerable also defines `any?` but with a different signature (zero arguments, or a block).

In the backtrace, I see SSHKit code that is trying to use the Enumerable `any?`, but somehow at runtime the Capistrano version is being called instead. I could be wrong, but this seems like a method dispatch bug in JRuby. It would be great if we could boil this down to a simple failing test case that we could report to the JRuby team.

**Comment by mattbrictson** [comment]
My best guess after looking into this some more is that Capistrano or SSHKit has a subtle race condition bug that is only surfacing when we run under the JRuby thread implementation.

Probably on this line (sshkit/command_map.rb:41)

```ruby
if prefix[command].any?
```

somehow `prefix[command]` is returning `nil`. Again, my guess is that this happens due to a non-threadsafe initialization bug.

Then, you end up with `nil.any?`, which blows up exactly like we are seeing;

```ruby
require "capistrano/all"
include Capistrano::DSL
nil.any?
# => ArgumentError: wrong number of arguments (0 for 1)
```

Massive props to anyone who can figure out why `prefix[command]` would return `nil`. Any guesses?

@andreimaxim are you doing anything with `SSHKit.config.command_map` in your project? Can you list all the Capistrano plugins you are using? Thanks!

**Comment by mattbrictson** [comment]
Ah, I think I found the race condition. I'll open a PR with a fix. Thanks everyone for the bug reports!

**Comment by mattbrictson** [comment]
Everyone that ran into this issue: can you test my branch of SSHKit to see if it resolves the problem for you? See https://github.com/capistrano/sshkit/issues/322
