### ISSUE TITLE
Install rvm 2.8.0 with ruby 1.8.7

### ISSUE THREAD

**Issue by solisoft** [capistrano/capistrano#1530]
Hi,

I want to install an old rvm version (2.8.0) but I have this error : 

gem install capistrano -v 2.8.0
ERROR:  Error installing capistrano:
	net-ssh requires Ruby version >= 2.0.

It use to work before ... any idea?

**Comment by leehambley** [comment]
Capistrano has a liberal requirement on `net-ssh` (i.e we require *any* version) their latest relea **requires** Ruby 2.2.

The fix is simple, name the last version of Net-ssh that you can find that works on your Ruby version in your Gemfile as well, and all should work.

**Comment by solisoft** [comment]
No, I did install net-ssh 2.1.4 which works fine with ruby 1.8.7 but capistrano still look for a more recent version.

I fixed my issue by : 
wget https://github.com/capistrano/capistrano/archive/v2.15.7.tar.gz
tar -xf v2.15.7.tar.gz
cd capistrano-2.15.7
gem build capistrano.gemspec
gem install --local capistrano-2.15.7.gem

Now I still have an issue with capistrano-ext which require net-ssh too (with ruby >= 2.0.) :(

**Comment by solisoft** [comment]
Also, I don't have a Gemfile in this (very) old project

**Comment by solisoft** [comment]
Just added a Gemfile, everything works fine now :+1:
