### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by finkelm** [capistrano/capistrano#1531]
I've been having trouble finding features, some of in ssh-kit. There seems to be many functions that aren't documented on the official documentation. `ssh-kit` seems to have done a much better job in this respect. Clearly this is asking a lot, but I thought it would make an important feature request.

**Comment by leehambley** [comment]
Hi @finkelm I'm not sure where to start, we did our best! Rdoc isn't the best way to document a DSL, we use to have such documentation but it's not working well for Rake apps. I assume you've seen capistranorb.com ?

**Comment by finkelm** [comment]
I have. I suppose features such as `as` and the like are documented in sshkit. Perhaps a link to that on the site would be appropriate? Since it's very much a part of the DSL.

**Comment by leehambley** [comment]
https://github.com/capistrano/capistrano#sshkit ?

**Comment by finkelm** [comment]
Perhaps just a listing of all the DSL. Just a thought. Right now they're in two different places, in two different formats. It's not obvious to a beginner where the DSL is coming from and where to refer.

**Comment by mattbrictson** [comment]
@finkelm We are doing our best to improve the docs, with a big recent push to the README and to [capistranorb.com](http://capistranorb.com).

I know that your concern is with the SSHKit DSL specifically, which we haven't written much about (yet). So this issue isn't "done" by any means. I'm going to move it to the https://github.com/capistrano/documentation repository where it is better suited.

:right: https://github.com/capistrano/documentation/issues/159
