### ISSUE TITLE
Feature request: implement :branch for svn

### ISSUE THREAD

**Issue by marcovtwout** [capistrano/capistrano#1533]
I noticed the `:branch` option is not used for svn. I am not a Ruby developer, but I have a suggestion on how to implement this. Implementing the branch option would provide more meaningful revision messages, and will make it a bit easier to use different branches for different environments (this is a common svn branching structure)

We could simply set the internal repository url by concatenating `:repo_url` and `:branch`. For example:
```rb
set :repo_url, 'https://github.com/user/repo'
set :branch, 'trunk' #default is "trunk". Other examples: "branches/feature_x" or "tags/1.0.0"
```

Revision log messages will also become more meaningful (currently always display "master"):
```
Branch trunk (at 22) deployed as release 20151208084855 by Marco
Branch branches/feature_x (at 22) deployed as release 20151208084855 by Marco
```

**Comment by mattbrictson** [comment]
It has been several years since I used Subversion, but could this work?

```ruby
# deploy.rb
set :branch, "trunk"
set :repo_url, -> { "svn://myhost/myrepo/#{branch}" }
```

Then when you override `:branch` (e.g. in `production.rb`), the repo URL will be built accordingly.

Is this what you had in mind?

**Comment by marcovtwout** [comment]
Yes, that would probably do.

Not sure if this is practical with backwards compatibility, but even nicer would be if this is default behavior when :scm is "svn" (as in starter post example)

**Comment by mattbrictson** [comment]
Considering the simplicity of the workaround, and the fact that this would almost certainly break backwards compatibility, I'm inclined to leave the behavior as-is.

But like I said, I'm not a Subversion user, so maybe there is a solution I'm not seeing that will preserve backwards compatibility. I'll leave this issue open in case anyone wants to chime in with other ideas.

**Comment by marcovtwout** [comment]
Maybe it would be sufficient to make the workaround example part of the documentation?

**Comment by marcovtwout** [comment]
I tried it like this, but the :branch value from my stage is not used.

```
# deploy.rb
set :repo_url, "https://svn.example.nl/foo/#{fetch(:branch)}"

# stages/staging.rb
set :branch, 'trunk'
```

Console output:
```
# Running: cap staging svn:check
(..)
Running /usr/bin/env svn info https://svn.example.nl/foo/master
(..)
```

**Comment by mattbrictson** [comment]
You need to use a proc, as I showed in my example:

```ruby
set :repo_url, -> { "svn://myhost/myrepo/#{branch}" }
```

**Comment by marcovtwout** [comment]
Confirmed, that works :)

**Comment by leehambley** [comment]
So, what next? Issue closed, or do we want to treat this as a doc issue, or does someone want to make a PR?

**Comment by marcovtwout** [comment]
Maybe put this as an example on http://capistranorb.com/documentation/getting-started/configuration/? Or do you know a better place?

**Comment by leehambley** [comment]
> Maybe put this as an example on http://capistranorb.com/documentation/getting-started/configuration/? Or do you know a better place?

Great idea @marcovtwout, do you want to prepare a PR for the capistrano/documentation repo ?

**Comment by marcovtwout** [comment]
https://github.com/capistrano/documentation/pull/145
