### ISSUE TITLE
within(directory){ execute(string) } should either 'just work' or 'boom'

### ISSUE THREAD

**Issue by ahoward** [capistrano/capistrano#1535]
docs aren't good enough to explain the design choice IMHO - just check
stackoverflow...

one solution is just to fix it - use shellwords to properly escape the command

```ruby
  require 'shellwords'

  def execute(*args, &block)
    if args.first.is_a?(String)
      command = Shellwords.escape(args.first)
    end

    # ...
  end
```

otherwise raise an exception

```ruby
  def execute(*args, &block)
    if args.first.is_a?(String) and inside_within?
      raise "don't do that"
    end

    # ...
  end
```

the current behavior of doing

```ruby
  within directory do  # silently ignored
    execute command
  end
```

just isn't POLS - the point of a library like cap is to be able to re-use code
but, currently, each and every use must re-invent 'cd into a (properly escaped
directory) and run commands', including handling the fact that

```ruby
  within(does_not_exist) do # raises
  end
```

```ruby
  execute "#{ does_not_exist }; command.sh" # reports a failed exit status that leads to debugging which part failed
```

a final solution would be to remove the 'within' API since it sometimes works,
and sometimes does not, issuing no exception nor warning

**Comment by ahoward** [comment]
moving to https://github.com/capistrano/sshkit/issues/306

**Comment by leehambley** [comment]
> docs aren't good enough to explain the design choice IMHO - just check
> stackoverflow...

Alright, that's a problem. Here's the thing, we need a list of commands that people try and do this thing with, to have some concrete arguments. The issue, briefly explained is that the command mapping (prefixing, suffixing, wrapping in `sudo`, etc) struggles (I dare say it's impossible) to do the right thing.

For the simplish cases of someone having a string such as `./configure --i=know what i'm doing` that *should* work, but it's not only about shell escaping what they give in a way that we don't trash it, but that we can confidently and correct wrap all the possible myriad of options that the API gives. If we special-case `within`, how about `as` and `with` and all the other API methods? At some point it breaks down.

(Edit: see you after the jump, thanks for moving it)
