### ISSUE TITLE
Allow dot in application_name

### ISSUE THREAD

**Issue by marcovtwout** [capistrano/capistrano#1536]
Is there a specific reason why `.` (dot) is not allowed in the `:application_name` variable? I would like to use it to match our vhost names.

**Comment by leehambley** [comment]
No good reason, should be an easy fix ,- we'd love a pr

**Comment by marcovtwout** [comment]
Sorry, I am not a Ruby developer. Should be trivial to improve, right?

**Comment by RochesterinNYC** [comment]
@marcovtwout are you going to write the PR?

**Comment by marcovtwout** [comment]
Yes, coming up.

**Comment by RochesterinNYC** [comment]
:+1:

**Comment by marcovtwout** [comment]
https://github.com/capistrano/capistrano/pull/1537
