### ISSUE TITLE
Why does the trace output use stderr?

### ISSUE THREAD

**Issue by marcovtwout** [capistrano/capistrano#1550]
https://github.com/capistrano/capistrano/blob/45e851bdc5ed80970a7be90f080f030aa7386190/lib/capistrano/application.rb#L29

I was expecting trace output to be sent to stdout instead of stderr (since it is quite handy to see the hooks also on successful commands).

**Comment by leehambley** [comment]
It's there because it's trace level output designed for debugging. Many posix tools behave the same way.

**Comment by marcovtwout** [comment]
I found that the default rake behavior is to output to stdout: http://docs.seattlerb.org/rake/doc/command_line_usage_rdoc.html
But also, I can set it myself using `--trace=stdout`.

**Comment by leehambley** [comment]
I've reopened the issue, maybe we should revaluate the default. It's a rare issue, but if we're deviating from Rake's behaviour, even if it's easy to fix, I'd be glad of "doing it right"

**Comment by mattbrictson** [comment]
There seems to be some miscommunication here. The Rake docs specify that **stderr** is the default. 

> --trace{=output} (-t)
Turn on invoke/execute tracing. Also enable full backtrace on errors. The output parameter is optional, but if specified it controls where the trace output is sent. If output is stdout, then trace output is directed to standard output. **If `output` is stderr, or if it is missing, then trace output is sent to standard error.**

Capistrano is not deviating from this.

**Comment by leehambley** [comment]
Good, I didn't think so. Blame the fact I've been on my feet 24h. Thanks
@mattbrictson

**Comment by marcovtwout** [comment]
I must have simply misread the docs, thanks for clarifying. :)
