### ISSUE TITLE
Garbled revision_log_message

### ISSUE THREAD

**Issue by rishabhmhjn** [capistrano/capistrano#1557]
I get this garbled text as string if I call `revision_log_message`

```
Branch master (at [?25h[0G[K[?25h[0G[Ka91779e) deployed as release 20160110105922 by rishabh
```

Does anyone know how to fix this?

**Comment by leehambley** [comment]
It's not garbled. It includes [ANSI escape sequences](https://en.wikipedia.org/wiki/ANSI_escape_code) for colorization. These don't get printed if your environment is setup correctly. If your environment is misrepresenting it's support for colors these codes will be printed.

**Comment by rishabhmhjn** [comment]
Setting `:pty` to `false` fixed this

I was setting `:pty` to `true` as I needed to use `sudo cmd`. However, I can't because `:pty` is set to `false`.

I am not sure if this is the right way to do it but here is a small hack that I had to use


```ruby
desc 'Task that needs sudo'
task :cap_task do
  on roles(:myrole) do
    enable_pty
    execute :sudo, :cmd
    disable_pty
  end
end

def enable_pty
  SSHKit::Backend::Netssh.config.pty = true
end

def disable_pty
  SSHKit::Backend::Netssh.config.pty = false
end
```

**Comment by leehambley** [comment]
Unfortunately `pty: true` is the hack here, you should make sure your user doesn't need to use `sudo` or use any Ruby library (there must be some) to strip the. Defining `pty: true` tells the upstream server that you have attached a "pseudo terminal", thus it assumes it can use colours. 

The hack is a mess, but if it works, just be aware that it's really a nasty hack.

**Comment by rishabhmhjn** [comment]
@leehambley thank you for your response.

I will try to fix need of sudo for my work
