### ISSUE TITLE
Docs for rollback are empty

### ISSUE THREAD

**Issue by will-in-wi** [capistrano/capistrano#1558]
http://capistranorb.com/documentation/getting-started/rollbacks/

Pointed out in https://stackoverflow.com/questions/34762582/capistrano-3-rollback-missing-tutorial

I'm going to try and take a crack at writing this based on reverse engineering the code, but I don't know when I will find time. I am creating this ticket in case anyone else wants to take a shot at it in the meantime. If someone else does try, please comment to that affect.

Thanks!

**Comment by mattbrictson** [comment]
Thanks! This documentation is sorely needed.

We actually have an issue already open in the docs repository where the website is maintained. Please move all discussion there:

https://github.com/capistrano/documentation/issues/124

**Comment by will-in-wi** [comment]
Thanks for clarifying this!
