### ISSUE TITLE
Retire the v3 label?

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1563]
@leehambley Seeing as every issue is v3 by default these days, any objection to me deleting the `v3` GitHub label?

We can keep the `v2` label around for the rare issue that targets 2.x.

Also, in an effort to clean up the labels, I would like to delete these as well if you have no objections:

* breaking-change (assigned to 1 open issue)
* documentation (2)
* duplicate (0)
* needs-rebase (2)
* under-consideration (15)

Nearly all the tagged issues haven't seen activity in a year or more, so the labels probably aren't very meaningful at this point.

**Comment by leehambley** [comment]
Agreed - let's kill it, all the labels if you like. I preferred your suggested scheme anyway.
