### ISSUE TITLE
cap --dry-run exits after deploy:check:linked_files

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1565]
The current `--dry-run` behavior is a bit broken because it does not get very far in the deploy flow. In fact, it doesn't make it past `deploy:check`.

Ideally the entire deploy flow (or as much as feasible) would run in dry run mode, allowing a user to preview the commands that would be run during a real deployment.

I believe the problem lies in definition the `deploy:linked_files` task, which has a hard `exit` call. Perhaps we should change it like so (assuming `dry_run?` is implemented in #1564):

```diff
@@ -71,7 +69,7 @@ namespace :deploy do
         linked_files(shared_path).each do |file|
           unless test "[ -f #{file} ]"
             error t(:linked_file_does_not_exist, file: file, host: host)
-            exit 1
+            exit 1 unless dry_run?
           end
         end
       end
```

Although this may just be the tip of the iceberg.

**Comment by jeremywadsack** [comment]
+1

**Comment by holstvoogd** [comment]
Tried it, seems this is the only exit that messes up the dry-run within capistrano itself.

**Comment by holstvoogd** [comment]
Actually, it seems someone made a change for it in sshkit:
https://github.com/capistrano/sshkit/commit/bb2b005113602067195180769bd412744f2e9754

Although I'm not sure if always returning true from test is ideal for dry-run purposes. Then again, neither is false in terms of ensuring a dry-run that represents the actual run...

**Comment by mattbrictson** [comment]
@holstvoogd Good catch! It seems then that this will be fixed when the next version of SSHKit is released. I'll mark this as closed.
