### ISSUE TITLE
Support Rake-style dry run behavior?

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1566]
In Capistrano 3.2.1 and prior, the `--dry-run` flag would execute Rake's dry run behavior, which is to just print tasks without executing the bodies of those tasks.

After 3.2.1, Capistrano implements its own dry run, which is different: it actually executes all tasks, but uses a `Printer` for the SSHKit backend rather than the default SSH. The result is that any `execute` will just print instead of running the remote command. So Capistrano's dry run is still a dry run of sorts, but different than what Rake does.

**This issue is a feature request to restore the Rake-style behavior.** Perhaps we could do this as an additional flag, so that both styles of dry run could be supported. Maybe `--dry-run` vs `--fake`, for example.

Rationale:

If Capistrano tasks were purely made up of SSHKit actions, the current dry run behavior would suffice. However, some projects have perfectly reasonable Capistrano tasks that are not just remote SSH executions. For example, a task may do something locally, like tag a release, or make an API call. These non-SSHKit actions *will be executed* during a `cap --dry-run`, which is bad.

Note however that since Capistrano uses `invoke` to chain tasks in its deploy flow, a pure Rake-style dry run will skip a large number of tasks. So while a Rake dry run could help in certain scenarios, it still has serious flaws.

**Comment by mattbrictson** [comment]
IMHO having two styles of dry run behavior would be confusing. Developers that need the Rake-style dry run can use the new `dry_run?` helper as a workaround. Closing.

**Comment by leehambley** [comment]
> IMHO having two styles of dry run behavior would be confusing.

Definitely, I think "dry run" was always a bad idea in Capistrano anyway, it should (if at all) be implemented with a pure printer backend, and something that prompts for input on tests/checks/branches, but that will be inordinately tricky to implement correctly.
