### ISSUE TITLE
Hosts filter with regex has regressed in master

### ISSUE THREAD

**Issue by will-in-wi** [capistrano/capistrano#1577]
From https://github.com/capistrano/documentation/pull/169

Capistrano 3.4.0 behavior is:

    cap --hosts=^local production deploy

Capistrano master behavior is:

    cap --hosts=/^local/ production deploy

The alternatives to not appear to work.

**Comment by mattbrictson** [comment]
Yep, you're right. Capistrano 3.4.0 worked with `--hosts=^local`, but master does not. In master, you have to surround the value with slashes, like `--hosts=/^local/`. I don't think regression was intentional.

**Comment by mattbrictson** [comment]
@cshaffer If you have time, can you weigh in on this? I see that you were the last person to work on the filters regexp code, so you're probably most familiar with it.

**Comment by cshaffer** [comment]
@mattbrictson Yep, I broke this. I wrote a breaking test, and I should have a fix by tomorrow.
