### ISSUE TITLE
roles have problem with attributes.

### ISSUE THREAD

**Issue by loganfreeman** [capistrano/capistrano#1579]
role :app, %w{vagrant@127.0.0.1}, :primary => true
role :web, %w{vagrant@127.0.0.1}, :primary => true
role :db,  %w{vagrant@127.0.0.1}, :primary => true
role :root, %w{vagrant@127.0.0.1}

The above works fine.

BUT

The following will mess up:

role :app, %w{vagrant@127.0.0.1}, :primary => true
role :web, %w{vagrant@127.0.0.1}, :primary => true
role :db,  %w{vagrant@127.0.0.1}, :primary => true
role :root, %w{vagrant@127.0.0.1}, :no_release => true

Then all the roles have the attribute  :no_release and its value is true.

Then 

For example, the following is skipped:

  task :set_previous_revision do
    on release_roles(:all) do
      target = release_path.join('REVISION')
      if test "[ -f #{target} ]"
        set(:previous_revision, capture(:cat, target, '2>/dev/null'))
      end
    end
  End

Because all roles are not release_roles anymore.

**Comment by mattbrictson** [comment]
I don't understand what you are trying to do here. You have only one server, `vagrant@127.0.0.1`, so of course any roles or options you declare will be applied to it.

Keep in mind: You don't deploy to a role in Capistrano; you deploy to servers. Think of roles and options like "tags"; they are a convenient way to filter servers; that's all.

Perhaps it would be less confusing if you avoided using the `role` declaration entirely, and used `server` instead:

```ruby
server "127.0.0.1", :user => "vagrant", :roles => %w(app web db root), :primary => true
```

> Because all roles are not release_roles anymore.

Again, there is no such thing as a *role* being "release" or not. Only *servers* can be considered "release" or not. Either `127.0.0.1` is release, or it isn't. Roles have nothing to do with it.

**Comment by loganfreeman** [comment]
so the following is enough?
```shell
server "127.0.0.1", :user => "vagrant"
```
no tags, no roles. 
I understand what you saying that roles and tags are used to filter servers.
but why the attribute is applied to all roles such that the filter is broken?

Thank you

**Comment by mattbrictson** [comment]
> but why the attribute is applied to all roles

Like I said, the attributes are *not applied to roles*. They are applied to *servers*. When you write this:

```ruby
role :app, %w(server1 server2), options
```

That is just a special shorthand syntax that means:

*Apply the `:app` role and these `options` to servers `server1` and `server2`.*

And when you write:

```ruby
on release_roles(:all)
```

That means:

*Run the following commands on all __servers__, for which the following is true: (1) the server is tagged with the `:all` role; and (2) the server doesn't have the `:no_release` option.*

I totally understand that Capistrano's terminology can be confusing, but we can't really change it at this point. If you have any suggestions for how we can improve the documentation to make things clearer, please let us know!

**Comment by leehambley** [comment]
Issue idle for too long. I'm going to automate the cleanup eventually
