### ISSUE TITLE
Placeholder wait for SSHKit 1.10.x

### ISSUE THREAD

**Issue by leehambley** [capistrano/capistrano#1628]
Placeholder here to remind me that we're waiting for [SSHKit `1.10`](https://github.com/capistrano/sshkit/milestones/1.10.0).

**Comment by mattbrictson** [comment]
We still have to cut a final release of 1.9.0.

**Comment by leehambley** [comment]
Indeed, but I don't feel right changing behaviour in 1.9x when we already
cut an RC, hence 1.10

(sent from my phone, please excuse typos)

**Comment by mattbrictson** [comment]
1.10 was released today.
