### ISSUE TITLE
Capistrano build fails when using Rake 11.0

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1629]
Rake 11.0 was recently released. If you try to run `rake spec` using Rake 11, it fails:

```
$ bundle exec rake spec rubocop
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00000002b73bd8>
/home/travis/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/rake_task.rb:101:in `define'
/home/travis/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/rake_task.rb:78:in `initialize'
/home/travis/build/capistrano/capistrano/Rakefile:7:in `new'
/home/travis/build/capistrano/capistrano/Rakefile:7:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

See also: https://travis-ci.org/capistrano/capistrano/jobs/114234293

My interpretation of the error is that Rake 11.0 is not compatible with RSpec 3.0.4.

We either need to restrict our Rake dependency to `~> 10.5`, or upgrade our RSpec dependency (I'm assuming newer versions of RSpec fix this). I suspect the latter will be more work.

**Comment by mattbrictson** [comment]
Looks like we'll need to upgrade to rspec-core 3.4.4 in order to fix Rake 11.x compatibility: https://github.com/rspec/rspec-core/pull/2197

**Comment by leehambley** [comment]
Keen eye @mattbrictson I'll have a look at this in a sec
