### ISSUE TITLE
NameError: uninitialized constant Capistrano::Application::RAKEVERSION

### ISSUE THREAD

**Issue by tcope25** [capistrano/capistrano#1639]
I'm trying to run a cap task that pulls files from the git repo.

```
serv1$ cap webservers:pull
Stage not set, please call something such as `cap production deploy`, where production is a stage you have defined.
```

```
serv1$ cap --version
cap aborted!
NameError: uninitialized constant Capistrano::Application::RAKEVERSION
```

#### Your configuration

```
Darwin 14.5.0 Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64 x86_64

ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
```

**Comment by will-in-wi** [comment]
Probably related to https://github.com/capistrano/capistrano/issues/1630

**Comment by leehambley** [comment]
@tcope25 please confirm your rake version so we can close this as a duplicate if that's the way it is.

**Comment by tcope25** [comment]
I looked at #1630 when I was researching this issue but it never fixed my issue at that time. I had my Capfile locked at a different version, so I had to change that as well as downgrade to rake 10.5.0. These two fixes got it working. Thanks for the quick response though!

**Comment by leehambley** [comment]
Thanks, I've a release pending on `3.4.1` which should fix this. (as in the other comment) thanks @tcope25

**Comment by koenpunt** [comment]
@leehambley when will `3.4.1` be released?

**Comment by leehambley** [comment]
Today, I've a 6hr train ride dedicated to Cap, 3.5 might land too.

(sent from my phone, please excuse typos)
