### ISSUE TITLE
Documentation, especially rails

### ISSUE THREAD

**Issue by dancinglightning** [capistrano/capistrano#1645]
Hi,
i'm late to the party: just set up my first Capistrano deploy for rails /passenger app.

This works great now that it's set up, but i just wanted to mention that the docs are out of sync and that makes adoption/setup a lot harder than need be.

I saw 3.0 is 2.5 years old and the docs still refer to 2.xx. The setup task "deploy:setup" doesn't seem to exist and with the addition of capistrano-rails / passenger things are substantially different from what i read.

I'd be happy to help in this process, but as a newbie not confident enough to just do it.

Thanks for the tool ,
Torsten

**Comment by leehambley** [comment]
What Docs @dancinglightning - the site at capistranorb.com is up to date and actively maintained.

**Comment by dancinglightning** [comment]
Hi @leehambley ,
i googled capistrano and the "best" newbie guide for a step-by-step setup was the wiki
https://github.com/capistrano/capistrano/wiki/2.x-from-the-beginning

I now saw on the wiki main page a big warning, but the other pages are missing and so i tried to make sense of it. 

The site doesn't have a similar step-by-step into, and is somewhat confusing about the installation, but that is another issues. This is about the wiki, so big notice on every page would resolve this for me.

**Comment by mattbrictson** [comment]
In addition to adding the warning to each page, perhaps we remove the wiki from the capistrano repository and move it to another repository for archival? We don't plan on using the wiki for 3.x documentation, and that would make this clearer.

**Comment by leehambley** [comment]
Indeed, let's just nuke the wiki (archive it somewhere). For end-to-end setup @dancinglightning you might look at https://www.youtube.com/watch?v=kmIownJ6x2I which is a bit out of date, dwells a little no Harrow, but otherwise does walk through Capistrano setup too. (If I grabbed the right link!)

**Comment by mattbrictson** [comment]
You can also check out my two-part article (part 2 concerns Capistrano+Rails):

https://mattbrictson.com/build-and-deploy-a-rails-vps-part-1
https://mattbrictson.com/build-and-deploy-a-rails-vps-part-2

**Comment by dancinglightning** [comment]
Good idea to just remove the wiki. Thanks for the links, i hope i wasn't unclear: my setup is done, i just wanted to report about the experience. Which brings me to comment on those:

@leehambley the video is superfast and only skims, not a good Capistrano intro (good for harrow though)

@mattbrictson that is a nicely written description and probably was spot on at the time: I dare say it is not how one would do this now, at least, and this is the point, not exactly. Eg, why not just require capistrano/rails . Or: in the new capistrano/rails config/secrets.yml is a linked file, so how does it get there (as is database.yml). Or: there is a task to create the directories on the server now (instead of 9)

Don't get me wrong, I understand that all those are small things if you know capistrano, just not if you don't. 

From my point the nuking resolves this issue and i have opened a doc related one on the site. I would suggest such a step-by-step to be part of the official docs, so it can be kept up to date.

**Comment by mattbrictson** [comment]
> I dare say it is not how one would do this now, at least, and this is the point, not exactly.

I disagree. But that's why the article is on my personal site and not part of the official docs: it's *my preferred Capistrano technique* and not necessarily appropriate for the community at large. (E.g. I don't use `secrets.yml` in my deployments.)

Because there are so many choices of Ruby version managers, databases, web servers, app servers, configuration management tools, etc., it is extremely hard to write a document that says "this is the way to deploy Rails". This is probably why no one has volunteered to maintain such a thing in the official docs.

**Comment by will-in-wi** [comment]
https://github.com/capistrano/capistrano/wiki/2.x-from-the-beginning no longer works, so I think this is resolved.
