### ISSUE TITLE
Archive the Capistrano 2.x wiki pages and turn off the wiki for this repo

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1646]
See discussion in #1645.

**Comment by mattbrictson** [comment]
@leehambley @dancinglightning I've created an archive of the 2.x wiki here: https://github.com/capistrano/capistrano-2.x-docs

Does that get the job done? If so I will turn the Capistrano wiki off.

**Comment by leehambley** [comment]
Job done!

(sent from my phone, please excuse typos)

**Comment by mattbrictson** [comment]
OK! The wiki has now been turned off.
