### ISSUE TITLE
Feature: `cap install` should check if we have a Git repository with a valid remote and set it up if not

### ISSUE THREAD

**Issue by leehambley** [capistrano/capistrano#1650]
#### Steps to reproduce

1. Run `cap install` in a directory that is not a Git repository (has no `.git/{,config}`)
2. Observe that cap install continues without error
3. Wonder why I don't have a `:repo_url` in my `deploy.rb`

#### Expected behaviour

* `cap install` should render the default remote (hard-code origin?) as the repository URL in the generated `config/deploy.rb`
* `cap install` should (maybe?) initialize a git repository if one does not exist and recommend to use Github or Bitbucket and print a link

#### Affected Files

* https://github.com/capistrano/capistrano/blame/0e66e7eb8e8696c4d9d33c06d291e1303fc0610c/lib/capistrano/tasks/install.rake

I'm also seeing that install script for the first time and wondering why it's not built using [Rake's file tasks](http://madewithenvy.com/ecosystem/articles/2013/rake-file-tasks/) or a thor generator (I'm far from Thor's biggest fan, last time I used it, it would exit `0` in all cases, because Aruba (rspec CLI testing tool) couldn't handle any other case, I *believe* however this has been fixed)

**Comment by leehambley** [comment]
It just came to my mind that we should also skip this prompt if artefacts of another supported SCM are present.

**Comment by mattbrictson** [comment]
I agree it would be nice if `:repo_url` (and possibly `:application` based on the project directory name) were filled in automatically during `cap install`. But running `git init` might be taking things too far, and it doesn't really save the user much time (they would still need to create the remote repo).

Ultimately, the user still must fill in many aspects of the generated files by hand. E.g. server IPs, additional plugins, etc. So any automation we do will have its limits, and I wouldn't spend too much time on it, IMHO.

**Comment by leehambley** [comment]
> So any automation we do will have its limits, and I wouldn't spend too much time on it, IMHO.

Absolutely it's a fine line to walk, I'm actually more disappointed in myself than anything that I'm so deeply muscle-memory trained to `git init .` after `mkdir` for any new project that I never imagined someone runs `cap install` in a directory that *isn't* already a Git repo.

**Comment by will-in-wi** [comment]
My personal opinion is that I'd rather not have `cap install` do anything other than create the Capistrano specific files. I would find it surprising and mildly annoying if a git repository suddenly appeared by virtue of running cap install.

Alternately, dumping some help text to the extent of indicating what the user needs to do next might be helpful. This would be in lieu of doing it for them.

My 2 cents.

Thanks!

**Comment by mattbrictson** [comment]
I created an alternative feature request that is less ambitious: #1651. Populate the `:repo_url` if possible, but don't run `git init`.
