### ISSUE TITLE
Reported bad build because of Rubocop

### ISSUE THREAD

**Issue by leehambley** [capistrano/capistrano#1670]
Rubocop has apparently gone mad, the change to the README marks the build as broken.

* https://travis-ci.org/capistrano/capistrano/builds/129168416

The outputs there seem new.

**Comment by will-in-wi** [comment]
I wonder whether there is a Rubocop version increase...

**Comment by will-in-wi** [comment]
Yeah, master breaks too. Fixing...

**Comment by mattbrictson** [comment]
Fixed by #1671
