### ISSUE TITLE
capistrano showing annoying warning in rails

### ISSUE THREAD

**Issue by flyingboy007** [capistrano/capistrano#1675]
running rails command showing this annoying warning after setting up  capistrano.

 

       Looks like your app's ./bin/rails is a stub that was generated by Bundler.
        
        In Rails 4, your app's bin/ directory contains executables that are versioned
        like any other source code, rather than stubs that are generated on demand.
        
        Here's how to upgrade:
        
          bundle config --delete bin    # Turn off Bundler's stub generator
          rake rails:update:bin         # Use the new Rails 4 executables
          git add bin                   # Add bin/ to source control
        
        You may need to remove bin/ from your .gitignore as well.
        
        When you install a gem whose executable you want to use in your app,
        generate it and add it to source control:
        
          bundle binstubs some-gem-name
          git add bin/new-executable
        
        WARN: Unresolved specs during Gem::Specification.reset:
              json (>= 1.7.7, ~> 1.7)
              rake (>= 0.8.7)
        WARN: Clearing out unresolved specs.
        Please report a bug if this causes problems.

Everything works fine as of now. But is it something to worry about? I found that its been reported before and I tried to resolve it as recoommended in this post..[issue link][1]

  [1]: https://github.com/capistrano/bundler/issues/45

    add line set :bundle_binstubs, nil
    remove bin from linked dirs set :linked_dirs, %w{log tmp/pids tmp/cache tmp/sockets vendor/bundle public/system}

But is not working in my case..

the gems I use are

      gem 'rails', '4.2.6'
      gem "capistrano", "~> 3.5.0"
      gem 'capistrano-rails', '~> 1.1.6'
      gem 'capistrano-rbenv', '~> 2.0.4'
      gem 'capistrano-passenger'

Am I doing something wrong here or is it safe to ignore?

**Comment by leehambley** [comment]
I'd suggest that Capistrano is in the wrong section of your Gemfile (it should be in a group) and/or that the issue lay with one of the plugins you are using, I'd guess https://github.com/capistrano/rails

The warning is harmless, but if you want to keep it in the main section of your Gemfile, and solve the warning, try asking at https://github.com/capistrano/rails and someone might be able to advise you

**Comment by flyingboy007** [comment]
@leehambley  it is in the development group and not in the main section. only rails is in the main section.

**Comment by leehambley** [comment]
Possibly you added:

```
set :bundle_binstubs, nil
```

Please double check the capistrano/rails docs to see where that line is acceptable.

**Comment by flyingboy007** [comment]
@leehambley  I havent added that line. I will check with capistrano/rails docs thanks..

**Comment by bogdanRada** [comment]
I personally have used that line like this:
```
set :bundle_bins, fetch(:bundle_bins, [])
```
And this configuration seems to be from https://github.com/capistrano/bundler . You migth want to take a look on their documentation.
