### ISSUE TITLE
Feature: Emit warning when invoke is used on a task that has already been invoked

### ISSUE THREAD

**Issue by leehambley** [capistrano/capistrano#1689]
See discussion in #1686 .

I think we have to monkey patch https://github.com/ruby/rake/blob/master/lib/rake/task.rb#L184 and hook in there (actually given that this only *reads* the value of `@already_invoked` we could just alias chain this method and emit a warning before hand if `@already_invoked` is truthy.

**Comment by mattbrictson** [comment]
Fixed via #1689.

**Comment by mattbrictson** [comment]
Reopening since #1724 was reverted.
