### ISSUE TITLE
I want Translate capistrano website into chinese, what should i do?

### ISSUE THREAD

**Issue by 1c7** [capistrano/capistrano#1690]
http://capistranorb.com/

:smile:

**Comment by InsomniaZ** [comment]
come on

**Comment by 1c7** [comment]
@InsomniaZ  what?

**Comment by leehambley** [comment]
Hey @1c7 thanks for the kind offer!

I'd prefer that you didn't as we've got some incoming changes to the site planned, and the documentation is difficult to keep in sync and up to date already, only in one language (the native language of two of the most active contributors!)

Would the site be translated into a foreign language I'd be very concerned that we couldn't commit to keep it up to date.

On the other hand, maybe it opens a whole new world in SE Asia to developers who can't benefit from Capistrano's existing docs, I'm not sure.

Would we have any more volunteers for keeping the documentation in foreign languages up to date ?

**Comment by 1c7** [comment]
@leehambley 
I am asking around on Ruby China Community see if more people interesting 
https://ruby-china.org/topics/30147

**Comment by will-in-wi** [comment]
@leehambley Do you know if there is software which allows us to track (ideally on a paragraph by paragraph level) which parts of the docs changed, and throw them in a queue for translation? It'd be nice to have the docs translated, and perhaps it would be doable if it was easy to mark which sections were up to date and help translate them…

With that said, perhaps it is better to have up to date docs in one language than out of date docs in many. Also, if a non-English speaker tried to ask for help in a ticket or SO post, I'm not sure how many people could help…

My 2¢ (in American currency).

**Comment by leehambley** [comment]
> @leehambley Do you know if there is software which allows us to track (ideally on a paragraph by paragraph level) which parts of the docs changed, and throw them in a queue for translation? It'd be nice to have the docs translated, and perhaps it would be doable if it was easy to mark which sections were up to date and help translate them…

The only thing I've seen is Git backed book authorship tools

**Comment by 1c7** [comment]
if you guys decide to use some translation tool, just let me know :D

btw, how http://capistranorb.com/ work?
some kind of CMS like wordpress? but write in Rails?
or just static website that generate by markdown document?

**Comment by mattbrictson** [comment]
The http://capistranorb.com site is generated using Jekyll, based on files in this repository: https://github.com/capistrano/documentation . There is a short README that explains how to build the site locally. We use GitHub Pages for hosting, which is free. Any code pushed to the `gh-pages` branch is automatically deployed to the site. It is mostly Markdown documents with some HTML and CSS.

Could you please move this discussion to a new issue in the documentation repository here? https://github.com/capistrano/documentation/issues . We try to keep all documentation-related issues and discussion in that repo.

Thanks!

**Comment by 1c7** [comment]
done.

https://github.com/capistrano/documentation/issues/191

:D

**Comment by mattbrictson** [comment]
We are planning to move the official documentation into this repository (under `docs/`), so I'm reopening this original issue and closing duplicate #1759.

**Comment by InFog** [comment]
Are there any plans to make capistranorb.com multilanguage?

**Comment by leehambley** [comment]
No, all three of the principal maintainers are native english speakers. As a Hamburg immigrant I could do a German translation …… but which Germans don't speak good enough English to read the docs?

**Comment by InFog** [comment]
I could do a Portuguese translation, but as soon as we start translating stuff the translators would have a bad time keeping everything up to date.

I guess it is better to close this issue then.

**Comment by BerkhanBerkdemir** [comment]
I'm not a contributor nor maintainer but use Capistrano. I believe the documentation should only be **English**. There is just one reason for it

* Documentation changes over the time and the translated document may stay behind it

Of course, managing translated document is not the job of maintainers, but controlling and checking are also another important step.

**Comment by 1c7** [comment]
understood, Thanks
