### ISSUE TITLE
`ArgumentError: comparison of Symbol with String failed` when running cap production doctor

### ISSUE THREAD

**Issue by zavan** [capistrano/capistrano#1691]
#### Steps to reproduce
Not sure, I just ran `cap production doctor` for the first time on my project.
Deploys are working as usual.

#### Your configuration
`cap production doctor --trace`

** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
Please enter 'production' if you know what you're doing (): production
** Invoke rbenv:validate (first_time)
** Execute rbenv:validate
** Invoke rbenv:map_bins (first_time)
** Execute rbenv:map_bins
** Invoke bundler:map_bins (first_time)
** Execute bundler:map_bins
** Invoke deploy:set_rails_env (first_time)
** Execute deploy:set_rails_env
** Invoke deploy:set_linked_dirs (first_time)
** Execute deploy:set_linked_dirs
** Invoke deploy:set_rails_env 
** Invoke doctor (first_time)
** Invoke doctor:environment (first_time)
** Execute doctor:environment

Environment

    Ruby     ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
    Rubygems 2.5.1
    Bundler  N/A
    Command  /home/zavan/.rbenv/versions/2.3.1/bin/cap production doctor
** Invoke doctor:gems (first_time)
** Execute doctor:gems

Gems

    capistrano              3.5.0
    airbrussh               1.0.2
    rake                    11.1.2
    sshkit                  1.10.0
    capistrano-bundler      1.1.4
    capistrano-harrow       0.5.1
    capistrano-rails        1.1.6
    capistrano-rbenv        2.0.4
    capistrano3-delayed-job 1.7.2
    capistrano3-puma        1.2.1
** Invoke doctor:variables (first_time)
** Execute doctor:variables

Variables

cap aborted!
ArgumentError: comparison of Symbol with String failed
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/doctor/variables_doctor.rb:23:in `sort'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/doctor/variables_doctor.rb:23:in `call'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/tasks/doctor.rake:17:in `block (2 levels) in <top (required)>'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `block in execute'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `each'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/airbrussh-1.0.2/lib/airbrussh/rake/context.rb:62:in `execute'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:209:in `block in invoke_prerequisites'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:207:in `each'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:207:in `invoke_prerequisites'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:186:in `block in invoke_with_call_chain'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `each'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block in top_level'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:78:in `block in run'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/application.rb:14:in `run'
/home/zavan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/bin/cap:3:in `<top (required)>'
/home/zavan/.rbenv/versions/2.3.1/bin/cap:23:in `load'
/home/zavan/.rbenv/versions/2.3.1/bin/cap:23:in `<main>'
Tasks: TOP => doctor => doctor:variables

**Comment by mattbrictson** [comment]
Are you calling `set` with a string key? Like this:

```ruby
set "my_var", "value"
```

Instead of this:

```ruby
set :my_var, "value"
```

Regardless, the doctor command shouldn't crash, but I want to understand why it isn't working in your case. Thanks for the report!

**Comment by zavan** [comment]
No, just checked. Also couldn't find anything in any of the capistrano gems I'm using (all in the latest version).

You're welcome, thanks for the gem!

**Comment by mattbrictson** [comment]
@zavan Can you try using my branch in PR #1695 and let me know if it fixes the bug for you?

**Comment by zavan** [comment]
Working!

After seeing the output:
```
"'production' if you know what you're doing" is not a recognized Capistrano setting (config/deploy/production.rb:1)
:bundle_binstubs is not a recognized Capistrano setting (config/deploy.rb:25)
"company code:" is not a recognized Capistrano setting (config/deploy/production.rb:12)
:linked_files is not a recognized Capistrano setting (config/deploy.rb:10)
```
I believe the problem is related to my code in `production.rb`:
```ruby
# check if the user really intended to deploy to production
set :env_check, ask("'production' if you know what you're doing", nil)

# get the subdomain
set :company_code, ask('company code:', 'some-company-code') 
```

**Comment by mattbrictson** [comment]
@zavan Ah, that's not how `ask` is intended to be used. Use `ask` by itself, not in conjunction with `set`.

E.g.

```ruby
ask :env_check
ask :company_code
```

This will then prompt and automatically set the value based on the user's input.

There is no easy way to change the text of the prompt; Capistrano will always prompt using this template:

```
Please enter %{key} (%{default_value}): 
```

If you think custom prompts would be a nice feature, feel free to open a feature request issue or propose a PR. Perhaps something like this?

```ruby
ask :env_check, nil, prompt: %q(Enter "production" if you know what you're doing)
```

**Comment by zavan** [comment]
I was following [the documentation](http://capistranorb.com/documentation/getting-started/user-input/) :stuck_out_tongue: 

I will check how hard it will be to do this, if it's not veeery hard I may implement it.

Thank you for the support!

**Comment by mattbrictson** [comment]
Yeah… pretty sure the documentation is wrong. I'll take care it. Thanks!
