### ISSUE TITLE
Is there any way to print full commands without "..." that are displayed while deploying?

### ISSUE THREAD

**Issue by nextofsearch** [capistrano/capistrano#1692]
Hi,

Is there any way to print full commands without "..." that are displayed while deploying? I'm troubleshooting of an issue that sidekiq is not running issue in multi-stage set-up even though there is no error while deploying.

#### Steps to reproduce
cap dev deploy

#### Expected behaviour
Sidekiq should start

#### Actual behaviour
There is no pid of sidekiq and no process either.

#### Your configuration

vm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
ruby-2.3.0@rails4.2
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

Environment

    Ruby     ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    Rubygems 2.5.1
    Bundler  1.11.2
    Command  /Users/danolee/.rvm/gems/ruby-2.3.0@rails42/bin/cap dev doctor

Gems

    capistrano                        3.5.0
    airbrussh                         1.0.2
    rake                              11.1.2
    sshkit                            1.10.0
    capistrano-bundler                1.1.4
    capistrano-git-submodule-strategy 0.1.20
    capistrano-harrow                 0.5.1
    capistrano-rvm                    0.1.2
    capistrano-sidekiq                0.5.4

Variables

    :application                 "worker"
    :branch                      "dev"
    :bundle_bins                 ["gem", "rake", "rails", "sidekiq", "sidekiqctl"]
    :bundle_flags                "--deployment --quiet"
    :bundle_path                 #<Pathname:/home/deployer/apps/worker/shared/bundle>
    :bundle_roles                :all
    :bundle_servers              [#<Capistrano::Configuration::Server:0x007f898b6d0be8 @user="deployer", @hostname="ec2-107-21-74-129.compute-1.amazonaws.com", @port=nil, @properties=#<Capistrano::Configuration::Server::Properties:0x007f898b6d0710 @properties={}, @roles=#<Set: {:app}>>>]
    :bundle_without              "development test"
    :chruby_map_bins             ["sidekiq", "sidekiqctl"]
    :default_env                 {}
    :deploy_to                   "/home/deployer/apps/worker"
    :deploy_user                 "deployer"
    :format                      :airbrussh
    :git_environmental_variables {:git_askpass=>"/bin/echo", :git_ssh=>"/tmp/worker/git-ssh.sh"}
    :git_strategy                Capistrano::Git::SubmoduleStrategy
    :keep_releases               5
    :local_user                  "danolee"
    :log_level                   :debug
    :pty                         false
    :rbenv_map_bins              ["sidekiq", "sidekiqctl"]
    :repo_url                    "@@@@@#@#@#@#@#"
    :rvm_map_bins                ["gem", "rake", "ruby", "bundle", "sidekiq", "sidekiqctl"]
    :rvm_path                    "~/.rvm"
    :rvm_ruby_version            "default"
    :rvm_type                    :auto
    :scm                         :git
    :sidekiq_config              "/home/deployer/apps/worker/shared/config/sidekiq.yml"
    :sidekiq_default_hooks       true
    :sidekiq_env                 "dev"
    :sidekiq_log                 "/home/deployer/apps/worker/shared/log/sidekiq.log"
    :sidekiq_options_per_process nil
    :sidekiq_pid                 "/home/deployer/apps/worker/shared/tmp/pids/sidekiq.pid"
    :sidekiq_processes           1
    :sidekiq_role                :app
    :sidekiq_timeout             10
    :sidekiq_user                nil
    :ssh_options                 {:keys=>["~/.ssh/aws-staging.pem"]}
    :stage                       :dev
    :tmp_dir                     "/tmp"

    :git_strategy is not a recognized Capistrano setting (config/deploy.rb:22)
    :sidekiq_config is not a recognized Capistrano setting (config/deploy.rb:50)

**Comment by leehambley** [comment]
https://github.com/mattbrictson/airbrussh#configuration
