### ISSUE TITLE
Syntax Error on Ruby 1.9.3

### ISSUE THREAD

**Issue by rscarvalho** [capistrano/capistrano#1693]
Ruby 1.9.3 doesn't support keyword arguments, and you're using them a lot here. If you do not support 1.9.3 please describe that [in your rubygems.org page](https://rubygems.org/gems/capistrano)

#### Steps to reproduce

I'm sure this is not specific to rails apps, but this was how I could get this reproduced:

1. Create a simple rails app
2. Configure `capistrano` and `capistrano-rails` in the Gemfile Following [the official docs](https://github.com/capistrano/rails/#installation)
3. Run `bundle exec cap install`

#### Expected behaviour

This command should capify the application

#### Actual behaviour

```sh
$ bundle exec cap install
/Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/lib/capistrano/configuration/filter.rb:1:in `require': /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/lib/capistrano/configuration.rb:132: syntax error, unexpected tLABEL (SyntaxError)
    def install_plugin(plugin, load_hooks:true)
                                          ^
/Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/lib/capistrano/configuration.rb:157: syntax error, unexpected keyword_end, expecting $end
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/lib/capistrano/configuration/filter.rb:1:in `<top (required)>'
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/lib/capistrano/dsl.rb:5:in `require'
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/lib/capistrano/dsl.rb:5:in `<top (required)>'
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/lib/capistrano/all.rb:11:in `require'
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/lib/capistrano/all.rb:11:in `<top (required)>'
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/bin/cap:2:in `require'
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/bin/cap:2:in `<top (required)>'
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/bin/cap:23:in `load'
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/bin/cap:23:in `<main>'
```

#### Your configuration

```sh
$ bundle exec cap doctor
/Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/lib/capistrano/configuration/filter.rb:1:in `require': /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/lib/capistrano/configuration.rb:132: syntax error, unexpected tLABEL (SyntaxError)
    def install_plugin(plugin, load_hooks:true)
                                          ^
/Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/lib/capistrano/configuration.rb:157: syntax error, unexpected keyword_end, expecting $end
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/lib/capistrano/configuration/filter.rb:1:in `<top (required)>'
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/lib/capistrano/dsl.rb:5:in `require'
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/lib/capistrano/dsl.rb:5:in `<top (required)>'
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/lib/capistrano/all.rb:11:in `require'
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/lib/capistrano/all.rb:11:in `<top (required)>'
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/bin/cap:2:in `require'
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/gems/capistrano-3.5.0/bin/cap:2:in `<top (required)>'
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/bin/cap:23:in `load'
	from /Users/rodolfo/code/rails/dre/vendor/ruby/1.9.1/bin/cap:23:in `<main>'
```

**Comment by leehambley** [comment]
See https://github.com/capistrano/capistrano/commit/552eeaab6361ee283ae33d356ef73eb86ec3131e

**Comment by rscarvalho** [comment]
@leehambley I see you changed it in the gemspec file, but I insist the information in **rubygems.org** is outdated: https://rubygems.org/gems/capistrano (The required version still says `>= 1.9.3`). Maybe more an admin task.

**Comment by mattbrictson** [comment]
@rscarvalho rubygems.org simply shows the requirements of the latest *published* released. We have not yet published a new version of Capistrano since this was fixed. This will probably happen in the next few weeks.

**Comment by hcatlin** [comment]
👋  from someone in March 2017 with this issue! :)

**Comment by leehambley** [comment]
Sorry @hcatlin - [Support for Ruby version 1.9.3 will end on February 23, 2015](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/)!

**Comment by leehambley** [comment]
Also, what's a fine, upstanding member of the Ruby community such as yourself doing playing with stone-age tooling?!

**Comment by Marcofeli** [comment]
Hi, actually I'm working with the stone-age tooling `Ruby 1.9.3` for some reason on 2018, so, I have this issue. Could one of you guys help me finding out a `Capistrano`  compatible version with this fossil?

**Comment by mattbrictson** [comment]
@Marcofeli a good place to look for answers is our changelog. According to our changelog, we dropped support for 1.9.3 with Capistrano 3.5.0. So I would suggest you try 3.4.0.

https://github.com/capistrano/capistrano/blob/master/CHANGELOG.md#350

<img width="711" alt="screen shot 2018-10-02 at 8 16 59 am" src="https://user-images.githubusercontent.com/189693/46358329-a0dc2a00-c61b-11e8-91a4-7f498f7eca66.png">
