### ISSUE TITLE
Doctor incorrectly reports ":git_strategy is not a recognized Capistrano setting"

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1694]
The `:git_strategy` variable is known by Capistrano and used by the built-in Git SCM. So this warning from `doctor:variables` is wrong:

```
:git_strategy                Capistrano::Git::SubmoduleStrategy

:git_strategy is not a recognized Capistrano setting (config/deploy.rb:22)
```

**Comment by mattbrictson** [comment]
If someone wants to try fixing this, it should just be a matter of adding `:git_strategy, :hg_strategy, :svn_strategy` to `VariablesDoctor::WHITELIST`.

**Comment by ShaneSaww** [comment]
@mattbrictson I have a commit ready to go that fixes this issue, but when setting up a new laptop I messed my git config. I'm going to fix that then re-upload this commit and open a PR once everything looks good. Assuming that works for you.

**Comment by mattbrictson** [comment]
Thanks! The commit looks good and I would appreciate the PR once you are ready. That said, please see if you can also include a test and a CHANGELOG entry in the PR. I can give you pointers on writing the test if you get stuck.

**Comment by ShaneSaww** [comment]
@mattbrictson Here is the new commit(if you want to make sure everything is good). 
I started working on the test, but I'm not 100% on how to best test it, so any guidance would be helpful.

**Comment by mattbrictson** [comment]
OK, can you please open a PR with what you have so far? We can move the discussion there.

Don't worry about making the commit perfect, we can always make tweaks and clean things up before the PR is ultimately merged. The important thing is to have a PR so there is a natural place for the discuss and review.

**Comment by ShaneSaww** [comment]
Awesome! PR is opened.
