### ISSUE TITLE
Suggestion: Primary should yield multiple servers (again)

### ISSUE THREAD

**Issue by Bertg** [capistrano/capistrano#1698]
In the 2.x versions of Capistrano indicating multiple servers as primary would execute the commands on each primary server. In the 3.x series this is only the first server. 

We have a specific use case where this is required: 

We have the same app deployed to multiple servers, and these exist in isolation. We do like to update these at the same time. This worked great for migrations in the 2.x series, but fails now on the 3.x series.

Two feature suggestions to enable this without surprises: 

* Warn (or fail) if multiple primary servers are configured
* Have a setting that explicitly ALLOWS multiple primary servers

If you think this is an acceptable change, I can implement it.

**Comment by will-in-wi** [comment]
I think this was fixed in https://github.com/capistrano/rails/pull/168

**Comment by mattbrictson** [comment]
Yes, in the latest `capistrano-rails` (in master, not yet released), you can now configure database migrations to run on whatever servers you want. See https://github.com/capistrano/rails/pull/168 for details. It sounds like that will address your use case.

I would rather not change the behavior of `primary`.

Let us know if the new `capistrano-rails` behavior works for you.

**Comment by Bertg** [comment]
@will-in-wi & @mattbrictson Thx for the info about the change in ```capistrano-rails```. This helps my specific case.

I do think that the suggested behaviour could be useful. If not added each capistrano plugin will have to do their own version of the fix that ```capistrano-rails``` has done.  I'll leave it to your judgement.

**Comment by leehambley** [comment]
Primary is specifically intended to be used for things where you can name one server to be specifically used. 

Thanks for reporting that fixed.
