### ISSUE TITLE
Capistrano 2.15.8 release missing changes?

### ISSUE THREAD

**Issue by Aqualon** [capistrano/capistrano#1701]
Hi, 

I just saw, that capistrano 2.15.8 exists on rubygems.org and according to gem-compare only the version changed and nothing else was changed codewise

```
$ gem compare capistrano 2.15.7 2.15.8
Fetching: capistrano-2.15.7.gem (100%)
Fetching: capistrano-2.15.8.gem (100%)
Compared versions: ["2.15.7", "2.15.8"]
  DIFFERENT date:
    2.15.7: 2015-11-15 00:00:00 UTC
    2.15.8: 2016-05-30 00:00:00 UTC
  DIFFERENT rubygems_version:
    2.15.7: 2.0.14
    2.15.8: 2.6.3
  DIFFERENT version:
    2.15.7: 2.15.7
    2.15.8: 2.15.8
  DIFFERENT files:
    2.15.7->2.15.8:
      * Changed:
            lib/capistrano/version.rb +1/-1
```

What's the reasoning behind this release? Or was it supposed to contain the two commits by @eric I see in https://github.com/capistrano/capistrano/commits/legacy-v2 which are not in the release?

**Comment by leehambley** [comment]
it was not supposed to contain any new commits, it was a canary release to test how many people had `~> 2.15.0` vs `2.15.7` hard coded in their gemfiles and gemspecs to measure how much effort it was worth putting into maintaining old versions, and/or thinking about starting to force people to upgrade.

See the notes on the releases page:

* https://github.com/capistrano/capistrano/releases/tag/v2.15.8
* https://github.com/capistrano/capistrano/releases/tag/v2.5.22

**Comment by leehambley** [comment]
@eric do you recall why we didn't release an updated version of 2.x.x at the time? (sorry to drag you into a thread six months after the fact)

**Comment by eric** [comment]
I don't recall why we didn't release it, but I definitely would be in favor of it.

**Comment by leehambley** [comment]
Released

* https://github.com/capistrano/capistrano/releases/tag/v2.15.9
* https://rubygems.org/gems/capistrano/versions/2.15.9
* https://github.com/capistrano/capistrano/releases/tag/v2.15.9
