### ISSUE TITLE
Remove `remote_file` method

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1710]
We've deprecated `remote_file` with a promise that it will be removed entirely in Capistrano 3.7.0. This issue is a reminder to remove it.

See #1679.

**Comment by mattbrictson** [comment]
Note that there is also a Cucumber feature that needs to be removed: https://github.com/capistrano/capistrano/blob/v3.5.0/features/remote_file_task.feature

**Comment by SaiVardhan** [comment]
@mattbrictson  Can you help me to get started with my contribution on this

**Comment by will-in-wi** [comment]
@SaiVardhan I'd suggest taking a look at the diff in https://github.com/capistrano/capistrano/commit/15085fd952cd1ea66cd2c0fd25f00f3f6eda0460.

I'd delete the `#remote_file` method in `lib/capistrano/dsl/task_enhancements.rb` and make all the tests pass again.

That'd at least be a start.

**Comment by mattbrictson** [comment]
#1745 was merged so this can be closed.
