### ISSUE TITLE
cap production deploy failed

### ISSUE THREAD

**Issue by yanchengv** [capistrano/capistrano#1720]
`DEBUG [1a31c418] Running /usr/bin/env [ -L /data/www/wechat/releases/20160705062743/tmp/pids ] as deploy@123.53.163.52
DEBUG [1a31c418] Command: [ -L /data/www/wechat/releases/20160705062743/tmp/pids ]

DEBUG [1a31c418] Finished in 0.017 seconds with exit status 1 (failed).

DEBUG [22cd258a] Running /usr/bin/env [ -d /data/www/wechat/releases/20160705062743/tmp/pids ] as deploy@123.53.163.52
DEBUG [22cd258a] Command: [ -d /data/www/wechat/releases/20160705062743/tmp/pids ]

DEBUG [22cd258a] Finished in 0.017 seconds with exit status 1 (failed).

INFO [195ac70e] Running /usr/bin/env ln -s /data/www/wechat/shared/tmp/pids /data/www/wechat/releases/20160705062743/tmp/pids as deploy@123.53.163.52
DEBUG [195ac70e] Command: /usr/bin/env ln -s /data/www/wechat/shared/tmp/pids /data/www/wechat/releases/20160705062743/tmp/pids

INFO [195ac70e] Finished in 0.017 seconds with exit status 0 (successful).

DEBUG [8f8edb2c] Running /usr/bin/env [ -L /data/www/wechat/releases/20160705062743/tmp/cache ] as deploy@123.53.163.52
DEBUG [8f8edb2c] Command: [ -L /data/www/wechat/releases/20160705062743/tmp/cache ]

DEBUG [8f8edb2c] Finished in 0.018 seconds with exit status 1 (failed).

DEBUG [bcb78ffb] Running /usr/bin/env [ -d /data/www/wechat/releases/20160705062743/tmp/cache ] as deploy@123.53.163.52
DEBUG [bcb78ffb] Command: [ -d /data/www/wechat/releases/20160705062743/tmp/cache ]

DEBUG [bcb78ffb] Finished in 0.014 seconds with exit status 1 (failed).

INFO [1de5a053] Running /usr/bin/env ln -s /data/www/wechat/shared/tmp/cache /data/www/wechat/releases/20160705062743/tmp/cache as deploy@123.53.163.52
DEBUG [1de5a053] Command: /usr/bin/env ln -s /data/www/wechat/shared/tmp/cache /data/www/wechat/releases/20160705062743/tmp/cache

INFO [1de5a053] Finished in 0.019 seconds with exit status 0 (successful).

DEBUG [003d5698] Running /usr/bin/env [ -L /data/www/wechat/releases/20160705062743/tmp/sockets ] as deploy@123.53.163.52
DEBUG [003d5698] Command: [ -L /data/www/wechat/releases/20160705062743/tmp/sockets ]

DEBUG [003d5698] Finished in 0.014 seconds with exit status 1 (failed).

DEBUG [3b686222] Running /usr/bin/env [ -d /data/www/wechat/releases/20160705062743/tmp/sockets ] as deploy@123.53.163.52
DEBUG [3b686222] Command: [ -d /data/www/wechat/releases/20160705062743/tmp/sockets ]

DEBUG [3b686222] Finished in 0.014 seconds with exit status 1 (failed).

INFO [99ffd5e7] Running /usr/bin/env ln -s /data/www/wechat/shared/tmp/sockets /data/www/wechat/releases/20160705062743/tmp/sockets as deploy@123.53.163.52
DEBUG [99ffd5e7] Command: /usr/bin/env ln -s /data/www/wechat/shared/tmp/sockets /data/www/wechat/releases/20160705062743/tmp/sockets
INFO [99ffd5e7] Finished in 0.015 seconds with exit status 0 (successful).
`

**Comment by mattbrictson** [comment]
Please use the issue template when reporting bugs. We need more information about what you are trying to do and where it is failing.

As it stands I don't see any errors in the log you posted. Closing.
