### ISSUE TITLE
Undefined method `config'

### ISSUE THREAD

**Issue by lhtdesignde** [capistrano/capistrano#1722]
Hi guys,
I'm running into an error when trying to deploy. I'm using version 3.5.0

`.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slackistrano-2.0.1/lib/slackistrano/capistrano.rb:73:in `block in post': undefined method `config' for #<Capistrano::Configuration:0x007f9454232ec8> (NoMethodError)`

Not sure where to look. Please maybe just point me to what this could be caused by. Thanks!

**Comment by troelskn** [comment]
Seems to be a problem in slackistrano, a 3rd party addon. Suggest you open an issue at https://github.com/phallstrom/slackistrano

**Comment by leehambley** [comment]
Please make sure you are using a plugin designed for Capistrano 2.

**Comment by lhtdesignde** [comment]
sorry yes was an old slackistrano plugin. thank you!
