### ISSUE TITLE
Question. Is it possible to specify a custom Capfile from command line?

### ISSUE THREAD

**Issue by bogdanRada** [capistrano/capistrano#1725]
Hello,
   First of all i want to thank You for the great work You are doing. I love this gem.

   I love it so much that i am working on a open-source proiect for deploying multiple applications în paralel . You can find it here: [capistrano_multiconfig_paralllel](https://github.com/bogdanRada/capistrano_multiconfig_parallel) 

I am working on version 2.0 which now is in a release candidate version ( rc2) .

I am going to try to explain în very short words why i need this feature. 

The old version required the gem to Be bundled în each of the applications Gemfile(s) which was not a good idea.

The new version doesn't need that. It can deploy any applications from any path on the machine 
By using a simple Yaml config file with the paths to those applications and without bundling it în every Application 

În order to make this work i have created another gem [capistrano_sentinel](https://github.com/bogdanRada/capistrano_sentinel]. Which basically emits some websocket events before a task is invoked and the first gem handles the parallel deploy and the part with consuming those messagea and acting on them depending on configuration

În order for this to work the first gem checks if the second one is part of the application Gemfile . 
If it is it will use that Gemfile and the Capfile of the application to deploy it în parallel.

The problem though is that if the second gem is not part of the application Gemfile . The first gem will create automatically a file 'Gemfile.multi_cap' which will contain besides the original Gemfile the other gem too.

În this case though în order to Be able to load the second gem properly i have to Patch automatically the Capfile of the application în order to require it.

But i really don't like that because then You won't be able to do normal Capistrano tasks while the jobs created by my gem are running. Because the original Gemfile doesn't contain it. So that will result în a LoadError if the second request is made from another terminal or terminal screen. 

So i was thinking if maybe would be possible to do something like Bundler does to specify a custom Capfile when running a Capistrano task either by a command line option or environment variable.  This would allow me to copy for that specific case the original Capfile , patch to include the other gem and that would not affect the original application. 

I know that is a long story   . I really tried to make it at short as possible. I know probably no one else would be interested în this feature.....it is really a corner case. But would really make my Day if this would be possible.

Sorry if i misspelled some letters . I am on my phone right now.

**Comment by mattbrictson** [comment]
Yes, Capistrano is built on Rake, and so it accepts the `-f` option to specify the Rakefile/Capfile.

```
cap -f Capfile.custom production deploy
```

Is that what you had in mind?

**Comment by bogdanRada** [comment]
Yes. I had no idea about that option . Awesome . You made my Day :)
