### ISSUE TITLE
Add acceptance test for deploy:rollback

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1736]
In general, Capistrano has several acceptance tests in the form of Cucumber features, and also many RSpec tests. Overall coverage is pretty good.

**However we are completely missing any kind of test for the `deploy:rollback` task.** This includes the general rollback functionality, plus the new `ROLLBACK_RELEASE` option that was recently added in #1731.

For reference, the rollback behavior is documented here: http://capistranorb.com/documentation/getting-started/rollbacks/

I think adding an acceptance test for this is a high priority. At its most basic, a Cucumber feature could:
1. Perform a deploy twice
2. Perform a rollback
3. Verify the `current` symlink points to the earlier release

Any help would be very much appreciated!

**Comment by larson004** [comment]
@mattbrictson  We should be closing this issue.

**Comment by mattbrictson** [comment]
Yes, thanks for the reminder! Closing

**Comment by mattbrictson** [comment]
Fixed via #1891
