### ISSUE TITLE
Capistrano Cucumber features are failing

### ISSUE THREAD

**Issue by SaiVardhan** [capistrano/capistrano#1743]
Hi,

When I try to run the capistrano cucumber features they are getting failed.

I installed bundler(1.10.5),Virtual Box and Vagrant. I can see a failure count of **13** features.

I tried running `bundle _1.10.5_ exec rake features`

**Comment by leehambley** [comment]
Can you post your output please, and try and fulfil some of the fields listed in the issue template that you deleted.

**Comment by SaiVardhan** [comment]
Sure @leehambley .

$ bundle exec rake features

Here is my output

`cap aborted!
Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:2220
/tmp/test_app/lib/capistrano/tasks/fail.rake:4:in `block (2 levels) in <top (required)>'
Tasks: TOP => deploy:starting => fail
(See full trace by running task with --trace)
The deploy has failed with an error: Connection refused - connect(2) for 127.0.0.1:2220
/home/sait/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/socket.rb:65:in `connect': Connection refused - connect(2) for 127.0.0.1:2220 (Errno::ECONNREFUSED)
	from /home/sait/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/socket.rb:65:in `connect_internal'
	from /home/sait/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/socket.rb:140:in `connect'
	from /home/sait/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/socket.rb:338:in `block in tcp'
	from /home/sait/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/socket.rb:232:in `each'
	from /home/sait/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/socket.rb:232:in `foreach'
	from /home/sait/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/socket.rb:328:in `tcp'
	from /home/sait/.rvm/gems/ruby-2.2.2/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:70:in `initialize'
	from /home/sait/.rvm/gems/ruby-2.2.2/gems/net-ssh-3.2.0/lib/net/ssh.rb:232:in `new'
	from /home/sait/.rvm/gems/ruby-2.2.2/gems/net-ssh-3.2.0/lib/net/ssh.rb:232:in `start'
	from /home/sait/.rvm/gems/ruby-2.2.2/gems/sshkit-1.11.2/lib/sshkit/backends/connection_pool.rb:59:in `call'
	from /home/sait/.rvm/gems/ruby-2.2.2/gems/sshkit-1.11.2/lib/sshkit/backends/connection_pool.rb:59:in `with'
	from /home/sait/.rvm/gems/ruby-2.2.2/gems/sshkit-1.11.2/lib/sshkit/backends/netssh.rb:155:in `with_ssh'
	from /home/sait/.rvm/gems/ruby-2.2.2/gems/sshkit-1.11.2/lib/sshkit/backends/netssh.rb:108:in `execute_command'
	from /home/sait/.rvm/gems/ruby-2.2.2/gems/sshkit-1.11.2/lib/sshkit/backends/abstract.rb:141:in `block in create_command_and_execute'
	from /home/sait/.rvm/gems/ruby-2.2.2/gems/sshkit-1.11.2/lib/sshkit/backends/abstract.rb:141:in `tap'
	from /home/sait/.rvm/gems/ruby-2.2.2/gems/sshkit-1.11.2/lib/sshkit/backends/abstract.rb:141:in `create_command_and_execute'
	from /home/sait/.rvm/gems/ruby-2.2.2/gems/sshkit-1.11.2/lib/sshkit/backends/abstract.rb:74:in `execute'
	from /tmp/test_app/lib/capistrano/tasks/failed.rake:3:in `block (2 levels) in <top (required)>'
	from /home/sait/.rvm/gems/ruby-2.2.2/gems/sshkit-1.11.2/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
	from /home/sait/.rvm/gems/ruby-2.2.2/gems/sshkit-1.11.2/lib/sshkit/backends/abstract.rb:29:in `run'
	from /home/sait/.rvm/gems/ruby-2.2.2/gems/sshkit-1.11.2/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
  Scenario: Triggering the custom task # features/deploy_failure.feature:14
    When I run cap "deploy"            # features/step_definitions/cap_commands.rb:1
    But an error is raised             # features/step_definitions/assertions.rb:109
      [vagrant] ssh -c "[ -f \"/home/vagrant/var/www/deploy/shared/fail\" ]"
      [vagrant] /home/sait/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler.rb:394:in `rescue in eval_gemspec':  (Bundler::Dsl::DSLError)
      [vagrant] [!] There was an error parsing `Gemfile`: There was a RuntimeError while loading capistrano.gemspec: 
      [vagrant] can't modify frozen String from
      [vagrant]   /home/sait/pramati/opensource/capistrano/capistrano.gemspec:8:in `block in <main>'
      [vagrant] . Bundler cannot continue.
      [vagrant] 
      [vagrant]  #  from /home/sait/pramati/opensource/capistrano/Gemfile:4
      [vagrant]  #  -------------------------------------------
      [vagrant]  #  # Specify your gem's dependencies in capistrano.gemspec
      [vagrant]  >  gemspec
      [vagrant]  #  
      [vagrant]  #  -------------------------------------------
      [vagrant] 	from /home/sait/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler.rb:383:in `eval_gemspec'
      [vagrant] 	from /home/sait/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler.rb:344:in `block in load_gemspec_uncached'
      [vagrant] 	from /home/sait/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:53:in `chdir'
      [vagrant] 	from /home/sait/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:53:in `block in chdir'
      [vagrant] 	from /usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
      [vagrant] 	from /home/sait/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:52:in `chdir'
      [vagrant] 	from /home/sait/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler.rb:339:in `load_gemspec_uncached'
      [vagrant] 	from /home/sait/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler.rb:329:in `load_gemspec'
      [vagrant] 	from /home/sait/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/dsl.rb:56:in `gemspec'
      [vagrant] 	from /home/sait/pramati/opensource/capistrano/Gemfile:4:in `eval_gemfile'
      [vagrant] 	from /home/sait/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/dsl.rb:36:in `instance_eval'
      [vagrant] 	from /home/sait/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/dsl.rb:36:in `eval_gemfile'
      [vagrant] 	from /home/sait/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/dsl.rb:10:in `evaluate'
      [vagrant] 	from /home/sait/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/definition.rb:24:in `build'
      [vagrant] 	from /home/sait/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler.rb:120:in `definition'
      [vagrant] 	from /home/sait/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler.rb:88:in `setup'
      [vagrant] 	from /home/sait/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'
      [vagrant] 	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
      [vagrant] 	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
      pid 32511 exit 1 (VagrantHelpers::VagrantSSHCommandError)
      ./features/support/vagrant_helpers.rb:31:in `run_vagrant_command'
      ./features/step_definitions/assertions.rb:111:in `/^an error is raised$/'
      features/deploy_failure.feature:16:in `But an error is raised'
    Then the failure task will run     # features/step_definitions/assertions.rb:98
`

**Comment by mattbrictson** [comment]
Hi, it looks like you are using Bundler 1.11.2. As noted in the [DEVELOPMENT](https://github.com/capistrano/capistrano/blob/master/DEVELOPMENT.md#setting-up-your-development-environment) documentation, you need to use Bundler 1.10.5 to run the Cucumber features. One way to do that is:

```
$ gem install bundler -v 1.10.5
$ bundle _1.10.5_ exec rake features
```

Also, for future reference, when posting output in a GitHub comment use triple backticks (aka "code fences") to ensure proper formatting, as described here: https://help.github.com/articles/creating-and-highlighting-code-blocks/

Thanks for helping out with Capistrano!

**Comment by will-in-wi** [comment]
I just tested the feature specs and they pass for me using the above bundler version lock.
