### ISSUE TITLE
within Directory not working

### ISSUE THREAD

**Issue by poc7667** [capistrano/capistrano#1748]
I tried to execute command under this folder `fetch(:latest_release_directory)`
However, I still have to append  `cd #{fetch(:latest_release_directory)} &&` before executing it.
Otherwise I will got exception, because it didn't switch to the target folder at all.

  gem "capistrano",  "~> 3.4.0", require: false

```
on roles(:app) do |host|
  within fetch(:latest_release_directory) do
      execute %Q( cd #{fetch(:latest_release_directory)} && sudo foreman export upstart -e .env /etc/init -a #{ENV['APP_NAME']} -u #{ENV['DEPLOYER']} -l /tmp/#{ENV['APP_NAME']}.log )
  end
end
```

**Comment by leehambley** [comment]
%Q makes a string and disables command mapping. Please see the
documentation for Capistrano and SSHKit, this is thoroughly documented.

(Sent from my Nexus 6, please forgive typos!)

**Comment by will-in-wi** [comment]
@poc7667 Did this fix the issue?

I created this test case: https://gist.github.com/will-in-wi/527327e31af30b3eae2068e2965be05b

From that, I got the following output:

```
$ bundle exec cap production test_case:testing
/tmp
00:00 test_case:testing
      01 pwd
      01 /tmp
    ✔ 01 localhost 2.883s
```

`pwd` and `puts` both returned the correct directory for me.
