### ISSUE TITLE
Deploy hangs when using password authentication

### ISSUE THREAD

**Issue by apertureless** [capistrano/capistrano#1751]
#### Steps to reproduce

Updated to latest cap version

Capistrano Version: 3.6.0 (Rake Version: 11.2.2)
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

Got 1 project where I have password auth.
Which worked before updating.

Now I get 

`Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.`

Full output:

```

cap production deploy
00:00 git:wrapper
      01 mkdir -p /***/tmp
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
user@clientip's password:Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
user@clientip's password:-----
    ✔ 01 user@clientip 6.292s
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
user@clientip's password:-----
    ✔ 01 user@clientip 7.565s
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
user@clientip's password:-----
      Uploading /kunden/client.de/tmp/git-ssh-client.de-production-user.sh 100.0%
      02 chmod 700 /kunden/client.de/tmp/git-ssh-client.de-production-user.sh
    ✔ 02 user@clientip 0.048s

```
#### Expected behaviour

It should deploy.

#### Actual behaviour

Asks 3 times for password and then after the third time nothing happens. 
And deploy does not work.

**Comment by mapps-fujisawa** [comment]
How about to write below into Gemfile, and install gem?
> gem "highline"

**Comment by apertureless** [comment]
Yeah that would erase the cleartext password, warning.
However the deploy still don't work.

```sh
cap production deploy
00:00 git:wrapper
      01 mkdir -p /****/tmp
user@ip's password: user@ip's password:
    ✔ 01 user@ip 2.782s
user@ip's password: stty: 'standard input': unable to perform all requested operations

user@ip's password: stty: 'standard input': unable to perform all requested operations
```

**Comment by leehambley** [comment]
There have been no changes in Capistrano which could have caused this. 

Please confirm that you haven't upgraded SSHKit or Net::SSH to something incompatible with your key authentication system.

`mkdir` should not require a password on the server (and, if it does, you'll need to use [an InteractionHandler](https://github.com/capistrano/sshkit#interactive-commands)), so it looks like an authentication prompt which should be solved by uding SSH keys.

**Comment by mattbrictson** [comment]
Just to be sure, I removed my public key from one of my servers and did a `cap production deploy:check` to see what would happen. I was prompted for my password (twice) and everything worked fine. I can't reproduce the problem. Nor do I see the `stty: 'standard input': unable...` warnings.

```
$ cap production deploy:check
00:00 git:wrapper
      01 mkdir -p /tmp
deployer@-----'s password: 
    ✔ 01 deployer@----- 2.071s
deployer@-----'s password: 
      Uploading /tmp/git-ssh-------production-mbrictson.sh 100.0%
      02 chmod 700 /tmp/git-ssh-------production-mbrictson.sh
    ✔ 02 deployer@----- 0.105s
00:04 git:check
      01 git ls-remote --heads git@bitbucket.org:mattbrictson/-----.git
      01 ce204d8b0931accbaaffffa0e39864929275921c refs/heads/master
    ✔ 01 deployer@----- 1.504s
00:06 deploy:check:directories
      01 mkdir -p /home/deployer/apps/-----/shared /home/deployer/apps/-----/releases
    ✔ 01 deployer@----- 0.114s
00:06 deploy:check:linked_dirs
      01 mkdir -p /home/deployer/apps/-----/shared/public/assets /home/deployer/apps/-----/shared/.bundle /home/deployer/apps/-----/shared/log /home/deployer/apps/-----/shar…
    ✔ 01 deployer@----- 0.200s
00:06 deploy:check:make_linked_dirs
      01 mkdir -p /home/deployer/apps/-----/shared /home/deployer/apps/-----/shared/config
    ✔ 01 deployer@----- 0.105s
```

My environment and gems (from running `cap production doctor`):

Environment

    Ruby     ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    Rubygems 2.6.6
    Bundler  1.12.5
    Command  ./.git/safe/../../bin/cap production doctor

Gems

    capistrano         3.6.0
    airbrussh          1.1.0
    rake               11.2.2
    sshkit             1.11.2
    net-ssh            3.2.0
    capistrano-bundler 1.1.4
    capistrano-harrow  0.5.3
    capistrano-rails   1.1.7

**Comment by apertureless** [comment]
Hm, versions seem to match.

```bash

$ cap production doctor

Environment

    Ruby     ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    Rubygems 2.5.1
    Bundler  N/A
    Command  /Users/apertureless/.rvm/gems/ruby-2.3.1/bin/cap production doctor

Gems

    capistrano          3.6.0
    airbrussh           1.1.0
    rake                11.2.2
    sshkit              1.11.2
    net-ssh             3.2.0
    capistrano-composer 0.0.6
    capistrano-harrow   0.5.3
    capistrano-wpcli    0.0.9  (update available)

```

Yeah SSH-Keys would solve this, however the project is running on an old crappy client server which is managed and ssh-key auth is not working. 

I am gonna investigate more and test it out on other projects, where ssh keys are working.

**Comment by apertureless** [comment]
Tried it on other servers, where ssk-keys work, by disabling them and use password auth.
But could not reproduce it. 

So I guess it has to do with the server. 

Closing here.

**Comment by mattbrictson** [comment]
Thank you for investigating and following up! 👍

**Comment by Screon** [comment]
Just `ssh-copy-id deploy@IPADDRESS` on your local mashine.
