### ISSUE TITLE
Version 3.7 SCM bug?

### ISSUE THREAD

**Issue by Vinsanity** [capistrano/capistrano#1754]
Getting no traction on StackOverflow so I apologize if posting this here is not the right area.

Based on the Readme here https://github.com/capistrano/capistrano/blob/v3.6.0/UPGRADING-3.7.md

Updating the Gemfile and running bundle install works correctly. However, removing the :scm variable from deploy.rb and adding

```
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git
```

to the Capfile produces the following error:

cap aborted!
LoadError: cannot load such file -- capistrano/scm/git

Looking at the repo and the available branches, I'm not seeing any directory for /scm and subsequently no git.rb file other than in the main /lib/capistrano/ directory.

Am I missing something here or is this a bug with the current master branch?

Thanks, Vincent
---

#### Steps to reproduce

1. Removed :scm variable from deploy.rb
2. Updated the Gemfile with `gem "capistrano", :github => "capistrano/capistrano"`
3. Added this to the Capfile 
```
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git
```
4. Ran `bundle exec cap staging XXX`

#### Expected behaviour

Connect to remote location and deploy code.

#### Actual behaviour

```
cap aborted!
LoadError: cannot load such file -- capistrano/scm/git
```

**Comment by mattbrictson** [comment]
Hi, thanks for the detailed report!

The master branch does not yet have all of the planned 3.7 features. Specifically the SCM changes are not merged into master yet. If you'd like to try them out (your testing would be much appreciated!), use the branch in this PR: #1572.

I hope to merge that stuff into master soon, but I can't promise an exact timeline.

**Comment by mattbrictson** [comment]
In the meantime, I agree this sentence is misleading/wrong:

> If you wish to try the new 3.7.0 behavior today, you can do so by using the master branch in your Gemfile

**Comment by Vinsanity** [comment]
Thank you Matt. This makes a lot more sense. I'd be happy to test this and report back to you with a `cap doctor` report and any other relevant output from my tasks.

Cheers!

**Comment by mattbrictson** [comment]
#1572 has been merged, so you can try this out in `master` now.

**Comment by andrecavallari** [comment]
I am also having same issue, any workaround??

**Comment by leehambley** [comment]
> I am also having same issue, any workaround??

This is an eight month old issue, it's unlikely to be relates, are you using the most up to date version @andrecavallari ?

**Comment by andrecavallari** [comment]
Yes, using most up to date version...

**Comment by mattbrictson** [comment]
@andrecavallari Please open a new GitHub issue and include the output of `cap --version` and the contents of your `Capfile` so that we can help you troubleshoot. Thanks!

**Comment by embasbm** [comment]
Hi there, please, let me put the info you @mattbrictson ask for, since I have exactly the same error as @andrecavallari 

⇒  cap --version
`Capistrano Version: 3.4.1 (Rake Version: 12.0.0)`

⇒  cat Capfile
```
require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/scm/git'
install_plugin Capistrano::SCM::Git
require 'capistrano/rvm'
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
require 'whenever/capistrano'
Dir.glob('lib/capistrano/tasks/*.cap').each { |r| import r }

```
And the error is:

```
(Backtrace restricted to imported tasks)
cap aborted!
LoadError: cannot load such file -- capistrano/scm/git
/Users/emba/Projects/_EventInc/eventinc/Capfile:3:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by leehambley** [comment]
Please try again with Capistrano defined at the correct version in your `Gemfile` using `bundle exec`

**Comment by embasbm** [comment]
Updating capistrano to `Installing capistrano 3.8.1` solved my issue. Thanks @leehambley
