### ISSUE TITLE
Can not upload file in an existing folder

### ISSUE THREAD

**Issue by poc7667** [capistrano/capistrano#1755]
I tried to upload index.html to my staging server,

`Errno::ENOENT: No such file or directory @ rb_sysopen - //home/deploy/workspace/webApp/current/index.html`

`upload! "#{Dir.pwd}/src/index.html", "/#{current_path}/index.html"`

However, `//home/deploy/workspace/webApp/current` did exist.

And if I try to `/tmp/index.html` it works perfect.

I thought Capistrano is matured to prevent this sort of freaky strange issue T_T

**Comment by will-in-wi** [comment]
Can you make a simple example application to demonstrate the issue? For example, just create a Gemfile, include Capistrano, set up only enough deployment to replicate the issue, anonymize your username/hostname, and then push the whole thing to github?

Here's an example of a minimal test case: https://gist.github.com/will-in-wi/527327e31af30b3eae2068e2965be05b

Thanks!

**Comment by troelskn** [comment]
Shouldn't it be `upload! "#{Dir.pwd}/src/index.html", "#{current_path}/index.html"`

**Comment by poc7667** [comment]
My bad, because I put the statement in `run_locally do` block. Now it's fixed.
Thanks
