### ISSUE TITLE
Appending to linked_dirs still output an empty variable if performed from gems

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [capistrano/capistrano#1757]
Might be related to `load:defaults` in some way, I'm not entirely sure why the variable ends up empty (setting it from `deploy.rb` works fine).

Can someone drive me toward a workarond? My only option so far is opening the source code of each gem and add stuff to `linked_dirs`

#### Steps to reproduce

Prepare the following files:

```ruby
# Gemfile
gem "capistrano", "~> 3.6.1"
gem "capistrano-bundler", "~> 1.1.4"
gem "capistrano-rails", "~> 1.1.7"
```

```ruby
# Capfile

# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Include tasks from other gems included in your Gemfile
# require "capistrano/bundler"
```

```ruby
# Capfile

# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Include tasks from other gems included in your Gemfile
# require "capistrano/bundler"
```

```ruby
# deploy.rb
# config valid only for current version of Capistrano
lock "3.6.1"

set :application, 'my_app_name'
set :repo_url, 'git@example.com:me/my_repo.git'

namespace :testme do
  desc "blah"
  task :hello do
    puts fetch(:linked_dirs).inspect
    puts fetch(:linked_files).inspect
    puts fetch(:bundle_bins).inspect
  end
end
```

```ruby
# config/deploy/development.rb
role :app, "127.0.0.1"
```

1. Run `bundle exec cap testme:hello`, it will output:

    nil
    nil
    nil

2. Uncomment in `Capfile` the line `require "capistrano/bundler"`
3. Based on [capistrano-bundler implementation](https://github.com/capistrano/bundler/blob/e47c041f5b5655ad81145087a0d7cb7d3aa4ef77/lib/capistrano/tasks/bundler.cap#L69), `linked_dirs` should now contain `.bundle`
4. Re-run `bundle exec cap testme:hello`, it will output:

    nil
    nil
    ["gem", "rake", "rails"]

#### Expected behaviour

The second output should be

    [".bundle"]
    nil
    ["gem", "rake", "rails"]

#### Actual behaviour

`linked_dirs` is `nil` (documentation says should be `[]`), and no value is added:

    nil
    nil
    ["gem", "rake", "rails"]

#### Your configuration

```
Environment

    Ruby     ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    Rubygems 2.4.6
    Bundler  1.12.5
    Command  /Users/francesco/.rvm/gems/ruby-2.2.1/bin/cap development doctor

Gems

    capistrano         3.6.1
    airbrussh          1.1.0
    rake               11.2.2
    sshkit             1.11.2
    net-ssh            3.0.2  (update available)
    capistrano-bundler 1.1.4
    capistrano-harrow  0.5.3
    capistrano-rails   1.1.7
```

**Comment by will-in-wi** [comment]
The line mentioned in step 3 is not available in the latest released version of Capistrano/Bundler yet. It was introduced in: https://github.com/capistrano/bundler/commit/6b23e523c337d966457e4c034a5e86b902ebcc4c

You can work around this for the time being by using `gem "capistrano-bundler", github: 'capistrano/bundler'` or by manually adding `set :linked_dirs, fetch(:linked_dirs, []) << '.bundle'` to your deploy.rb.

Thanks for the complete test case! This made it really easy to reproduce and debug. 👍

**Comment by Fire-Dragon-DoL** [comment]
No problem for the full testcase, sorry to have wasted your time though 😞  I assumed master was the same in the ruby gem.

I'm closing the bug since I assume it's a no-bug in reality
