### ISSUE TITLE
Capistrano in ruby script

### ISSUE THREAD

**Issue by leehambley** [capistrano/capistrano#1764]
_From @ddarbyson on December 3, 2014 4:16_

I could not get this to work with the following line found at http://capistranorb.com/documentation/advanced-features/capistrano-pure-ruby/

``` ruby
Dir.glob('capistrano/tasks/*.rake').each { |r| import r }
```

However, using `load` seems to work just fine

``` ruby
Dir.glob('capistrano/tasks/*.rake').each { |r| load r }
```

_Copied from original issue: capistrano/documentation#107_

**Comment by leehambley** [comment]
_From @Kriechi on January 15, 2015 14:3_

Did you get any specific error message?
I just tried it in a blank irb context without getting any errors...

**Comment by leehambley** [comment]
_From @ddarbyson on January 15, 2015 16:1_

It's been a while so I don't quite remember. Since this post, I haven't change from `load r` so I'm assuming the issue is still there.

**Comment by leehambley** [comment]
_From @Kriechi on January 15, 2015 16:4_

If you could supply more context would be great.
Otherwise this might be pretty hard to track down...

Did you get an error?
Did the `.rake` load - or not?
Did you have any `.rake` files - or was the directory-tree missing?
Capistrano version?

**Comment by leehambley** [comment]
_From @ddarbyson on January 15, 2015 16:5_

No problem. I'm actually am kicking up some development in a couple weeks. I'll keep this flagged and report back my findings.

**Comment by leehambley** [comment]
Actually we kinda have this https://vimeo.com/133892224 - might serve as a reference. For a complete picture, I used to maintain a "Capistrano Handbook", which I was in talks to make into a real book - but another book which I can't seem to find now was published in the meantime, so we elected not to do it.

**Comment by leehambley** [comment]
_From @will-in-wi on January 18, 2016 14:47_

I'm confused. I don't see any reference to single ruby file Capistrano deployment in the video.

**Comment by leehambley** [comment]
yep, useless link, my bad - I thought this was the "document an end to end setup of Cap" ticket for which I wanted to make a text version of the video. Sorry for wasting 10 mins of your life!

**Comment by leehambley** [comment]
_From @will-in-wi on January 18, 2016 14:53_

Heh, no waste, I now know about Harrow and the SSHKIT_COLOR param, both of which were new to me.

**Comment by leehambley** [comment]
_From @will-in-wi on January 18, 2016 14:54_

I'm trying to set up an example single script deployment. It looks like the require structure has changed since the docs were written, for example, `Capistrano::Application.invoke('production')` doesn't work, and I'm getting errors such as `Don't know how to build task ':check'`. I'll see if I can figure out why `deploy.rake` isn't getting pulled in.

**Comment by leehambley** [comment]
Thanks @will-in-wi it's been a long time since it worked as documented, entierly possible that a world of things has changed. Interesting is that "`deploy.rake`-missing" hints might be found in the tail end of @mattbrictson 's "how to load a rakefile" stuff in his new Cap plugin branch... lemme see if I can find a reference

**Comment by leehambley** [comment]
Actually, maybe it's just you're `require`ing the wrong thing? https://github.com/capistrano/capistrano/blob/45e851bdc5ed80970a7be90f080f030aa7386190/lib/capistrano/deploy.rb#L3

**Comment by leehambley** [comment]
_From @will-in-wi on January 18, 2016 16:26_

I'm not sure the code as written in the docs has ever worked. I pointed it at a local copy of Capistrano and started bisecting. The commit which created `capistrano/all` still has the `Don't know how to build task 'production'` error. The same errors that exist today existed as of 3.0.0.

I'm not having any success in writing a new single file example.

I'm inclined to say that this doc page should be entirely removed to avoid misleading people. I'm happy to make a PR to that effect. If this is useful, then perhaps a new ticket for the maintainers of Capistrano to figure this out would be in order.

**Comment by leehambley** [comment]
_From @will-in-wi on January 18, 2016 16:30_

Added a PR in case this is the way you want to go. https://github.com/capistrano/documentation/pull/155

At a bare minimum, it might make sense to remove it pending writing a new one.

**Comment by leehambley** [comment]
_From @mattbrictson on January 18, 2016 17:11_

@will-in-wi @leehambley I have a open PR to reinstate the Capistrano-in-a-script behavior. It still needs tests and a CHANGELOG, but it is ready for feedback:

https://github.com/capistrano/capistrano/pull/1548

**Comment by leehambley** [comment]
_From @will-in-wi on January 18, 2016 17:32_

It looks like we could put back the docs using the contents of `capistrano/inline` as part of the script. Once `capistrano/inline` becomes part of Capistrano, the docs could be simplified.

Does this sound like a reasonable solution?

**Comment by leehambley** [comment]
_From @mattbrictson on January 18, 2016 18:2_

Unfortunately the `capistrano/inline` script only works if certain changes are made to Capistrano's `setup.rb`. 

```diff
-    load deploy_config_path
-    load stage_config_path.join("#{stage}.rb")
+    load deploy_config_path unless deploy_config_path.nil?
+    load stage_config_path.join("#{stage}.rb") unless stage_config_path.nil?
```

So I don't think we can offer it as a solution in the docs until part or all of that PR is merged.

**Comment by will-in-wi** [comment]
Closing this at it seems like there is little desire for it. The PR was closed.

**Comment by ddarbyson** [comment]
Reviewing back since 2016 - the last time I integrated as pure ruby, I see the documentation has been removed for ` Capistrano in ruby script`... did something change? I'd like to do this with 3.10 and was simply going to reuse some old code. 

Let me know. It will save me some time if the approach is different then https://raw.githubusercontent.com/gazay/capistrano.github.io/master/documentation/advanced-features/capistrano-pure-ruby/index.markdown

**Comment by mattbrictson** [comment]
It has been a couple years, but I believe the instructions in the documentation did not work, which is why they were removed. [I started a PR](https://github.com/capistrano/capistrano/pull/1548) to re-implement the feature but there seemed to be no interest from the community, so it was subsequently abandoned.

If you have a real-world use-case for this feature, we could perhaps revive that PR. Would you be willing to help test and document it?

**Comment by ddarbyson** [comment]
I could test for you. I’m rewriting some tools which manage the deployment of over 300 sites. I used Capistrano 3.0 as pure ruby implementation to achieve this. Let me know how to test and give it a go.
