### ISSUE TITLE
3.5 and 3.6 not deploying latest revision if using a branch

### ISSUE THREAD

**Issue by gommo** [capistrano/capistrano#1773]
This seems to have occurred since upgrading from 3.4 to 3.5 (and also occurs in 3.6)

I have a specific deploy configuration that deploys off a branch
e.g.
set :branch, 'feature/SPP-979-SignUpform'

It is just using the revision it last checked out (before I upgrade) at /repo

If I remove the repo directory on the server then it then fetches the latest off that branch but then subsequent deploys are then just stuck at that new /repo revision number

**Comment by mattbrictson** [comment]
Thanks for opening a report. Let's see if we can get to the bottom of this!

Nearly everyone that uses Capistrano with Git (myself included) deploys using branches, whether that be the `master` branch or a custom branch (I use `development` for staging environments). So there must be something unique about your environment that is triggering this bug. We just need to find it.

First, can you tell us what Git version you are using? Run `git version` **on the server**.

Next, can you show us in your Capistrano log output where the improper revision is being used? When you run a deploy, you should see both the branch name being used and the resulting revision. Can you paste output? Like this:

```
00:06 git:create_release
      01 mkdir -p /home/deployer/apps/xxxxxx/releases/20160906012432
    ✔ 01 deployer@xxxxxx 0.141s
      02 git archive master | tar -x -f - -C /home/deployer/apps/xxxxxx/releases/20160906012432
                     ^^^^^^
    ✔ 02 deployer@xxxxxx 0.286s
00:07 git:set_current_revision
      01 echo "0fdaccf40334b72c11219148014b6663777b3aa8" >> REVISION
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ✔ 01 deployer@xxxxxx 0.141s
```

Then compare that with what you see from your local machine, like this:

```
$ git rev-list --max-count=1 origin/master
0fdaccf40334b72c11219148014b6663777b3aa8
```

**Comment by gommo** [comment]
Here's one from a first deploy

00:19 git:update
      01 git fetch --depth 1 origin feature/SPP-979-SignUpform
      01 From bitbucket.org:xxxxxx
      01  * branch            feature/SPP-979-SignUpform -> FETCH_HEAD
    ✔ 01 spp@xxxxx
00:27 git:create_release
      01 mkdir -p /opt/socialpinpoint/dev-myspp/releases/20160905223049
    ✔ 01 spp@xxxxx
      02 git archive feature/SPP-979-SignUpform | tar -x -f - -C
/opt/socialpinpoint/dev-myspp/releases/20160905223049
    ✔ 02 spp@xxxxx
00:28 git:set_current_revision
*      01 echo "b5cac4cf3a740d12d42ed668dd8297042cf9a30f" >> REVISION*
    ✔ 01 spp@xxx
00:28 deploy:symlink:linked_files

Then made changes and redeployed and we still get the same revision

   The repository mirror is at /opt/socialpinpoint/dev-myspp/repo
00:10 git:update
      01 git fetch --depth 1 origin feature/SPP-979-SignUpform
      01 From bitbucket.org:xxx
      01  * branch            feature/SPP-979-SignUpform -> FETCH_HEAD
    ✔ 01 spp@xxx
00:21 git:create_release
      01 mkdir -p /opt/socialpinpoint/dev-myspp/releases/20160906005942
    ✔ 01 spp@xxxx
      02 git archive feature/SPP-979-SignUpform | tar -x -f - -C
/opt/socialpinpoint/dev-myspp/releases/20160906005942
    ✔ 02 spp@xxx
00:22 git:set_current_revision
      01 echo "b5cac4cf3a740d12d42ed668dd8297042cf9a30f" >> REVISION
    ✔ 01 spp@xxxxx

Git version
spp@ ~ () $ git version
git version 1.8.3.1

Here's a cat of the revisions.log
You can see the change to 3.5/3.6 where the revision number is expanded.
Branch feature/SPP-1059-devmyspp (at ac44309) deployed as release
20160802005447 by colin
Branch feature/SPP-1059-devmyspp (at 6bd71ff) deployed as release
20160802030416 by colin
Branch feature/SPP-979-SignUpform (at f6d0eaa) deployed as release
20160803060737 by colin
Branch feature/SPP-979-SignUpform (at 9b8acb2) deployed as release
20160803063119 by colin
Branch feature/SPP-979-SignUpform (at 5ea5c94) deployed as release
20160803064152 by colin
Branch feature/SPP-979-SignUpform (at 8072ecc) deployed as release
20160803065040 by colin
Branch feature/SPP-979-SignUpform (at 7939514) deployed as release
20160803121732 by colin
Branch feature/SPP-979-SignUpform (at 7beec75) deployed as release
20160810092354 by colin
Branch feature/SPP-979-SignUpform (at cefb3c9) deployed as release
20160810093405 by colin
Branch feature/SPP-979-SignUpform (at 3e01703) deployed as release
20160810103729 by colin
Branch feature/SPP-979-SignUpform (at d8439c4) deployed as release
20160812060255 by colin
Branch feature/SPP-979-SignUpform (at 12329b1) deployed as release
20160827110928 by colin
Branch feature/SPP-979-SignUpform (at bf01107) deployed as release
20160902024751 by colin
Branch feature/SPP-979-SignUpform (at c05e7a5) deployed as release
20160902033657 by colin
Branch feature/SPP-979-SignUpform (at d9ce062) deployed as release
20160902094046 by colin
Branch feature/SPP-979-SignUpform (at 66b6a1c) deployed as release
20160903014533 by colin
Branch feature/SPP-979-SignUpform (at 998ebf7) deployed as release
20160903023142 by colin
Branch feature/SPP-979-SignUpform (at 180c6f7) deployed as release
20160904060739 by colin
Branch feature/SPP-979-SignUpform (at 180c6f7) deployed as release
20160904063547 by colin
Branch feature/SPP-979-SignUpform (at
180c6f7bd9c9160bc84d7320073a9017c414efb6) deployed as release
20160904110311 by colin
Branch feature/SPP-979-SignUpform (at
180c6f7bd9c9160bc84d7320073a9017c414efb6) deployed as release
20160904111331 by colin
Branch feature/SPP-979-SignUpform (at
180c6f7bd9c9160bc84d7320073a9017c414efb6) deployed as release
20160904113139 by colin
Branch feature/SPP-979-SignUpform (at
180c6f7bd9c9160bc84d7320073a9017c414efb6) deployed as release
20160905212817 by colin
Branch feature/SPP-979-SignUpform (at
180c6f7bd9c9160bc84d7320073a9017c414efb6) deployed as release
20160905214800 by colin
*Branch feature/SPP-979-SignUpform (at
b5cac4cf3a740d12d42ed668dd8297042cf9a30f) deployed as release
20160905223049 by colin*
*Branch feature/SPP-979-SignUpform (at
b5cac4cf3a740d12d42ed668dd8297042cf9a30f) deployed as release
20160906005942 by colin*

The last 2 pushes changes because I removed the /repo directory on the
server

**Comment by gommo** [comment]
Cheers for helping with this too. Hopefully I'm just missing a step after upgrading somewhere?

**Comment by mattbrictson** [comment]
Thanks for the logs. One more bit of info, just as a sanity check. What do you get when you run this locally?

```
git rev-list --max-count=1 origin/feature/SPP-979-SignUpform
```

**Comment by mattbrictson** [comment]
Finally, I see in your logs that your `git` command is different than mine. Yours is:

```
git fetch --depth 1 origin ...
```

Whereas mine is:

```
git remote update --prune
```

Based on the Capistrano source, I can deduce that you are have this in your configuration:

```
set :git_shallow_clone, 1
```

Correct?

Furthermore, when I look at the code, there is a comment that says:

> Note: Requires git version 1.9 or greater

But you are running 1.8.3.1.

Could that be the problem?

The code looks like this:

https://github.com/capistrano/capistrano/blob/e27b0322f2e84104023d64dd6e63436a15ca7c91/lib/capistrano/git.rb#L31-L38

```ruby
def update
  # Note: Requires git version 1.9 or greater
  if (depth = fetch(:git_shallow_clone))
    git :fetch, "--depth", depth, "origin", fetch(:branch)
  else
    git :remote, :update, "--prune"
  end
end
```

**Comment by gommo** [comment]
It could very well be the git version on the server. I will update and test

**Comment by gommo** [comment]
Pretty sure git was the cause

**Comment by EddieOne** [comment]
>Requires git version 1.9 or greater
This worked, thanks 👍

**Comment by edwardnewton** [comment]
I faced the same issue. My git version was: `1.9.1` and my capistrano version was `3.5.0`,
updating capistrano to lock `3.10.1` fixed the issue.
hope it helps someone

**Comment by lain0** [comment]
But in capistrano 3.16 i have this issue!
