### ISSUE TITLE
Testing Depfu, a tool to automatically check and update your dependencies

### ISSUE THREAD

**Issue by halfbyte** [capistrano/capistrano#1775]
I've asked @leehambley, who is an old acquaintance from the Hamburg rails scene, if Capistrano would like to test out a tool a friend and I are working on. He told me to open up an issue here.

As it contains all the important infos I'll just copy in the relevant parts from that email here. 

Me and a friend are working on a “greenkeeper.io for Ruby”, a service that helps you keep your dependencies up to date by issuing pull requests when new versions are released.

We’ve built a first version and have been testing it with a fork of capistrano for the last month. The results look promising so we were hoping you would be interested in testing it for real.

The service is doing two things that can help you maintain capistrano:
- Create a pull request when one of your dependencies releases a new version that is outside your specified version range. Depending on the build status you can decide to merge it or use it as the starting point for making the upgrade work.
- Make sure new versions within your specified version range are behaving well: We force the new version to get installed during the travis build to see if there are errors during bundle install or during the test run. This results in a much shorter feedback loop to see if any if your dependencies introduced a breaking change. And you can be sure your gem can be installed at any time.

If you’re interested you can have a look at what happened to our capistrano fork in the last month: 

http://depetual.herokuapp.com/repos/18

You can see how we’ve created branches for all version updates with more or less success. What makes capistrano a bit special is your (for a ruby project, at least) large number of internal dependencies. This made us wonder if you would consider all of the capistrano-harrow and airbrush PR’s as noise and if we probably need an ignore feature for those.

We’re looking for OS maintainers to test and help us shape what we have, so that it can really improve how projects manage their dependencies. As it’s still a bit rough around the edges you can expect a lot of handholding from us. We will watch every update very closely and hope to learn what works for you and what doesn’t.

If you’re interested in trying this out, let us know and I’ll add “the real” capistrano repository to our service within the next week or so.

**Comment by will-in-wi** [comment]
I'm not against it… I haven't spent enough time working on Capistrano core to know whether newly released deps outside of the gemspec target range cause an issue.

I like the idea, though. If there was a free or inexpensive version someday that worked with an internally hosted GitLab instance, I'd probably push for its usage by my employer.

**Comment by halfbyte** [comment]
Hiya,

if you want to try this out, we’re now ready for signups, so someone with admin access to the capistrano repos (we’ll need that for installing a webhook to get notified on updates and test statuses) should sign up at https://depfu.io and activate the repo there. The process is very similar to activating travis-ci for example.

(Yes, we’ve renamed the project. Naming is hard, but we’re happy with Depfu so far.)

After you’ve activated it, we will, as promised, closely monitor the activity and also this issue, so this issue might be a good place to give us your feedback on both the activation process but also the first few real updates and the resulting pull requests.

Also, @will-in-wi, if you want to be notified on a private repo version of depfu, you can do so on our website at https://depfu.io/get_started, there’s a signup form for our notification list.

Thanks so much for your interest so far, let’s see how this goes.

(cc @theflow)
