### ISSUE TITLE
Custom Filters

### ISSUE THREAD

**Issue by DylanFrese** [capistrano/capistrano#1776]
I would like to implement my own custom (command-line) filters, that apply to `on` like `HOSTS` or `ROLES`. An example would be `REGIONS`, or extending `HOSTS` to match SaltStack minion IDs as well as FQDNs/IPs.

However, [filter.rb](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/configuration/filter.rb) and [configuration.rb](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/configuration.rb#L109) are rather 'closed', making it difficult to do this, and I have to monkey-patch in my own filters.

I am aware of using property filtering to restrict individual tasks to certain targets in the deploy, but that is not quite what I'm looking for.

**Comment by mattbrictson** [comment]
My gut reaction is that this is not something that we want to support in Capistrano core. However I understand your frustration about the lack of a clean extension point for you to add custom filtering. 

Perhaps the best way to accommodate this is via a custom task. You could write a rake task called `regions` that accepts an argument (in other words, it can be invoke by `regions[arg]`). That task could go through the list of defined servers and remove the ones the don't match the filter.

```
cap production regions[123] deploy
```

We might need to change Capistrano to provide a method for you to remove a server, but doesn't seem like a big deal.

Would something like that work?

Ultimately if we're going to support this, I would like it to be done with the smallest change possible. I don't see custom filters as a common use case, so the solution would have to be very low risk.

**Comment by DylanFrese** [comment]
I think that even simpler would just to be to open up the list of filters in `configuration.rb` for appending. Monkey-patching or refining if I want to change the behaviour of `HOSTS` or `ROLES` is not too bad.

**Comment by mattbrictson** [comment]
OK, can post a quick patch or open a PR with what you have in mind? We can work from there.

**Comment by will-in-wi** [comment]
I'm a fan of making this possible. I personally use hostnames and the host regex option to accomplish it at present. My use case is that we have several locations, and we prepend a two char location code to our server names. For example, our servers at our main location are hqsomething01, while our servers in our California location are casomething01. So I can limit a deploy by running `cap prod --hosts=^hq deploy`.

But if we didn't have the servers named this way, I'd need more granular deployment capabilities as defined above.

I'll help out as I can.

Incidentally, a hack which can accomplish this is using env variables. For example you can set up your `config/deploy/production.rb` like so:

```ruby
if ENV['REGION_ONLY'] == 'ca'
  server 'casomething01', roles: [:blah, :app, :db, :web]
end
```

Then you would invoke Capistrano like so:

```
REGION_ONLY=ca cap production deploy
```

**Comment by DylanFrese** [comment]
@mattbrictson I created a pull request that should suffice ; I'll add tests if you point me to where to add them.

**Comment by mattbrictson** [comment]
Custom filters were added in 3.7.0 via #1777.
