### ISSUE TITLE
Remove rbx-2 (Rubinius) from CI?

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1783]
rbx-2 segfaults when running RuboCop (so we worked around it, 7695476) and now Travis is [failing to install rbx-2](https://travis-ci.org/capistrano/capistrano/jobs/164640875#L141) altogether, which is breaking all our builds. Is there enough demand for Rubinius that we should keep testing it? It seems more trouble than it's worth.

My understanding is that the Rubinius release process can produce unstable or inconsistent builds, so these issues are bound to crop up from time to time.

We could change our Travis config to allow rbx-2 builds to error [without breaking the build](https://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail), but in practice I don't think that's much different than removing it altogether.

**Comment by will-in-wi** [comment]
I don't personally use Rubinius.

Is it possible to set it to retry N times on failure? It seems rather sporadic...

**Comment by mattbrictson** [comment]
I must admit I know almost nothing about Rubinius. I thought it was a alternative implementation of Ruby (a la JRuby), but the [Rubinius website](https://rubinius.com) says it is a platform for building programming languages, and now I am thoroughly confused.

Maybe we could switch from rbx-2 to rbx-3, since apparently 2.x releases stopped last year. But I can't find a changelog anywhere and 3.0 has [no release notes](https://github.com/rubinius/rubinius/releases/tag/v3.0). The Rubinius book [makes a big deal](https://book.rubinius.com/manuscript/versioning.html) about not following Semver, so I'm not sure what upgrading entails.

Anyway, it would be great if someone that uses Rubinius could shed some light on all this! 😄

**Comment by will-in-wi** [comment]
Maybe for the moment, make rubinius an allowed failure, and then leave this ticket open for a while for others to jump in.

**Comment by will-in-wi** [comment]
It seems like there is relatively little usage of Rubinius among Capistrano users. I'm closing this ticket. If anyone wants to open specific tickets for support, they may.
