### ISSUE TITLE
Release 3.7.0.beta1?

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1798]
Given that Capistrano 3.7.0 will contain a fundamental change to the SCM system, I think this may warrant a beta release.

Any objections?

Are there any outstanding issues or PRs to resolve before releasing 3.7.0.beta1?

/cc @leehambley @will-in-wi

**Comment by will-in-wi** [comment]
I like the idea of a beta release. I don't see anything blocking with just a quick look at the ticket queues.

**Comment by leehambley** [comment]
No issue with a beta release, pets see how many people use it and allow
that to inform our decisions in the future

(Sent from my Nexus 6, please forgive typos!)

**Comment by mattbrictson** [comment]
🚢🍾✨  

https://rubygems.org/gems/capistrano/versions/3.7.0.beta1
https://github.com/capistrano/capistrano/releases/tag/v3.7.0.beta1
