### ISSUE TITLE
Capistrano 3 symlink task 

### ISSUE THREAD

**Issue by Medesko** [capistrano/capistrano#1799]
Hi,  

I want to create the symlink config/parameters.js shared folder to my release_path

This not work Capistrano 3
`task :symlink do
    execute "rm -f #{release_path}/config/parameters.js"
    execute "ln -nfs #{shared_path}/config/parameters.js #{release_path}/config/parameters.js"
  end
`

Please someone can help me ?

**Comment by mikegee** [comment]
Instead of defining that `symlink` task, try this config:

```ruby
append :linked_files, %w{config/parameters.js)
```

http://capistranorb.com/documentation/getting-started/configuration/

**Comment by Medesko** [comment]
thanks
