### ISSUE TITLE
Add task for deleting failed deploy directory after deploy:failed

### ISSUE THREAD

**Issue by avekrivoy** [capistrano/capistrano#1800]
Hi!
I'm using Capistrano 3. How can I delete failed releases on deploy:failed without writing my own task? The point is that failed releases stay in the releases directory and accidentally I can rollback to broken release by typing cap deploy:rollback
For now I'm using this task:

namespace :deploy do

  desc 'Delete failed release'  
  task :rm_failed do  
    on roles(:all) do  
      execute(:rm, "-rf #{release_path}")
    end
  end

end

after 'deploy:failed', 'deploy:rm_failed'

**Comment by leehambley** [comment]
Support is done at https://groups.google.com/forum/#!forum/capistrano
