### ISSUE TITLE
Migration status before deploy

### ISSUE THREAD

**Issue by Rubioli** [capistrano/capistrano#1803]
I am using `capistrano raisl gem` in my application. When I run `cap production deploy` it deploys my changes and at the same time it runs my `db:migration` and runs all my pending migration.

For a testing reason I don't want it to run `cap production deploy:migrate` on `deploy`.

How can I prevent it to run `deploy:migrate` when deploying and more importantly how I can see my migrations `status` to see all my pending migrations `capistrano` will run. For instance  in development ENV I can just run `rake db:migrate:status` and its shows me which migrations are `up` or `down` and which will/need to run?

*My Versions:*

**Rails:  4.2.4**

`gem 'capistrano', '~> 3.5'`

**Comment by leehambley** [comment]
Please read the CONTRIBUTION guidelines before deleting them and posting in the wrong place.
