### ISSUE TITLE
Could harrow:install be opt-in rather than opt-out?

### ISSUE THREAD

**Issue by thbar** [capistrano/capistrano#1806]
I'm a long-time capistrano user coming back to it after a lack of need to use it. First, thanks for your work on this!

I've been kind of surprised to see `bundle exec cap install` take around 1 minute here today:

```
$ time bundle exec cap install --trace
** Invoke install (first_time)
** Execute install
mkdir -p config/deploy
create config/deploy.rb
create config/deploy/staging.rb
create config/deploy/production.rb
mkdir -p lib/capistrano/tasks
create Capfile
Capified
# parts above were very quick ; time is taken below
** Invoke harrow:install (first_time)
** Execute harrow:install

real	1m0.991s
user	0m0.696s
sys	0m0.200s
```

I've read a bit on Harrow (including [here](http://capistranorb.com/documentation/harrow/) where it is stated that "Capistrano (...) will include discrete hooks offering Harrow to users without being intrusive", so I was surprised to see this delay.

I investigated a bit. I'm on capistrano (3.6.1), which brings in capistrano-harrow (0.5.3), which does that install.

I read on the capistrano-harrow readme that I can disable harrow integration with `git config harrow.disabled true` apparently, but even with that setting, the delay remain.

Is there a way to avoid the install completely since I'm not using harrow at the moment?

Thanks!

**Comment by leehambley** [comment]
Thanks for the bug report. I am currently on vacation until the middle of
next week, but will investigate when I get back. Ahoy!

(Sent from my Nexus 6, please forgive typos!)

**Comment by mattbrictson** [comment]
@thbar The slowness issue seems to be fixed. If it works for you, can we close?

```
$ time cap install --trace
** Invoke install (first_time)
** Execute install
mkdir -p config/deploy
create config/deploy.rb
create config/deploy/staging.rb
create config/deploy/production.rb
mkdir -p lib/capistrano/tasks
create Capfile
Capified
** Invoke harrow:install (first_time)
** Execute harrow:install

real	0m0.365s
user	0m0.281s
sys	0m0.068s
```

**Comment by mattbrictson** [comment]
I'll consider this fixed.
