### ISSUE TITLE
Removing old releases goes wrong

### ISSUE THREAD

**Issue by markri** [capistrano/capistrano#1810]
When removing old releases (default behaviour, and explicitly setted at :keep_releases: 5) it removes the newly created release instead of the old releases.

Looking at lib/capistrano/tasks/deploy.rake @ line 151 it says

`releases = capture(:ls, "-xtr", releases_path).split`

Which should be an ordered list, but executing it on command line shell it give me
```
ls -xtr
20161201100437  20161201112702  20161202132042  20161202131122  20161201114136
```

For more easy viewing I added some line breaks

```
20161201100437  
20161201112702  
20161202132042  
20161202131122  
20161201114136
```
Which is definitely not in order, which is why it removes the wrong releases at cleanup. 
Also executed:

```
[marco@server releases]$ ls -alsrt
total 24
4 drwxr-xr-x. 13 deploy deploy 4096  1 dec 11:00 20161201100437
4 drwxr-xr-x. 13 deploy deploy 4096  1 dec 12:25 20161201112702
4 drwxr-xr-x. 13 deploy deploy 4096  1 dec 12:39 20161202132042
4 drwxr-xr-x. 13 deploy deploy 4096  1 dec 12:39 20161202131122
4 drwxr-xr-x. 13 deploy deploy 4096  1 dec 12:39 20161201114136
0 drwxrwxr-x.  4 deploy deploy   68  2 dec 14:20 ..
4 drwxrwxr-x.  7 deploy deploy 4096  2 dec 14:20 .
[marco@server releases]$ date
vr dec  2 14:50:24 CET 2016
```

As it seems the release it self has a different creation date (yesterday) than the actual constructed timestamp (e.g. file system date is 1 dec 12:39 while folder timestamp is 2016 12 02 13:11:22), how is this possible?

Used gems:
```
capistrano (3.6.1)
capistrano-composer (0.0.6)
capistrano-file-permissions (0.1.1)
capistrano-harrow (0.5.3)
capistrano-symfony (0.4.0)
capistrano-tarball (0.1.2)
```

Capfile
```
require "capistrano/setup"
require "capistrano/deploy"
require 'capistrano/symfony'
require 'capistrano/tarball/load'

```

deploy.rb
```
lock '3.6.1'
set :application, ENV['project']
set :deploy_to, ENV['caproot']
set :scm, :tarball
set :tarball_release_tag, ENV['revision']
set :tarball_name, "tarbal.tar.gz"
set :tarball_local_path, File.join(Dir.pwd, fetch(:tarball_name))
set :tarball_package_cmd, "echo 'noop'"
set :pty, true
set :linked_files, ENV['userfiles'].split(/,/)
set :linked_dirs, ENV['userdirs'].split(/,/)
set :keep_releases, 5

# Disable composer
Rake::Task['deploy:updated'].prerequisites.delete('composer:install')

# Symfony settings
SSHKit.config.command_map[:php] = ''

set :symfony_env,  "prod"
set :symfony_console_path, 'bin/tenant bin/console'
set :symfony_console_flags, "--no-debug"
set :controllers_to_clear, ["app_*.php", "config.php"]
set :permission_method, :acl
set :file_permissions_users, ["php-fpm", "netvlies"]

namespace :deploy do

  before 'deploy:publishing', 'deploy:migrate', 'deploy:setup_fabric'
  before 'deploy:published', 'deploy:php_reload'
  before 'deploy:updated', 'deploy:symfony_parameters_symlink', 'symfony:build_bootstrap'

  desc "Doctrine migrations"
  task :migrate do
    invoke "symfony:console", "doctrine:migrations:migrate", '--no-interaction'
  end

  desc "CentOS 7 opcode clear"
  task :php_reload do
     on "#{ENV['username']}@#{ENV['hostname']}" do
       execute "sudo systemctl reload php-fpm"
     end
  end

  desc "RabbitMQ fabric"
  task :setup_fabric do
     invoke "symfony:console", "rabbitmq:setup-fabric --env=prod"
  end

  desc 'Link parameters.ini.$env to parameters.ini DB params enclosed with # will be replaced'
  task :symfony_parameters_symlink do
     on "#{ENV['username']}@#{ENV['hostname']}" do
         execute "sed -i -e 's/#mysqldb#/#{ENV['mysqldb']}/' #{release_path}/app/config/parameters.#{ENV['dtap']}.yml
            sed -i -e 's/#mysqluser#/#{ENV['mysqluser']}/' #{release_path}/app/config/parameters.#{ENV['dtap']}.yml
            sed -i -e 's/#mysqlpw#/#{ENV['mysqlpw']}/' #{release_path}/app/config/parameters.#{ENV['dtap']}.yml
            ln -fs #{release_path}/app/config/parameters.#{ENV['dtap']}.yml #{release_path}/app/config/parameters.yml"
     end
   end
end
```

**Comment by will-in-wi** [comment]
Odd. According to my shell, `-t` sorts by update time, and is resulting in the issue.

I wonder whether this is intended and the bug is in the fact that the releases are created at different times, or whether we should drop the `-t` and depend on the folder names instead…

**Comment by markri** [comment]
As I want to continue on my project I just removed the r and t flag which working fine for me now

**Comment by mattbrictson** [comment]
Looks like we will have to roll back #1141, which is what introduced the `-t` flag. AFAIK, there is not a reliable way to sort by creation date. The `-t` flag sorts by modification date, which *often* correlates with creation date, but is not guaranteed.

@markri Would you like to take a shot at a PR?

/cc @plu @leehambley

**Comment by leehambley** [comment]
Agreed, roll it back. This feels like an eight year long running joke :( this has *never* worked reliably. We have the flag to `ls` because peopel can customize the release directory name to something that doesn't sort properly in Ruby (say, SHA1 hashes or something nonsensical) and then they need to rely on the filesystem.

We could also consider *explicitly* updating directory attrs on deploy, to *explicitly* set the mtime when we touch a deploy?

I wonder also if something like… I dunno, image uploads are somehow burried in a release, are bubbling up to affect the parent directory mtimes or something

**Comment by mattbrictson** [comment]
Maybe we should print a warning and skip `cleanup_releases` if the releases directory contains anything other than the default timestamped-based directory names. That way people customizing the release names or otherwise messing with that directory are not at the risk of unexpected data loss.

**Comment by markri** [comment]
Just created a PR which fixes this issue. Included a warning and cleanup skip when other folders are found than timestamp folders

**Comment by mattbrictson** [comment]
Fixed via #1811 and released in 3.7.0.

**Comment by lorenzoferrarajr** [comment]
Hello, I think version 2.15.9 is also affected by this problem. Anyone with more knowledge on the project can confirm or deny my suspects?

**Comment by a-ta-ta** [comment]
Maybe it will help anybody.
Capistrano was deploying the current release with wrong date (previous) and  removing it with cleanup.
The problem was in timestamp used for the name of the release.

Sometimes I work with notebook which has virtualbox and ubuntu on it. When my notebook slept for a couple of days it was showing the wrong date on ubuntu (thinking like there was no sleep time). So when I was commiting to git it commited  wrong date which resulted in wrong date for release and further problems.

Saying in couple of words - check the time of the latest commit and update it if it's wrong.
