### ISSUE TITLE
Release Capistrano 3.7.0 (final)

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1813]
The good news is that we didn't receive any bug reports for 3.7.0.beta1. The bad news is that we got [relatively few downloads](https://rubygems.org/gems/capistrano/versions/3.7.0.beta1) for the beta, so I guess the lack of reports is not surprising. The lesson here is that maybe betas are not worth the trouble?

Anyway, are we all good for releasing the final version of 3.7.0? I can handle updating the CHANGELOG and publishing the gem, etc.

/cc @leehambley @will-in-wi

**Comment by will-in-wi** [comment]
Sounds good to me!

**Comment by leehambley** [comment]
It's the final nail in the "beta release" coffin for me, they are *never* used.

**Comment by mattbrictson** [comment]
🚢 https://github.com/capistrano/capistrano/releases/tag/v3.7.0
