### ISSUE TITLE
Typo in hg.rake preventing release with mercurial

### ISSUE THREAD

**Issue by godoftheds** [capistrano/capistrano#1816]
### Steps to reproduce
Attempt to release via mercurial

### Expected behavior
Release happens

### Actual behavior
Release fails on the hg:clone step it throws the following error:
The deploy has failed with an error: undefined local variable or method `hr' for #<SSHKit::Backend::Netssh:0x00000001190540>

It looks like this issue is just caused by a typo in  capistrano/lib/capistrano/scm/tasks/hg.rake on line 31 it says hr.update_mirror this should be changed to hg_plugin.update_mirror.

**Comment by mattbrictson** [comment]
Thanks for pointing this out! Can you put together a quick PR with a CHANGELOG entry?

**Comment by godoftheds** [comment]
I won't be able to until tomorrow so if someone just wants to do it tonight they can go ahead. Otherwise I'll do it in the morning
