### ISSUE TITLE
Problem when deploying after updating to 3.7.0

### ISSUE THREAD

**Issue by teaearlgraycold** [capistrano/capistrano#1821]
### Steps to reproduce

We used to use bitbucket for source code hosting, and later moved to github. I found that one of our apps had difficulty at this step during deployment:

```bash
cd /opt/.../repo && ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="2.3.3" GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/--------.sh" ; /usr/bin/env git remote update --prune )
```

Which would yield the following response from git:

```
Fetching origin
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
```

I eventually found that the problem was that capistrano was not updating the "origin" remote configured in `/opt/.../repo/config` to my new github repo, even though my `deploy.rb` specified a github remote.

Editing the `repo/config` file fixed my issue.

### System configuration

https://gist.github.com/teaearlgraycold/53888c500d78cf1e21820a3af4e4989d

**Comment by mattbrictson** [comment]
Hi, sorry you ran into this issue. This problem (Capistrano's inability to automatically detect a changed `repo_url`) predates 3.7.0, and is being tracked in issue #1545. I'll close this one as a duplicate.

**Comment by teaearlgraycold** [comment]
Alright, thanks for letting me know
