### ISSUE TITLE
set a variable can be access outside task block.

### ISSUE THREAD

**Issue by zw963** [capistrano/capistrano#1830]
Following is a example:

```rb
namespace :unicorn do
  task :start do
    ....
  end  
end


if some_varialbe == 'new_production'
  after 'deploy:published', 'unicorn:start'
end
```

I want to know how to set a condition for this case. Thanks.

~~BTW:  set a constant is worked, but, this not the correct way, right?~~

Thanks

**Comment by leehambley** [comment]
Please see the mailing list for support and pay attention to the `CONTRIBUTING` guidelines. https://groups.google.com/forum/#!forum/capistrano
