### ISSUE TITLE
Allow cap command to work from within subdirectory

### ISSUE THREAD

**Issue by dan-passaro** [capistrano/capistrano#1832]
Using capistrano 3.7.1, if I run `cap qa deploy` from a subfolder, it says

    Stage not set, please call something such as `cap production deploy`, where production is a stage you have defined.

So my `cap qa deploy` has turned into `cd .. && cap qa deploy && cd -`

It's a very minor annoyance but I run into it all the time.  Would it be okay for cap to behave like rake and git in that it searches parent dirs for its files?

**Comment by leehambley** [comment]
Are you *sure* Rake looks in parent directories, we are based on Rake, and I don't have the feeling that it does.

**Comment by mattbrictson** [comment]
I believe `rake` *does* search parent directories until it finds a `Rakefile`. I've encountered this behavior before.

However, I don't know why `cap` doesn't do the same thing, nor do I have a good intuition for how much work is required to make this change.

One question we'd have to answer: when loading `config/deploy.rb`, etc., should that be relative to the working directory, or relative to the `Capfile`? Probably the latter, right?

If anyone wants to try making a PR for this, please chime in.

**Comment by mattbrictson** [comment]
Here's the relevant bit of code from rake:

https://github.com/ruby/rake/blob/93e55a4ef1dbaee42f0f355f86d837c4e2551fc1/lib/rake/application.rb#L655-L665

**Comment by dan-passaro** [comment]
Rake also seems to change its working directory. At least 10.4.2 I'm able to cd to a subdir and run "rake serve" for one of my projects where the serve command does `sh "python some_script.py"`.

Although the `ensure` block in the linked code makes it seem like that shouldn't happen...

Either way it does seem appropriate for cap to use the Capfile directory as its working directory

**Comment by mattbrictson** [comment]
I don't have time to do all the testing and documentation necessary for a PR at the moment, but this patch seems to be the fix:

```diff
diff --git a/lib/capistrano/application.rb b/lib/capistrano/application.rb
index f3105a43..09264e04 100644
--- a/lib/capistrano/application.rb
+++ b/lib/capistrano/application.rb
@@ -2,7 +2,7 @@ module Capistrano
   class Application < Rake::Application
     def initialize
       super
-      @rakefiles = %w{capfile Capfile capfile.rb Capfile.rb} << capfile
+      @rakefiles = %w{capfile Capfile capfile.rb Capfile.rb}
     end
 
     def name
@@ -96,11 +96,19 @@ module Capistrano
       super
     end
 
-    # allows the `cap install` task to load without a capfile
     def capfile
       File.expand_path(File.join(File.dirname(__FILE__), "..", "Capfile"))
     end
 
+    # allows the `cap install` task to load without a capfile
+    def find_rakefile_location
+      if (location = super).nil?
+        [capfile, Dir.pwd]
+      else
+        location
+      end
+    end
+
     def version
       ["--version", "-V",
        "Display the program version.",
```

Does anyone want to run with this and make a PR?
