### ISSUE TITLE
Ask function with no default still prints parenthesis

### ISSUE THREAD

**Issue by chamini2** [capistrano/capistrano#1834]
I find it strange that if there is no default, the `ask` function still prints `()`, what do you think of removing it?

```
ask(:value, "value now")
```

prints

> Please enter value now (): <user input>

changing it to

> Please enter value now: <user input>

**Comment by mattbrictson** [comment]
Yep, good point. I agree that's a bug. Fixes are welcome. 😁

**Comment by chamini2** [comment]
Closed in #1835
