### ISSUE TITLE
Publish Capistrano 3.7.2

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1838]
I'm planning on pushing a new Capistrano release this weekend. As a general rule, I have been aiming for a 6-week cadence for gem releases across the board, and the last release for this gem was 2016-12-16.

Since there are tweaks to existing behavior but no new features (although as with everything semver, this is somewhat debatable), I am going to call it 3.7.2. Diff: https://github.com/capistrano/capistrano/compare/v3.7.1...HEAD

If there are any objections, or if should hold off for now, let me know!

/cc @leehambley @will-in-wi

**Comment by will-in-wi** [comment]
From a brief glance, I agree with your assessment of the version.

:+1:

**Comment by mattbrictson** [comment]
Works for me! 

🚢 https://rubygems.org/gems/capistrano/versions/3.7.2
