### ISSUE TITLE
cannot gem install capistrano 2.14.x or 2.15.x in ruby version < 2.x

### ISSUE THREAD

**Issue by jyanko** [capistrano/capistrano#1844]
Cannot successfully install capistrano version 2.15.x into a ruby version prior to ruby 2.0

---

### Steps to reproduce

install failing in older ruby (which used to work)
```
$ rvm use --create ruby-1.8.7-p374@test_cap
$ rvm --force gemset empty
$ gem install capistrano -v "~>2.15"
```

install still fails after manually installing the defined dependencies
```
$ rvm current
ruby-1.8.7-p374@test_cap

$ gem list

*** LOCAL GEMS ***

bundler (1.14.3)
highline (1.6.21)
json (1.8.6)
net-scp (1.0.4)
net-sftp (2.0.5)
net-ssh (2.6.8)
net-ssh-gateway (1.1.0)

$ gem install capistrano -v "~> 2.15.9" --no-rdoc --no-ri
Fetching: net-ssh-4.0.1.gem (100%)
ERROR:  Error installing capistrano:
	net-ssh requires Ruby version >= 2.0.
```

### Expected behavior
capistrano should be able to satisfy dependencies and install. 

### Actual behavior

Install to a clean gemset fails

Install to a gemset that has had defined dependencies satisfied manually still fails as it appears that something is attempting to pull net-ssh version 4.0.1 even though version 2.6.8 which satisfies the dependency is already installed

### Workaround

Installing dependencies by hand, then running gem install capistrano with one of the following flags does allow the gem to be installed, but still requires the manual pre-installation of the dependencies
* `--minimal-deps`
* `--conservative flag` 

```
$ gem list

*** LOCAL GEMS ***

bundler (1.14.3)
highline (1.6.21)
json (1.8.6)
net-scp (1.0.4)
net-sftp (2.0.5)
net-ssh (2.6.8)
net-ssh-gateway (1.1.0)

$ gem install capistrano -v "~> 2.15.9" --no-rdoc --no-ri --minimal-deps
Fetching: capistrano-2.15.9.gem (100%)
Successfully installed capistrano-2.15.9
1 gem installed
[jyanko@ds-deploy ~]$ gem list

*** LOCAL GEMS ***

bundler (1.14.3)
capistrano (2.15.9)
highline (1.6.21)
json (1.8.6)
net-scp (1.0.4)
net-sftp (2.0.5)
net-ssh (2.6.8)
net-ssh-gateway (1.1.0)
```

### System configuration
* `CentOS release 6.8 (Final)`
* `rvm 1.28.0`
** `ruby-1.8.7-p374`
** `ruby-1.9.3-p551`

Thanks for helping improve Capistrano!

**Comment by mattbrictson** [comment]
Thanks for the detailed report.

This is an unfortunate limitation of rubygems. Although gems like net-ssh can declare a "minimum Ruby version", `gem install` does not honor it when deciding which version to download and install. It is only when it attempts the installation does it notice the Ruby requirement and fail, and at this point it is too late.

As Capistrano maintainers, I don't think there is anything we can do to prevent this.

However, the newest version of Bundler (which it appears you already have installed) *does* supposedly do the right thing with respect to the minimum Ruby version. You therefore might have better luck installing via `bundle install` instead.

I.e. create a Gemfile:

```ruby
# Gemfile
source "https://rubygems.org"
gem "capistrano", "~> 2.15.9"
```

And then:

```
bundle install
```

**Comment by mattbrictson** [comment]
This Gemfile works for Ruby 1.9.3:

```ruby
source "https://rubygems.org"
gem "capistrano", "~> 2.15.9"
gem "net-ssh", "< 4.0"
```

**Comment by jyanko** [comment]
@mattbrictson - thanks for the tips.

I had already started trying out using bundler to get deploy host setup but you helped drive me in the right direction as far as how to define versions in the Gemfile.

Items of note...
* for ruby 1.8.7 - must also define a version of highline in Gemfile
* for ruby 1.9.3 - highline version could be excluded in Gemfile
* saw different behavior between sources during the bundle install
* hitting an internal mirror I got "net-ssh-3.2.0 requires ruby version >= 2.0" 
* hitting "https://rubygems.org" did not experience that error

Here is the Gemfile that ultimately worked to get capistrano installed into my  ruby-1.8.7-p374@test_cap gemset  
```
$ cat Gemfile.deploy | egrep -v "^(source|$)"
group :deploy do
  gem "capistrano", "~> 2.15"
  gem "net-ssh", "< 2.10"
  gem "highline", "< 1.7"          # this line not needed for ruby >= 1.9.3
end

$ gem list
*** LOCAL GEMS ***

bundler (1.14.3)
capistrano (2.15.9)
highline (1.6.21)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (2.9.4)
net-ssh-gateway (1.3.0)
```

I discovered that it is very easy to mask a problem that would raise itself only when installing to a clean host/gemset if the Gemfile.lock WAS NOT being removed on each pass during test installs, so I took to using the following alias to reset things and bundle install for each edit I made to the Gemfile I was working on..

```
alias resetGemset='rm -f Gemfile.deploy.lock &&  rvm --force gemset empty && echo "[CURRENT GEMSET]: $(rvm current)" && echo "[CURRENT GEMLIST]:" && gem list && echo "[CURRENT GEMFILE]:" && cat Gemfile.deploy && bundle install --gemfile Gemfile.deploy &&  echo "[UPDATED GEMLIST]:" && gem list'
```

For reference, I'll note some of the failed Gemfile contents with their issues encountered below...

Fails: highline-1.7.8 requires ruby version >= 1.9.3
```
$ cat Gemfile.deploy | egrep -v "^(source|$)"
group :deploy do
  gem "capistrano", "~> 2.15"
end

$ cat Gemfile.deploy | egrep -v "^(source|$)"
group :deploy do
  gem "net-ssh", "< 4.0"
  gem "capistrano", "~> 2.15"
end
```
Fails: net-ssh-3.2.0 requires ruby version >= 2.0
```
$ cat Gemfile.deploy | egrep -v "^(source|$)"
group :deploy do
  gem "capistrano", "~> 2.15"
  gem "net-ssh", "< 4.0"
  gem "highline", "< 1.7"
end
```

**Comment by mattbrictson** [comment]
You might consider opening an issue at the Bundler repo if you haven't done so already. I am pretty sure that Bundler 1.14 is supposed to honor the minimum Ruby version and do the right thing. The behavior we're seeing seems like a Bundler bug to me.

I'll close this issue since you seem to have found a workaround.

**Comment by jyanko** [comment]
Thanks @mattbrictson 

Just for the backreference, it looks like someone else has opened a similar issue on the bundler project over the weekend.  

* https://github.com/bundler/bundler/issues/5425

I just chimed in on its comment thread
