### ISSUE TITLE
:repo_tree configuration doesn't work with Mercurial

### ISSUE THREAD

**Issue by zebastiane** [capistrano/capistrano#1849]
Hi,

I'm using Capistrano 3.7.1 and I wanted to use the `repo_tree` option.
Unfortunately with Mercurial it doesn't work, and deployment fails.

```
00:02 hg:create_release
      01 hg archive --type tgz -p . -I website --rev develop | tar -x --strip-components 1 -f - -C /var/www/html/releases/20170217155548
      01 hg archive: invalid arguments
      01 tar: This does not look like a tar archive
      01 tar: Skipping to next header
      01 tar: Exiting with failure status due to previous errors
```

`git archive` writes to the standard output, but `hg archive` doesn't.

**Comment by mattbrictson** [comment]
Hi, thanks for the report! Can you also include your `capistrano [stage] doctor` output so we can see exactly what values you are using for `repo_tree` and other settings?

@townsen I think you were the developer that contributed the `repo_tree` feature. Are you available to help troubleshoot? I am not familiar with Mercurial, so my ability to assist here is fairly limited. Thanks!

**Comment by zebastiane** [comment]
Hi,

Thanks for the reply.

[Here is a gist](https://gist.github.com/zebastiane/be5a7c3424f78481d32a7b49e741f919) with the output of `bundle exec cap recette doctor`.

Maybe a solution is to create an archive, extract it and then remove the file.

**Comment by mattbrictson** [comment]
I could be wrong, but it doesn't look like `tar` or the format of the archive is the problem. The error comes before that point:

```
hg archive: invalid arguments
```

So the way Capistrano is calling `hg` is the underlying problem, no?

**Comment by mattbrictson** [comment]
> `git archive` writes to the standard output, but `hg archive` doesn't

Yes, I think you are onto something here. If I were to create a branch with some changes to how Capistrano uses `hg archive`, would you be willing to test it?

**Comment by zebastiane** [comment]
Yes `hg archive` needs a destination

```
$ hg help archive
hg archive [OPTION]... DEST
```

A solution could be, replacing this [line](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/scm/hg.rb#L39)

```
hg "archive --type tgz -p . -I", tree, "--rev", fetch(:branch), "| tar -x --strip-components #{components} -f - -C", release_path
```

With these commands

```
hg "archive --type tgz -p . -I", tree, "--rev", fetch(:branch), "release.tar.gz"
tar -x --strip-components #{components} -f release.tar.gz -C", release_path
rm release.tar.gz
```

But I don't know Capistrano guidelines and how such temporary files should be handled.

Another option is to use the `--type files` option to archive files with `hg archive`. It archives files directly without an archive format, but the directory structure is kept. The benefit of using `--strip-components` is lost, the files must be moved after. 

> Yes, I think you are onto something here. If I were to create a branch with some changes to how Capistrano uses `hg archive`, would you be willing to test it?

Yes, I could do that
