### ISSUE TITLE
airbrussh configuration of command_output not working

### ISSUE THREAD

**Issue by avonderluft** [capistrano/capistrano#1866]
### Steps to reproduce

Using default airbrussh format in cap 3.8

In my deploy.rb I'm setting `command_output` to false, but everything still shows on the console.
```   
set :log_level, :info
set :format_options, command_output: false, log_file: "deploy_logs/deploying.log"
```

### Expected behavior
no output (or minimal) to console

### Actual behavior
Full output to console, no matter what is set as `command_output` false or :stderr

### System configuration
https://gist.github.com/avonderluft/d4ba9be7e7b40482042ba5d7805b3d0d

**Comment by mattbrictson** [comment]
Closing in favor of https://github.com/mattbrictson/airbrussh/issues/104
