### ISSUE TITLE
Problems when remote user has tcsh or csh as default shell

### ISSUE THREAD

**Issue by kperry42** [capistrano/capistrano#1870]
I'm attempting to upgrade from Cap 2.x to Cap 3.x - everything worked fine in 2.x.  With version 3, I'm seeing the following issue:  For legacy reasons, the account I'm using on the remote servers that I'm deploying to has tcsh as its login shell.  I set a couple of envars in :default_env in my config/deploy.rb.  When I run, say, "cap dev deploy", it fails.  

Every command that it tries to execute - including such basics as "deploy:check:directories" produces a (non-fatal, but problematic) "export: Command not found" error.  When it tries to read the contents of the REVISION file in the "deploy:set_previous_revision" task, this happens:
```
 DEBUG [294ec78e] Command: ( export COMPOSER_DISCARD_CHANGES="true" PATH="/opt/rh/rh-php56/root/usr/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/apps/nodejs/current/node/bin" ; /usr/bin/env cat /usr/local/apps/timeline/current/REVISION 2>/dev/null )

 DEBUG [294ec78e]       export: Command not found.

 DEBUG [294ec78e]       cat: 2: No such file or directory
```
So there appear to be two major issues: the lack of an "export" function in tcsh, and the different syntax for routing stderr (tcsh doesn't know what to do with the "2>").

As best I can tell from searching the docs and the web, the only way to get around this at present is to change the user's login shell to bash.  This requirement should at least be well-documented; but preferably, there would be a way to tell Capistrano that the remote user is using tcsh, and have it issue valid tcsh commands.

I mentioned this yesterday in a comment on [sshkit issue 354](/capistrano/sshkit/issues/354#issuecomment-288864314)

(Sorry for the lack of a gist showing this behavior - I don't have a publicly accessible server that's set up this way.)

**Comment by leehambley** [comment]
FWIW from a friend who happend to have an example to hand:

```
[root@pike profile.d]# cat go.csh
set path = ( $path /usr/local/go/bin )
[root@pike profile.d]# cat go.sh
export PATH=$PATH:/usr/local/go/bin
```

Non the less, according to the IEEE Standard 1003.1 (POSIX, 2004) `export` is standard, and the syntax for redirection is specifiied in the same document

 - http://pubs.opengroup.org/onlinepubs/007904975/utilities/export.html
 - http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_07

I'm hesitant to tar "tcsh" as "non-standard", but it appears based on what I've read to fly in the face of anything that might be called standard in modern operating systems.

I thought we had documented somewhere that we expect a POSIX shell, but perhaps it's time to make sure.

I don't think you need to set the user's shell to bash, but `sh` or *something* would go a long way.

**Comment by mattbrictson** [comment]
Wow, I had no idea that (t)csh was so different! Sounds like we should mention that Capistrano assumes an `sh` style shell prominently in the documentation.

**Comment by kperry42** [comment]
Yes it would be great if there was prominent mention of this fact in the doc.  I'd suggest putting it on the "Converting from 2.x" page and also somewhere in the normal flow of instructions on getting started.

Declaring that a POSIX shell is a requirement does seem reasonable, when you put it in those terms. Although, even if I had found that statement in the docs, I probably wouldn't have clued in that tcsh isn't POSIX.  Anyway, In my particular case, I think we can manage to sort out our legacy issues and switch the user account in question to using bash.  (Side note - it is possible to define a shell alias to replace the missing export command, but the output redirection problem doesn't seem to have a decent work-around.)

**Comment by mattbrictson** [comment]
@kperry42 Thanks for the feedback. Would you be willing to make a first pass at those changes? Our documentation is Markdown files, and source for the "Converting from 2.x" page is here: https://github.com/capistrano/capistrano/blob/master/docs/documentation/upgrading/index.markdown

I'd appreciate a PR if you have time!
