### ISSUE TITLE
Cannot set custom Capistrano configuration paths

### ISSUE THREAD

**Issue by BentCoder** [capistrano/capistrano#1876]
Hi,

I'm trying to change the default folder structure (as shown below) by implementing [How can I set Capistrano configuration paths?](http://capistranorb.com/documentation/faq/how-can-i-set-capistrano-configuration-paths/). However, everytime I run `cap install` default folders structure gets created again. Is there some kind of cache?

Thanks

**Default** *unwanted*
```
config
  - deploy.rb
  - deploy
    - prodiction.rb
    - staging.rb
```

**Aiming at**
```
cap
  - deploy.rb
  - tasks
  - stages
    - prodiction.rb
    - staging.rb
```

**Gemfile**

```
source 'https://rubygems.org'
gem 'capistrano', '~> 3.8'
```

**Capfile**
```
set :deploy_config_path, 'cap/deploy.rb'
set :stage_config_path, 'cap/stages'

require "capistrano/setup"
require "capistrano/deploy"
require "capistrano/scm/git"

install_plugin Capistrano::SCM::Git

Dir.glob('cap/tasks/*.rb').each { |r| import r }
```

**Comment by mattbrictson** [comment]
Hi, thanks for the report.

To my knowledge it is not possible to configure the behavior of `cap install`. When you run `cap install`, it always builds out the default directory structure. `cap install` is supposed to be run before a `Capfile` even exists, so there is no place to put any configuration for it.

However, what you *can* do is configure where Capistrano looks for the `deploy.rb` and staging files when you run other commands, like `cap production deploy`. In other words, once you've manually structured your project and put the `deploy.rb`, etc. exactly where you like, you can change your `Capfile` as you've done in your example and then `cap production deploy` will work.

Does that make sense?

**Comment by mattbrictson** [comment]
Also: we're always looking for contributors to improve the docs. If you feel the documentation is misleading in this case, please feel free to open a PR.

**Comment by BentCoder** [comment]
So what you're saying is, we should create the structure manually rather than expecting `cap install` to do it for us. I'll try it tomorrow and see what happens first then close this issue if it works. Thanks for the info.

**Comment by BentCoder** [comment]
As you said, it worked perfectly fine so thank you again for enlighten me.
