### ISSUE TITLE
Using doas or su instead of sudo

### ISSUE THREAD

**Issue by rsiddle** [capistrano/capistrano#1881]
It would be useful to have a figuration for using either `sudo` or `doas` which is used in OpenBSD.

Is there any easy way of overriding all `sudo` commands to be `doas` or switching the user using `su`?

**Comment by mattbrictson** [comment]
Hi, thanks for the suggestion. I think this is already possible with the [SSHKit command map](https://github.com/capistrano/sshkit#the-command-map).

```ruby
# deploy.rb
SSHKit.config.command_map[:sudo] = "doas"
```

**Comment by mattbrictson** [comment]
If the command map solution didn't work for you, let me know and we'll reopen this issue.
