### ISSUE TITLE
Feature request: configurable 'releases' and 'shared' directory path

### ISSUE THREAD

**Issue by ShoobyBan** [capistrano/capistrano#1889]
Our new hosting partner has nearly the same structure as default Capistrano (releases, shared, current) but with slightly different directory names. Currently this directory names are hardwired.

---

### Steps to reproduce
Setting variables in a deploy target:
set :shared_directory, "___shared"
set :releases_directory, "___releases"
set :current_directory, "http"

### Expected behavior
Would produce the directory structure with given names.

### Actual behavior
The 'shared' and 'releases' directories are hardcoded, they can't be changed from configuration.

### System configuration
N/A

**Comment by ShoobyBan** [comment]
Created a pull request (sorry, no test changes) https://github.com/capistrano/capistrano/pull/1890

Many Thanks

**Comment by leehambley** [comment]
@ShoobyBan I may be mistaken but I'm sure we've rejected this change before for two reasons:

- We want to keep the configuration API small, that means having as few top level global variables
- Not wanting to make too much configurable, the value in Capistrano comes from the standardisation

It may also be that we've never argued this exact case, but have rejected changes that allow the configuration of the individual (timestamped) release directories.

I'll let the other maintainers chime in.

**Comment by ShoobyBan** [comment]
@leehambley thank you for the review and the explanation. Sorry, I did not check the closed pull requests, I see now, #1818 although it was only for releases_path... 
Too bad, Capistrano is such a flexible tool otherwise.
I hope other maintainers will see value in my humble contribution :)

**Comment by leehambley** [comment]
Hey @ShoobyBan - The PR you mentioned is actually a bit of a hot topic, plenty of core, and plugin functionality relies on being able to predict the sorting of the release directory, so it's a much riskier proposition that leads to more breakage than your suggestions, I just wanted to give you a bit of context. 👍

**Comment by mattbrictson** [comment]
It's always hard to make a judgement call for these things. I'll support making these paths configurable if there is test coverage and a mention in the docs. 👍

**Comment by leehambley** [comment]
I second Matt's view. He usually has a better overview than I, and a better intuition of what's going to cause problems down the line. Updating issue flags to reflect the "would take a patch" consensus.

**Comment by mikegee** [comment]
I think this issue can be closed now that https://github.com/capistrano/capistrano/pull/1943 is merged.

**Comment by mattbrictson** [comment]
Good point, thanks!
