### ISSUE TITLE
Deploy flag --prereqs required

### ISSUE THREAD

**Issue by wurde** [capistrano/capistrano#1892]
Without the --prereqs flag my `cap production deploy` command fails with an SSHKit::Runner::ExecuteError. This shouldn't happen based on the flag description as a way to "list task dependencies".

I couldn't find --prereqs flag in the source code, so I'm not sure what it is doing.

I tried tracing the issue through the capistrano source code starting at the point of failure; the git:wrapper command. I tried setting tmp_dir but that didn't seem to affect this hard requirement of --prereqs.

    bundle exec cap production deploy --trace
    #=> Identity added: /dev/fd/63 (rsa w/o comment)
    #=> ** Invoke production (first_time)
    #=> ** Execute production
    #=> ** Invoke load:defaults (first_time)
    #=> ** Execute load:defaults
    #=> ** Invoke bundler:map_bins (first_time)
    #=> ** Execute bundler:map_bins
    #=> ** Invoke deploy:set_rails_env (first_time)
    #=> ** Execute deploy:set_rails_env
    #=> ** Invoke deploy:set_linked_dirs (first_time)
    #=> ** Execute deploy:set_linked_dirs
    #=> ** Invoke deploy:set_rails_env 
    #=> ** Invoke deploy (first_time)
    #=> ** Execute deploy
    #=> ** Invoke deploy:starting (first_time)
    #=> ** Execute deploy:starting
    #=> ** Invoke deploy:check (first_time)
    #=> ** Invoke git:check (first_time)
    #=> ** Invoke git:wrapper (first_time)
    #=> ** Execute git:wrapper
    #=> 00:00 git:wrapper
    #=>       01 mkdir -p /home/ubuntu/capistrano/tmp
    #=> cap aborted!
    #=> SSHKit::Runner::ExecuteError: Exception while executing as ubuntu@15.134.11.79: Authentication failed for user ubuntu@15.134.11.79
    #=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
    #=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
    #=> Net::SSH::AuthenticationFailed: Authentication failed for user ubuntu@15.134.11.79
    #=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh.rb:250:in `start'
    #=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/connection_pool.rb:59:in `call'
    #=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/connection_pool.rb:59:in `with'
    #=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/netssh.rb:172:in `with_ssh'
    #=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/netssh.rb:125:in `execute_command'
    #=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:141:in `block in create_command_and_execute'
    #=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:141:in `tap'
    #=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:141:in `create_command_and_execute'
    #=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:74:in `execute'
    #=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/capistrano-3.8.1/lib/capistrano/scm/tasks/git.rake:8:in `block (3 levels) in eval_rakefile'
    #=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
    #=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:29:in `run'
    #=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
    #=> Tasks: TOP => deploy:check => git:check => git:wrapper
    #=> The deploy has failed with an error: Exception while executing as ubuntu@15.134.11.79: Authentication failed for user ubuntu@15.134.11.79
    #=> ** Invoke deploy:failed (first_time)
    #=> ** Execute deploy:failed

**Comment by wurde** [comment]
As mentioned, my deployments work perfectly when I have the --prereqs flag, but it bothers me that I have no idea why. It's a hack that could lead to build failures when using future versions of Capistrano.

**Comment by leehambley** [comment]
`--prereqs` seems to be one we inherited from `rake`:

- https://github.com/ruby/rake/blob/e0198444af8f41724d34b3709cdcfbecc6fbace9/lib/rake/application.rb#L485-L488

**Comment by wurde** [comment]
Interesting. This may be an order of operations issue. I notice with --prereqs that git:wrapper occurs earlier than when not set.

**Comment by wurde** [comment]
My .gitlab-ci.yml configuration is using password SSH key pairs.

    # Install ssh-agent utility.
    - 'which ssh-agent || ( apt -y update -qq && apt -y install -qq openssh-client )'
    # Run ssh-agent to set SSH relevant variables.
    - eval $(ssh-agent -s)
    # Add SSH key from Stored Variable to the authentication agent.
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    # Disable host key checking (only secure for docker build servers).
    - mkdir -p ~/.ssh
    # - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    # Print capistrano version for debugging purposes.
    - bundle exec cap -V
    # Deploy application using capistrano.
    # - bundle exec cap production deploy --prereqs --trace --print-config-variables
    - bundle exec cap production deploy

**Comment by wurde** [comment]
A successful build with --prereqs looks like this.

    $ bundle exec cap -V
    Capistrano Version: 3.8.1 (Rake Version: 12.0.0)
    $ bundle exec cap production deploy --prereqs --trace --print-config-variables
    Config variable set: :print_config_variables => true
    cap bundler:clean
    cap bundler:install
    cap bundler:map_bins
    cap default
        deploy
    cap deploy
    cap deploy:assets:backup_manifest
    cap deploy:assets:precompile
    cap deploy:assets:restore_manifest
    cap deploy:check
        git:check
    cap deploy:check:directories
    cap deploy:check:linked_dirs
    cap deploy:check:linked_files
    cap deploy:check:make_linked_dirs
    cap deploy:cleanup
    cap deploy:cleanup_assets
        set_rails_env
    cap deploy:cleanup_rollback
    cap deploy:clobber_assets
        set_rails_env
    cap deploy:compile_assets
        set_rails_env
    cap deploy:failed
    cap deploy:finished
    cap deploy:finishing
    cap deploy:finishing_rollback
    cap deploy:log_revision
    cap deploy:migrate
        set_rails_env
    cap deploy:migrating
        set_rails_env
    cap deploy:new_release_path
    cap deploy:normalize_assets
        set_rails_env
    cap deploy:print_config_variables
    cap deploy:published
    cap deploy:publishing
    cap deploy:restart
    cap deploy:revert_release
        rollback_release_path
    cap deploy:reverted
        bundler:install
    cap deploy:reverting
    cap deploy:rollback
    cap deploy:rollback_assets
        set_rails_env
    cap deploy:rollback_release_path
    cap deploy:set_current_revision
        git:set_current_revision
    cap deploy:set_linked_dirs
    cap deploy:set_previous_revision
    cap deploy:set_rails_env
    cap deploy:started
    cap deploy:starting
    cap deploy:symlink:linked_dirs
    cap deploy:symlink:linked_files
    cap deploy:symlink:release
    cap deploy:symlink:shared
    cap deploy:updated
        bundler:install
    cap deploy:updating
        new_release_path
    cap doctor
        doctor:environment
        doctor:gems
        doctor:variables
        doctor:servers
    cap doctor:environment
    cap doctor:gems
    cap doctor:servers
    cap doctor:variables
    cap git:check
        git:wrapper
    cap git:clone
        git:wrapper
    cap git:create_release
        git:update
    cap git:set_current_revision
    cap git:update
        git:clone
    cap git:wrapper
    cap install
    cap load:defaults
    cap production
    Creating cache default...
    Created cache
    Job succeeded

**Comment by leehambley** [comment]
Could you post the output of `$ cap doctor` please? And confirm if you're specifying Capistrano in your gemfile or not, and/or running with `bundle exec ...` (or any shell tooling that does that for you automagically)

**Comment by wurde** [comment]
./Gemfile

    # Use Capistrano for deployment
    gem 'capistrano-rails', '~> 1.2'

**Comment by wurde** [comment]
I'll running cap doctor on my build server.

**Comment by wurde** [comment]
This is the `cap doctor` output when run on the build server (temporary docker image).

bundle exec cap production doctor

    Environment
        Ruby     ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
        Rubygems 2.6.12
        Bundler  1.15.0
        Command  /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/bin/cap production doctor

    Gems
        capistrano         3.8.1
        airbrussh          1.2.0
        rake               12.0.0
        sshkit             1.13.1
        net-ssh            4.1.0
        capistrano-bundler 1.2.0
        capistrano-rails   1.2.3

    Variables
        :application                 "rails_demo"
        :assets_prefix               "assets"
        :assets_roles                [:web]
        :branch                      "master"
        :bundle_bins                 ["gem", "rake", "rails"]
        :bundle_flags                "--deployment --quiet"
        :bundle_jobs                 "2\n"
        :bundle_path                 #<Pathname:/home/ubuntu/rails_demo/shared/bundle>
        :bundle_roles                :all
        :bundle_servers              [#<Capistrano::Configuration::Server:0x00000001d5e610 @keys=[], @local=false, @user="ubuntu", @hostname="15.134.11.79", @port=nil, @properties=#<Capistrano::Configuration::Server::Properties:0x00000001d5e2a0 @properties={}, @roles=#<Set: {:app, :db, :web}>>>]
        :bundle_without              "development test"
        :conditionally_migrate       true
        :default_env                 {}
        :deploy_to                   "/home/ubuntu/rails_demo"
        :format                      :airbrussh
        :git_environmental_variables {:git_askpass=>"/bin/echo", :git_ssh=>"/home/ubuntu/capistrano/tmp/git-ssh-rails_demo-production-ubuntu.sh"}
        :git_shallow_clone           false
        :git_wrapper_path            "/home/ubuntu/capistrano/tmp/git-ssh-rails_demo-production-ubuntu.sh"
        :keep_assets                 3
        :keep_releases               3
        :linked_dirs                 ["log", "tmp/pids", "tmp/cache", "tmp/sockets", "vendor/bundle", "public/system", "public/uploads", "public/assets"]
        :linked_files                ["config/database.yml", "config/secrets.yml"]
        :local_user                  "ubuntu"
        :log_level                   :debug
        :migration_role              :app
        :migration_servers           #<Capistrano::Configuration::Server:0x00000001d5e610 @keys=[], @local=false, @user="ubuntu", @hostname="15.134.11.79", @port=nil, @properties=#<Capistrano::Configuration::Server::Properties:0x00000001d5e2a0 @properties={}, @roles=#<Set: {:app, :db, :web}>>>
        :pty                         false
        :rails_env                   :production
        :repo_url                    "https://wurde:'XXX'@code.example.com/wurde/rails_demo.git"
        :stage                       :production
        :tmp_dir                     "/home/ubuntu/capistrano/tmp"
        
        :bundle_jobs is not a recognized Capistrano setting (/usr/local/lib/ruby/2.4.0/delegate.rb:83)
        :keep_assets is not a recognized Capistrano setting (/usr/local/lib/ruby/2.4.0/delegate.rb:83)

    Servers (1)
        ubuntu@15.134.11.79 [:app, :db, :web]

**Comment by leehambley** [comment]
Thanks for posting that, I think there's a bit of a misunderstanding here; so you posted that without `--prereqs` it doesn't work, and the output you pasted is actually just the list of tasks that get called (the prerequisites) when you run a deploy:

```
$ bundle exec cap production deploy --prereqs --trace --print-config-variables
Config variable set: :print_config_variables => true
cap bundler:clean
cap bundler:install
cap bundler:map_bins
cap default
    deploy
cap deploy
cap deploy:assets:backup_manifest
cap deploy:assets:precompile
cap deploy:assets:restore_manifest
cap deploy:check
```

The other syntax for the output you pasted shows that the tasks are actually running, not just being enumerated, and that you have an authentication failure:

```
#=> ** Invoke deploy:check (first_time)
#=> ** Invoke git:check (first_time)
#=> ** Invoke git:wrapper (first_time)
#=> ** Execute git:wrapper
#=> 00:00 git:wrapper
#=>       01 mkdir -p /home/ubuntu/capistrano/tmp
#=> cap aborted!
#=> SSHKit::Runner::ExecuteError: Exception while executing as ubuntu@15.134.11.79: Authentication failed for user ubuntu@15.134.11.79
#=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
#=> /builds/wurde/rails_demo/vendor/bundle/ruby/2.4.0/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
#=> Net::SSH::AuthenticationFailed: Authentication failed for user ubuntu@15.134.11.79
```

**Comment by wurde** [comment]
That's my understanding too. The --prereqs flag simply prints the commands out on the terminal and the issue is an authentication failure. However everything works perfectly when I have the --prereqs flag, but when that flag is removed I get the authentication error.

**Comment by wurde** [comment]
Looking at the rake code I can't imagine --prereqs does anything more than print out the list of commands. I think the command could mask an authentication failure in my build server.

Yup. I'm positive this is an SSH authentication issue being masked by that flag. It faked me into thinking I had set everything up correctly.

**Comment by wurde** [comment]
It would be nice if capistrano pushed up the real issue (auth error), so build servers get the right info.

**Comment by leehambley** [comment]
the output tells you the operation and the error:

```
#=> 00:00 git:wrapper
#=>       01 mkdir -p /home/ubuntu/capistrano/tmp
#=> cap aborted!
#=> SSHKit::Runner::ExecuteError: Exception while executing as ubuntu@15.134.11.79: Authentication failed for user ubuntu@15.134.11.79
```
