### ISSUE TITLE
Capistrano leaks local user account name to deployment log

### ISSUE THREAD

**Issue by rbq** [capistrano/capistrano#1893]
### Steps to reproduce
1. Set up Capistrano project
2. Deploy to remote server

### Expected behavior
* Private information about developer machine config should not leak to remote server
* Local account names that make no sense to others should no be (ab-)used to distinguish between people on a project-wide scale.
* Deployment logs should contain information that is actually useful, such as a human readable, manually configured user names. In many cases that would probably be your Git `user.name` setting for the specific project.

### Actual behavior
* Capistrano leaks local user account name to log without even warning the user about it. This serves little purposes since other parties usually don't know your personal account name. But it might be something that you might not want to share with clients, e.g. a silly Star Wars reference, `admin`, your girlfriends name, some other project or whatever.

**Comment by mattbrictson** [comment]
Hi, thanks for the report! I agree, Capistrano should not surprisingly publish what some might consider personal information.

The `$USER` that you are seeing in the logs is driven by the `:local_user` Capistrano variable. So it is easy to change this to any value you want. For example, you could do this:

```ruby
# In deploy.rb
set :local_user, -> { `git config user.name`.chomp }
```

The bigger issue here is do we want to change the default behavior? If so, how do we do this in a backwards-compatible way?

`:local_user` is used in multiple places:

1. Attribution in `revisions.log`
2. Creating a per-user unique filename for the `:git_wrapper_path`
3. An unknown number of third-party Capistrano plugins may depend on it

The Git `user.name` might work for most projects, but we cannot assume that everyone is using Git. Further, as you point out, `$USER` is not good option either.

Any suggestions?

**Comment by rbq** [comment]
Hi, thanks for the advice about the `:local_user` config key. I think adding (a) this setting to the generated default config and (b) mentioning it in the [documentation](http://capistranorb.com/documentation/getting-started/structure/) would already help a lot in terms of preventing undesirable surprises.

My personal preference for future defaults would be to …

1. decouple the `revisions.log` info from `:local_user`. Introduce a new config key specifically for this purpose (probably something more general like `:deployed_by` that could equally well represent information about the CI server triggering/executing the build)
2. not add any name to `revisions.log` unless `:deployed_by` is `.present?`
3. put a sensible default for `:deployed_by` into newly generated `deploy.rb` files; maybe Git `user.name` `||` unknown
4. find a better way to deal with `:git_wrapper_path`; I guess using the local user name doesn't actually prevent collisions anyway since multiple CI servers might just happen to use the same default user?

I guess if backward-compatibility is required, `:deployed_by` could default to `:local_user`. Maybe combined with a deprecation warning?

**Comment by mattbrictson** [comment]
@rbq thanks for the suggestions! Would you be willing to open a PR to:

1. Add `:local_user` to the generated default config (modify [deploy.rb.erb](https://github.com/capistrano/capistrano/blob/7ba6e446ff4f517814d8e5a79710aa122a8b9064/lib/capistrano/templates/deploy.rb.erb))
2. Add a mention of this setting in the documentation (modify [structure/index.markdown](https://github.com/capistrano/capistrano/blob/7ba6e446ff4f517814d8e5a79710aa122a8b9064/docs/documentation/getting-started/structure/index.markdown))

I can create a separate feature request based on your code change suggestions.

I am planning on issuing a rubygems release very soon (likely this weekend), so if we could squeeze your PR in before then, that would be great!

**Comment by will-in-wi** [comment]
This has been fixed in https://github.com/capistrano/capistrano/pull/1895
