### ISSUE TITLE
Known, non-critical, security vulnerability re: verification of host keys

### ISSUE THREAD

**Issue by jaredbeck** [capistrano/capistrano#1896]
After discussing this security vulnerability in private, the capistrano team have come ".. to the conclusion that this is not a critical security vulnerability .." and have asked me to open an issue.

**tl;dr workaround**: add `set :ssh_options, paranoid: :secure` to `config/deploy.rb`.

# Original Vulnerability Report

Hi Matt,

As you know, to be secure, Capistrano and the people who use it must configure SSH correctly. Some configuration options are the responsibility of the users, and others are the responsibility of Capistrano.

When using SSH (in any context) the host key of the server must be verified. Failing to do so is a well-known vulnerability leading to DNS-based person-in-the-middle attacks. This attack is so well-known that it is mentioned in the manual page for SSH.

>
> Additionally, the server must be able to verify the client's host key (see the description of /etc/ssh/ssh_known_hosts and ~/.ssh/known_hosts, below) for login to be permitted.  This authentication method closes security holes due to IP spoofing, DNS spoofing, and routing spoofing.
>

Capistrano does not check host keys.

There is a workaround. Users can `set :ssh_options, paranoid: :secure`. This option will be passed, as you know, to net-ssh.

We believe capistrano should set this option by default. Systems should be secure by default. Perhaps there are legitimate use-cases where an insecure configuration is desirable, but security should be the default.

If you agree, please let me know what your timeline will be for releasing a fix.

Thank you for your consideration,
-Jared

# Response from Capistrano Team

Hi Jared,

I’ve discussed this with the other maintainers, and we all came to the conclusion that this is not a critical security vulnerability that warrants requesting a CVE.

Capistrano relies on net-ssh’s default behavior for host key verification, which is trust-on-first-use (and verify thereafter). As you point out, this is not as secure as it could be, but it strikes a good balance. If we were to issue an emergency patch to change this behavior, it would likely break a lot of Capistrano workflows, especially those involving unattended deploys (e.g. via CI).

The maintainers would prefer to move this discussion to a public forum, so that we can weigh these pros and cons and find a solution that works. For example, perhaps we can include a recommended host key verification setting in the deploy.rb that is generated for new projects, with appropriate documentation, while maintaining the current default for legacy projects.

If you are comfortable with continuing this conversation in public, would you mind creating an issue on GitHub?

Once again, thank you for taking the time to surface this issue and for helping to improve Capistrano for everyone!

**Comment by jaredbeck** [comment]
Hi Matt, Thanks for the quick response.

On Mon, Jun 12, 2017 at 11:02 AM, Matt Brictson <matt@mattbrictson.com> wrote:
> Hi Jared,
>
> I’ve discussed this with the other maintainers, and we all came to the conclusion that this is not a critical security vulnerability that warrants requesting a CVE.
>

CVEs are impossible to get anyway unless you're a big company, or ruby
lang. itself. :)

> Capistrano relies on net-ssh’s default behavior for host key verification, which is trust-on-first-use (and verify thereafter).

To clarify, this means accepting whatever you get on first use, and
writing that to known_hosts? This matches our observations of cap.'s
default config.

> As you point out, this is not as secure as it could be, but it strikes a good balance. If we were to issue an emergency patch to change this behavior, it would likely break a lot of Capistrano workflows, especially those involving unattended deploys (e.g. via CI).
>

I hadn't thought about CI. I suppose people would have to configure
known_hosts on CI.

> The maintainers would prefer to move this discussion to a public forum, so that we can weigh these pros and cons and find a solution that works. For example, perhaps we can include a recommended host key verification setting in the deploy.rb that is generated for new projects, with appropriate documentation, while maintaining the current default for legacy projects.
>

I think my recommendation remains the same: newly generated config.
files should use `:secure`. People who want an insecure configuration
can change that setting. If we can't achieve that, documentation in
the generated file would be a good start. I will also suggest printing
something to stdout when known_hosts is modified.

>
> If you are comfortable with continuing this conversation in public, would you mind creating an issue on GitHub?
>

Sure, will do.

> Once again, thank you for taking the time to surface this issue and for helping to improve Capistrano for everyone!
>

You're quite welcome. We use capistrano for almost all of our
non-heroku apps, it's been great.

**Comment by leehambley** [comment]
> the generated file would be a good start. I will also suggest printing something to stdout when known_hosts is modified.

For the record I'm against modifying or using the system `known_hosts` file. SSHKit already supports using a project-local SSH config, I think - if we're going against the grain of all the other tools which simply devnull these host key checks that we should encourage people to commit a known hosts file to the repo, somewhere under the Capistrano part of the tree.

Otherwise, who makes the call… the intern who'll do anything to get error messages to go away? That's no more secure than dev nulling them as we do now.

**Comment by leehambley** [comment]
Hi @jaredbeck as I'm discussing this with a colleague just now I am reminded that we also write a git wrapper script to explicitly tell Git to skip strict host key checking when cloning a repository via SSH, this is not affected by your workaround of calling `set :ssh_options,...` and needs further investigation.

**Comment by joshribakoff** [comment]
Can someone explain the current behavior? Is Capistrano (or net-ssh) saving the host key on first connect, and then verifying against that on subsequent connections (this would be the same way SSH on linux works). That doesn't seem like a security concern, as its how SSH already works.

Or is it never verifying at all? That's a security problem.

**Comment by mattbrictson** [comment]
> Is Capistrano (or net-ssh) saving the host key on first connect, and then verifying against that on subsequent connections (this would be the same way SSH on linux works).

Yes, this is how net-ssh works by default. It trusts the host key on first use, adds it to `known_hosts`, and then verifies against that on subsequent connections. This is how Capistrano and net-ssh work today.

The request in this issue is about locking it down even further, so that Capistrano uses net-ssh's "paranoid" mode by default. In that mode, it *only* allows connections to hosts that are already in the `known_hosts` file. That means to deploy to a server for the first time, you'd have to manually SSH to it first, or somehow add the key by some other means before Capistrano would allow you to connect.

**Comment by jaredbeck** [comment]
Matt's summary is accurate.

Note that the `:paranoid` setting has been renamed to `:verify_host_key`. (https://github.com/net-ssh/net-ssh/pull/524)

**Comment by will-in-wi** [comment]
Perhaps the solution here is to, at most, add the following lines to the default `deploy.rb`:

```ruby
# Uncomment the following to require manually verifying the host key before first deploy.
# set :ssh_options, verify_host_key: :secure
```

**Comment by leehambley** [comment]
Agreed.

**Comment by jaredbeck** [comment]
Thanks Will, I like the change to the deploy.rb template https://github.com/capistrano/capistrano/pull/1935. I think it will raise awareness of this issue, and give people who need secure systems a chance to configure correctly.

Two other issues have been raised here, so maybe we don't want to close this yet?

> .. we [capistrano] also write a git wrapper script to explicitly tell Git to skip strict host key checking when cloning a repository via SSH, this is not affected by your workaround of calling set :ssh_options,... and needs further investigation.

Did this get investigated?

> I .. suggest printing something to stdout when known_hosts is modified.

But, it is `net-ssh` that is silently, sneakily editing our `known_hosts` files isn't it? So I should file an issue with `net-ssh` about that?

**Comment by will-in-wi** [comment]
@jaredbeck Could you take those two specific concerns and open new tickets with them?

It looks like net-ssh is doing the `known_hosts` editing: https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/known_hosts.rb#L182 But I'm not sure I would want a library writing to standard output. So, could you open that here, and then Matt and/or Lee can weigh in on where they think it would make sense to address (or not) this?

I've reopened this ticket and will close it once the new tickets are opened. Thanks!
