### ISSUE TITLE
Make relative instead of absolute links

### ISSUE THREAD

**Issue by x-yuri** [capistrano/capistrano#1900]
Please, let us finish the conversation. I'd like to hear what @ain has to say.

@ain To be honest I'm not sure I'm [following][5].

> a decision that is 2 years old, at its current pace, is probably already obsolete

Here you supposedly mean, that having absolute symlinks no longer makes sense? Or is it just a general statement?

> The important matter is always to solve the problem in its scope and I didn't see it in Cap scope back in the days.

This supposedly means, that `capistrano` shouldn't have switched to absolute symlinks 2 years ago (back in the days). The problem should have been solved on the side of some other application.

> It's a cerbot and server routing problem, not a Cap problem.

And this must mean, that the problem at hand (the one I've run into, with `certbot`) shouldn't be solved on `capistrano`'s side.

Summing it up, it's not clear what's your take on `capistrano` using absolute symlinks nowadays.

Then, let me describe the issue I've run into, just in case. I have a pysical server with LXC containers. In each LXC container there's a site running. On a physical server I have `nginx`, which proxies HTTP requests to corresponding container based on Host header. To obtain SSL certificate for a site, I must tell `certbot` path to document root.

If I run `certbot` on a physical machine, I have no way to pass it path to document root, since symlink to current realease doesn't work outside of a container.

If I run `certbot` inside of a container, I have no way to automatically renew certificate. Since for that I need to restart `nginx` on the physical server from inside of a LXC container. For `nginx` to notice the new certificate.

This issue may manifest itself with FTP servers. (I believe at least some of them allow to chroot user to a directory.) And maybe SFTP ones. And generally with any kind of chroot.

And I see no advantages to using absolute symlinks over relative ones. At least nobody has told me any yet. But I see disadvantages.

Also, do you know anything about this decision everybody's talking about? From history of this [repo][1] I see [absolute symlinks][2] were [used][3] from day [one][4]. And more importantly, what was the reason to choosing absolute symlinks?

[1]: https://github.com/capistrano/capistrano/commit/49a07542#diff-aa4465f31474e46370f8f1f204f7d51eR70
[2]: https://github.com/capistrano/capistrano/blob/49a075427d299e3a3eafc02a34eec0b39098fa8b/lib/capistrano/dsl/paths.rb#L16-L18
[3]: https://github.com/capistrano/capistrano/blob/49a075427d299e3a3eafc02a34eec0b39098fa8b/lib/capistrano/dsl/paths.rb#L12-L14
[4]: https://github.com/capistrano/capistrano/blob/49a075427d299e3a3eafc02a34eec0b39098fa8b/lib/capistrano/dsl/paths.rb#L4-L6
[5]: https://github.com/capistrano/capistrano/pull/1187#issuecomment-310899836

**Comment by ain** [comment]
I don't think running `certbot` inside a container is necessarily a good idea. It took less than 10 lines outside the container to sort that out for __all domains__ on the server for me. Also allowing easy cert update automation on all domains. You just run `certbot` against the custom port. Separation of interests.

The below is for HAProxy, but I'm sure you can replicate this for Apache or nginx.

```
frontend http-in
  bind *:80
  mode http
  acl letsencrypt_control path_beg -i /.well-known/acme-challenge/
  use_backend letsencrypt if letsencrypt_control
backend letsencrypt
  mode http
  server letsencrypt 127.0.0.1:51212
