### ISSUE TITLE
Getting can't modify frozen #<Class:#<Rake::Task:0x007f88ab1af578>> While running cap dev shell

### ISSUE THREAD

**Issue by ethicalmohit** [capistrano/capistrano#1904]
I am trying to setup Capistrano for a project and getting the below error while running cap dev shell. I am getting the same error on cap dev deploy:check.

deploy.rb
```
set :application, "fex"
set :repo_url, "git@bitbucket.org:faasos/fex.git"

set :ec2_access_key_id,"AAAAAAAAAAA"
set :ec2_secret_access_key,"AAAAAAAAAAAAAAAAAAAAAA"
set :ec2_project_tag, 'Projects'
set :ec2_roles_tag, 'Roles'
set :ec2_stages_tag, 'Stages'
set :default_shell, "/usr/bin/bash"
set :shell, "bash"

set :keep_releases, 20

namespace :deploy do

  desc "run the frontend"
  task :seed do
    run "cd #{fetch(:deploy_to)}/current/code/fex/frontend; nohup puma RAILS_ENV=#{rails_env} &"
  end

  desc 'Restart application'
  task :restart do
    on roles(:fex), in: :sequence, wait: 5 do
      within "#{fetch(:deploy_to)}/current/" do
        # Your restart mechanism here
        begin
          #execute "fuser -k 3000/tcp"
        rescue =>e
          puts "[Error] e.to_s"
        end
       #execute "cd /home/ubuntu/code/fex/frontend && RAILS_ENV="development" nohup puma &"
        end
    end
  end
after :publishing, :restart

  after :restart, :clear_cache do
    on roles(:foodex), in: :groups, limit: 3, wait: 10 do
      # Here we can do anything such as:
      # within release_path do
      #   execute :rake, 'cache:clear'
      # end
    end
  end
end
```

dev.rb
```
require "cap-ec2/capistrano"

set :rails_env, :dev
set :branch, "master"
set :deploy_user, "ubuntu"
set :full_app_name, "fex"
set :deploy_to, "/home/#{fetch(:deploy_user)}/code/#{fetch(:full_app_name)}"

ec2_role :frontend,user: 'ubuntu'
ec2_role :samachar,user: 'ubuntu'
```

```
imohit:prod$ cap dev shell
WARNING: load:defaults has already been invoked and can no longer be modified.
Check that you haven't loaded a Capistrano plugin in deploy.rb by mistake.
Plugins must be loaded in the Capfile to initialize properly.
(Backtrace restricted to imported tasks)
cap aborted!
can't modify frozen #<Class:#<Rake::Task:0x007f88ab1af578>>

Tasks: TOP => dev
(See full trace by running task with --trace)
```

```
cap dev deploy:check
WARNING: load:defaults has already been invoked and can no longer be modified.
Check that you haven't loaded a Capistrano plugin in deploy.rb by mistake.
Plugins must be loaded in the Capfile to initialize properly.
(Backtrace restricted to imported tasks)
cap aborted!
can't modify frozen #<Class:#<Rake::Task:0x007f98992971b8>>

Tasks: TOP => dev
(See full trace by running task with --trace)
```

**Comment by ethicalmohit** [comment]
This has been fixed by calling the required modules in the "Capfile".

  ```
  require 'capistrano/bundler'
    require "cap-ec2/capistrano"
    require 'capistrano/rails/assets'
    require 'capistrano/rails/migrations'
```

**Comment by mattbrictson** [comment]
Glad to hear you solved the issue. Could we improve the error messaging or behavior for other people that may encounter this in the future? If you have any suggestions let us know. Thanks!

**Comment by ethicalmohit** [comment]
Yes, It would be good if It can display the clear message instead of ambiguous (can't modify frozen #<Class:#<Rake::Task:0x007f98992971b8>>) that these packages are required. As Its displaying When I tried to enable the "set :scm, :git" And it says that this does not supported anymore. You have to use the below lines in CapFile.

```
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git
```

**Comment by mattbrictson** [comment]
> Yes, It would be good if It can display the clear message instead of ambiguous (can't modify frozen #Class:#<Rake::Task:0x007f98992971b8>) 

The error includes this text:

```
WARNING: load:defaults has already been invoked and can no longer be modified.
Check that you haven't loaded a Capistrano plugin in deploy.rb by mistake.
Plugins must be loaded in the Capfile to initialize properly.
```

Could that be improved somehow? Is the problem that it is hard to see this message amongst the other output?

> When I tried to enable the "set :scm, :git" And it says that this does not supported anymore.

Are you referring to this message?

```
[Deprecation Notice] `set :scm, :git` is deprecated.
To ensure your project is compatible with future versions of Capistrano,
remove the :scm setting and instead add these lines to your Capfile after
`require "capistrano/deploy"`:
 
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git
```

That seems pretty good to me. How would you suggest improving it?

**Comment by ethicalmohit** [comment]
Yes, the below message is awesome as its displaying the specific part which needed to be targeted.

```
[Deprecation Notice] `set :scm, :git` is deprecated.
To ensure your project is compatible with future versions of Capistrano,
remove the :scm setting and instead add these lines to your Capfile after
`require "capistrano/deploy"`:
 
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git
```

I was confused with the below message, As which plugin it is taking about and Was ignoring it almost because it says its just a warning. It says that the problem is with deploy.rb, I was looking into it. Later on, I tried adding another thing which required many other plugins to be included in Capfile and it works. It seems to be the convention than a rule. 

```
WARNING: load:defaults has already been invoked and can no longer be modified.
Check that you haven't loaded a Capistrano plugin in deploy.rb by mistake.
Plugins must be loaded in the Capfile to initialize properly.
```

**Comment by mattbrictson** [comment]
Good feedback. I'll open a separate issue. Thanks!

**Comment by ethicalmohit** [comment]
@mattbrictson I would be more than happy to assist you and to contribute to the project. Thanks for the great tool. :)

**Comment by mattbrictson** [comment]
@ethicalmohit thanks for the offer to assist the project! We have [several issues](https://github.com/capistrano/capistrano/issues?q=is%3Aissue+is%3Aopen+label%3A%22you+can+help%21%22) that are tagged "you can help". If any of those catch your eye, leave a comment to let us know you're interested in submitting a PR. We might be able to offer implementation or testing tips. There are also [some documentation issues](https://github.com/capistrano/capistrano/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20label%3A%22you%20can%20help!%22%20label%3Adocumentation) that don't require any coding.
