### ISSUE TITLE
It is not clear that `require "<plugin>"` should not be used in stages; warning doesn't help

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1905]
From @ethicalmohit  in https://github.com/capistrano/capistrano/issues/1904#issuecomment-314857950

-----

I was confused with the below message, As which plugin it is taking about and was ignoring it almost because it says its just a warning. It says that the problem is with deploy.rb, I was looking into it. [The offending file was actually `deploy/dev.rb` (a stage).]  Later on, I tried adding another thing which required many other plugins to be included in Capfile and it works. It seems to be the convention than a rule.

```
WARNING: load:defaults has already been invoked and can no longer be modified.
Check that you haven't loaded a Capistrano plugin in deploy.rb by mistake.
Plugins must be loaded in the Capfile to initialize properly.
```

**Comment by leehambley** [comment]
Thanks for picking this up @mattbrictson - maybe we should simply prevent the behaviour and exit with a fatal error. Something akin to the growing trend of making compiler warnings fatal.

- https://blog.mozilla.org/nnethercote/2017/07/05/how-we-made-compiler-warnings-fatal-in-firefox/
- https://golang.org/doc/faq#unused_variables_and_imports
- etc

Maybe we simply blow up if someone reaches that line, and explain why?

**Comment by mattbrictson** [comment]
Yes, this warning has been in Capistrano for a few versions now, so it is probably safe to promote it to a fatal error. Ideally it would also print the offending file and line number (e.g. in `deploy/production.rb`), although that might be more difficult.

**Comment by will-in-wi** [comment]
Looks like this blows up already. Is there more to do on this ticket?

https://github.com/capistrano/capistrano/blob/master/lib/capistrano/immutable_task.rb#L25
https://github.com/capistrano/capistrano/blob/master/spec/lib/capistrano/immutable_task_spec.rb#L28

**Comment by mattbrictson** [comment]
Maybe the thing to do here is to change `WARNING` to `ERROR` in the text. It is not really a warning if it causes an uncaught exception. 😄
