### ISSUE TITLE
Tasks in after hooks are not shown

### ISSUE THREAD

**Issue by ivanovaleksey** [capistrano/capistrano#1910]
I got custom task that is run after deploy is finished.  
In `config/deploy.rb` I have
```
...
after 'deploy:finished', 'deploy:post_revision'
```

But I can't see this task in Capistrano output. So I can't really see all the task that were run during deploy process.

The Capistrano output is like the following
```
...
01:41 deploy:log_revision
      01 echo "Branch auto-migrate (at 0edcca1f79cafa973c000af5dfaaf7bc27fd05eb) deployed as release 20170721152104 by aleksey" >> /home/rc_apps/rails/revisions.log
```

### Expected behavior
I expect to see all the task that are turn during deployment process including `after` hooks.

### Actual behavior
I see only tasks that are run via `invoke` method.

### System configuration
I use Capistrano `3.8.2`

Is it expected behaviour or there is some bug here?

Thank you.

**Comment by mattbrictson** [comment]
Tasks are logged only if they execute SSH commands. This is because logging in Capistrano is the responsibility of SSHKit.

Does your `post_revision` task execute SSH commands (`on...execute`)?

**Comment by ivanovaleksey** [comment]
@mattbrictson thank you for the reply.
`deploy:post_revision` looks like this
```
namespace :deploy do
  task :post_revision do
    on roles(:web) do
      within release_path do
        revision = {
          server: fetch(:stage),
          branch: fetch(:branch),
          revision: fetch(:current_revision)
        }

        # sending revision with POST request
      end
    end
  end
end
```

**Comment by ivanovaleksey** [comment]
@mattbrictson I have moved all logic to a Rake task and called it via `execute`.
Now `deploy:post_revision` Capistrano task is shown in the output.
Thank you very much!
