### ISSUE TITLE
Why capistrano fails on ssh authentication ?

### ISSUE THREAD

**Issue by coderubyonrails** [capistrano/capistrano#1913]
The detailed of problem has been explained in below link, sorry for explanation mentioned in stackoverflow. 
 
https://stackoverflow.com/questions/45659362/why-capistrano-fails-during-rvm-version-check?noredirect=1#comment78290783_45659362

Thankyou all.

**Comment by leehambley** [comment]
GitHub issues are not for questions of this nature. Please read the `CONTRIBUTION` guidelines before deleting them.
