### ISSUE TITLE
Run capistrano with a seperate ruby to worked with current project bundler.

### ISSUE THREAD

**Issue by zw963** [capistrano/capistrano#1914]
Please see this issue, thanks

https://github.com/bundler/bundler/issues/5950

**Comment by zw963** [comment]
Maybe the properly question is:

How to use capistrano to run `bundle list` with a seperate traveling-ruby (independent the ruby which is used in project), anywhy, capistrano just a deployment tools, it should run any shell command as use with
shell, right? as following:

```sh
x=$(bundle list)
# or x=`bundle list`
echo "$x"
```

use with shell, it always work.

**Comment by mattbrictson** [comment]
Duplicate of https://github.com/bundler/bundler/issues/5950. Closing.
