### ISSUE TITLE
Capistrano deploy webpacker:install error - Webpack binstubs not found. Have you run rails webpacker:install ?

### ISSUE THREAD

**Issue by Austex** [capistrano/capistrano#1919]
I'm trying to deploy my app to digital ocean using capistrano and I keep getting this error.

Webpack binstubs not found.
Have you run rails webpacker:install ?
Make sure the bin directory or binstubs are not included in .gitignore

I have tried all the following to get it resolved:
`rake assets:precompile`
`rails webpacker:install`
`rake assets:precompile RAILS_ENV=production`
`rails webpacker:compile`
`bundle config --delete bin`
`rails app:update:bin`
`bundle install --binstubs`

My example test case is here in this Gist: https://gist.github.com/Austex/dd4ec3eb9547d55a96f389feb257c2ec

### Expected behavior
It should deploy but its getting hung up on the binstub for webpacker. Any ideas?

**Comment by leehambley** [comment]
https://github.com/rails/webpacker/issues/823

**Comment by leehambley** [comment]
Binstubs is a Bundler topic, if you elect to use Binstubs you'll need to consult their documentation, and the `rails/webpacker` issue you have opened. As you didn't provide a complete log we can't really help you.
