### ISSUE TITLE
Release Capistrano 3.10.0

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1942]
We are due for another Capistrano release according to our six-week cadence. Next up is 3.10.0. I think this warrants a minor version bump because there is some new behavior.

I'll do the release to Rubygems on Monday morning PDT if there are no objections.

---

https://github.com/capistrano/capistrano/compare/v3.9.1...HEAD

* [#1922](https://github.com/capistrano/capistrano/pull/1922): Prevents last good release from being deleted during cleanup if there are too many subsequent failed deploys
* As of this release, version 2.x of Capistrano is officially End of Life. No further releases of 2.x series are planned, and pull requests against 2.x are no longer accepted. The maintainers encourage you to upgrade to 3.x if possible.
* [#1937](https://github.com/capistrano/capistrano/pull/1937): Clarify error message when plugin is required in the wrong config file.
* [#1930](https://github.com/capistrano/capistrano/issues/1930): Default to locking the version using the pessimistic version operator at the patch level.

**Comment by leehambley** [comment]
Surprisingly amount of useful stuff in there. Thanks for taking care of the
release Matt.

**Comment by mattbrictson** [comment]
📦 https://rubygems.org/gems/capistrano/versions/3.10.0
