### ISSUE TITLE
Optional linked_files - only create symlink if file exists - do not throw error

### ISSUE THREAD

**Issue by kimwue** [capistrano/capistrano#1944]
Has this been discussed already? We would like to link our Symfony file config_local.yml, so its the same between all deployment folders. Although on other environments of the same project, this file is not needed at all.

Workaround: we create an empty config_local.yml on all other environments.

Would be nice if `set :linked_files` could have an "only if file exists" option.

Thanks,
Kim

**Comment by leehambley** [comment]
Why not add your own `set :optional_linked_files` with a simple task? We designed Capistrano to be extensible and self-documenting, just add something like this:

```
    desc "Symlink linked files"
    task :linked_files do
      next unless any? :linked_files
      on release_roles :all do
        execute :mkdir, "-p", linked_file_dirs(release_path)

        fetch(:linked_files).each do |file|
          target = release_path.join(file)
          source = shared_path.join(file)
          next if test "[ -L #{target} ]"
          execute :rm, target if test "[ -f #{target} ]"
          execute :ln, "-s", source, target
        end
      end
    end
  end
```

Taken from here https://github.com/capistrano/capistrano/blob/f79a386aadc5da27647a57014051098f5a1eba61/lib/capistrano/tasks/deploy.rake#L131-L146 to your own script and define your own behaviours.

Checking if the file exists is also done in deploy.rake and is trivially applied to your own use-case:

- https://github.com/capistrano/capistrano/blob/f79a386aadc5da27647a57014051098f5a1eba61/lib/capistrano/tasks/deploy.rake#L85-L97
