### ISSUE TITLE
Getting "LoadError: cannot load such file -- cap-ec2/capistrano" issue suddenly with Capistrano gem v3.4.1

### ISSUE THREAD

**Issue by ethicalmohit** [capistrano/capistrano#1949]
Hey,

We are getting below issue while deploying from Jenkins suddenly. However, I have already require the cap-ec2/capistrano plugin under CapFile.

Error:

cap dev deploy
WARNING: load:defaults has already been invoked and can no longer be modified.
Check that you haven't loaded a Capistrano plugin in deploy.rb by mistake.
Plugins must be loaded in the Capfile to initialize properly.
(Backtrace restricted to imported tasks)
cap aborted!
can't modify frozen #<Class:#Rake::Task:0x000000012a3bd0>
Caused by:
LoadError: cannot load such file -- cap-ec2/capistrano

Gemfile:
gem 'cap-ec2', '~> 1.0'

Any hint?

**Comment by leehambley** [comment]
You don't specify the Capistrano o version you're using which we ask for in
the issue template.

Likely you've just been "upgraded" to the stricter release Matt made last
week, did you check the change log?

**Comment by ethicalmohit** [comment]
@leehambley My bad. We are using Cap v3.8.2. Previously we were getting the version lock error like below.

Capfile locked in the version 3.4.1 but 3.8.2 is loaded then we have removed the lock and then this issue came.

I have also added it to CapFile. 

No, I haven't read the changelog yet. Let me do it now.

**Comment by leehambley** [comment]
Thanks, I don't recall exactly what we changed, I wasn't personally
involved, bit something about handling errors of this sort were discussed
at least.

Regardless of what you find in the change log, the error message tells you
exactly the problem, it's not safe to load plugins from stage files. I
think if you move the plugin include you ought to be fine.

**Comment by ethicalmohit** [comment]
@leehambley Yes, Its fixed for most of the projects. :)

**Comment by ethicalmohit** [comment]
@leehambley can you help me to load capistrano 3.8.1 and lock the same? Because I am getting issue with 3.10.0. 

I have created a new issue with detailed description over here: https://github.com/capistrano/capistrano/issues/1950
