### ISSUE TITLE
Getting error "fatal: Not a valid object name"

### ISSUE THREAD

**Issue by alienxp03** [capistrano/capistrano#1953]
I'm setting up [Samson](https://github.com/zendesk/samson) to make deployment easier for everyone in my team. However, most of the time the deployment would fail when it's trying to achieve. I keep getting ` fatal: Not a valid object name` error when it's trying to archive the repo in the `git:create_release` stage.

Just wondering if these issues are related?

[972](https://github.com/capistrano/capistrano/issues/972)
[https://github.com/capistrano/capistrano/pull/1826](1826)

### Steps to reproduce
Commands that I use in Samson is pretty straightforward.

```ruby
bundle install
bundle exec cap staging deploy
```

### Expected behavior
It should deploy to a staging server

### Actual behavior
Getting error
```
     02 git archive staging-feature/update_slackistrano-2017-11-23_09-48-04-1 | /usr/bin/env tar -x -f - -C /var/www/my-app-staging/releases/20171124082805
      02 fatal: Not a valid object name
      02 tar: This does not look like a tar archive
```

### System configuration
```

Environment

    Ruby     ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    Rubygems 2.6.10
    Bundler  1.16.0
    Command  /Users/azuan/Workspace/KFit/fave-deploy/cached_repos/7fac35551fc64ff0876e752f5c6dd498/artifacts/bundle/ruby/2.3.0/bin/cap staging doctor

Gems

    capistrano               3.10.0
    airbrussh                1.3.0
    rake                     11.3.0 (update available)
    sshkit                   1.15.0 (update available)
    net-ssh                  4.2.0
    capistrano-bundler       1.1.4  (update available)
    capistrano-db-tasks      0.4    (update available)
    capistrano-delayed-job   1.1.0
    capistrano-faster-assets 1.0.2  (update available)
    capistrano-gitflow       1.6.0
    capistrano-passenger     0.0.2  (update available)
    capistrano-rails         1.1.8  (update available)
    capistrano-rails-console 2.1.1  (update available)
    capistrano-rbenv         2.0.3  (update available)
    capistrano-sidekiq       0.20.0
```

**Comment by kevellis124** [comment]
What was the problem here?

**Comment by alienxp03** [comment]
I need to dig up to find the exact details. But from the top of my mind, the issue was with the cached repo. The `origin` was linked to local repo instead of the remote, so that's causing the issue above.

**Comment by alienxp03** [comment]
Can't help you much unfortunately since I'm not using it anymore. What I remembered, I had to run some custom git command in the before hook to update the origin. And it works after that. A bit hacky I guess, but works well. Just that I'm not using it anymore, so I can't help much with the code.

**Comment by 3eggert** [comment]
I found a solution here:
https://stackoverflow.com/a/23936586/1197085
**"I had the same issue, until I realized I was pulling the nonexistent branch from git."**
