### ISSUE TITLE
Unable to run a task to start Sinatra application

### ISSUE THREAD

**Issue by jedrekdomanski** [capistrano/capistrano#1955]
Hi, sorry for posting this here but on Stackoverflow I am getting no answer to my problem.
I have a simple Sinatra app which I run locally by running `rackup -p 9210' command and I want to write a capistrano task which, after deployment to my server, will start my Sinatra app just I would do locally.

Here'is my task:
desc 'Start application'
  task :start do
    on roles(:app), in: :sequence, wait: 5 do
      within '/my/app/folder/' do
        execute "rackup -p 9210"
    end
  end
end

but it throws an error `bash: rackup: command not found`
What am I missing here?

**Comment by leehambley** [comment]
https://stackoverflow.com/questions/11203024/rackup-command-not-found is your problem (pre-existing question on SO)

**Comment by jedrekdomanski** [comment]
I am not happy with this answer, because it does not solve my problem. I have tried `execute "rackup -p 9210"` but the same error occurs. I use rvm and bundler and when I do `execute "bundle exec rackup -p 9210"` it throws similar error `bash: bundle: command not found`

**Comment by mattbrictson** [comment]
Have you tried:

```ruby
execute :bundle, "exec rackup -p 9120"
```

**Comment by jedrekdomanski** [comment]
That kind of worked except that it keeps my local console busy with the process:
```
00:00 deploy:start
      01 /usr/local/rvm/bin/rvm default do bundle exec rackup -p 9210 &
      01 Puma starting in single mode...
      01
      01 * Version 3.11.0 (ruby 2.3.0-p0), codename: Love Song
      01
      01 * Min threads: 0, max threads: 16
      01
      01 * Environment: development
      01
      01 * Listening on tcp://localhost:9210
      01
      01 Use Ctrl-C to stop
      01
```
How do I make this command run permanently on the remote server?

**Comment by mattbrictson** [comment]
I would say that's beyond the scope of Capistrano and a more general conversation of long-running processes, daemons, etc. I suggest taking this to a more general forum like SO. Personally, I would never start a server process via Capistrano; instead I would use a process monitor like upstart, systemd, etc.

**Comment by jedrekdomanski** [comment]
Ok, thank you. I will try to figure this out.

2017-12-06 17:51 GMT+01:00 Matt Brictson <notifications@github.com>:
