### ISSUE TITLE
Declaring a `role` with no port number unexpectedly overrides existing `server` port number

### ISSUE THREAD

**Issue by stoivo** [capistrano/capistrano#1956]
### Steps to reproduce
I have a staging environment where I need to pass the port. The project user 3.4.1 and I upgraded to 3.10.1. I read the changelogs and did what I found necessary. 

```
server fetch(:domain), user: fetch(:user), roles: %w{web app db}, port: 2232

role :web, fetch(:domain)
role :app, fetch(:domain)
role :db, fetch(:domain), primary: true
```
It look like this and used to work. Now I am getting `ECONNREFUSED: Connection refused - connect(2) for x.x.x.x:22.
Which is pointing on the wrong port.
```
server fetch(:domain), user: fetch(:user), roles: %w{web app db}, port: 2232

role :web, fetch(:domain)
role :app, fetch(:domain)
role :db, fetch(:domain), primary: true
```
I change to 
```
server fetch(:domain), user: fetch(:user), roles: %w{web app db}, port: 2232

role :web, fetch(:domain), port: 2232
role :app, fetch(:domain), port: 2232
role :db, fetch(:domain), primary: true, port: 2232 
```
and all works.
Or I can do
```
options = fetch(:ssh_options)
set :ssh_options do
  options[:port] = 2232
  options
end

server fetch(:domain), user: fetch(:user), roles: %w{web app db}

role :web, fetch(:domain)
role :app, fetch(:domain)
role :db, fetch(:domain), primary: true # This is where Rails migrations will run
```
And this also works. 

### Expected behavior
I want to know that the expected behavior. I since I only define one server.

### System configuration
Please link to the output of `cap <stage> doctor` in a GitHub Gist.
https://gist.github.com/stoivo/da436ede81fbb4b9117547d818268229

Thanks for and awesome tool!

**Comment by mattbrictson** [comment]
Thanks for the report. I think this may indeed be a bug, but I also see a problem in your configuration.

You are specifying both `server` and `role`, which is redundant and potentially conflicting. The intention of the configuration DSL is that you should use either one system or the other.

In other words, you can use the `server` technique:

```ruby
server fetch(:domain), user: fetch(:user), roles: %w{web app db}, port: 2232, primary: true
```

Or the `role` technique:

```ruby
role :web, fetch(:domain), port: 2232, primary: true
role :app, fetch(:domain), port: 2232, primary: true
role :db, fetch(:domain), port: 2232, primary: true
```

Declaring both `role` and `server` at the at the same time will potentially lead to unexpected results, as you are seeing.

I almost always recommend the `server` method as it is usually more concise and intuitive.

**Comment by stoivo** [comment]
I wouldn't say that this is a bug. Thanks for clearing it up for me.
