### ISSUE TITLE
Git repository disappeared 🤷

### ISSUE THREAD

**Issue by atebit** [capistrano/capistrano#1961]
Any help on this would be stupendous because it doesn't make sense at all to me.

For, a seemingly non-reason, cap just lost the ability to see my git repo..

```
00:00 git:wrapper
      01 mkdir -p /tmp
    ✔ 01 deploy@45.32.91.107 0.245s
      Uploading /tmp/git-ssh-digiramp-production-atebit.sh 100.0%
      02 chmod 700 /tmp/git-ssh-digiramp-production-atebit.sh
    ✔ 02 deploy@45.32.91.107 0.250s
00:01 git:check
      01 git ls-remote git@github.com:adjustcreative/digiramp.git HEAD
      01 ERROR: Repository not found.
      01 fatal: Could not read from remote repository.
      01 Please make sure you have the correct access rights
      01 and the repository exists.

Caused by:
SSHKit::Command::Failed: git exit status: 128
git stdout: Nothing written
git stderr: ERROR: Repository not found.
fatal: Could not read from remote repository.
```

I've copied the line `git ls-remote git@github.com:adjustcreative/digiramp.git` and pasted directly into terminal and get this: 

```
git ls-remote git@github.com:adjustcreative/digiramp.gitatebit:digiramp atebit$ git ls-remote git@github.com:adjustcreative/digiramp.git
fa174f9d90d2b7fdfa20cf921d7e219bfda0d447	HEAD
905ac6f5b57d34c82e6955d503cfa802d43ff3d9	refs/heads/heroku_mods
fa174f9d90d2b7fdfa20cf921d7e219bfda0d447	refs/heads/master
22bee22ded9d347519146f7ea5a646fb7a4cc23e	refs/heads/vultr_mods
```
The ssh keys are valid, and added to both Github and locally with ssh-add.. 

Has anyone seen this issue before?

**Comment by leehambley** [comment]
> I've copied the line git ls-remote git@github.com:adjustcreative/digiramp.git and pasted directly into terminal and get this:

http://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/

Please try this. I highly doubt this is a Capistrano bug, and your question may better belong on StackOverflow or similar where people with experience not focused on Capistrano itself may be able to help you.

**Comment by atebit** [comment]
Ok thanks, we can close it out.

**Comment by leehambley** [comment]
Did you solve it, or find another solution, your answer may be valuable for future Caprinauts.

**Comment by mrudult** [comment]
I'm experiencing the same issue on my Ubuntu 20 server after doing an `apt-get upgrade`. Everything was working well before that. Quite strange.

@atebit Did you find a solution for this?

**Comment by mrudult** [comment]
Okay. I figured it out. On the remote server, a colleague of mine had created a public-private key pair. I deleted them and it worked.
