### ISSUE TITLE
Capistrano documentation should recommend require:false in Gemfile

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1963]
Capistrano gems shouldn't be loaded within a Rails app. They are intended to be used by the `cap` command, not within Rails itself. But Capistrano gems will indeed be loaded by Rails if a user follows the instructions in the README, which says to add this to the Gemfile:

```ruby
gem "capistrano", "~> 3.10"
```

I argue that the correct instruction is:

```ruby
gem "capistrano", "~> 3.10", require: false
```

The penalty for omitting `require: false` is marginally slower boot time and more memory consumption. But in some cases for poorly-written Capistrano plugins it can cause actual crashes like this: https://stackoverflow.com/q/48493332/4625365

I think our documentation should recommend users always add `require: false` for Capistrano-related gems as a general rule of thumb.

**Comment by mikegee** [comment]
I strongly agree, since cap's DSL is monkey-patched into the top level object.

**Comment by leehambley** [comment]
> But in some cases for poorly-written Capistrano plugins it can cause actual crashes like this: https://stackoverflow.com/q/48493332/4625365

Yikes, agreed!
