### ISSUE TITLE
different md5sum ?

### ISSUE THREAD

**Issue by keulu** [capistrano/capistrano#1966]
can someone explain me why my .tar.gz after deploy on 3 servers got 3 different md5sum ?

```
desc "Create archive"
    task :make_archive do
        on roles(:scripts_max) do
            execute [
                # compress
                "cd #{fetch(:deploy_to)}current",
                "tar -zcvf scripts_openwrt.tar.gz *",
                "sudo chown #{fetch(:www_user)}:#{fetch(:www_group)} scripts_openwrt.tar.gz",
                "sudo chmod #{fetch(:www_perms)} scripts_openwrt.tar.gz",
            ].join(' && ')
        end
    end
    before :finishing, :make_archive
```

i've got 3 différents checksum when i do `md5sum scripts_openwrt.tar.gz`, but dates, files size, files content are logically the sames no ?

**Comment by leehambley** [comment]
Unless your servers clocks are synchronized it's quite unlikely that your servers will all generate an exactly equal hash. 

For future such questions please use StackOverflow, the GitHub issue template you deleted when reporting the issue contains instructions on asking for help when not reporting a bug in Capistrano itself. Thanks

**Comment by keulu** [comment]
ok, thx for the tips, and sorry for asking on git.
