### ISSUE TITLE
DEPLOY FAILED rm: cannot remove '/home/app/papis/releases/20180219183240/config/database.yml': No such file or directory

### ISSUE THREAD

**Issue by tchirktema** [capistrano/capistrano#1967]
I need your help . When I run cap production deploy I obtain this error
(Backtrace restricted to imported tasks)
``cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host paroles.lyrics228.net: rm exit status: 1
rm stdout: rm: cannot remove '/'/home/app/papis/eleases/20180219183240/config/database.yml': No such file or directory
rm stderr: Nothing written

Caused by:
SSHKit::Command::Failed: rm exit status: 1
rm stdout: rm: cannot remove ''/home/app/papis/releases/20180219183240/config/database.yml': No such file or directory
rm stderr: Nothing written

Tasks: TOP => deploy:symlink:linked_files
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing on host exemple.net: rm exit status: 1
rm stdout: rm: cannot remove ''/home/app/papis/releases/20180219183240/config/database.yml': No such file or directory
rm stderr: Nothing written

** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:

  INFO [f6cfae90] Finished in 1.189 seconds with exit status 0 (successful).

  INFO [32a665de] Running /usr/bin/env ln -s '/home/app/papis/shared/config/database.yml '/home/app/papis/releases/20180219183240/config/database.yml as papis@IP_ADDRESS

 DEBUG [32a665de] Command: /usr/bin/env ln -s '/home/app/papis/shared/config/database.yml '/home/app/papis/releases/20180219183240/config/database.yml

 DEBUG [05424f41] 	rm: 

 DEBUG [05424f41] 	cannot remove ''/home/app/papis/releases/20180219183240/config/database.yml'

 DEBUG [05424f41] 	: No such file or directory

 DEBUG [05424f41] 	

  INFO [32a665de] Finished in 1.032 seconds with exit status 0 (successful).

 DEBUG [9f311409] Running [ -L '/home/app/papis/releases/20180219183240/config/secrets.yml ] as papis@IP_ADRESSS

 DEBUG [9f311409] Command: [ -L '/home/app/papis/releases/20180219183240/config/secrets.yml ]

 DEBUG [9f311409] Finished in 1.016 seconds with exit status 1 (failed).

 DEBUG [9ab7459e] Running [ -f '/home/app/papis/releases/20180219183240/config/secrets.yml ] as  papis@IP_ADRESSS

 DEBUG [9ab7459e] Command: [ -f '/home/app/papis/releases/20180219183240/config/secrets.yml ]

 DEBUG [9ab7459e] Finished in 1.000 seconds with exit status 0 (successful).

  INFO [9c14bbc0] Running /usr/bin/env rm '/home/app/papis/releases/20180219183240/config/secrets.yml as papis@IP_ADRESSS

 DEBUG [9c14bbc0] Command: /usr/bin/env rm'/home/app/papis/releases/20180219183240/config/secrets.yml

  INFO [9c14bbc0] Finished in 0.991 seconds with exit status 0 (successful).

  INFO [592a16ec] Running /usr/bin/env ln -s '/home/app/papis/shared/config/secrets.yml '/home/app/papis/releases/20180219183240/config/secrets.yml as  papis@IP_ADRESSS

 DEBUG [592a16ec] Command: /usr/bin/env ln -s '/home/app/papis/shared/config/secrets.yml '/home/app/papis/releases/20180219183240/config/secrets.yml

  INFO [592a16ec] Finished in 0.921 seconds with exit status 0 (successful).

**Comment by leehambley** [comment]
The issue template you deleted when filing this issue contained instructions on how and where to submit a proper bug report. This issue tracker is for issues with Capistrano itself, not support for learning, that is better handled on StackOverflow.com where this issue has been discussed many times. 

Please take the time to read the documentation and follow a guide, and if you are convinced that Capistrano is broken, check which plugin you are using and report an issue on the relevant plugin's GitHub page.

As your error message indicates your issue is with an absent `database.yml`, highly likely correlated to a Rails application deployment issue, and a common beginner problem.
