### ISSUE TITLE
TypeError: no _dump_data is defined for class Thread::Mutex

### ISSUE THREAD

**Issue by vassilevsky** [capistrano/capistrano#1969]
Hello :)

Here's my humble setup:

	Environment

	    Ruby     ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
	    Rubygems 2.6.12
	    Bundler  1.15.4
	    Command  /Users/vassilevsky/.rbenv/versions/2.3.1-p0/bin/cap staging doctor

	Gems

	    capistrano         3.10.1
	    airbrussh          1.3.0
	    rake               12.3.0
	    sshkit             1.16.0
	    net-ssh            4.2.0
	    capistrano-bundler 1.3.0
	    capistrano-rails   1.3.1
	    capistrano-rbenv   2.1.3

I'm getting this error when I try to deploy a project:

	cap aborted!
	TypeError: no _dump_data is defined for class Thread::Mutex
	/Users/vassilevsky/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.10.1/lib/capistrano/dsl.rb:76:in `dump'
	/Users/vassilevsky/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.10.1/lib/capistrano/dsl.rb:76:in `on'
	/Users/vassilevsky/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.10.1/lib/capistrano/tasks/deploy.rake:64:in `block (3 levels) in <top (required)>'
	/Users/vassilevsky/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
	/Users/vassilevsky/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
	/Users/vassilevsky/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
	/Users/vassilevsky/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/airbrussh-1.3.0/lib/airbrussh/rake/context.rb:62:in `execute'
	/Users/vassilevsky/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
	/Users/vassilevsky/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	<...many more lines are omitted as irrelevant...>

I have inspected the hosts being dumped:

	[#<Capistrano::Configuration::Server:0x007f8c72cc1fe0 
		@keys=[], 
		@local=false, 
		@user=nil, 
		@hostname="<...redacted...>", 
		@port=nil, 
		@properties=#<Capistrano::Configuration::Server::Properties:0x007f8c72cc1d38 
			@properties={}, 
			@roles=#<Set: {:web}>>, 
		@ssh_options={
			:known_hosts=>#<SSHKit::Backend::Netssh::KnownHosts:0x007f8c740b2428 
				@_mutex=#<Thread::Mutex:0x007f8c740b2388>, 
				@files={
					"~/.ssh/known_hosts"=>#<SSHKit::Backend::Netssh::KnownHostsKeys:0x007f8c741438d8 
						@_mutex=#<Thread::Mutex:0x007f8c74143888>, 
						@path="/Users/vassilevsky/.ssh/known_hosts", 
						@hosts_keys={
							"github.com"=>[#<OpenSSL::PKey::RSA:0x007f9ed0c2f558>],
							<...many more hosts...>
						}, 
						@hosts_hashes=[]>, 
					"~/.ssh/known_hosts2"=>#<SSHKit::Backend::Netssh::KnownHostsKeys:0x007f8c72d806e8 
						@_mutex=#<Thread::Mutex:0x007f8c72d80698>, 
						@path="/Users/vassilevsky/.ssh/known_hosts2", 
						@hosts_keys={}, 
						@hosts_hashes=[]>, 
					"/etc/ssh/ssh_known_hosts"=>#<SSHKit::Backend::Netssh::KnownHostsKeys:0x007f8c72d80350 
						@_mutex=#<Thread::Mutex:0x007f8c72d80300>, 
						@path="/etc/ssh/ssh_known_hosts", 
						@hosts_keys={}, 
						@hosts_hashes=[]>, 
					"/etc/ssh/ssh_known_hosts2"=>#<SSHKit::Backend::Netssh::KnownHostsKeys:0x007f8c74083a38 
						@_mutex=#<Thread::Mutex:0x007f8c740839e8>, 
						@path="/etc/ssh/ssh_known_hosts2", 
						@hosts_keys={}, 
						@hosts_hashes=[]>
				}>, 
			:logger=>#<Logger:0x007f8c740b2298 
				@progname=nil, 
				@level=4, 
				@default_formatter=#<Logger::Formatter:0x007f8c740b2270 @datetime_format=nil>, 
				@formatter=nil, 
				@logdev=#<Logger::LogDevice:0x007f8c740b21a8 
					@shift_size=nil, 
					@shift_age=nil, 
					@filename=nil, 
					@dev=#<IO:<STDERR>>, 
					@mon_owner=nil, 
					@mon_count=0, 
					@mon_mutex=#<Thread::Mutex:0x007f8c740b2158>>>, 
			:password_prompt=>#<Net::SSH::Prompt:0x007f8c73157de8>
		}, 
		@netssh_options={
			<...basically a copy of ssh_options...>
		}>]

So, the error is correct: the objects being dumped have mutexes inside, and they cannot be dumped.
Guess that RuboCop did not warn against Marshal.dump for no reason after all :D

This method has [tests](https://github.com/capistrano/capistrano/blob/master/spec/integration/dsl_spec.rb#L459). They all pass. And the reason for that is that the test server objects don't have mutexes inside them:

	[#<Capistrano::Configuration::Server:0x007fee1f220258 
		@keys=[], 
		@local=false, 
		@user=nil, 
		@hostname="example1.com", 
		@port=nil, 
		@properties=#<Capistrano::Configuration::Server::Properties:0x007fee1f221b58 
			@properties={:active=>true}, 
			@roles=#<Set: {:web}>>>, 
	<...a couple more servers...>]

I tried getting rid of mutexes:

```ruby
# config/deploy.rb

set :ssh_options, {
  known_hosts: nil,
  logger: nil
}
```

but then I get this error:

	/Users/vassilevsky/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.16.0/lib/sshkit/backends/connection_pool.rb:59:in `call': Passing nil, or [nil] to Net::SSH.start is deprecated for keys: known_hosts

I don't know what to do :)

**Comment by mattbrictson** [comment]
Hi, thanks for the detailed report!

I have not yet been able to reproduce this despite using the same versions of capistrano, sshkit, net-ssh, etc. However I am using Ruby 2.5.0, so perhaps this is something specific to Ruby 2.3.1. I'll continue to investigate.

In the meantime, this may be a workaround; can you try it?

```rb
# config/deploy.rb
set :ssh_options, known_hosts: Net::SSH::KnownHosts
```

**Comment by mattbrictson** [comment]
Just verified: Ruby 2.3.1 works fine for me as well.

Also, when I inspect the hosts that are being passed to `Marshall.dump`, like this:

```diff
--- a/lib/capistrano/dsl.rb
+++ b/lib/capistrano/dsl.rb
@@ -67,6 +67,7 @@ module Capistrano
 
     # rubocop:disable Security/MarshalLoad
     def on(hosts, options={}, &block)
+      puts Configuration.env.filter(hosts).inspect
       subset_copy = Marshal.dump(Configuration.env.filter(hosts))
       SSHKit::Coordinator.new(Marshal.load(subset_copy)).each(options, &block)
     end
```

I do not see any mutex:

```
[#<Capistrano::Configuration::Server:0x007f869c404a78 @keys=[], @local=false, @user="deployer", @hostname="REDACTED", @port=nil, @properties=#<Capistrano::Configuration::Server::Properties:0x007f869c404730 @properties={}, @roles=#<Set: {:app, :backup, :cron, :db, :redis, :sidekiq, :web}>>>]
```

 Can you post your `deploy.rb` and `staging.rb` (with any sensitive information redacted)? Perhaps you are interacting with the Capistrano DSL in some way that is causing different output than I am seeing.

**Comment by mattbrictson** [comment]
I see this issue has many 👍's but no further comments. Can anyone provide further detail or reproduction steps?

**Comment by vassilevsky** [comment]
Thanks, Matt. Looks like this is something in my config. I haven't found the problem yet. I will open another issue if required.

**Comment by urbanautomaton** [comment]
FWIW, and for anyone else encountering this error, we experienced it in our app and I've constructed a [minimal reproduction here](https://github.com/urbanautomaton/cap-mutex-repro).

In short, it seemed to be caused by having `include SSHKit::DSL` in some of our task namespaces. Removing this fixed the bug with no apparent ill effects (as of Capistrano 3.11.0).
