### ISSUE TITLE
Opt out of warning if a task is skipped because of re-invocation

### ISSUE THREAD

**Issue by axsuul** [capistrano/capistrano#1970]
Are we accepting pull requests to disable the following warning?

```
If you really meant to run this task again, use invoke!("rails:docker:build")
THIS BEHAVIOR MAY CHANGE IN A FUTURE VERSION OF CAPISTRANO. Please join the conversation here if this affects you.
https://github.com/capistrano/capistrano/issues/1686
```

Due to the way I've developed my tasks, they sometimes overlap but I'd still like them to only be invoked once. Or is there a better way to check if the task has been invoked before invoking?

**Comment by mattbrictson** [comment]
We may tweak the working of the warning, but I don't see us removing it right now.

> is there a better way to check if the task has been invoked before invoking?

Assuming you are using Rake 11 or newer, you can do this:

```ruby
invoke("rails:docker:build") unless Rake::Task["rails:docker:build"].already_invoked
```

**Comment by axsuul** [comment]
@mattbrictson Thanks!

Defined this helper method for future reference

```ruby
def invoke_once(task)
  invoke(task) unless Rake::Task[task].already_invoked
end
```
