### ISSUE TITLE
any? DSL raises "ArgumentError: wrong number of arguments"

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1974]
```
Failures:

  1) Capistrano::DSL checking for presence variable exists, is not an array 
     Failure/Error:
       def any?(key)
         value = fetch(key)
         if value && value.respond_to?(:any?) && value.method(:any?).arity < 1
           value.any?
         else
           !fetch(key).nil?

     ArgumentError:
       wrong number of arguments (given 0, expected 1)
     # ./lib/capistrano/configuration.rb:47:in `any?'
     # ./lib/capistrano/configuration.rb:50:in `any?'
     # ./spec/integration/dsl_spec.rb:386:in `block (3 levels) in <top (required)>'
     # ./spec/integration/dsl_spec.rb:405:in `block (4 levels) in <top (required)>'
```

This seems to be a test ordering issue.

Using Ruby 2.4.3, I can consistently reproduce using the following seed:

```
$ bundle exec rspec --seed 50238
```

**Comment by will-in-wi** [comment]
I cannot reproduce with the same version of Ruby on my local box… I wonder whether a specific version of a dependency is in play…

**Comment by mattbrictson** [comment]
```
$ bundle exec rspec --seed 50238 --bisect
Bisect started using options: "--seed 50238"
Running suite to find failures... (1.37 seconds)
Starting bisect with 1 failing example and 392 non-failing examples.
Checking that failure(s) are order-dependent... failure appears to be order-dependent

Round 1: bisecting over non-failing examples 1-392 .. ignoring examples 197-392 (1.91 seconds)
Round 2: bisecting over non-failing examples 1-196 .. ignoring examples 99-196 (1.85 seconds)
Round 3: bisecting over non-failing examples 1-98 . ignoring examples 1-49 (0.7288 seconds)
Round 4: bisecting over non-failing examples 50-98 . ignoring examples 50-74 (0.69932 seconds)
Round 5: bisecting over non-failing examples 75-98 .. ignoring examples 87-98 (1.32 seconds)
Round 6: bisecting over non-failing examples 75-86 .. ignoring examples 81-86 (1.33 seconds)
Round 7: bisecting over non-failing examples 75-80 . ignoring examples 75-77 (0.65938 seconds)
Round 8: bisecting over non-failing examples 78-80 .. ignoring example 80 (1.3 seconds)
Round 9: bisecting over non-failing examples 78-79 . ignoring example 78 (0.69808 seconds)
Bisect complete! Reduced necessary non-failing examples from 392 to 1 in 11.11 seconds.

The minimal reproduction command is:
  rspec ./spec/integration/dsl_spec.rb[1:4:3:1] ./spec/lib/capistrano/application_spec.rb[1:8] --seed 50238
```

**Comment by mattbrictson** [comment]
The Ruby version does not seem to make a difference. I am using this Gemfile.lock: https://gist.github.com/mattbrictson/2f273794045f3fd453afa2b478735f71

**Comment by mattbrictson** [comment]
Just to be clear: this is not isolated to our testing environment. This is a legitimate bug. This simple `deploy.rb` for example causes a crash:

```ruby
set :foo, Object.new
any? :foo # => ArgumentError: wrong number of arguments (given 0, expected 1)
```

**Comment by will-in-wi** [comment]
With your Gemfile.lock, I was able to reproduce. I took the diff between your failing `Gemfile.lock` and my working one. Then I bisected the offending project. This commit in Mocha broke it: https://github.com/freerange/mocha/commit/befb416021b08d663b78024e6537680d93c64ac3 The parent commit works, this commit fails.

**Comment by mattbrictson** [comment]
Thanks, that explains why this started failing in CI. That's good that we can both reproduce this.

That said, I don't think mocha is at fault. This is an actual Capistrano bug that we need to fix. Is there something else I need to do before we can merge #1975?

**Comment by will-in-wi** [comment]
Two questions before merge:

1. What do you think about my suggestion in the PR of `value.method(:any?).parameters == []` instead of the rescue?
2. Why do you think it is a bug in Capistrano? I haven't spent nearly as much time in this as you have, so an answer of "trust me" would be enough. :)

**Comment by will-in-wi** [comment]
Nevermind on 1, you just responded

**Comment by mattbrictson** [comment]
Well, I don't think the `any?` DSL method should raise an exception under any circumstances. It is simply supposed to check whether or not a variable of that name is set, and additionally, if that variable has an array-like value, whether that value is empty.

Right now if the variable is set to a non-array, it just blows up, [per my comment above](https://github.com/capistrano/capistrano/issues/1974#issuecomment-377960463).

```ruby
set :foo, Object.new
any? :foo # => ArgumentError: wrong number of arguments (given 0, expected 1)
```

**Comment by will-in-wi** [comment]
Makes sense. Thanks for explaining! Merging…

**Comment by chase439** [comment]
I'm getting the same error as the subject of this issue. Is there a fix?

My test is as simple as: `expect("foo").to include("bar")`
