### ISSUE TITLE
Release cleanup fails locally 

### ISSUE THREAD

**Issue by gonzoinc** [capistrano/capistrano#1979]
I run a deploy to a local staging test env the cleanup process fails with the below error:

````
DEBUG [45e8d81a] Running /usr/bin/env ls -x /Library/WebServer/Documents/faces_staging/releases on 127.0.0.1
 DEBUG [45e8d81a] Command: /usr/bin/env ls -x /Library/WebServer/Documents/faces_staging/releases
 DEBUG [45e8d81a]       20180426125410 20180426125440 20180426142907 20180426143153 20180426143509
20180426143538 20180426143659 20180426143721 20180426143811 20180426143921
20180426144219 20180426175342
 DEBUG [45e8d81a] Finished in 0.022 seconds with exit status 0 (successful).
  WARN Skipping cleanup of invalid releases on 127.0.0.1; unexpected foldername found (should be timestamp)
````

When I run the production instance and push to the actual production server the releases are cleaned up correctly as defined by :keep_release.  I have checked all folder and user permissions and they are all correct. This is all done locally on a Mac OSX 10.11.16.

deploy.rb
```
# config valid for current version and patch releases of Capistrano
lock "~> 3.10.2"

set :application, "faces"

set :repo_url, "git@gitlab.XXXXXXXXXXXX.git"
set :branch, 'master'

set :format, :pretty
set :pty, true
set :keep_releases, 2

append :linked_dirs, "images"
```

staging.rb file
```
set :stage, :staging
role :app, %w{127.0.0.1}

server '127.0.0.1', user: ENV['CAP_USER'], roles: %w{app}

set :deploy_to, "/Library/WebServer/Documents/staging/"

SSHKit.config.command_map[:bash] = "/bin/bash"
SSHKit.config.command_map[:composer] = "/usr/local/php5-5.6.30-20170213-115230/bin/php /usr/local/bin/composer.phar"
  

#Deploy tasks
namespace :deploy do

  desc "Update composer dependencies"
  task :composer_install do
    on roles(:app) do

        within release_path do
            info "Running composer"
            execute 'composer', 'install', '--no-dev', '--optimize-autoloader'
        end
    end
  end
  
  after :updated, "deploy:composer_install"
end
```

LMK if there is anything else I need to supply. I have been searching for some time and not finding much at all on the "unexpected foldername found" error.

Thanks,

**Comment by mattbrictson** [comment]
@gonzoinc did you figure out what the problem was?

**Comment by gonzoinc** [comment]
Nope, releases folder currently contains the following folders and nothing more. All are 14 digits long. 

```
20180426125410
20180426143153
20180426143659
20180426143921
20180426190358
20180430192515
20180501123043
20180521184927
20180521185746
20180525181623
20180426125440
20180426143509
20180426143721
20180426144219
20180430191855
20180430192534
20180501151227
20180521185118
20180521191521
20180525181710
20180426142907
20180426143538
20180426143811
20180426175342
20180430192350
20180430192600
20180501151447
20180521185233
20180525181517
20180525182022
```

**Comment by will-in-wi** [comment]
@gonzoinc Could you try adding the following snippet to your `config/deploy.rb` and then run `bundle exec cap production temp_testing:cleanup` (modify `production` if you are using a different environment).

```ruby
namespace :temp_testing do
  desc "Clean up old releases"
  task :cleanup do
    on release_roles :all do |host|
      releases = capture(:ls, "-x", releases_path).split
      valid, invalid = releases.partition { |e| /^\d{14}$/ =~ e }

      puts "There are #{valid.count} valid entries"
      puts "There are #{invalid.count} invalid entries"
      if invalid.any?
        puts "invalid.any? returned true"
        invalid.each do |e|
          puts "Invalid entry: #{e.inspect}"
        end
      end
    end
  end
end
```

**Comment by pareeohnos** [comment]
Sorry to hijack but having exactly the same problem right now. I've done some digging and inspected the `releases` variable and it seems that it's failing to split things correctly, so `invalid` actually contains tab chars and new line chars so technically are wrong. And in some cases it hasn't actually split them at all. I modified my locally installed gem slightly and added the following debug lines

```
puts "RAW #{capture(:ls, "-x", releases_path)}"
puts "RELEASE #{releases}"
```

And I'm getting the following output:

```
RAW 20190213095014	20190213101751	20190213115146	20190213162813	20190214095224
20190214134828	20190215135857	20190215143359	20190215144729	20190215151152
20190215152609	20190215153536	20190215171444	20190215172943	20190218135034
20190218150454	20190218155104

RELEASE ["20190213095014\t20190213101751\t20190213115146\t20190213162813\t20190214095224", "\n20190214134828\t20190215135857\t20190215143359\t20190215144729\t20190215151152", "\n20190215152609\t20190215153536\t20190215171444\t20190215172943\t20190218135034", "\n20190218150454\t20190218155104"]
```

As you can see, the releases array has been split incorrectly so it's not surprising that the partition call isn't working as expected

**Comment by mattbrictson** [comment]
@pareeohnos what is the value of `$;` in your Ruby environment? By default it is `nil`, which will cause `split` with no arguments to split based on whitespace. Based on your output my guess is that your environment is different, hence the odd behavior you are seeing.

```ruby
puts "RAW #{capture(:ls, "-x", releases_path)}"
puts "RELEASE #{releases}"
puts $;.inspect
```

In any case, I agree that we should change the code to `split(" ")` because that removes any implicit dependence on `$;`. Would you be interested in opening a PR?

Thanks for digging into this and reporting your results!

**Comment by pareeohnos** [comment]
@mattbrictson That statement is giving me `nil` as well so doesn't seem to be that. Is it possible that a different shell might cause the result of the `capture` to be slightly different? Our staging server is running `zsh` so not sure if that's interfering at all?

Yeah would be happy to open a PR for this :)

**Comment by mattbrictson** [comment]
`split` and `split(' ')` should behave identically, so I am confused why changing that makes a difference.

```
$ irb
>> "20190213095014\t20190213101751\t20190213115146\t20190213162813\t20190214095224".split
[
    [0] "20190213095014",
    [1] "20190213101751",
    [2] "20190213115146",
    [3] "20190213162813",
    [4] "20190214095224"
]
>> "20190213095014\t20190213101751\t20190213115146\t20190213162813\t20190214095224".split(" ")
[
    [0] "20190213095014",
    [1] "20190213101751",
    [2] "20190213115146",
    [3] "20190213162813",
    [4] "20190214095224"
]
```

**Comment by mattbrictson** [comment]
Perhaps you are right, that `zsh` on the server is the problem. Is `ls -x` outputting in color, for example? Those non-printable characters might be screwing things up. Maybe try this, so you can see the non-printable characters:

```ruby
puts "RAW #{capture(:ls, "-x", releases_path)}".inspect
```

**Comment by pareeohnos** [comment]
I've done a little more digging, and it's really strange behaviour but it seems the issue only comes up when there are enough releases that `ls` returns its result over multiple lines. At that point, the result of it contains `\n` and `\t` chars which is what appears to be messing it up. As a test I added in some extra files into the releases directory and tried the following:

```
releases = "2018000000000\t20180000000000\t20180000000001\t20180000000002\t20180000000003\n20180000000004\t20180000000005\t20180000000006\t20180000000007\t20180000000008\n20180000000009\t20180000000010\t20190215171444\t20190215172943\t20190218135034\n20190218150454\t20190218155104"

puts a.split
[
  [0] "2018000000000\t20180000000000\t20180000000001\t20180000000002\t20180000000003",
  [1] "\n20180000000004\t20180000000005\t20180000000006\t20180000000007\t20180000000008",
  [2] "\n20180000000009\t20180000000010\t20190215171444\t20190215172943\t20190218135034",
  [3] "\n20190218150454\t20190218155104"
]

puts a.split(' ')
[
  [ 0] "2018000000000",
  [ 1] "20180000000000",
  [ 2] "20180000000001",
  [ 3] "20180000000002",
  [ 4] "20180000000003",
  [ 5] "20180000000004",
  [ 6] "20180000000005",
  [ 7] "20180000000006",
  [ 8] "20180000000007",
  [ 9] "20180000000008",
  [10] "20180000000009",
  [11] "20180000000010",
  [12] "20190215171444",
  [13] "20190215172943",
  [14] "20190218135034",
  [15] "20190218150454",
  [16] "20190218155104"
]
```

I'm not sure why `split` and `split(' ')` are different - as you say they should behave identically but something here isn't right

**Comment by mattbrictson** [comment]
That `split` behavior is truly bizarre. What is the `a` variable in your example? Shouldn't it be `releases.split`?

I'm also curious what you get for these:

```ruby
a.class # => String < Object
a.method(:split).source_location # => nil
```

**Comment by pareeohnos** [comment]
Oh sorry that is meant to be `releases`. I had put `a` in my actual test since I'm lazy and just forgot to correct those when I pasted the output. But good call on the `source_location`. Turns out we've got some legacy code which is monkey patching the `String` class and replacing the `split` method, and even though it appears that whoever set it up used slightly different arguments to the ruby default which is causing the issues. Instead of setting the first argument to `$;` it is set to the regex pattern `/$/` which if you put into the default split implementation causes the strang behaviour I've been seeing.

So after all that, turns out to be a bug in our app not capistrano

**Comment by leehambley** [comment]
> Turns out we've got some legacy code which is monkey patching the `String` class and replacing the `split` method, and even though it appears that whoever set it up used slightly different arguments to the ruby default which is causing the issues.

If you're on a new enough version of Ruby and don't feel like lobotomising the legacy code just yet, you might think about fencing it in with refinements https://docs.ruby-lang.org/en/2.4.0/syntax/refinements_rdoc.html to reduce the scope leak of your string monkey patch?

**Comment by pareeohnos** [comment]
Ah I'd forgotten about them. Though fortunately the code is so old I'm pretty certain it's not being used so will just rip it out :)
