### ISSUE TITLE
SSHKit::Runner::ExecuteError: Exception while executing on host xx.xx.xx.xx: connection closed by remote host

### ISSUE THREAD

**Issue by vvsmanoharvadapalli** [capistrano/capistrano#1983]
Hi there,

We are implementing capistrano for our rails application(Rails 5 + aws + ruby 2.3.1 + capistrano 3). But I'm getting the following error while I execute the following command.
`cap production deploy`

> SSHKit::Runner::ExecuteError: Exception while executing on host xx.xx.xx.xx: connection closed by remote host

deploy.rb

`server 'my aws server ip', port: 3000, roles: [:web, :app, :db], primary: true`
`set :repo_url,        'git@github.com:myusername/myrepo.git'`
`set :application,     'myapp'`
`set :user,            'ubuntu'`
`set :puma_threads,    [4, 16]`
`set :puma_workers,    0`
`set :pty,             true`
`set :use_sudo,        false`
`set :stage,           :production`
`set :deploy_via,      :remote_cache`
`set :deploy_to,       "/home/#{fetch(:user)}/apps/#{fetch(:application)}"`
`set :puma_bind,       "unix://#{shared_path}/tmp/sockets/#{fetch(:application)}-puma.sock"`
`set :puma_state,      "#{shared_path}/tmp/pids/puma.state"`
`set :puma_pid,        "#{shared_path}/tmp/pids/puma.pid"`
`set :puma_access_log, "#{release_path}/log/puma.error.log"`
`set :puma_error_log,  "#{release_path}/log/puma.access.log"`
`set :ssh_options, { forward_agent: true, user: fetch(:user), keys: %w(~/.ssh/id_rsa) }`
`set :puma_preload_app, true`
`set :puma_worker_timeout, nil`
`set :puma_init_active_record, true  # Change to false when not using ActiveRecord`
`namespace :puma do`
`  desc 'Create Directories for Puma Pids and Socket'`
`  task :make_dirs do`
`    on roles(:app) do`
`      execute "mkdir #{shared_path}/tmp/sockets -p"`
`      execute "mkdir #{shared_path}/tmp/pids -p"`
`    end`
`  end`
``
`  before :start, :make_dirs`
`end`
`namespace :deploy do`
`  desc "Make sure local git is in sync with remote."`
`  task :check_revision do`
`    on roles(:app) do`
`      unless `git rev-parse HEAD` == `git rev-parse origin/master``
`        puts "WARNING: HEAD is not the same as origin/master"`
`        puts "Run `git push` to sync changes."`
`        exit`
`      end`
`    end`
`  end`
`  desc 'Initial Deploy'`
`  task :initial do`
`    on roles(:app) do`
`      before 'deploy:restart', 'puma:start'`
`      invoke 'deploy'`
`    end`
`  end`
`  desc 'Restart application'`
`  task :restart do`
`    on roles(:app), in: :sequence, wait: 5 do`
`      invoke 'puma:restart'`
`    end`
`  end`
`  before :starting,     :check_revision`
`  after  :finishing,    :compile_assets`
`  after  :finishing,    :cleanup`
`  after  :finishing,    :restart`
`end`

deploy/production.rb

`set :user, "ubuntu"`
`server "my aws ip", port: 3000, roles: [:app, :web, :db], :primary => true `
`set :ssh_options, { forward_agent: true, user: fetch(:user), keys: %w(~/.ssh/id_rsa) }`

Gemfile

`gem 'capistrano',         require: false`
`gem 'capistrano-rvm',     require: false`
`gem 'capistrano-rails',   require: false`
`gem 'capistrano-bundler', require: false`
`gem 'capistrano3-puma',   require: false`

Please help me getting out of this. 
Ty

**Comment by leehambley** [comment]
Please try asking at StackOverflow, the issue `connection closed by remote host` means that either  `github.com:myusername/myrepo` is not accessible and GitHub closed the connection, or that your server itself closed the SSH connection.

We try and keep this issue tracker free of support issues as we just don't have the capacity to help everyone with their unique problems and setups, StackOverflow has many much more gifted people who can help you.

**Comment by vvsmanoharvadapalli** [comment]
Thanks for your reply.
It's a private repo and we replaced the repo and usernames with "myrepo" and "myusername".
