### ISSUE TITLE
Reported vulnerability from GitHub scanner for Nokogiri in docs/

### ISSUE THREAD

**Issue by leehambley** [capistrano/capistrano#1986]
@mattbrictson @will-in-wi I'm not sure what to do here, we have a transient dependency on Nokogiri via transient dependencies in the "github-pages" gem. 

I don't trust upgrading GitHub pages gem and the rest of the world we pull in with it to render the docs faithfully.

If we agree we care about the vulnerability (I don't see how we can be affected, it's an injection attack with crafted tags which can then compromise the host. The injection attack would require someone getting code into our repo, which we would notice, and the "attack" is against sandboxed GitHub pages rendering services/servers. Risk is **low** as far as I can read it.)

**Comment by will-in-wi** [comment]
I'll take a look at it. We may be able to just update Nokogiri and not impact the rest of the rendering pipeline. If not, I'll render it both ways and compare.

**Comment by leehambley** [comment]
It suggested to upgrade the Gemfile.lock, but because nokogiri is mentioned twice, both times transiently a simple `= 1.8.1` to `~> 1.8.2` made me a bit nervous, I'm from the school or never screwing manually with gemfile.lock after bad experiences.

**Comment by will-in-wi** [comment]
Running `bundle update nokogiri` only changes Nokogiri on my box. I doubt it'll affect anything, but I'm going to run a Jekyll build with old nokogiri, upgrade, rebuild, and diff to confirm.

**Comment by leehambley** [comment]
Ah, nice - that's cool. I ran into a bunch of problems ("can't build native extension…") and ran out of time to test it and wanted to check with you guys that we agreed on a direction.

**Comment by will-in-wi** [comment]
The diff comes out empty. I pushed the branch here: https://github.com/capistrano/capistrano/pull/1987

**Comment by will-in-wi** [comment]
I'll take a few minutes to upgrade the entire docs tree and diff it later.
