### ISSUE TITLE
Restart Puma Server Won't Read New Environment Variables

### ISSUE THREAD

**Issue by lzhang-location** [capistrano/capistrano#1989]
*Steps to reproduce

    1. On Linux Ubuntu 16.04 updated .bashrc with Export MY_NEW_VARIABLE=new value

    2. Used Capistrano deployed the application, which include "restart" puma

    3.The MY_NEW_VARIABLE is not visible to application running on. puma

    4. As a work-around, if I "stop" puma, and "start" puma, the new env variable will be pick up by puma

Expected behavior

Puma application should recognize new environment variables in .bashrc etc,

Actual behavior

New environment variable should be picked up by app running on puma
System configuration

Ruby 2.3.3.:
**Rails version 5.1.2 **:
**Puma version 3.8.1 **
Capistrano 3

**Comment by leehambley** [comment]
Capistrano doesn't have any built in support for working with Puma, I'd suggest you check with the author of the plugin you are using.

Best guess, you talk about restarting puma, but then reference *shell* startup files. This guide may help http://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/

In future please read the issue template before deleting it. The things we ask for are specifically honed after years of helping people solve their problems. With the information we have at hand, it seems like you haven't quite understood the relationship between the shell, your process and capistrano and it's modes over SSH.
