### ISSUE TITLE
deploy:migrate fails if db/schema.db is missing.

### ISSUE THREAD

**Issue by acesuares** [capistrano/capistrano#1991]
### Steps to reproduce
Remove db folder, or put it in .gitignore
then do 'cap production deploy'
### Expected behavior
Deployment
### Actual behavior

````
Tasks: TOP => deploy:migrate
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as user@server: Exception while executing as user@server: rake exit status: 1
rake stdout: Nothing written
rake stderr: rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /var/www/App/releases/20180624112354/db/schema.rb
````

### System configuration
https://gist.github.com/acesuares/a5cb99884c528cee72223a328558579b

**Comment by will-in-wi** [comment]
This is as expected. If the Capistrano rails migration task is called, and is fails, it is expected that the deployment fails. This isn't Capistrano behavior, this is how the rails migration take task behaves. If you don't want to run migrations, there are instructions for omitting that part of the deployment here: https://github.com/capistrano/rails

**Comment by acesuares** [comment]
Thanks! Didn't know that.
