### ISSUE TITLE
Accessing stage variables in deploy.rb

### ISSUE THREAD

**Issue by mcg** [capistrano/capistrano#2004]
### Steps to reproduce
Set a custom variable in a stage:

`set :stagevar, 'this is a stage'`

Access this variable in deploy.rb:

`set :deployvar, -> { fetch(:stagevar) }`

### Expected behavior
Using `fetch(:deployvar)` in `deploy.rb` should contain the contents of the `:stagevar` variable.

### Actual behavior
`:deployvar` is `nil`

Basically I am trying to do this, https://capistranorb.com/documentation/faq/how-can-i-access-stage-configuration-variables/. 

Without accessing variable(`:deployvar`) in `deploy.rb`, `cap <stage> doctor` shows that it has the correct value, from the `:stagevar`. If I use/fetch the variable in `deploy.rb` and run `doctor` it's `nil`. Thinking that it may be Ruby or Cap version dependent, I've tried over several versions of both, with the same result.

Very sorry if this isn't a bug and I am just using this wrong, but I spent a bunch of time looking and it seems like a bug.

**Comment by mattbrictson** [comment]
Capistrano loads `deploy.rb` first, then it loads the stage that was specified on the command-line.

In your example, `fetch(:deployvar)` is indirectly calling `fetch(:stagevar)`, so it is the same as if you had just written `fetch(:stagevar)`. If you do this at the top level of `deploy.rb`, this will return `nil`, as you've seen. That's because the stage file hasn't been loaded yet. That is expected behavior.

Capistrano intends for you to use `fetch` within a `task` definition or within a deferred block (i.e. `-> { ... }`). A bare `fetch` at the top level is something you should never need to do in practice.

**Comment by mattbrictson** [comment]
You can see the load order here:

https://github.com/capistrano/capistrano/blob/7921fe6f8e70d6bfc85e4f0b9023ac7d491195ae/lib/capistrano/setup.rb#L27-L28

**Comment by mcg** [comment]
Docs at https://capistranorb.com/documentation/faq/how-can-i-access-stage-configuration-variables/ seems to say I can do this tho. So you can't use a custom variable set in a stage in deploy.rb.

**Comment by mattbrictson** [comment]
Yes, you can.

```ruby
# deploy/production.rb
set :greeting, "hello production"
```

```ruby
# deploy/staging.rb
set :greeting, "hello staging"
```

```ruby
# deploy.rb
task :greet do
  puts fetch(:greeting)
end
```

```
$ cap production greet
hello production

$ cap staging greet
hello staging
```

**Comment by mcg** [comment]
Now if I could only set that task as a default `before` every other task, which afaik isn't possible and what had me trying to do what generated this ticket. Anyhow, HUGE thanks for the info/help and sorry for the noise here.

**Comment by mcg** [comment]
I am refactoring an existing cap that uses a ton of custom namespaces/tasks. I would need to hook into them all for that. Originally I hoped to set a var in the stage to "go down the refactored path", but it looks like I'll need to use an ENV var for this. Which I had wanted to avoid.

**Comment by leehambley** [comment]
@mcg  it's perhaps somewhat off topic for this thread, but you should be able to programatically add a prerequisite for all tasks, or monkeypatch `Rake::Task`. 

Capistrano is based on Rake, if you look into the code Capistrano is just a subclassed `Rake::Application` and you can leverage the hints listed here to metaprogram against the taskset:

- https://ruby.github.io/rake/doc/rakefile_rdoc.html#label-Accessing+Task+Programmatically

We can't _really_ support that, you're pretty much going off-road, but it ought to be doable. Caveat that the load order might bite you if you monkeypatch or metaprogram too early (but Matt's notes above ought to help you find the right place to hook in)
