### ISSUE TITLE
Custom double dash argument?

### ISSUE THREAD

**Issue by gonace** [capistrano/capistrano#2007]
Hi
I've been searching for a solution to add custom "double dash" arguments to Capistrano but have failed. Is there any to do this?

We are running Ruby 2.4.2 and Puma with phased-restarts but at some point, we want to restart the puma processes.

So we'd like to add a double dash argument "--with-restart" so that we can tell the task to restart the puma application server instead of the phased-restart.

Regards

**Comment by mattbrictson** [comment]
There is not really an extension mechanism in capistrano for adding command line options.

However capistrano is based on rake, which does have a feature where you can specify arguments in the form of environment variables. So you could do this:

```
cap production deploy WITH_RESTART=1
```

And then in your task you could use that variable like this:

```ruby
if ENV["WITH_RESTART"]
  # do something here
end
```

Does that help?

**Comment by gonace** [comment]
Hi
Yes, that will be fine for us, thanks @mattbrictson
