### ISSUE TITLE
Security Certificate Issues

### ISSUE THREAD

**Issue by charlieartist** [capistrano/capistrano#2015]
In setting up the local build on a new machine, I went to install Capistrano via Ruby using\ `gem install capistrano`

Upon doing this, was met with this error:
`ERROR:  Could not find a valid gem 'capistrano' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)`

Is there any plan to address this issue?

**Comment by leehambley** [comment]
This is a problem with your ruby version,and /or the certificates on
rubygema.org.

I'm on mobile right now,.but I believe the solution was newer Rubygems gem
downloaded from your browser and installed by hand, then it should work.

**Comment by leehambley** [comment]
https://guides.rubygems.org/ssl-certificate-update/

**Comment by charlieartist** [comment]
@leehambley Thank you. I cleared out my Ruby installs, and reinstalled. Am now running.
