### ISSUE TITLE
deploy:cleanup fails when there are a lot of releases 

### ISSUE THREAD

**Issue by azin634** [capistrano/capistrano#2026]
This came up for me when I was cleaning up one of our projects that for some reason was never cleaned before. It had about 5000 releases. The error I was getting was `argument list too long`.

### Expected behavior
releases should be cleaned up 

### Actual behavior
argument list too long error

I would love to submit a PR to fix this if it helps. I was thinking of just slicing up the releases by some number N and executing them separately. I already tested this and it works.

**Comment by leehambley** [comment]
Good catch, and thank you for the report @azin634 !

Your proposed solution sounds good, before you go away hacking it up I'd like to draw your attention to POSIX `getconf` and the conf value `ARG_MAX` (`$ getconf ARG_MAX`) which is system dependent.

You could easily `capture()` this value and use it as a basis for knowing how to split up the string into chunks the shell is willing and able to accept.

- https://linux.die.net/man/1/getconf
- https://pubs.opengroup.org/onlinepubs/009695399/basedefs/limits.h.html

Alternatively if you don't want to go down that path, we may be able to accept something that deletes releases in reasonably sized batches (say, 100?)

I'm sure @mattbrictson and @will-in-wi would share my reluctance to add a user-visible configuration parameter, so if we go the path of picking a magic number for the number of releases to delete, without querying `getconf` then we should strive to choose a default that does not require us to expose the configuration option.

What do you all think?

**Comment by leehambley** [comment]
Absolutely @azin634 I think the `ARG_MAX` is the _correct_ solution to be portable and reliable, but honestly taking a magic number of releases and deleting them is probably good enough for everyone, and we'd take that patch.
