### ISSUE TITLE
Deployment Failure - Webpacker assets:precompile

### ISSUE THREAD

**Issue by alliedarmour** [capistrano/capistrano#2039]
Hey folks,

currently I'm trying to bring my Rails 6 app to production on an Ubuntu Server, and for that, I'm using Capistrano. I spent one day to prepare the project and it works quite well, but I can't get around one error.
I followed the instructions on webpacker to link the dependencies in the linked_dirs and running yarn install before the assets: precompile, that's when I get this error:

In a StackOverflow thread, someone said it could because I'm using the 5$ DigitalOcean Server with just 1GB RAM? Could that be the issue? Cause webpacker seems to work!

```
00:47 deploy:assets:precompile
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake assets:precompile
      01 [Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
      01 I, [2019-10-10T11:01:27.724567 #10699]  INFO -- : Writing /home/deploy/webmenue/releases/20191010110029/public/assets/pdf-9124940acc21064e2797d4fc331490b7dd2616867e513e126f2a163025a71bc7.css
      01 I, [2019-10-10T11:01:27.725085 #10699]  INFO -- : Writing /home/deploy/webmenue/releases/20191010110029/public/assets/pdf-9124940acc21064e2797d4fc331490b7dd2616867e513e126f2a163025a71bc7.css.gz
      01 I, [2019-10-10T11:01:27.728319 #10699]  INFO -- : Writing /home/deploy/webmenue/releases/20191010110029/public/assets/MultiFactor-ec7b30855ff129ef43275ce9047d6b28196613335a7fde0aa2b9b937c7e7b0e6.png
      01 I, [2019-10-10T11:01:27.733297 #10699]  INFO -- : Writing /home/deploy/webmenue/releases/20191010110029/public/assets/logo-d3cf944e7b444e9265ffc5708b91386900a04c498681b2ee8b4537e92ce93757.jpg
      01 I, [2019-10-10T11:01:27.737513 #10699]  INFO -- : Writing /home/deploy/webmenue/releases/20191010110029/public/assets/top-1b883a805cfc1445462e1accd2d4f9db4062476e1d0ca24842f2691e8ca72231.png        
      01 I, [2019-10-10T11:01:28.315834 #10699]  INFO -- : Writing /home/deploy/webmenue/releases/20191010110029/public/assets/express/lib/application-9232ebdb20ad39572e70fb9e29810e63dbb63b58f5f18617c7c2bc8…
      01 I, [2019-10-10T11:01:28.316656 #10699]  INFO -- : Writing /home/deploy/webmenue/releases/20191010110029/public/assets/express/lib/application-9232ebdb20ad39572e70fb9e29810e63dbb63b58f5f18617c7c2bc8…
      01 Compiling…
      01 Compilation failed:
      01
#<Thread:0x00000000031d6db8@C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as deploy@142.93.104.71: rake exit status: 1 (SSHKit::Runner::ExecuteError)
```

Any suggestions?

Thanks!

**Comment by leehambley** [comment]
Moin @alliedarmour,

Looks like your system is missing something - it looks like maybe node modules are not installed, or maybe that your environments rely on a .bashrc (or similar) script to put the node environment into the path.

This from our docs might help explain some "unexpected" behaviour - https://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/ if you try things in a console you're not really replicating what happens when Capistrano tries.

I'm going to close this, but you can follow-up with a StackOverflow post, this is for sure not a Capistrano bug, and we prefer to offer that kind of help on SO.

Feel free to cross-post if you don't come to a solution and link the SO post here.

Liebe Grüße aus Hamburg ;-)

**Comment by undu82** [comment]
Hi, you need to restart the server and than deploy

Regards

**Comment by pelcasandra** [comment]
Did you find a solution to this? I'm having the same problem.

**Comment by alliedarmour** [comment]
@pelcasandra for me it was the lack of hardware. I decided to compile the webpacker assets locally and just upload them to the remote server!

**Comment by ibantoo** [comment]
hey I have the same problem, like the error above but i aleady did restart server but still the same, and the error they gave not clear as well, i have tried many things for days but still cant resolve, can  the contributors help please @undu82 @alliedarmour @leehambley

**Comment by undu82** [comment]
Did you try to update your Capistriano gem? After the last update, I haven't had any more problems
Regards
