### ISSUE TITLE
how to deploy localhost?

### ISSUE THREAD

**Issue by MisterBowie** [capistrano/capistrano#2041]
```
server 'localhost', roles: %w{web app db production} # no need to set SSH configs.
namespace :db do
  task :seeds do
    on roles(:app) do
      within "#{fetch(:deploy_to)}/current" do
        with RAILS_ENV: fetch(:rails_env) do
          execute :rails,"db:seed","RAILS_ENV=production"
        end
      end
    end
  end
end
```
But remind me of this mistake！
```
(Backtrace restricted to imported tasks)
cap aborted!
NoMethodError: undefined method `roles_array' for #<SSHKit::Host:0x00000000013d5990>

Tasks: TOP => whenever:update_crontab
(See full trace by running task with --trace)
The deploy has failed with an error: undefined method `roles_array' for #<SSHKit::Host:0x00
```

**Comment by mattbrictson** [comment]
Sorry, I am not familiar with how localhost deploys work with Capistrano. However, I see that you are having problems with the `whenever:update_crontab` task. Perhaps you could report this problem to the [whenever](https://github.com/javan/whenever) project to see if they can provide a workaround: https://github.com/javan/whenever .

**Comment by MisterBowie** [comment]
> Sorry, I am not familiar with how localhost deploys work with Capistrano. However, I see that you are having problems with the `whenever:update_crontab` task. Perhaps you could report this problem to the [whenever](https://github.com/javan/whenever) project to see if they can provide a workaround: https://github.com/javan/whenever .

I used the whenever, I can use it after deleting.

**Comment by MisterBowie** [comment]
> > Sorry, I am not familiar with how localhost deploys work with Capistrano. However, I see that you are having problems with the `whenever:update_crontab` task. Perhaps you could report this problem to the [whenever](https://github.com/javan/whenever) project to see if they can provide a workaround: https://github.com/javan/whenever .
> 
> I used the whenever, I can use it after deleting.

thanks
