### ISSUE TITLE
.htaccess deploy request advice

### ISSUE THREAD

**Issue by breakroncowof** [capistrano/capistrano#2043]
Hello to everyone,

I'm a newbie in capistrano world but I tried to understand it :)

I have a question, I have manage to deploy my project that I stored on my git repo without problems.
After some configuration with "linked_files" and "linked_dirs" all works very well. 
But today I noticed that .htaccess file in root folder of my project (that is present updated in my git repo) not deploy correctly (deploy always an old version of that (maybe first deploy that I made)).

I know that probably is a stupid question but If can you advice me with some solution I'm very grateful as well as continuing to learn to use this fantastic tool!

Thank you in advance

**Comment by mattbrictson** [comment]
Have you added `.htaccess` to `:linked_files`? If so, Capistrano will _delete_ whatever `.htaccess` file is in your git repo and replace it with a symlink to the version that is in the shared directory. Maybe that is what is happening?

**Comment by breakroncowof** [comment]
No, I added others files and folders to linked_dirs and linked_files but not .htaccess.
In fact based on what I made would have .htaccess updated ( like others files and folders of my projects  ) with that on git repo but not in this case.
.htaccess is old respect of what I have on my git repo.

**Comment by mattbrictson** [comment]
Hmm, I am stumped then. As you probably know, when Capistrano creates a release it makes a copy of the latest files in git (the `master` branch, by default) into a `releases/<TIMESTAMP>` directory. Unless you have custom tasks that modify the contents of directory, every file within that release should match what was in git.

Subsequently, Capistrano modifies the `current` symlink to point to that release.

Possibly, if your server is failing to detect the update to the `current` symlink, it could be serving files out of an old release. I would recommend SSH-ing into the server and checking the contents of the latest `releases/<TIMESTAMP>` directory and the destination of the `current` link to verify what is happening.

**Comment by breakroncowof** [comment]
Infact I am stumped too.
Current folder point correct releases/<TIMESTAMP> folder with project but in the latest releases folder there is old (or default) htaccess and not my htaccess that is in git repo.
I try to redeploy various times but everytime all files are correct with that in my git repo but htaccess not.

So it's strange behaviour and infact I thought that is my fault somewhere.

Maybe are there problems with hidden files? I'ts only my guess...
I don't really know where to bang my head

Thank you in advance for your answer.

**Comment by breakroncowof** [comment]
seems that capistrano overwrite htaccess with default one

**Comment by will-in-wi** [comment]
One option to try would be to delete the `current` symlink and all of the `releases/*` folders, and then do a new deploy. If the wrong htaccess file is still there, delete the `repo/` folder and redeploy again.

**Comment by breakroncowof** [comment]
> One option to try would be to delete the `current` symlink and all of the `releases/*` folders, and then do a new deploy. If the wrong htaccess file is still there, delete the `repo/` folder and redeploy again.

Nothing.. I tried all of that but problem persists and seems very strange

**Comment by breakroncowof** [comment]
I tried various solution but nothing.
Maybe are there a problems with hidden files? perhaps capistrano have difficult to match hidden files? I don't know is only my suppose because this behaviour is very strange ans seems impossible that heppens only in my env.

Thank you in advance for your answer

**Comment by breakroncowof** [comment]
Ok, i resolved the issue.
it's not a capistrano problem but a command during magento install with capistrano (composer install) that overwrite my htaccess from my repo.

Thank you for your time
