### ISSUE TITLE
Capistrano 3.12.0 much slower for default cases

### ISSUE THREAD

**Issue by Fjan** [capistrano/capistrano#2049]
Upgrading to Capistrano 3.12.0 makes deploys about twice as slow because `git_wait_interval` is now set to 3 seconds default (Caused by: https://github.com/capistrano/capistrano/pull/2044).

I think that for the majority of users this wait time is not necessary, it's mainly helpful to address issues with a particular Gitlab setup mentioned in the commit.

I think changing the default back to zero probably makes most sense. Alternatively, Capistrano could perhaps detect a multiple server deploy and set the value accordingly. (As a last resort, it should at least be well documented that most users need to add `set :git_wait_interval, 0` to get the speed back).

---

### Steps to reproduce
Upgrade Capistano to 3.12.0
Deploy something

### Expected behavior
Should be similar speed to Capistrano 3.11.2

### Actual behavior
It's over two times slower

**Comment by mattbrictson** [comment]
@Fjan would you also be interested in opening a corresponding PR with the fix? It should just be a one-line change here:

https://github.com/capistrano/capistrano/blob/0741c3498a3b7bd2d25e3b76c9d04ce5477fb1b7/lib/capistrano/scm/git.rb#L22

Plus corresponding updates to `spec/lib/capistrano/scm/git_spec.rb`.

I can do it at my next opportunity, but I wanted to give you a first shot. 🙂

**Comment by Fjan** [comment]
Thanks, but I won't have time to look at this for a while, so if you can make the change that would be great.

**Comment by grzegorzblaszczyk** [comment]
@mattbrictson If nobody will fix it today, I will do it in the evening - I think it's me who caused this issue for @Fjan and the rest of capistrano users. I will create a PR today. 

Sorry for this guys, I will make it up for you with the PR today.

**Comment by grzegorzblaszczyk** [comment]
@mattbrictson Please see PR #2050 .
