### ISSUE TITLE
Deprecation warning on dsl.rb

### ISSUE THREAD

**Issue by jsonUK** [capistrano/capistrano#2061]
### Steps to reproduce
Running a capistrano deploy, does not matter what stage you specify.

### Expected behavior
Error should not appear.

### Actual behavior
This error appears amongst the deploy information:
```
/usr/local/lib/ruby/gems/2.7.0/gems/capistrano-3.14.0/lib/capistrano/dsl.rb:36: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/lib/ruby/gems/2.7.0/gems/i18n-1.8.2/lib/i18n.rb:195: warning: The called method `t' is defined here
```

### System configuration
```
Environment

    Ruby     ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
    Rubygems 3.1.2
    Bundler  N/A
    Command  /usr/local/bin/cap beta doctor

Gems

    capistrano 3.14.0
    airbrussh  1.4.0
    rake       13.0.1
    sshkit     1.21.0
    net-ssh    6.0.2
```

Sorry there is not much more info I can give than that - but I did spot i18n also has a bug open for their line of code:
https://github.com/ruby-i18n/i18n/issues/516

I hope this is enough information to go on - thanks for making a great tool!

**Comment by leehambley** [comment]
Thanks for the report, I think this was fixed 8d ago by this PR which isn't included in any releases yet, could you please confirm and close or comment this ticket appropriately?

- https://github.com/capistrano/capistrano/pull/2060

Thanks, and thanks also for digging into `ruby-i18n`

**Comment by jsonUK** [comment]
Yup - confirm the merge fixes line 36 of dsl.rb in the mentioned issue.

Will wait for the next release - thank you :)
