### ISSUE TITLE
git stderr: Permission denied (publickey)

### ISSUE THREAD

**Issue by khanimdad** [capistrano/capistrano#2065]
What does this error mean and how can i fix it

$ cap production deploy
00:00 git:wrapper
      01 mkdir -p /tmp
    ✔ 01 deploy@u2h1.yoopedia.com 2.883s
    ✔ 01 deploy@u2h3.yoopedia.com 2.903s
    ✔ 01 deploy@u2h2.yoopedia.com 2.955s
      Uploading /tmp/git-ssh--production-imdad.sh 100.0%
      Uploading /tmp/git-ssh--production-imdad.sh 100.0%
      Uploading /tmp/git-ssh--production-imdad.sh 100.0%
      02 chmod 700 /tmp/git-ssh--production-imdad.sh
    ✔ 02 deploy@u2h3.yoopedia.com 0.392s
    ✔ 02 deploy@u2h2.yoopedia.com 0.388s
    ✔ 02 deploy@u2h1.yoopedia.com 0.414s
00:07 git:check
      01 git ls-remote git@github.com:youtoo-inc/unicircles.git HEAD
      01 Permission denied (publickey).
      01 fatal: Could not read from remote repository.
      01
      01 Please make sure you have the correct access rights
      01 and the repository exists.
      01 724449f266dec2c4d23b4611fcf0093600d849e2	HEAD
    ✔ 01 deploy@u2h1.yoopedia.com 1.934s
      01 724449f266dec2c4d23b4611fcf0093600d849e2	HEAD
    ✔ 01 deploy@u2h2.yoopedia.com 2.001s
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@u2h3.yoopedia.com: git exit status: 128
git stdout: Nothing written
git stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Caused by:
SSHKit::Command::Failed: git exit status: 128
git stdout: Nothing written
git stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Tasks: TOP => deploy:check => git:check
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@u2h3.yoopedia.com: git exit status: 128
git stdout: Nothing written
git stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:

  INFO [c8d06c66] Running /usr/bin/env chmod 700 /tmp/git-ssh--production-imdad.sh as deploy@u2h1.yoopedia.com

 DEBUG [c8d06c66] Command: ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="2.2.2" ; /usr/bin/env chmod 700 /tmp/git-ssh--production-imdad.sh )

  INFO [c00e8a00] Finished in 0.392 seconds with exit status 0 (successful).

  INFO [3382f9e2] Finished in 0.388 seconds with exit status 0 (successful).

  INFO [c8d06c66] Finished in 0.414 seconds with exit status 0 (successful).

  INFO [8331e4e8] Running /usr/bin/env git ls-remote git@github.com:youtoo-inc/unicircles.git HEAD as deploy@u2h1.yoopedia.com

 DEBUG [8331e4e8] Command: ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="2.2.2" GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/git-ssh--production-imdad.sh" ; /usr/bin/env git ls-remote git@github.com:youtoo-inc/unicircles.git HEAD )

  INFO [9cc0ffec] Running /usr/bin/env git ls-remote git@github.com:youtoo-inc/unicircles.git HEAD as deploy@u2h3.yoopedia.com

 DEBUG [9cc0ffec] Command: ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="2.2.2" GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/git-ssh--production-imdad.sh" ; /usr/bin/env git ls-remote git@github.com:youtoo-inc/unicircles.git HEAD )

  INFO [cf8dfef8] Running /usr/bin/env git ls-remote git@github.com:youtoo-inc/unicircles.git HEAD as deploy@u2h2.yoopedia.com

 DEBUG [cf8dfef8] Command: ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="2.2.2" GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/git-ssh--production-imdad.sh" ; /usr/bin/env git ls-remote git@github.com:youtoo-inc/unicircles.git HEAD )

 DEBUG [9cc0ffec] 	Permission denied (publickey).

 DEBUG [9cc0ffec] 	fatal: Could not read from remote repository.

Please make sure you have the correct access rights

and the repository exists.

 DEBUG [8331e4e8] 	724449f266dec2c4d23b4611fcf0093600d849e2	HEAD

  INFO [8331e4e8] Finished in 1.934 seconds with exit status 0 (successful).

 DEBUG [cf8dfef8] 	724449f266dec2c4d23b4611fcf0093600d849e2	HEAD

  INFO [cf8dfef8] Finished in 2.001 seconds with exit status 0 (successful).

**Comment by leehambley** [comment]
Please read the issue template before deleting it and asking in the wrong forum. We provide some limited support on StackOverflow.com for configuration issues such as this.
