### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by simbiont123** [capistrano/capistrano#2070]
Hello, 

we noticed that translations are not working properly. We got many missing translations error messages after cap execution (using multi stage deployment) e.g.
```
translation missing: en.capistrano.question_prompt_default
translation missing: en.capistrano.keeping_releases
```

As a workaround we overwrite default i18n keys.
```
I18n.backend.store_translations(:en, capistrano: {question_prompt_default: "%{key} (%{default_value}): "})
ask(:continue_with_deploy, "y", prompt: "Continue with deploy? (y/n)")
```

We consider that there could be some problem with loading capistrano/i18n.rb.

### System configuration
ruby 2.7.2p137
rails 6.0.3.4
capistrano (3.14.1)
capistrano-bundler (2.0.1, 1.6.0)
capistrano-faster-assets (1.1.0)
capistrano-rails (1.6.1, 1.5.0)
capistrano-rbenv (2.2.0, 2.1.6)
capistrano-runit-core (0.2.0)
capistrano-runit-puma (0.2.1)
capistrano-scm-rsync (0.1.2)

Thanks for helping improve Capistrano!

**Comment by mattbrictson** [comment]
It sounds like you may have another `capistrano/i18n.rb` file installed in your system other than the one that comes with the `capistrano-3.14.1` gem. Could you do an experiment? Place this code in your `deploy.rb` and see what output you get.

```ruby
puts $LOADED_FEATURES.grep %r{capistrano/i18n}
```

I get this:

```
/Users/mbrictson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/capistrano-3.14.1/lib/capistrano/i18n.rb
```

**Comment by simbiont123** [comment]
Hello,

thanks for your quick response. We tried it with the following result:

`/Users/work/.rvm/gems/ruby-2.7.2/gems/capistrano-3.14.1/lib/capistrano/i18n.rb`

**Comment by mattbrictson** [comment]
Hmm. And if you open the file you listed, does it look right? I.e. it matches https://github.com/capistrano/capistrano/blob/v3.14.1/lib/capistrano/i18n.rb ?

If so, then the only other thing I can think of is that some other gem that is being loaded during your `cap deploy` is changing/corrupting the `I18n` store. You could try a couple things:

- Find the `i18n` gem on your system and edit it to add a `puts` statement inside the `store_translations` method. Then you can observe if there are things being written to `I18n` that you don't expect, or if Capistrano's default translations aren't getting stored for some reason.
- Maybe some gem is changing the `I18n.backend` value? In other words, when capistrano boots, it stores its translations in the default backend, but then later some non-capistrano code is changing the backend, thus wiping out the defaults.
- Use a tool like [rg](https://github.com/BurntSushi/ripgrep) to search through all the capistrano plugin gems you are using to see if they make `I18n` calls. Or you could go to the GitHub repository for each of those gems and search there.

**Comment by saboter** [comment]
@simbiont123 Sometimes your app I18n can overwrite the translations loaded by capistrano. Workaround is to extract  translations from capistrano/i18n.rb into yaml file and add them to your app locales.

**Comment by simbiont123** [comment]
Hello,

we tried it and it looks like there is a gem or some part of our implementation, which overwrites translations loaded by capistrano. Workaround with extraction of translations from capistrano/i18n.rb into a local file is good enough solution for us.

Thanks for your help @mattbrictson @saboter
