### ISSUE TITLE
How to use personal access token for github?

### ISSUE THREAD

**Issue by RailsCod3rFuture** [capistrano/capistrano#2078]
As you've probably seen, github is enforcing an access token only policy where you cannot use the username/password combo with the url to access private repositories. Does capistrano have a method for it?

**Comment by RailsCod3rFuture** [comment]
I've been searching everywhere for an approach that allows me to use the personal access token. Can't seem to find anything -- I'm receiving warnings that I cannot use username/password to deploy

**Comment by leehambley** [comment]
The preferred method is to use the SSH access unless something strictly prevents it.

SSH has a concept of "Agent forwarding" which allows your SSH key (on your machine) to be made available to your servers during deploy time, so that the servers can "borrow" your access to clone private repositories (be that the main repo or the sub-repos you may have as modules, or gems, etc)

Is there some reason that SSH key access doesn't work for your set-up?

**Comment by RailsCod3rFuture** [comment]
I actually did start on it yesterday, but didn't quite know how to fully set it up for capistrano....Does anyone have a mock deploy.rb/CapFile file with a tutorial video or article? I need to get this right, given that the system is being used in production for a large quantity of users

**Comment by RailsCod3rFuture** [comment]
I'll share my capfile/deploy.rb next monday if need be.

**Comment by leehambley** [comment]
If you're nervous about breaking production, you can follow this guide from GitHub https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

Then you can perform these two (point five) checks:

1. Locally, `git ls-remote <ssh url to your repo>`
2. Locally run `ssh-add -l` and check that your key agent `-l`ists at least one key
3. Run (all in one line) something like `ssh -A  deploy@myserver.com git ls-remote <ssh url to your repo>`

(this runs the same command as you, via the deploy user from your server.) This all gets pretty close to the fundamentals of what's going on when Capistrano runs a deploy this way.

Beware two things:

- use of an agent, or not (`ssh-add`) will depend on your system, explore google. Also AgentForwarding is *not* enabled by default (security reasons) for SSH, hence the `-A` in `ssh -A ...`, in SSHKit it is enabled by default. 
- changing from an HTTP to an SSH remote URL will confuse likely Capistrano, you may need to remove the repository cache directory from the server. I _felt_ like we addressed the root of this problem some years ago, but one can never be sure, occasionally issues still surface about it.
