### ISSUE TITLE
"cap production deploy" fails at different steps each time?

### ISSUE THREAD

**Issue by cratag** [capistrano/capistrano#2082]
I have an Ubuntu 18.04 server, and I want to deploy my app to it.
I've been struggling with Capistrano for a couple hours. Whenever I fix some error, it moves past that error, prompts a new one and (many times) fails at a previously solved error. Some other times it just works 5 steps and fails at a new one. 

If there were an error in my configuration, wouldn't I get stuck in the same error constantly? Is it possible a server capacity issue? (RAM, DISK, etc?)

DISK:
```
mr2552@ip-10-5-121-225:~$ df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p1   49G  3.0G   46G   7% /
```

RAM:
```
mr2552@ip-10-5-121-225:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        172M        3.2G         12M        482M        3.4G
Swap:            0B          0B          0B
```

Most of the errors include these two sentences:
```
mkdir stdout: Nothing written
mkdir stderr: Nothing written
```

This is the most common error: 

[SSHKit::Runner::ExecuteError: Exception while executing as mr2552@10.5.121.225: mkdir exit ][1]

After 5 attempts with the previous error, no files or code changed, no server restart:

[Git clone directory already exists][2]

So I went into the server and deleted the cloned folder myself, and advanced a few steps further, only to crash to the error 
["Directory does not exist '/var/www/CRISPR_Citrus/repo'"][3]
running `cap production deploy` again repeated the error, so I went to the server and created an empty `repo` folder, and received:

[A very similar error to the first ones][4]
a couple more of the [same errors][5]

until the 4th attempt showed 

[repo does not exist][6]

----------

Am I going crazy?

SSH key from server is configured in the Deploy Keys section of the repo.

These are my files:
```ruby
#config/deploy.rb
# config valid for current version and patch releases of Capistrano
lock "~> 3.16.0"

set :application, "CRISPR_Citrus"
set :repo_url, "git@github.com:cratag/crisprcitrus.git"

set :tmp_dir, "/home/mr2552/tmp"

set :chruby_ruby, 'ruby 3.0.0p0'

SSHKit.config.command_map[:env] = '/usr/bin/env'
```

```ruby
# config/deploy/production.rb
# server-based syntax
# ======================
# Defines a single server with a list of roles and multiple properties.
# You can define all roles on a single server, or split them:

# server "example.com", user: "deploy", roles: %w{app db web}, my_property: :my_value
# server "example.com", user: "deploy", roles: %w{app web}, other_property: :other_value
# server "db.example.com", user: "deploy", roles: %w{db}

server '10.5.121.225', user: 'mr2552', roles: %w{app db web}
...
```

```ruby
#Capfile.rb

# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Load the SCM plugin appropriate to your project:
#
# require "capistrano/scm/hg"
# install_plugin Capistrano::SCM::Hg
# or
# require "capistrano/scm/svn"
# install_plugin Capistrano::SCM::Svn
# or
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

# Include tasks from other gems included in your Gemfile
#
# For documentation on these, see for example:
#
#   https://github.com/capistrano/rvm
#   https://github.com/capistrano/rbenv
#   https://github.com/capistrano/chruby
#   https://github.com/capistrano/bundler
#   https://github.com/capistrano/rails
#   https://github.com/capistrano/passenger
#
# require "capistrano/rvm"
# require "capistrano/rbenv"
# require "capistrano/chruby"
# require "capistrano/bundler"
# require "capistrano/rails/assets"
# require "capistrano/rails/migrations"
# require "capistrano/passenger"

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }

require 'capistrano/rails'
require 'capistrano/chruby'

```

  [1]: https://docs.google.com/document/d/1uM2RpPC6Sx2kUFeqIx4A4Nz4nDO5vWD8dkO5nBW-ZJk/edit?usp=sharing
  [2]: https://docs.google.com/document/d/124IoB7hnkjpNK2Pm_gAnOJn0d3tf-Aa_6UHR_ywlvgo/edit?usp=sharing
  [3]: https://docs.google.com/document/d/1N_F4q8Xmj4V44L3WJ8kMw-iV_YCpkPGKo2FwI5AzTZo/edit?usp=sharing
  [4]: https://docs.google.com/document/d/1gI2JKQmSJTbP36wwQCjzYDOJI9yA3ecyYs7njo_oRIc/edit?usp=sharing
  [5]: https://docs.google.com/document/d/1UQ7qA5CwTmSlz7c4qPYOcW6MO_kOwFb-OXUNStoUwz8/edit?usp=sharing
  [6]: https://docs.google.com/document/d/11wqC6WgRihLEDWUzKvpkNM3dHCMFo41TKIWZ0lFzVYQ/edit?usp=sharing

**Comment by leehambley** [comment]
My first intuition would be something running like `fail2ban` or something on the host machine which is causing issues.

Some of the other errors (dir exists which should not) may be explained by Capistrano being interrupted at an inopportune time.

On the server, in a separate window you can check the logs, I can't advise you much how to do that, I don't use Ubuntu and the links I found are outdated, but typically check the system journal, `authd` logs, or any checking if fail2ban or similar is installed.

**Comment by cratag** [comment]
`sudo fail2ban-client status` returns `sudo: fail2ban-client: command not found`

and

```
mr2552@ip-10-5-121-225:~$ /var/log/fail2ban.log
-bash: /var/log/fail2ban.log: No such file or directory
```

in both Host computer and Server computer. I'll try and check the logs now, thank you

**Comment by cratag** [comment]
In system logs, mostly the error is 

`Apr 20 19:36:46 ip-10-5-121-225 systemd-resolved[699]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.`
which from what I've read is not an error, but rather a warning.

There's this line that caught my attention:
`Apr 20 19:36:28 ip-10-5-121-225 login_duo: Failed Duo login for 'mr2552' from 172.25.178.xxx`
mr2552 is my server username, 10-5-121-225 my server ip and the last ip, my computer's

Whenever I try to see the logs, I get many of those `NXDOMAIN` messages, but the latter one only shows when I `cap production deploy`


In Auth logs, this gets constantly repeated upon calling the logs:
```
Apr 20 19:41:26 ip-10-5-121-225 sudo:   mr2552 : TTY=pts/0 ; PWD=/ ; USER=root ; COMMAND=/bin/cat /var/log/auth.log
Apr 20 19:41:26 ip-10-5-121-225 sudo: pam_unix(sudo:session): session opened for user root by mr2552(uid=0)
```

and as far as I can see, everything else is correct:

```
Apr 20 19:41:25 ip-10-5-121-225 sshd[5670]: Accepted publickey for mr2552 from 172.25.178.xxx port 42768 ssh2: RSA SHA256:TScRJKIboLrEuiQ00jH+frK86R677KNaXDjyNfxxxx
Apr 20 19:41:25 ip-10-5-121-225 sshd[5670]: pam_unix(sshd:session): session opened for user mr2552 by (uid=0)
Apr 20 19:41:25 ip-10-5-121-225 systemd-logind[905]: New session 59 of user mr2552.
```

I've censored my IP and key just in case

**Comment by leehambley** [comment]
So I worked once in a place that used Duo login multi factor auth and it's a nightmare. 

The https://manpages.ubuntu.com/manpages/precise/man8/login_duo.8.html software (there's probably a configuration in the server that forces this, see the man page)

With that in mind, probably you need to petition whoever maintains this server to turn that off for your deploy user, at least temporarily for testing, and ask them what kinds of selinux or apparmor they might run.

But you are probably also lacking permissions. Try deleting as much of the half-ways installed config as you can, and making a clean run with no checked-out stuff (Capistrano is usually good at conditionally creating only the missing stuff, but a clean slate cannot hurt)

It's very difficult to deploy to servers with unknown configurations, let alone when 3rd party policing software is installed that may be prematurely hanging up connections or imposing other restrictions which change the rules of the standard linux permissions and conventions.

**Comment by leehambley** [comment]
I also just noticed something alarming:

```
Finished in 37.317 seconds with exit status 0
```

(from one of the docs about creating a session)

Does creating a directory *really* take 30 seconds? Is it possible that duologin is somehow blocking waiting for you to add a 2nd factor code? This line of code should take nominally 30.300ms to run, not *thirty* seconds.

Do you see anything weird (multi-factor second factor input?) when trying to log-in without Capistrano, just using an SSH key?

**Comment by cratag** [comment]
There's a big chance this is the issue. I can't get rid of two factor auth, but I will try to remove it from the ubuntu server if possible, and let you know

**Comment by leehambley** [comment]
I noted in the footer of the documentation for the duo auth helper that it only applies to login shells. 

The difference may be quite subtle, but since you are using chruby which is typically configured via a "dotfile", often times a login shell is assumed or implied.

We document the difference between login and non-login shells here https://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/ and explain the implications, and how to test your real shell, and Capistrano pseudo shell for what kind of shell you are using.

In the end automated tools like Capistrano *should* use a non-login, non-interactive shell, but these days not many people know the difference and lots of tools have incompatible defaults.

Please start here in _our_ docs, because it may be possible to convince Capistrano not to use a login shell, if it currently is doing, which, based on the duoauth docs would eliminate that component, just because 2FA doesn't apply from their side to non-login shells.

**Comment by cratag** [comment]
Thank you very much, @leehambley your thoughts were totally correct. DUO authentication was messing up my capistrano deployment.

I created a new user in my server for deployment, as such:

```
$ NEWUSER=testuser  #Replace with desired Ubuntu user name. This creates a variable.
$ adduser $NEWUSER
$ usermod -aG sudo $NEWUSER  #If you would like to give them root access
$ mkdir -m 700 /home/$NEWUSER/.ssh
$ echo "User's PUBLIC key" > /home/$NEWUSER/.ssh/authorized_keys
$ chmod 600 /home/$NEWUSER/.ssh/authorized_keys
$ chown -R $NEWUSER:$NEWUSER /home/$NEWUSER/.ssh
$ restorecon -FRvv /home/$NEWUSER/.ssh  #Required if Selinux is running on the server
```
if it prompts user doesn't exist:
`sudo addgroup groupname #create the group`
I still have an issue with rbenv, but that has nothing to do with this, so I'll close with this comment.
