### ISSUE TITLE
bash: /home/myuser/.rbenv/bin/rbenv: No such file or directory when production deploying

### ISSUE THREAD

**Issue by cratag** [capistrano/capistrano#2083]
```
 bundler:config
      01 $HOME/.rbenv/bin/rbenv exec bundle config --local deployment true
      01 bash: /home/ers/.rbenv/bin/rbenv: No such file or directory
```

Terminal logs `/home/MYUSER/.rbenv/bin/rbenv: No such file or directory` which is true:

```
ls /home/ers/.rbenv
plugins  shims  version  versions
```

I don't have a bin/rbenv folder. I believe it should be somewhere else, but running rbenv doctor shows:

```
~/.rbenv# curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
Checking for `rbenv' in PATH: /usr/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /home/ers/.rbenv/plugins/ruby-build/bin/rbenv-install (ruby-build 20210423)
Counting installed Ruby versions: 1 versions
Checking RubyGems settings: OK
Auditing installed plugins: OK
```

but `cd /usr/bin/rbenv` is unreachable. I can go to `/usr/bin` and when I `ls -al`, I'm able to see rbenv folder in a specific way:

`lrwxrwxrwx  1 root   root          26 May  1  2017  rbenv -> ../lib/rbenv/libexec/rbenv`

and I can't find that `../lib/` folder

**Comment by leehambley** [comment]
I'd suggest reopening this at https://github.com/capistrano/rbenv 

Or, really just installing Ruby directly on the host. rbenv, rvm, and chruby are fine, but if you can just install a system Ruby you will have an easier time. Just check what versions of Ruby you can get from the Ubuntu package repositories, and maybe you strike lucky.
