### ISSUE TITLE
Change chmod inside magento2 deployment with cap 

### ISSUE THREAD

**Issue by Minirock** [capistrano/capistrano#2085]
Hi, sorry to come here but the SO doesn't seem very populated ;) 

We have a capistrano for our magento application

The deploy are working fine from `tools/cap/config/deploy.rb` and run correctly each specific env we have like for example `tools/cap/config/deploy/production.rb`

The problem is that during the deploy process we would like to change the chmod command made by capistrano cause this is getting us some trouble we need to setup manually the rights after each deploy. (but not on every ones of our projects, so I don't think this is due to a cap bug neither, more likely to some internal configuration we have).

Anyway, we clearly see in the `capistrano.log`

    INFO [db28dba5] Running /usr/bin/env find /var/www/ourwebsite/web/releases/20201117160947 -type f ! -perm 660 -exec chmod 660 {} + as domain@ip

So that chmod 660 must be defined somewhere...but I can't find where.

So I'm looking into a way to "extend" that capistrano behaviour...or at least to add a specific tasks at the end of the current deploy process that will do what we want.

I've seen there was a way to define specific tasks cause we got this in our `Capfile`

    # Load custom tasks from `lib/capistrano/tasks` if you have any defined
    Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }

But currently we didn't get any of them.

Thanks for your assistance.

**Comment by leehambley** [comment]
> change the chmod command made by capistrano

For this you will need to overwrite the task. This is a Rake feature, not a Capistrano feature, as we extend their DSL. You can learn about the tasks that are executed at deploy time here https://capistranorb.com/documentation/getting-started/flow/ and you can extend/overwrite/replace tasks such as by following this Rake guide: https://www.rubycommunity.org/articles/customizing-rails-rake-tasks

Note that "reopening" (Defining again, an already existing task) by default _extends_ the definition, so in the above linked article you will note that they are "clear"ing the existing definition. You can see an example of a chmod in a task, all in situ here https://github.com/capistrano/capistrano/blob/f5a16779a7e6ddf6768ea2c1f39b101ffeba796b/lib/capistrano/scm/tasks/git.rake#L10 and copy whatever parts you need.

> So that chmod 660 must be defined somewhere...but I can't find where.

Search in this repository for it, or post more complete logs. It's likely it doesn't come from `capistrano/capistrano`, but from a gem you are using on-top.

> But currently we didn't get any of them.

That suggests your require line above (which looks correct) isn't being executed, or isn't finding any files. You can probably debug this yourself, but I can at least confirm that importing rakefiles is the correct approach.

**Comment by Minirock** [comment]
I managed to do what I wanted with the following rake tasks

    namespace :magento do
        namespace :setup do
           desc 'Custom rights on application'
           task :permissions do
               on release_roles :all do
                  within release_path do
                      execute :find, release_path, "-type d ! -perm 755 -exec chmod 755 {} +"
                      execute :find, release_path, "-type f ! -perm 644 -exec chmod 644 {} +"
                 end
             end
          end
       end
    end
