### ISSUE TITLE
Can't get correct ~ ($HOME) within cap rake task.

### ISSUE THREAD

**Issue by zw963** [capistrano/capistrano#2088]
---

### Steps to reproduce

Because i set `deploy_to` to a string prefix with  `~/app` (use ~ instead of $HOME)

```
set :deploy_to, "~/apps/#{fetch(:application)}_#{fetch(:stage)}"
```

it expand well when deploy use cap.

But, when i create a new cap task like this to try to get the absolute path of `deploy_to`, it get wrong result.

```
# ...
# expand ~ into my local laptop $HOME, this is not correct.
Pathname("#{deploy_to}/current/config/#{service_name}").expand_path # => /home/zw963/current/config/

# I have to workaround to use following command get correct result.
capture("cd #{deploy_to}/current/config/#{service_name}; pwd") # => /home/deployer/current/config

# ...
```

So, is there exist a correct way to do this? which i don't know?

Thank you.

**Comment by mattbrictson** [comment]
My recommendation is to use the explicit path instead of relying on the shell to expand it for you. In this case, you know that the home directory of the deployer user is `/home/deployer`. So use that in your `:deploy_to` setting. This is how I've always done it.

```ruby
set :deploy_to, -> { "/home/deployer/apps/#{fetch(:application)}_#{fetch(:stage)}" }
```

Note that this will not work:

```ruby
Pathname("#{deploy_to}/current/config/#{service_name}").expand_path
```

That is because `Pathname` and `.expand_path` are plain Ruby concepts that don't know anything about the remote host that you are interacting with in Capistrano. They will always be evaluated locally to your laptop. In Capistrano, Ruby code is never executed on the remote host. Only the shell commands inside strings, like `"cd #{deploy_to}"` are actually executed remotely.

**Comment by zw963** [comment]
@mattbrictson , so, double confirm, there is never exists a `ruby block` way, to wrap all ruby code to run only on remote ruby environment on remote server, right?

**Comment by zw963** [comment]
What i means is, there maybe exists a block, e.g. like 

```rb
within release_path do
   # we know we run command within release path
end
```
so, i curious, if exists another block like this.

```rb
eval_on_remote_server do
   # some ruby code will eval on remote server
end
```

**Comment by zw963** [comment]
I spend hours to try to write one task like this:

1. read a file use ruby ERB from remote server
2. read a yaml file and parse it from remote server
3. generate parsed content
4. save those content into a new file on remote server.


```rb
project_config_file = "/home/deployer/app/current/config/nginx_production.rb"

# step 1, it work
erb = ERB.new("#{capture("cat #{project_config_file}")}")

# step 2, it work
config = YAML.load(capture("cat #{deploy_to}/current/system_config.yml")).dig(service_name, fetch(:stage).to_s)

# step 3, works

content = erb.result_with_hash(config).to_s

# step 4, i want to save content into a new file, with same name, same format, how to do that from a cap task?

Following is my attempt:

execute "cat <<< \"#{xx}\" > #{project_config_file}"
```

it not work, because generated string all "\n" stripped, e.g. original nginx config change to like this:

```
upstream app_server {; server 127.0.0.1:3000;; }; ; server {; listen 80;; server_name localhost;; ; location ~ \.(aspx|php|jsp|cgi)$ {; return 410;; }; ; location / {; proxy_set_header X-Forwarded-For ;; proxy_set_header Host ;; proxy_set_header   X-Real-IP   ;; proxy_pass http://app_server;; proxy_buffering on;; proxy_buffers 32 16k;; proxy_set_header   Upgrade ;; proxy_set_header   Connection Upgrade;; # gzip off;   # 当 https 时, 应该关闭?; }; ; location ~ \.(js|css) {; root /home/deployer/apps/marketbet_crawler_production/shared/public;; gzip_static on;; expires max;; add_header Cache-Control public;; add_header Access-Control-Allow-Origin *;; }; }
```

Can you please give me some idea about how to resolve this?

i can't find answer on stackoverflow, thank you.

**Comment by mattbrictson** [comment]
> so, double confirm, there is never exists a `ruby block` way, to wrap all ruby code to run only on remote ruby environment on remote server, right?

Correct. Capistrano has no ability to run code in a remote ruby environment.

The only way you could hack it is by manually invoking the ruby interpreter. Assuming `ruby` is installed on the remote host and in the PATH, you could theoretically do this:

```ruby
on roles(:app) do
  output_from_remote_ruby = capture(%Q{ruby -e 'puts "hello from remote ruby"'})
end
```

Probably not what you want. 😅

**Comment by mattbrictson** [comment]
> it not work, because generated string all "\n" stripped

I'm not sure capistrano can accomplish what you are trying to do. If you pass a string to `execute` that contains newlines, capistrano assumes you mean to run several individual commands separated by newlines. You can see that code here:

https://github.com/capistrano/sshkit/blob/7473458b0422e27dbcadcdcfcffa65fa46bb64c1/lib/sshkit/command.rb#L236-L238

The only thing I can think of is using the `upload!` approach. Capistrano (via SSHKit, on which it is based) has the ability to upload a file or a string from your local machine to a path on the remote host. Check out the examples here:

https://github.com/capistrano/sshkit/blob/master/EXAMPLES.md#upload-a-file-from-disk

Anyway, this conversation has now strayed pretty far from the original topic ("Can't get correct ~ ($HOME) within cap rake task") and GitHub issues is not a general support/discussion forum, so I will close this issue. Good luck!

**Comment by zw963** [comment]
@mattbrictson 

I resolve this issue use you suggested `ruby -e` solution.  ; )

like this: (add to cap task)

```rb
if project_config_file.extname.end_with? ".erb"
      new_project_config_file = project_config_file.sub_ext('') # remove .erb suffix
      ruby_script = <<-HEREDOC
require 'erb'
require 'yaml'
erb = ERB.new(File.read("#{project_config_file}"))
config = YAML.load_file("#{_deploy_to}/current/system_config.yml").dig("#{service_name}", "#{fetch(:stage)}")
File.write("#{new_project_config_file}", erb.result_with_hash(config))
HEREDOC
      execute "cat '#{ruby_script.inspect}' |ruby"
    end
```

It dirty, but work anyway, thanks for you help.

**Comment by zw963** [comment]
BTW:  i don't remember the exact reason i use ~ in my cap config like this

```
set :deploy_to, "~/apps/#{fetch(:application)}_#{fetch(:stage)}"
```
but, in fact, i can add above code into config/deploy.rb instead individual stage file, anyway, eliminate duplicate code.
