### ISSUE TITLE
Documentation references the deprecated :scm variable

### ISSUE THREAD

**Issue by elondaits** [capistrano/capistrano#2110]
The [configuration section of the documentation](https://github.com/capistrano/capistrano/blob/master/docs/documentation/getting-started/configuration/index.markdown) mentions the `:scm` variable, although [it's now deprecated](https://github.com/capistrano/capistrano/blob/master/UPGRADING-3.7.md#the-scm-variable-is-deprecated).

**Comment by mattbrictson** [comment]
Good catch! The `:scm` section of that page should probably be removed, yes? To you want to open a PR? If not, I am happy to do it.

**Comment by elondaits** [comment]
[Done](https://github.com/capistrano/capistrano/pull/2111)
