### ISSUE TITLE
Connection stale when running a command that takes ~4 hours to finish

### ISSUE THREAD

**Issue by pioz** [capistrano/capistrano#2118]
I'm running a `mysqldump` command using sshkit in a Ruby script. Something like `execute 'mysqldump options...'`

All works fine if the DB is small, but when I use my script on a big database (the `mysqldump` command takes ~4 hours to finish), the `execute` command never ends and the connection is stale. I can see that the `mysqldump` has finished logging via ssh to the database server.

Any idea to help me? Are there some options that I should use to avoid this problem?

**Comment by mattbrictson** [comment]
Closing as resolved via https://github.com/capistrano/sshkit/issues/503
