### ISSUE TITLE
Docs bug

### ISSUE THREAD

**Issue by YouSysAdmin** [capistrano/capistrano#2138]
The image in the S3 bucket used as the link to the GitHub repo is not accessible (403)

[docs/_layouts/default.html][1]

<img width="334" alt="Screenshot 2023-08-16 at 8 07 41 PM" src="https://github.com/capistrano/capistrano/assets/1385374/5bb004af-3ecf-4b0e-9bd1-5948e49df117">

[1]:https://github.com/capistrano/capistrano/blob/31e142d56f8d894f28404fb225dcdbe7539bda18/docs/_layouts/default.html#L48

**Comment by mattbrictson** [comment]
Thanks for the report! I'm not sure why that's in S3 as opposed to being a normal file in the repo. 🤔
