### ISSUE TITLE
~/.rvm/gems/ruby-3.3.0/gems/net-ssh-7.2.1/lib/net/ssh/known_hosts.rb:3: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of net-ssh-7.2.1 to add base64 into its gemspec.

### ISSUE THREAD

**Issue by arthurduarte1** [capistrano/capistrano#2149]
### Steps to reproduce
Simple do: `cap production deploy` using ruby v3.3.0 and Capistrano v3.17

### Expected behavior
Show nothing.

### Actual behavior
Show Warning message about `net-ssh` library

### System configuration
Environment

    Ruby     ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
    Rubygems 3.5.3
    Bundler  2.5.3
    Command  ~/.rvm/gems/ruby-3.3.0/bin/cap production doctor

Gems

    capistrano 3.18.0
    airbrussh  1.5.1
    rake       13.1.0
    sshkit     1.22.0
    net-ssh    7.2.1

**Comment by mattbrictson** [comment]
As indicated in the warning message, this is a net-ssh issue. It should be fixed in the next release of net-ssh. See: https://github.com/net-ssh/net-ssh/pull/933
