### ISSUE TITLE
`set_current_revision_time` hangs in 3.19.0

### ISSUE THREAD

**Issue by digitalmoksha** [capistrano/capistrano#2161]
I've just pulled in `3.19.0`. When I deploy (to staging in this case), the deploy hangs in `set_current_revision_time`.  It never returns.

This is a git deploy.  Here is the debug trace of just the `deploy:set_current_revision_time` task.

```
> cap staging deploy:set_current_revision_time -t
** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke rbenv:validate (first_time)
** Invoke rbenv:install (first_time)
** Execute rbenv:install
** Invoke rbenv:install_rbenv (first_time)
** Execute rbenv:install_rbenv
** Invoke rbenv:install_ruby_build (first_time)
** Execute rbenv:install_ruby_build
** Invoke rbenv:install_ruby (first_time)
** Execute rbenv:install_ruby
** Invoke rbenv:install_bundler (first_time)
** Invoke rbenv:map_bins (first_time)
** Execute rbenv:map_bins
** Execute rbenv:install_bundler
** Execute rbenv:validate
** Invoke rbenv:map_bins
** Invoke bundler:map_bins (first_time)
** Execute bundler:map_bins
** Invoke deploy:set_rails_env (first_time)
** Execute deploy:set_rails_env
** Invoke deploy:set_linked_dirs (first_time)
** Execute deploy:set_linked_dirs
** Invoke deploy:set_rails_env
** Invoke deploy:set_current_revision_time (first_time)
** Invoke git:set_current_revision_time (first_time)
** Execute git:set_current_revision_time
```

When I run `git log -1 --pretty=format:%ct master` in the `repo` directory, it works fine, and shows the output with the screen cleared

```
1718981228
(END)
```

`Q` is required to quit the display.

Here is the process list via `ps aux`

```
myuser+ 163161  0.0  0.0 113420  1752 pts/24   Ss+  17:53   0:00 bash -c cd /home/REPOPATH/repo && ( ENVIRONMENT VARIABLES ; /usr/bin/env git log -1 --pretty=format:"%ct" master )
myuser+ 163195  0.0  0.0 113420   772 pts/24   S+   17:53   0:00 bash -c cd /home/REPOPATH/repo && ( ENVIRONMENT VARIABLES ; /usr/bin/env git log -1 --pretty=format:"%ct" master )
myuser+ 163196  0.0  0.0 116888  1512 pts/24   S+   17:53   0:00 git log -1 --pretty=format:%ct master
```

Adding `Rake::Task["git:set_current_revision_time"].clear_actions` to my `config/deploy.rb` does bypass it for now.

**Comment by G-Rath** [comment]
At this point I don't have a lot of theories since this has been working for us for a while without issue and I was deploying with v3.19.0 literally yesterday (and plan to be today) so this seems very weird, but let's see if we can find some threads.

Could you give more info on your setup? at Ackama we use Ubuntu 20.04+ instances with Ruby 3.1~3.3, and I'll confirm version of `git` my test server is using shortly.

**Comment by digitalmoksha** [comment]
I'm on CentOS 7 and `git version 1.8.3.1`.

It feels like it's getting hung up displaying the version. If you do `git log -1 --pretty=format:%ct master` on your system, so it print the version to stdout or in something that needs to be dismissed.

**Comment by G-Rath** [comment]
Nope no hang:

```
deploy@staging-app-i-123abc:~/little-ruby-app/repo$ git log -1 --pretty=format:%ct main
1719636170
deploy@staging-app-i-123abc:~/little-ruby-app/repo$ git --version
git version 2.25.1
```

For what it's worth while we don't typically use CentOS we do have one such legacy server which I snuck onto to check - I'm not sure if it's CentOS 7 but it is using the same version of `git` as you and it didn't hang

**Comment by G-Rath** [comment]
Oh also, while I don't know a lot of the details (yet), from what I understand Capistro uses a ["git wrapper"](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/scm/git.rb#L10-L14), which is [sort of mentioned a few times here](https://capistranorb.com/documentation/getting-started/cold-start/) but it's not explicitly clear to me what issues its meant to be overcoming.

That doc does say:

> Depending how you have set your Git authentication credentials up, checking Git can be a bit complicated, so we’ve shipped a task in the core library that can check your git access, Git isn’t particularly scriptable, so one has to wrap Git in a shell script that makes it behave.

and

> With the git wrapper in place, we can safely script against Git without it prompting us for input

It'd be worth digging into that a bit more I think...

**Comment by digitalmoksha** [comment]
OK, from https://stackoverflow.com/questions/48341920/git-branch-command-behaves-like-less

> As other answers pointed out, Git defaults to piping itself into a pager (less by default) for most commands.

I do set the `LESS` environment variable, and doing `unset LESS` makes the output go straight to stdout, same behavior as you.

**Comment by digitalmoksha** [comment]
wdyt about doing a `git log -1 --pretty=format:%ct master | cat`. That seems to work for me.  I thought the `--no-pager` option mentioned in SO would work, but it doesn't work with `git log`.

Or maybe redirect it to a file, `git log -1 --pretty=format:%ct master > REVISION_TIME`

You should be able to create  it by setting `LESS=-R --hilite-search --ignore-case` (which is what I have)

**Comment by G-Rath** [comment]
I'll need to defer that decision to @mattbrictson at this point, as I'm not familiar enough with the tradeoffs or the wider implementation to say what the fix should be.

I do think that piping to a file is probably not desired since we want to avoid creating an empty file for the user if the time cannot be retrieved for some reason.

though after having started this comment...

> I thought the --no-pager option mentioned in SO would work, but it doesn't work with git log.

when you say it doesn't work, do you mean it errors or just does nothing? because it looks like `git --no-pager log` works but it's important that it comes _before_ `log` as `--no-pager` is a [`git` level flag](https://git-scm.com/docs/git/2.26.0)

i.e. this works for me:
```
LESS='-R --hilite-search --ignore-case' git --no-pager log
```

**Comment by digitalmoksha** [comment]
You're right - I put `--no-pager` after the `pretty` option - you know, the obvious place 😄 

But `git --no-pager log -1 --pretty=format:%ct master` works for me!

**Comment by mattbrictson** [comment]
@G-Rath @digitalmoksha nice troubleshooting! It sounds like we should ship a 3.19.1 with the command changed from `git log` to `git --no-pager log`? Are either of you interested in opening a PR for that?

**Comment by G-Rath** [comment]
@mattbrictson yup that's what I was thinking and was going to do a PR but got distracted 😅 

I can have one up sometime in the next couple of days (probably today, but just in case more distractions popup...)

**Comment by digitalmoksha** [comment]
Thanks, `3.19.1` fixes the problem! 🚀
