### ISSUE TITLE
built-in rails asset compile: skip if no changes to assets?

### ISSUE THREAD

**Issue by jrochkind** [capistrano/capistrano#227]
This guy: http://www.bencurtis.com/2011/12/skipping-asset-compilation-with-capistrano/

Has a very clever way to have the assets:precompile task only run if there are changes to assets requiring it. As this is by far the slowest part of my cap deploy, this is convenient. 

Very clever, actually does a git log to see if there were any changes in assets directories since last commit. 

Would you be interested in a pull request adding this to the built-in assets:precompile task?

There are a couple bugs/missing things in that example that would have to be fixed. (Like not failing fatal if ./vendor/assets doesn't exist, and also checking (if it exists) lib/assets, and geez, sadly we'd probably have to add a new cap config for what dirs to check, since that's theoretically configurable in Rails, but cap can't access the Rails configuration. sigh.)

But the blog author also notes that this only works for git. It uses cap lines `source.next_revision(current_revision)` and `source.local.log(from)`, which I hadn't known existed (where do those come from?), but I guess they only work for git?  How come, and how could we check?  Most people are using git, and even if this only works for git, I think it's a great feature -- would it work to check for `source.respond_to?(:next_reversion)` and same with `source.local.log`, and only do this check if everything needed is there? Any advice on how to do this 'right'?

**Comment by frostblooded** [comment]
So, is there any hope for this to be added?

**Comment by mattbrictson** [comment]
@frostblooded This thread hasn't been touched in over 4 years, so most of the discussion here is probably no longer relevant. Can you clarify what feature(s) you are referring to? Then we can help direct you to the right place.

Please note that we are working on Capistrano v3 now, and Capistrano v2 is no longer supported. If you are looking for a change to v2 then we probably won't be able to help you at this point.

**Comment by will-in-wi** [comment]
I'll also note that this thread, if continued, belongs in https://github.com/capistrano/rails.
