### ISSUE TITLE
net-ssh 2.6.0 issues

### ISSUE THREAD

**Issue by skorfmann** [capistrano/capistrano#286]
I had this error after upgrading net-ssh from 2.5.2 to 2.6.0

```
connection failed for: [server] (ArgumentError: Could not parse PKey: no start line)
```

This seems to be related to net-ssh, but as I came across this issue in capistrano I'm filing the issue here now. Not sure what the problem is, no idea how to fix it :) 

My workaround is just requiring net-ssh 2.5.2 explicitly for now.

**Comment by vijay-wal** [comment]
Execute this command and try: 

```
eval `ssh-agent -s`                           
ssh-add           

```
