### ISSUE TITLE
Problem with folder already exists

### ISSUE THREAD

**Issue by toptierlabs** [capistrano/capistrano#328]
If I execute cap deploy I get the following error:

triggering start callbacks for `deploy'
- executing `multistage:ensure'
  *** Defaulting to`staging'
- executing `staging'
- executing `deploy'
  triggering before callbacks for`deploy'
- executing `check_production'
- executing `deploy:update'
  *\* transaction: start
- executing `deploy:update_code'
  updating the cached checkout on all servers
  executing locally: "git ls-remote git@github.com:xxxxxxx/myproject.git develop"
  command finished in 5163ms
- executing "if [ -d /var/www/staging-myproject/shared/cached-copy ]; then cd /var/www/staging-myproject/shared/cached-copy && git fetch -q origin && git fetch --tags -q origin && git reset -q --hard 26b7ff0248cef4c57c177f1e26d80b2ba719208c && git clean -q -d -x -f; else git clone -q git@github.com:xxxxxxx/myproject.git /var/www/staging-myproject/shared/cached-copy && cd /var/www/staging-myproject/shared/cached-copy && git checkout -q -b deploy 26b7ff0248cef4c57c177f1e26d80b2ba719208c; fi"
  servers: ["184.169.131.xxx", "myprojectpreview.com"]
  [184.169.131.xxx] executing command
  [myprojectpreview.com] executing command
  *\* [184.169.131.xxx :: out] fatal: destination path '/var/www/staging-myproject/shared/cached-copy' already exists and is not an empty directory.
    command finished in 64664ms
  **\* [deploy:update_code] rolling back

Any help?

**Comment by swapnil-iref** [comment]
yes it is a big issue still

**Comment by leehambley** [comment]
It's easily fixed by removing the directory, this issue was closed by the original poster, closed issues don't usually get attention, open a new one if you need help, please observe the contribution guidelines for writing a good issue.
