### ISSUE TITLE
export $PATH do not load correctly in capistrano

### ISSUE THREAD

**Issue by leomao10** [capistrano/capistrano#413]
Hi, 

I encounter a problem with capistrano that it could not load $PATH correct from `/etc/profile`.

OS is Ubuntu 12.04.2, and here is what I did:

I tried to install ruby-1.9.3 using [ruby-build](https://github.com/sstephenson/ruby-build) like this:

```
ruby-build 1.9.3-p392 /usr/local/ruby
```

And symlink it to /usr/bin

I export bin dir under this ruby dir to `/etc/profile`so that I could use command like `bundler` system wide:

```
export PATH=$PATH:/usr/local/ruby/bin
```

It works fine when I ssh login directly. I can run `bundle -v` without any issue and I can see /usr/local/ruby/bin when I run `echo $PATH`

But it could not find `bundler` when I use capistrano.

I then tried to put export code in many other places like, /etc/.bash.bashrc, ~/.bashrc, ~/.bash_profile.  Neither of them work. Run `echo $PATH` in `cap shell`, would not include the path at all.

Did I do something wrong or I need to do extra setting for my server/capistrano script

**Comment by LongMan** [comment]
That is exactly my problem! Thank you!

**Comment by samuelgbrown** [comment]
i had this too, oops, thanks :-)

**Comment by heaven** [comment]
We have some exports in /etc/profile.d/ which don't load with capistrano.

**Comment by leehambley** [comment]
> We have some exports in /etc/profile.d/ which don't load with capistrano.

That is in no way related to this closed issue, have you read the FAQ? http://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/#

**Comment by heaven** [comment]
Which questions it is supposed to answer? I am pretty sure that I do know the difference between log in and interactive sessions, but I don't see how to load my environment constants during deploy with capistrano, without duplicating them manually in deploy.rb. Or should this FAQ convince me that I don't need to because capistrano doesn't have an option for this, showing me some diagrams and/or schemas?

**Comment by leehambley** [comment]
The FAQ explains why we *intentionally* do not load those files.
