### ISSUE TITLE
reading the variable "latest_release" before "deploy" task happens makes capistrano BREAK

### ISSUE THREAD

**Issue by knocte** [capistrano/capistrano#440]
If you set up some task this way:

before 'deploy', 'some_task', 

And in some_task you simply read the "latest_release" variable (in a puts line for instance), then:

Current results:
a) If it's the first deploy ever in capistrano (the www folder doesn't exist), capistrano breaks completely, it cannot deploy.
b) If it's not the first deploy, then it will make capistrano change its behaviour with regards to the "current" symlink, because it will point to the previous release instead of the last one (after the deploy happened).

Expected results:
a) It should work.
b) It should point current to the latest release.

This is a big fuckup IMHO.

**Comment by knocte** [comment]
People are still upvoting my stackoverflow answer linked above, which seems to hint that this bug is still present in 3.x.

**Comment by leehambley** [comment]
thanks for checking the so answer upvote rates @knocte

**Comment by leehambley** [comment]
This issue is more than five years old, and refers to a long obsolete version of Capistrano, please open a new issue.

**Comment by batmanbury** [comment]
Can someone link to this "new" issue?

**Comment by mattbrictson** [comment]
This issue is very old and the discussion was not very productive, so I will lock it. If you are a Capistrano v3 user running into an error using the `latest_release` setting please open a new issue.

**Comment by mattbrictson** [comment]
@batmanbury there is no "new" issue; please open one if you are running into this problem.
