### ISSUE TITLE
Capistrano fails when trying to deploy Rails asset manifest

### ISSUE THREAD

**Issue by aardvarkk** [capistrano/capistrano#468]
I'm not really sure what's going on here (and I'm fairly new to Ruby/Rails), but I've found that my deploy.rb is failing in v2.15.4 but working in v2.14.2. The output is detailed here:

http://stackoverflow.com/questions/16411129/capistrano-fails-when-trying-to-deploy-rails-asset-manifest

Basically when it gets to the point of copying the file `manifest.yml`, Capistrano seems to be no longer able to determine the appropriate folder to copy to. It ends up trying to execute this:

`executing "cp -- /u/apps/myapp/shared/assets/manifest.yml /u/apps/myapp/releases/unable/assets_manifest.yml"`

Notice the string "unable" in the path, instead of an actual number. Not sure how to debug this or anything, so all I know how to do is create an issue at this point and hope somebody can figure out what's going on. I'm happy to help identify the specific code problem if somebody can point me to how to debug this further.

**Comment by dan** [comment]
@nigelramsay Did you ever resolve this?

**Comment by nigelramsay** [comment]
@dan wow, that was 3 years ago. I can't remember sorry.
