### ISSUE TITLE
Can't turn off or override assets:precompile

### ISSUE THREAD

**Issue by activestylus** [capistrano/capistrano#498]
I've commented out the line for loading this script in my Capfile, which looks like this

``` ruby
load 'deploy' if respond_to?(:namespace) # cap2 differentiator
# load 'deploy/assets'
Dir['vendor/gems/*/recipes/*.rb','vendor/plugins/*/recipes/*.rb'].each { |plugin| load(plugin) }
load 'config/deploy'
```

In my deploy.rb:

``` ruby
namespace :deploy do
  namespace :assets do
    task :precompile do
      logger.info "No precompile"
    end
  end
end
```

Yet no matter what I try, cap insists on running the precompile task, which turns a 5 second deploy into a 15 minute affair. My app is in a stable state right now so I rarely, if ever need to re-compile assets.

I'm currently running rails (3.2.12), ruby-1.9.3-p194 and capistrano-2.15.4

Any suggestions?

**Comment by cuperman** [comment]
If anyone is having this problem, you have to clear the assets precompile action rather than trying to override it.

http://capistranorb.com/documentation/advanced-features/overriding-capistrano-tasks/

**Comment by leehambley** [comment]
Glad the docs came in useful Jeff, ita a common theme over the years!
