### ISSUE TITLE
copy_exclude not considered on Cap 3 deployments

### ISSUE THREAD

**Issue by ain** [capistrano/capistrano#515]
``` ruby
set :copy_exclude, %w{.git .DS_Store web concept config lib}
```

is not considered by Capistrano 3, is there a replacement setting that achieves the same or is it a subject to custom implementation in v3?

Specs:
- Git
- Capistrano Version: 3.0.0.pre3 (Rake Version: 10.0.4)
- ruby 2.0.0p195 (2013-05-14 revision 40734) [x86_64-darwin11.4.2]

**Comment by tejasbubane** [comment]
Is `export-ignore` documented somewhere? Google search shows no documentation for this.

**Comment by testzugang** [comment]
search for "git export-ignore", e.g. http://git-scm.com/docs/gitattributes
