### ISSUE TITLE
Don't run cleanup on rollback by default

### ISSUE THREAD

**Issue by dbackeus** [capistrano/capistrano#547]
When running `cap:rollback` the `cap:rollback:cleanup` task gets run by default.

However `cap deploy` does not run `cap deploy:cleanup` unless explicitly added as a trigger.

When using unicorn and similar servers that do 0 downtime deploys by pre-loading a new set of server app instances - removing the old deployed directory will cause errors until the new ones have booted.

So optimally `cap:rollback:cleanup` should not run unless explicitly told to do so.

This also adheres to the principle of least surprise as the behaviour becomes consistent with what people are used to from running `cap deploy`.

**Comment by jsha** [comment]
I'd also very much like for `cap:rollback` to not run `cap:rollback:cleanup` by default. I've used Capistrano extensively for deploys at Twitter and for personal projects, and the default `cap:rollback:cleanup` behavior has very frequently gotten in the way of debugging deploy problems. If there's any sort of error during a deploy, usually the evidence of that error is in the release directory that `cap:rollback:cleanup` automatically deletes. This winds up wasting a lot of time trying to track down the problem.

An alternate proposal: what about creating a separate directory, parallel to releases, called e.g. failed-releases/, and moving directories there after a rollback? It could be subject to the same regime of cleaning up more than N entries that the releases directory is subject to. And then you would retain the property that the releases directory only contains releases that got as far as `deploy:restart`.

**Comment by leehambley** [comment]
I was under the impression that v3 didn't delete failed released by default.

**Comment by jsha** [comment]
Good point, thanks. I'll try upgrading to v3.
