### ISSUE TITLE
v3: Possibility to move the config folder

### ISSUE THREAD

**Issue by gjuric** [capistrano/capistrano#610]
Is it possible to add an option to specify the location of the config folder?

I see I can change the location of tasks folder if I edit the Capfile and replace this line:   

``` ruby
Dir.glob('lib/capistrano/tasks/*.cap').each { |r| import r }
```

In Capistrano 2 I had something like this in my Capfile:

``` ruby
set :stage_dir, 'deployment/deploy'
require "./deployment/railsless-deploy.rb"
load 'deployment/deploy' if respond_to?(:namespace)
```

**Comment by vincenzodibiaggio** [comment]
Works great, thanks!
Just a note: if we use a custom path, we need to update also paths to load custom tasks:

```
# default deploy_config_path is 'config/deploy.rb'
set :deploy_config_path, 'deploy/deploy.rb'
set :stage_config_path, 'deploy/stages'
```

```
# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
Dir.glob('deploy/lib/capistrano/tasks/*.rb').each { |r| import r }
```

**Comment by mjacobus** [comment]
Where did you set that, @vincenzodibiaggio ? Capfile?

I tried that and that did not work...

**Comment by vincenzodibiaggio** [comment]
yep @mjacobus 

try also 
```Dir.glob('deploy/lib/capistrano/**/*.rb').each { |r| import r }```

**Comment by mjacobus** [comment]
Thanks @vincenzodibiaggio !

I will try that. I just accidentally found [this](http://capistranorb.com/documentation/faq/how-can-i-set-capistrano-configuration-paths/) while trying to find something else.

Cheers!
