### ISSUE TITLE
Syntax for putting long running rake tasks in background and return immediately

### ISSUE THREAD

**Issue by salimane** [capistrano/capistrano#634]
I have a rake task that I created a capistrano task for. the task could take a long time so i want to launch it as a background and let cap command return immediately.
here is the code :

``` ruby
namespace :long_running_task do
  task :default, :roles => :db, :only => { :primary => true } do
    run "cd /my/path && nohup bundle exec rake my_long_running_task RAILS_ENV=#{rails_env} 2>&1 >> /my/path/log/long_running_task.log &"
  end
end
```

When I run `cap staging long_running_task`, it doesn't automatically return. But when I run the command `cd /my/path && nohup bundle exec rake my_long_running_task RAILS_ENV=staging 2>&1 >> /my/path/log/long_running_task.log &` directly on the server, it returns immediately and the task is running in the background.

I've tried , `:pty => false`, `:pty => true`, but none of them works.
I've also found http://stackoverflow.com/questions/1109274/starting-background-tasks-with-capistrano and http://stackoverflow.com/questions/18076558/background-task-with-capistrano but none helped.

Thanks

**Comment by HenleyChiu** [comment]
To be fair, putting issues in a public facing site like Github makes it so much easier to discover via Google (which I just did) vs. a mailing list, which is not as easily accessible by crawlers. I'd love it if people kept putting issues here, even if you're breaking the "rules".

**Comment by davidlaprade** [comment]
For anyone else who stumbles on this issue and gets a 404 on the github link, [this](https://github.com/mperham/sidekiq/blob/b7e7d7fcd9e36d32568f0407441ce7c3395f4354/lib/sidekiq/capistrano.rb#L43) appears to be what @kirs was referring to: 

```ruby
run "cd #{current_path} ; nohup #{fetch(:sidekiq_cmd)} -e #{rails_env} -C #{current_path}/config/sidekiq.yml -i #{idx} -P #{pid_file} >> #{current_path}/log/sidekiq.log 2>&1 &", :pty => false
```
