### ISSUE TITLE
Add Hook for Deploy Failure

### ISSUE THREAD

**Issue by clintonb** [capistrano/capistrano#708]
When deployment fails, I need to call certain tasks (e.g. send a Hipchat notification). Previously this was accomplished via the on_rollback hook. This doesn't seem to exist in v3. Can it be added, or is there a task to which I can hook?

Edit: I don't need to rollback a specific task or even the entire deployment. I basically need to know when a deployment has failed, regardless of the specific task that failed.

**Comment by itsSaad** [comment]
how do we get the exception inside the deploy:failed hook?
something like this:
````
    after 'deploy:failed', :send_for_help do
        puts "#{exception}"
end

**Comment by mattbrictson** [comment]
@itsSaad you could try: `puts $!`

**Comment by itsSaad** [comment]
`$!` give me only a string description like `Exception while executing on host <my-ip>: exit`.
What i think I need was discussed by @seenmyfate above. But that specific feature didnt make it in the pull request #756

**Comment by mattbrictson** [comment]
`$!` should be the exception object, not a string. From there you can get:

* `$!.backtrace`
* `$!.class.name`
* `$!.inspect`

What specifically are you looking for?
