### ISSUE TITLE
Issue executing a command within a directory

### ISSUE THREAD

**Issue by rahul-sekhar** [capistrano/capistrano#719]
While writing a task, this works fine and executes within "/some/path":

```
within "/some/path" do
    execute "pwd"
end
```

This does not - it executes within the `deploy_to` path:

```
within release_path do
    execute "pwd && ls"
end
```

In fact, it seems like executing a command with whitespace in it does not work as expected in a `within` block.

**Comment by sarink** [comment]
+1 to everything @andyzei said

I don't understand why you wouldn't just execute the command, as-is. If the user forgot to escape their spaces, so what? That doesn't seem like capistrano's problem, nor is it capistrano's problem to protect a user from themselves. Bash doesn't care if you mistype a bash command, why would capistrano? So this "safety feature" really results in an awfully inconsistent/difficult-to-follow API, imo.

**Comment by leehambley** [comment]
You are free to use any other piece of software that more closely aligns
with your philosophy.

When we have bugs we fix them, when features or caveats are difficult to
use or unclear, we improve the documentation, this is how OSS should work,
and you at also free to contribute code, and put in the work to make a case
for changing something.

**Comment by sarink** [comment]
So.. the reason, I guess, is "leehambley said so" ? I mean, is there any practical reason other than trying to protect a user from themselves being bad at bash?

My post was not meant to be offensive, I was (and still am) simply wondering why you believe this way is better?

**Comment by leehambley** [comment]
> My post was not meant to be offensive, I was (and still am) simply wondering why you believe this way is better.

Years of watching people screw things up... we had to make a decision, and the command map function is valuable enough to justify making this slightly (for some experienced people) weird API. IT's not optimal, by any means, but given how `cd` and env vars work in short lived SSH sessions, we don't have a lot of choice. Also, we tried using SSH back channels to manage the connection state (directory, paths, env vars, etc) but it created a massive complexity and synchronisation burden.

**Comment by scottsb** [comment]
@leehambley I completely follow the reasoning for why this behaves as it does, but I'm wondering: given that the behavior is inconsistent and the "right" way is to have the command without white space, would you consider logging a notice to the console if a command is included with whitespace in it? There would naturally need to be some way to disable the notice for those cases where someone knows what they're doing.

**Comment by leehambley** [comment]
The problem is both are equally valid ways to use the APIs, so warning on
one of two equally useful use cases seems inelegant.

**Comment by codener** [comment]
This is the same behavior as Ruby's [`system`](http://ruby-doc.org/core-2.2.0/Kernel.html#method-i-system), `exec` etc methods have, right? I think the only unexpected thing is that a command with spaces *is* actually run, but only ignoring path settings.
