### ISSUE TITLE
Cannot deploy without SCM

### ISSUE THREAD

**Issue by tazsingh** [capistrano/capistrano#722]
If I `delete :scm`, I simply cannot deploy with Capistrano 3.

For a bit of context, I use JRuby's Warbler for deployment so I don't actually use a SCM at all.

**Comment by Envek** [comment]
I solved this with such setup (thanks @chqr for his [None SCM](https://github.com/chqr/capistrano-scm-none-example/blob/master/lib/capistrano/tasks/none.rake) example!)

 1. Added `lib` folder to load path in `Capfile`
    ```ruby
    $LOAD_PATH.unshift File.join(File.dirname(__FILE__), 'lib')
    ```

 2. Added None SCM as `lib/capistrano/none.rb` file with contents:
    ```ruby
    # See https://github.com/capistrano/capistrano/issues/722
    namespace :none do
      task :check do
        true
      end

      task :create_release do
        on release_roles(:web) do |_host|
          execute :mkdir, '-p', release_path
        end
      end

      task :set_current_revision do
        on release_roles(:web) do |_host|
          execute :ln, '-s', release_path, current_path
        end
      end
    end
    ```

 3. And then in `config/deploy.rb`
    ```ruby
    set :scm, :none
    ```

 4. PROFIT!

As I personally think, Capistrano should be decoupled from SCMs, ad deploy not always requires `git checkout` or anything, but Capistrano provides a lot of good stuff like rollbacks, plugins, and very good flow, but sometimes all you need is `rsync` some prebuilt content to the server (and I do not want to set up build environment on server only for deploy).

Thanks everyone!

**Comment by leehambley** [comment]
It's in the works to bring in a `:none` SCM. I had in mind that it meant *extracting* the Git and Subversion SCMs, but maybe not… If you'd be kind enough to prepare a `:none` SCM (as above) as a PR according to our CONTRIBUTING guidelines, I'd be more than happy to merge it. We're scaling up for a big release at the tail end of this week.

**Comment by mk-qi** [comment]
m

**Comment by cbrunnkvist** [comment]
At one place I was supposed to do a rails deployment for the ops team just laughed when I asked if they could open access between the internal git repo (let alone github) and the production server environment. 😞 

A simple `set :scm, :git_copy` strategy that does exactly what you think you'd expect would be very useful in some situations.

**Comment by mattbrictson** [comment]
An update for those interested: Capistrano 3.7 added the option to disable SCM entirely like this:

```ruby
set :scm, nil
```

So now you can use Capistrano sans SCM, per the original request of this issue.

Furthermore, 3.7 adds a documented SCM plugin system to make building things like "git copy" more straightforward: http://capistranorb.com/documentation/advanced-features/custom-scm/

**Comment by treenewbee** [comment]
need a clean cap without deploy and scm
