### ISSUE TITLE
SSH gateway support in v3

### ISSUE THREAD

**Issue by jeffbyrnes** [capistrano/capistrano#725]
I read the release announcement, so I'm aware that this has been removed on-purpose.

I'm opening this issue to (hopefully) keep track of this feature's re-introduction, as it's crucial to our infrastructure.

**Comment by jorgeorpinel** [comment]
To @filipegiusti's [suggestion](https://github.com/capistrano/capistrano/issues/725#issuecomment-29962869): Is there a way to setup different users for the proxy as for the deployment server(s) themselves? Something like:

    require 'net/ssh/proxy/command'
    
    set :ssh_options, {
      auth_methods: %w(publickey),
      proxy: Net::SSH::Proxy::Command.new('ssh jump_user@proxy -W %h:%p'),
    }
    
    role :app, %w{root@prod_server1 deploy@prod_server2}
    role :web, %w{root@prod_server1 deploy@prod_server2}

Or, how would this be done via a local /.ssh/config file ?

**Comment by dalehamel** [comment]
Having an issue here where the current proxy implementation **massively** leaks processes and thus file descriptors, which slows things down and often causes capistrano to hit default fdlimits of 1024.

I have a case where i have a bastion host (gateway), and 12 hosts behind that bastion.

During a deploy to this host, capistrano spawns (and doesn't reap) literally **hundreds** of processes, who's pipes back to the parent end up causing the capistrano process to get reaped for fd usage.

I'm trying to nail down exactly where the bug us (where the processes are leaking) because capistrano has 3 layers to it for this (cap, sshkit, net-ssh), but I feel like having an option to set up and reuse gateways would easily solve this problem.

**Comment by leehambley** [comment]
Gateway management is a concern for the *host* SSH (and Net::SSH) have ways to use gateways, that and using the SSH control master should solve your problem. http://www.anchor.com.au/blog/2010/02/ssh-controlmaster-the-good-the-bad-the-ugly/

We'd be glad of any improvements you can make, and of course it's bad if we're leaking fds and connections, but it certainly shouldn't be a show stopper.

Worth mentioning, that you can *commit* a `./myproject/.ssh/config` to your project, and it'll be picked up and merged with the system config at `~/.ssh/config` (and, `/etc/ssh/config`) taking priority, so you can configure system level gateways and tunnels, use the control master to reuse connections, and Capistrano's pooling and connection reuse should be *virtually* unused, except reusing already reused system connections.

Try it out and let us know if it helps.

**Comment by dalehamel** [comment]
@leehambley we found the issue and were able to prove that sshkit is the one leaking file descriptors.

We solved the issue with a monkey patch, against sshkit, so I'll open a PR there.

**Comment by leehambley** [comment]
Awesome thanks for investigating to improve our stuff, we have a new release scheduled for *really* soon (this weekend, time permitting) - so you won't have to live with a monkey patch for too long. For what it's worth as I'm sure you know, you can use your own fork, or our master of SSHKit (once we merge your PR) with `gem 'sshkit', github: 'capistrano/sshkit'` in your project's Gemfile.

**Comment by deepredsky** [comment]
I have similar problem using 
net-ssh-3.0.1
on ruby 2.2.* versions

Here is a simple script to trigger it.

```ruby
require 'net/ssh'
require 'net/ssh/proxy/command'

Net::SSH.start('abc.domain.com', 'deployer', proxy: Net::SSH::Proxy::Command.new('ssh deployer@gateway.com -W %h:%p')) do |ssh|
  # capture all stderr and stdout output from a remote process
  output = ssh.exec!("hostname")
  puts output
end
```

and here is a trace

```
/Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/proxy/command.rb:82:in `write_nonblock': Resource temporarily unavailable - write would block (IO::EAGAINWaitWritable)
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/proxy/command.rb:82:in `send'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/buffered_io.rb:99:in `send_pending'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/buffered_io.rb:115:in `wait_for_pending_sends'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/packet_stream.rb:118:in `send_packet'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/session.rb:233:in `send_message'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/algorithms.rb:190:in `send_kexinit'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/algorithms.rb:146:in `accept_kexinit'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/session.rb:202:in `block in poll_message'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/session.rb:180:in `loop'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/session.rb:180:in `poll_message'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/session.rb:217:in `block in wait'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/session.rb:215:in `loop'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/session.rb:215:in `wait'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/session.rb:87:in `initialize'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh.rb:222:in `new'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh.rb:222:in `start'
from tmp/ssh.rb:4:in `<main>'
```

**Comment by leehambley** [comment]
Some reason you can't use a proxy command in a SSH config file? (SSHKit
will read a file like ~/.SSH/config from your project root)

**Comment by deepredsky** [comment]
I posted the comment on an issue in net-ssh, realising it's is more to do with net-ssh 

https://github.com/net-ssh/net-ssh/issues/122#issuecomment-159571724

however, i have tried both ~/.ssh/config and .ssh/config files with ProxyCommand configured. I get same error. However I am able to ssh using the gateway and even ssh commands to those servers without any problem.

**Comment by MarioRuiz** [comment]
I am a little confuse in here.
I need to connect to a server, let's think this one:
myuser@server1.com:22 password:'mypwd'
when i am connected to it... then I have access to my other server
myuser@server2.com:22 password:'mypwd'

So i tried to do it  like this:

require 'net/ssh'
require 'net/ssh/proxy/command'

proxy = Net::SSH::Proxy::Command.new('ssh server1.com -W %h:%p')


Net::SSH.start('server2.com, 'myuser', :password=>"mypwd", :proxy => proxy) do |my_ssh|
              my_ssh.open_channel do |channel|
                channel.exec("ls")
              end
end


and i get this message: 
C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-3.2.0/lib/net/ssh/proxy/command.rb:67:in `rescue in open': No such file or directory - ssh server1.com -W serer2.com:22.......

**Comment by leehambley** [comment]
https://github.com/capistrano/sshkit#tunneling-and-other-related-ssh-themes
