### ISSUE TITLE
SVN support removed

### ISSUE THREAD

**Issue by ZhijieWang** [capistrano/capistrano#752]
Hello all, 
This is my first time using capistrano. Lucky or unlucky, capistrano 3 just released. I think I found a bug, maybe not. The capistrano removed svn support. I set scm to svn or subversion, but neither worked. In the gem installed folder, I can find a git.rb, but nothing related to subversion.
Can anyone help me?

cannot load such file -- capistrano/subversion.rb
/Users/Bill/.rvm/gems/ruby-2.0.0-p247/gems/capistrano-3.0.0/lib/capistrano/setup.rb:14:in `load'
/Users/Bill/.rvm/gems/ruby-2.0.0-p247/gems/capistrano-3.0.0/lib/capistrano/setup.rb:14:in`block (2 levels) in <top (required)>'
/Users/Bill/.rvm/gems/ruby-2.0.0-p247/gems/capistrano-3.0.0/lib/capistrano/application.rb:12:in `run'
/Users/Bill/.rvm/gems/ruby-2.0.0-p247/gems/capistrano-3.0.0/bin/cap:3:in`<top (required)>'
/Users/Bill/.rvm/gems/ruby-2.0.0-p247/bin/cap:23:in `load'
/Users/Bill/.rvm/gems/ruby-2.0.0-p247/bin/cap:23:in`<main>'
Tasks: TOP => production

**Comment by elliothay** [comment]
Were these fixes included? I seem to be running into the same issues, and the latest release was after these comments. Is there a different build I should be using?

Thank you.

**Comment by dsthode** [comment]
A slightly old technology but still in use in several places, so I figured out a way to use Subversion with Capistrano overcoming the problems with authentication to the SVN server the following way:

In file lib/capistrano/svn.rb I modified line 19 from:

to the following:


Did the same with the other methods and got a working SVN with authentication, adding the variables :svn_username and :svn_password to the deployment file.

If there is interest and the way it is done is considered fine, I can create a pull request with the changes.

**Comment by leehambley** [comment]
Please do!

**Comment by dsthode** [comment]
Great! Added PR #1402 

Made a slight change to not specify the parameters in each class method, but instead push them to the args array in the svn method if :svn_username and :svn_password are defined in the deployment file
