### ISSUE TITLE
deploy_to does not work in a stage config file

### ISSUE THREAD

**Issue by czerasz** [capistrano/capistrano#815]
I place the `set :deploy_to` in each of the stage config files: `config/deploy/production.rb` and `config/deploy/staging.rb`

Example:

```
set :deploy_to, '/home/user/htdocs/app-name'
```

After running `cap staging deploy:check --trace` I can see that this value was not applied:

```
...
** Execute deploy:check:directories
 INFO [91f6713c] Running /usr/bin/env mkdir -pv /var/www/shared /var/www/releases on example.net
DEBUG [91f6713c] Command: /usr/bin/env mkdir -pv /var/www/shared /var/www/releases
...
```

I use a basic capistrano structure:

```
├── Capfile
├── config
│   ├── deploy
│   │   ├── production.rb
│   │   └── staging.rb
│   └── deploy.rb
└── lib
    └── capistrano
            └── tasks
```

I thought that those stage config files are there to define custom variables for each stage?

**Comment by sp-niemand** [comment]
Still an issue :(

**Comment by mattbrictson** [comment]
@sp-niemand Overriding `:deploy_to` in a stage file is definitely supposed to work, and indeed for my own projects it is working fine. (Capistrano 3.4.0)

My only guess is that you are using a very old version of Capistrano (v2?) that behaves differently, or perhaps you have a Capistrano plugin loaded that is breaking the default functionality. Any insights you have on this would help us troubleshoot.

Have you tried, e.g. adding a `puts` statement to your stage file to verify that is actually being used?
