### ISSUE TITLE
set :asset_env doesn't allow overrides

### ISSUE THREAD

**Issue by Shazzaam** [capistrano/capistrano#835]
In my deploy script for Capistrano 2, I had:

set :asset_env, "#{:asset_env} RAILS_RELATIVE_URL_ROOT=/myapp_uat"

So in Capistrano 3, I have:

set :asset_env, "#{fetch(:asset_env)} RAILS_RELATIVE_URL_ROOT=/myapp_uat"

But when I run:

bundle exec cap development deploy:assets:precompile

It doesn't include the RAILS_RELATIVE_URL_ROOT variable:

cd $HOME/myapp_uat/current && ( PATH=$HOME/.rbenv/shims:$HOME/.rbenv/bin:$PATH RAILS_ENV=development bundle exec rake assets:precompile

**Comment by cmar** [comment]
Google brought us here. We ran into this issue for an older project still on Capistrano 2.13. We fixed it by setting `RAILS_RELATIVE_URL_ROOT` in the default_environment

```
   before 'deploy:assets:precompile' do
     logger.debug "using RAILS_RELATIVE_URL_ROOT=/myapp"

     set :default_environment, {
       'RAILS_RELATIVE_URL_ROOT' => '/myapp'
     }
   end
```
