### ISSUE TITLE
Previous release path variable

### ISSUE THREAD

**Issue by sosedoff** [capistrano/capistrano#877]
In capistrano 2 there was a variable `previous_release`. 

Is there a way to get a previous release path with version 3 ?

**Comment by kidlab** [comment]
I use this to get previous release path:
```
previous_release = Dir[File.join(releases_path, "*/")].sort[-2]
```

**Comment by zx1986** [comment]
I do this whit `previous = capture("ls -Ct #{releases_path} | awk '{print $2}'").to_s.strip`
to get the previous release directory after 'deploy:published'.
but a lots of bug ....

**Comment by leehambley** [comment]
You can also look at the target of the `current` symlink early in the deploy process (before the new `current`/release path is changed) to get the previous release and cache it to a variable.

**Comment by zx1986** [comment]
>  early in the deploy process (before the new current/release path is changed) 

Thanks! @leehambley 
I will got check out which stage that was.

**Comment by hron84** [comment]
If you `capture("readlink #{current_path}")` before `deploy:symlink:release`, you will get the previous release path. 

Btw, @leehambley, this could be done from Capistrano code too, at the start of the process. If there is no `previous_release` then it should simply make the string empty. It can cause some confusion, but it would be definitely better than the current state.

**Comment by leehambley** [comment]
Gabor, if you've got time to open a PR Matt and I will be glad to help
guide you through getting it merged. It's difficult for he and I to
shepherd fearures we don't personally use through to completion, but we'd
love to help you make a contribution if we can.

(Sent from my Nexus 6, please forgive typos!)

**Comment by hron84** [comment]
@leehambley at weekend I'll take a look if I do not forget it completely :smile:
