### ISSUE TITLE
Capistrano fails silently if specified git branch doesn't exist

### ISSUE THREAD

**Issue by paulschreiber** [capistrano/capistrano#886]
If you deploy from a git branch that doesn't exist, Capistrano doesn't throw an error.

    set :repo_url, "git@gitlab.my.org:web.git"
    set :scm, :git
    set :branch, "some-nonexistant-branch"

And then:

    cap deploy

You get a deploy, and the post-deploy tasks run successfully.

**Comment by mattbrictson** [comment]
Closing because this no longer seems to be a problem in Capistrano 3.4.0. I get `git stderr: fatal: Not a valid object name` when specifying a nonexistent branch.
