### ISSUE TITLE
Files in tmp should be created with 0600, and any created directories with 0700.

### ISSUE THREAD

**Issue by leehambley** [capistrano/capistrano#910]
Ignoring the fact that this breaks some of the group related policies on which I personally rely, the file modes of incidentally created files and directories by Capistrano are too open, and may present a security risk under certain circumstances.

**Comment by mattbrictson** [comment]
I assume this issue refers to the git wrapper script we upload to `/tmp`, which is the only place I think we use a temp file in Capistrano itself.

Adding "you can help" tag if anyone wants to try doing a PR for this.
