### ISSUE TITLE
Allow specifying a server with no roles and have it available through on roles(:all)

### ISSUE THREAD

**Issue by rosenfeld** [capistrano/capistrano#968]
Currently, if you specify a server without specifying any roles, you won't be able to connect to that server when inside a block `on roles(:all)`.

Maybe the default :roles option could be something like [:default]. Makes sense?

We don't have any special roles in our settings, but we're forced to add something like roles: [:anything] in order to be able to use Capistrano.

**Comment by mattbrictson** [comment]
Closing because I believe this has been fixed. When I use Capistrano `master` I can successfully run commands using `on release_roles(:all)` even if the server lacks any explicit role.

Please re-open if this is not the case.
