### ISSUE TITLE
Problem when the repository is changed

### ISSUE THREAD

**Issue by Piioo** [capistrano/capistrano#972]
When I deploy capistrano creates an folder "repo". In this folder has capistrano the clone of the respository.

When in die deployment is the respository changed. Capistrano do not register this and creates releases folders from the old copy of "repo" in which is the old respository.

(We habe change from a local respository to github).

I have to delete the repo folder.

**Comment by wangboguo** [comment]
Deleting repo folder worked for me.
Setting repo_url didn't work.
